_docs/_help/best_practices/in-app_messages/previous_in-app_message_generations.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md
Closes #**BD-960**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-960: Fix broken links and image sizing

_docs/_user_guide/administrative/access_braze/single_sign_on.md, assets/js/broken_redirect_list.js
---
---
<details>
</details>
<details>
- …
=> Fix broken links and redirects

_docs/_hidden/wip_partnerships/WIP_guidelines.md
---
---
<details>
</details>
<details>
- …
=> Partner Template Tweaks

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/action_buttons.md
---
---
<details>
</details>
<details>
- …
=> Clarify iOS Action Button documentation

_docs/_api/transactional_message_api_campaign.md
Minor tweaks now that this product is GA (should have been done a while ago) 
- remove hidden tag 
- clarify language around target users and conversion events
---
---
<details>
</details>
<details>
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, and all Header …
=> update txn email docs

_docs/_api/api_campaigns.md, _docs/_api/api_campaigns/api_campaigns.md, _docs/_api/api_campaigns/transactional_api_campaign.md, _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md, _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
---
---
<details>
</details>
<details>
- …
=> Transactional Email API Campaign Endpoint and Doc GA

_docs/_api/api_campaigns/transactional_api_campaign.md
Bolding UI text and buttons Pt. 2, capitalization fixes
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they …
=> Update Transactional Endpoint Pt. 2

_docs/_partners/isv_partners/cohort_import.md
> I'm adding a table with error codes and descriptions to **cohort_import.md**
Closes #**BD-963**
---
---
<details>
</details>
<details>
- On Voice: You …
=> BD-963: Add Cohort Import error codes table

_docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
> I'm removing a note from key_value_pairs.md 
Closes #**BD-965**
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly …
=> BD-965: Remove note to contact CSM for silent push notifications

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md, _docs/_user_guide/engagement_tools/canvas/canvas_funnel_reports.md
---
---
<details>
</details>
<details>
- …
=> Clarify funnel report conversion timing window

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
Adds hmac_sha1_hex, hmac_sha1_base64, hmac_sha256_hex, hmac_sha256_base64 as advanced liquid filters (primarily to support various uses of JWT for Connected Content requests).
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they are an …
=> Add additional hmac liquid filters

_docs/_home/metadata.md, _docs/_home/static_video.md, _docs/_home/styling_test_page.md, _docs/_home/templates.md
---
---
<details>
</details>
<details>
- …
=> Removing docs from Algolia indexing

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Trivial spelling error.
(no associated issue.)
---
---
<details>
</details>
<details>
<summary>ATTENTION: For PR Reviewers</summary>
</details>
=> trivial misprint: visable -> visible

_docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
https://github.com/Appboy/appboy-ios-sdk/blob/master/HelloSwift/HelloSwift/AppDelegate.swift#L93
=> Make nullable params optional

_docs/_developer_guide/platform_integration_guides/unity/android/sdk_integration.md, _docs/_developer_guide/platform_integration_guides/unity/content_cards.md, _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Updates for recent Unity release
*
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly Professor. Imagine, if you will, the …
=> catchall unity docs updates

_docs/_developer_guide/platform_integration_guides/fireos/push_notifications/integration.md, _docs/_developer_guide/platform_integration_guides/unity/android/adm_push_notifications.md, _docs/_developer_guide/platform_integration_guides/unity/android/push_notifications.md
https://jira.braze.com/browse/SDK-1568
Unity docs on ADM registration
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly …
=> SDK-1568 - unity adm docs

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
---
---
<details>
</details>
<details>
- …
=> Segment Link Fix

_docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
> I'm updating scheduled_delivery.md to mention that the end date for a scheduled delivery campaign is inclusive, as well as a few minor tweaks and a link fix.
Closes #**BD-968**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, …
=> BD-968: Clarify end date for scheduled messaging

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md
---
---
<details>
</details>
<details>
- …
=> Typo in Rudderstack Doc

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
---
---
<details>
</details>
<details>
- …
=> BD-961: Clarify mParticle Integration Instructions

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Closes #**BD-970**
---
---
<details>
</details>
<details>
- On Voice: …
=> Clarify case sensitivity for CSV imports

_docs/_hidden/private_betas/nested_object_support.md
---
---
<details>
</details>
<details>
- …
=> BD-969: Liquid Syntax Fix

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
---
---
<details>
</details>
<details>
- …
=> Fixing serialization example

_docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_wide/analytics_overview.md
> I'm adding a warning to all **setting_custom_attributes.md** files to warn against using Braze's reserved standard attribute names as names for custom attributes.
Closes #**BD-971**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, …
=> BD-971: Add warning regarding naming custom attributes using Braze's reserved keys

_docs/_user_guide/administrative/manage_your_braze_users/teams.md
> I'm adding the Teams bite to the Teams page, as well as making a few minor style and formatting updates.
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a …
=> Add 'Teams' Braze Bite

_docs/_hidden/private_betas/nested_object_support.md
Reverts braze-inc/braze-docs#2310
=> Revert "BD-969: Liquid Syntax Fix"

_docs/_api/objects_filters/event_object.md, _docs/_api/objects_filters/purchase_object.md, _docs/_hidden/private_betas/nested_object_support.md, _docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md, assets/js/broken_redirect_list.js
> I'm updating the following pages with additional information on supported data types for event properties:
- Event Object
- Purchase Object
- Nested Object Support
Closes #**BD-967**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, …
=> Update docs for Nested Event Property GA — MERGE 6/29

_docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/fireos/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_wide/analytics_overview.md
Reverts braze-inc/braze-docs#2312
=> Revert "BD-971: Add warning regarding naming custom attributes using Braze's reserved keys"

_docs/_developer_guide/platform_wide/app_group_configuration.md, _docs/_hidden/private_betas/link_aliasing.md
---
---
<details>
</details>
<details>
- …
=> Liquid App Group Version Bite

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/ott_devices.md, _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/ott_devices.md, _includes/archive/android/in_app_messages/ott_iam.md
https://jira.braze.com/browse/SDK-1608
- [] No
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly Professor. Imagine, if you …
=> SDK-1608 - added ott docs for android/fireOS

_docs/_help/release_notes.md, _docs/_help/release_notes/2021.md, _docs/_help/release_notes/2021/july.md
---
---
<details>
</details>
<details>
- …
=> July 2021 Release Notes

_docs/_help/help_articles/push/no_push_notification_was_received.md, _docs/_user_guide/data_and_analytics.md
Closes #**BD-973**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-973: Fix typo

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
---
---
<details>
</details>
<details>
- …
=> BD-911: Custom Android In-App Review Prompts

_docs/_help/release_notes.md, _docs/_help/release_notes/2021/july.md, _docs/_partners/message_orchestration/attribution.md, _docs/_partners/message_orchestration/attribution/appsflyer.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md
---
---
<details>
</details>
<details>
- …
=> Release Notes Pt. 2

_docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
---
---
<details>
</details>
<details>
- …
=> BD-976: Add Liquid Reference to Custom Footer Documentation

_docs/_partners/message_personalization/location/radar.md
Closes #**BD-977**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-977: Radar Link Update

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Closes #**BD-978**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-978: Add details on max length of custom attribute arrays

_docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
---
---
<details>
</details>
<details>
- …
=> Alias Link Fix

_docs/_user_guide/data_and_analytics/report_metrics.md
Closes #**BD-980**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-980: Clarify unique impressions incrementation

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
> I'm changing the personalisation tags for campaigns/canvases because some were missing and the Canvas attributes section was not clear. I also added a new row for Canvas step attributes to make it clear that you can pull in specific step data into the message using Liquid
---
---
<details>
</details>
<details> …
=> BD-982: Fixed Personalization Tags for Canvas/Campaigns

_docs/_partners/message_personalization/dynamic_content/movable_ink.md, assets/js/broken_redirect_list.js
---
---
<details>
</details>
<details>
- …
=> Redirects for old Hidden Beta Links

_docs/_help/best_practices/race_conditions.md
---
---
<details>
</details>
<details>
- …
=> Add Braze Bite on Race Conditions

_docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/push_notifications.md
> Current link links to a Navigation title instead of actual page and gets routed to the docs landing page instead
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly Professor. Imagine, if …
=> Update Android Push Integration Link

_docs/_user_guide/data_and_analytics/report_metrics.md, _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
> I'm adding definitions to the Report Metrics Glossary for simple survey metrics.
Closes #**BD-985**
---
---
<details>
</details>
<details>
- On Voice: You …
=> BD-985: Add simple survey metrics definitions

_docs/_api/objects_filters/user_attributes_object.md
> I'm clarifying that only custom events with timestamps in the future will default to the current time, not custom attributes. Also reformatting the data types list into a table for readability.
Closes #**BD-984**
---
---
<details>
</details>
<details>
- Always speak to the Braze …
=> BD-984: Clarify future timestamp behavior

_docs/_user_guide/onboarding_with_braze/data_points.md
Closes #**BD-987**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-987: Correcting 'User ID' data point usage

_docs/_user_guide/onboarding_with_braze/email_setup/authentication.md, _docs/_user_guide/onboarding_with_braze/email_setup/consent_and_address_collection.md, _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md, _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md, _docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
---
---
<details>
</details>
<details>
- …
=> CVR Article Improvements - Pt. 2

_docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
> I'm clarifying an option in Action-Based Delivery campaigns based on guru cards
---
---
<details>
</details>
<details>
- On …
=> Clarify 'Receive' options in Action-Based Delivery campaigns

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
---
---
<details>
</details>
<details>
- …
=> Removing gendered language in email subscription doc

_docs/_user_guide/administrative/access_braze/single_sign_on.md
---
---
<details>
</details>
<details>
- …
=> BD-983; Clarify SSO support note

assets/js/broken_redirect_list.js
> I'm adding a redirect for a broken link found in training
---
---
<details>
</details>
<details>
- On Voice: You should aim to …
=> Redirect broken link

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
> I'm adding more specific information to the table of "Initial Conditions" in change_your_canvas_after_launch.md
Closes #**BD-989**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a Marketer, …
=> BD-989: Clarify initial conditions

_docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md, _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md, assets/css/_tabs.scss
---
---
<details>
</details>
<details>
- …
=> Update Email/Phone Example Requests with Tabs

assets/js/algolia_header_search.js, assets/js/algolia_main_search.js
---
---
<details>
</details>
<details>
- …
=> Use description for search

_docs/_user_guide/message_building_by_channel/content_cards/about.md
> I'm updating the Content Cards **about_md** with a section on the advantages of using Content Cards vs. having content built directly into your app build by your tech team (from Braze Bonfire).
---
---
<details>
</details>
<details>
- Always speak to the …
=> Add info on advantages of using Content Cards

_docs/_home/templates/get_endpoint.md, _docs/_home/templates/post_endpoint.md
> I'm adding `noindex:true` to a few templates that showed up in search results.
---
---
<details>
</details>
<details>
- On …
=> Add noindex to templates

_docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
Closes #**BD-991**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-991 - Replace semicolon with colon in JSON example

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/fireos/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/overview.md, _docs/_help/best_practices.md, _docs/_help/best_practices/news_feed.md, _docs/_hidden/other/client_integration_gallery.md, _docs/_hidden/other/user_onboarding.md, _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md, _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/in-app_messages.md, _docs/_user_guide/message_building_by_channel/push/about.md, _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md, assets/js/broken_redirect_list.js
> Add hidden:true to select Best Practices articles
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a …
=> Best Practices Rework - Pt.1

_docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
First time contributing to the repo. Just testing the water w. a very minor typo. 
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly Professor. Imagine, if you will, the smartest, but also …
=> [NO TICKET] user profile lifecycle minor typo

_docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
> I'm updating the Android Push troubleshooting.md to include additional troubleshooting for deep links
Closes #**BD-992**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a Marketer, or an …
=> BD-992: Update Android Push troubleshooting.md

_docs/_hidden/private_betas/nested_custom_attribute_support.md
> I'm updating the sample requests and sample custom attribute objects in nested_custom_attribute_support.md to use the `most_played_song` object instead of the `last_played_song` object.
Closes #**BD-993**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - …
=> BD-993: Update usage examples

_docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
=> Update simple_survey.md - MERGE 7/15

_docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
Closes #**BD-994**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-994 - Update broken link

_docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
Updating method name in iOS SDK.
See:
https://github.com/Appboy/AppboyKit/pull/3840
https://jira.braze.com/browse/SDK-1596
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly …
=> [SDK-1596] Updated IAM display method on iOS

_docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/logging_custom_events.md, _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/logging_custom_events.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md, _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
---
---
<details>
</details>
<details>
- …
=> Adding Custom Attribute/Event Dev Guide Links to Data and Analytics Section

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
---
---
<details>
</details>
<details>
- …
=> Clarify changing control variant distribution in a Canvas after launch

_docs/_api/objects_filters/event_object.md, _docs/_api/objects_filters/purchase_object.md
Closes #**BD-997**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-997: Update app_id to required field in user track API documentation

_docs/_api/endpoints/export/campaigns/get_campaign_details.md
---
---
<details>
</details>
<details>
- …
=> IAM GET /campaign/details response - MERGE 7/20

_docs/_user_guide/onboarding_with_braze/sms_setup/terms.md
---
---
<details>
</details>
<details>
- …
=> Replace markdown code elements with HTML in SMS terms glossary

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
---
---
<details>
</details>
<details>
- …
=> Updating Census Integration, Linking to Census Docs

_docs/_api/endpoints/user_data/post_user_track.md
> I'm removing the section on "Queued Responses" from the POST: User Track endpoint documentation
Closes #**BD-999**
---
---
<details>
</details>
<details>
- …
=> BD-999: Remove queued responses section from post_user_track.md

_docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
=> [July 21] remove early access for survey

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
Closes #**BD-1000**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1000 - Update code snippets to match API tab formatting

_docs/_developer_guide/platform_integration_guides/fireos/push_notifications/testing.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
> I'm removing the {{ }} around `YOUR_API_KEY` in the cURL examples on the iOS and FireOS testing.md pages, which were causing the text to not display.
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, …
=> BD-1001: Fix API key parameter not displaying in cURL examples

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md, _docs/_user_guide/onboarding_with_braze/email_setup/ssl/ssl_clicktracking.md, _docs/_user_guide/onboarding_with_braze/sms_setup/short_and_long_codes.md, _docs/_user_guide/onboarding_with_braze/sms_setup/sms_laws_and_regulations.md
---
---
<details>
</details>
<details>
- …
=> General article scrubbing

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Closes #**BD-1002**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1002: Clarify difference between Push Enabled and Push Enabled for App

assets/js/broken_redirect_list.js
Closes #**BD-1004**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1004 - Fix broken link for IAM specs

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/beacon_integration.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/network_offline_mode_integration.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md, _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md, _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md, _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md, _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md, _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md, _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/baidu_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/huawei_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/silent_push_notifications.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md, _docs/_developer_guide/platform_integration_guides/android/sample_apps.md
https://jira.braze.com/browse/SDK-1353
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they are an …
=> [SDK-1353] Android Appboy->Braze doc updates

_docs/_developer_guide/platform_integration_guides/ios/storage.md
---
---
<details>
</details>
<details>
- …
=> Update 'timezone' to 'time zone'

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Small tweak to include new fields to SMS InboundReceive and SMS Send events
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as …
=> updating SMS currents events with new fields

_docs/_hidden/private_betas/nested_custom_attribute_support.md
Closes #**BD-1006**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1006: Add datetime limitation to nested_custom_attribute_support.md

_docs/_help/release_notes.md, _docs/_help/release_notes/2021.md, _docs/_help/release_notes/2021/august.md
> Adding release notes for August 2021
---
---
<details>
</details>
<details>
- On Voice: You should aim to be a Friendly …
=> August 2021 Release Notes

_docs/_help/faqs.md, _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
---
---
<details>
</details>
<details>
- …
=> Add In-App Messages FAQ

_docs/_api/endpoints/user_data/post_user_track.md
Closes #**BD-1005**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1005: Add X-Braze-Bulk header to /users/track endpoint

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Closes #**BD-1008**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1008: Update custom_events.md with nested support for event properties

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
---
---
<details>
</details>
<details>
- …
=> Update mParticle Endpoint Description

_docs/_partners/canvas_steps/google_audience_sync.md
---
---
<details>
</details>
<details>
- …
=> Google Audience Sync to GA - MERGE 7/28

_docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
Closes #**BD-1009**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1009: Clarify uninstall_tracking.md

_docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md, _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md, _docs/_hidden/private_betas/ios_sdk_integration.md
This iOS integration guide takes you on a step-by-step journey on setup best practices when first integrating the iOS SDK and its core components in your application. This guide will help you decouple any dependencies on the Braze iOS SDK from the rest of your production code.
=> iOS SDK Journey

_docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
---
---
<details>
</details>
<details>
- …
=> Updating Blocklist Behavior

_docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md
---
---
<details>
</details>
<details>
- …
=> Fix YAML issue

_docs/_user_guide/message_building_by_channel/content_cards/reporting.md
> I'm repeating the call out to the Report Metrics Glossary and making it more visible in the Content Cards **reporting.md**
Closes #**BD-1011**
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, …
=> BD-1011: Call out report metrics glossary for Content Cards

_docs/_user_guide/personalization_and_dynamic_content/liquid.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
---
---
<details>
</details>
<details>
- …
=> Minor Liquid docs update and add `assign` Content Block tip

_docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
from the context, I expect the intended word is "complement" because the POST request complements the transactional email in the sense of completing or going together with it.
---
---
<details>
</details>
<details>
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, and …
=> misprint: "compliment" -> "complement"

_docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
---
---
<details>
</details>
<details>
- …
=> Add tip for optimizing email preview text

_docs/_api/endpoints/messaging/send_messages/post_send_messages.md
fixed typo and added some additional color around the campaign_id key.
---
---
<details>
</details>
<details>
- Always speak to the Braze customer - refer to them as …
=> Update to post_send_messages documentation

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
Closes #**BD-1013**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1013: Fix Canvas doc inconsistencies

_docs/_api/api_key.md
Closes #**BD-1012**
---
---
<details>
</details>
<details>
- On Voice: …
=> BD-1012: Remove statement that app_id is optional for email object

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Adding support callout in TealiumAudience and EventStream Docs

_docs/_help/help_articles/campaigns_and_canvas/not_triggering.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/testing/race_conditions.md
Closes #**BD-1014**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1014: Add warning about potential race conditions during campaign/Canvas creation

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
Closes #**BD-1015**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1015: Clarify email validation behavior

_docs/_developer_guide/platform_integration_guides/android/push_notifications/integration/standard_integration.md
Fixes a typo in the package
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> android/Fix package typo 

_docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add additional 30 for 30 tips

_docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/delivery_types/scheduled_delivery.md
Closes #**BD-1020**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1020 - Update link

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/census.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1019: Census Delta Updates

_docs/_user_guide/engagement_tools/campaigns/scheduling_and_organizing/attribute_triggers.md
Closes #**BD-1018**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1018: Add note for custom attributes trigger

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
See https://segment.com/docs/connections/spec/ecommerce/v2/
=> Order Completed

_docs/_user_guide/data_and_analytics/braze_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1022: Add Tealium to Currents List

_docs/_api/basics.md, _docs/_api/endpoints/export/user_data/post_users_identifier.md
Closes #**BD-1025**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1025: Create alert and update API limits for Users by Identifier Endpoint

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> [No Ticket][Trivial] Remove old android push info

_docs/_user_guide/message_building_by_channel/sms/sms_campaign_analytics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1027: Update SMS Analytics

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md, _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md, _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md, _docs/_api/objects_filters/recipient_object.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1024: Update Recipients Object Formatting

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1030: Update Silent Remote Notification

_docs/_developer_guide/platform_integration_guides/android/android_12.md, _includes/archive/android/intial_sdk_setup/android_sdk_integration.md
=> Android 12 Upgrade Guide

_docs/_api/endpoints/messaging.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md
Closes #**BD-1029**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1029: Add a page for Delete Scheduled API-Triggered Canvases endpoint

_docs/_user_guide/message_building_by_channel/in-app_messages/create.md
> I'm changing the "server-side event triggering" and "local in-app message delivery" links in Step 6 under "Triggering" to current links for each.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ ATTN: For …
=> Fixing broken links in create.md

_docs/_user_guide/administrative/company_settings/security_settings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1032: 2FA Reset

_docs/_api/objects_filters/event_object.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1031: Clarify API Event Object

_docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1034: Appsflyer Toggle

_docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
adding details to how we will drop requests when the original end user sent an email is not the one requesting an unsubscribe requests via the list-unsubscribe header.
---
<details>
<br>
</details>
<details>
<br> …
=> list-unsubscribe clarifications - MERGE 8/17

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
…e going out on August 17. Do not merge until August 18.
> Support JSON in Connected Content POST bodies
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Updates connected content documentation - MERGE 8/18

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
Closes #**BD-1037**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1037: Update Canvas Persistent Entry Properties

_docs/_developer_guide/platform_wide/tv_and_ott.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> TVOS Link Fix

_includes/html_include.html
Prioritize using article title as the HTML title if available. Fallback to nav title.
I left the "Braze" prefix but let me know if you want it removed.
---
<details>
<br>
</details>
<details>
<br> …
=> Use article_title as HTML title

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Closes #**BD-1038**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1038: Add additional `most_recently_used_device` tags

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> Fixing minor syntax issues and a broken alert
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix Liquid use case examples and broken alert

_includes/html_include.html
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Remove Prefix from Tab

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix broken link for Canvas doc

_docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
Closes #**BD-1040**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1040: Fix typo

_docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md, _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md, assets/js/broken_redirect_list.js
Closes #**BD-1043**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1043: Move list-unsubscribe content to Email Settings page

_docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/implementation_guide.md, _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md, _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Minor alert edits

_docs/_user_guide/data_and_analytics/report_metrics.md
Closes #**BD-1044**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1044: Remove inapplicable News Feed report metrics

_docs/_user_guide/engagement_tools/campaigns/faq.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Closes #**BD-1042**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1042: Clarify local time zone for Canvas steps 

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Amperity Redirect

_config.yml
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add article title to index

_docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
https://jira.braze.com/browse/SDK-1683
Adds instructions for implementing an ABKContentCardsTableViewControllerDelegate at developer_guide/platform_integration_guides/ios/content_cards/customization/#handling-clicks-manually
---
<details>
<br>
</details>
<details>
<br>
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page …
=> [SDK-1683] add ABKContentCardsTableViewControllerDelegate instructions

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Added Redirect for Link Causing Server Error

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
> I'm changing Android deeplinking documentation because how to use a custom WebView activity wasn't documented.
Closes #N/A
- [ x ] Yes (4.0.0 Nov 18, 2019)
---
<details>
<br>
- [ x ] Check that all links work.
- [ x ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
</details>
<details>
<br> …
=> Add Custom WebViewActivity instructions

_docs/_api/endpoints/export/sms.md, _docs/_api/endpoints/export/sms/get_query_invalid_numbers.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Hiding new API Endpoint until release

_docs/_user_guide/engagement_tools/templates_and_media/faqs.md
Closes #**BD-1056**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1056: Fix heading levels

_docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
Closes #**BD-1057**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1057: Unify note on REST API triggering across core SDKs

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/androidx_integration.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md, _docs/_user_guide/message_building_by_channel/email/mpp.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Minor Edits: Noting Android Specific Articles and Adding iOS 15 field to MPP

_docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Reverts braze-inc/braze-docs#2609
=> Revert "BD-1060: Fix missing code snippet in push notification integration.md…"

_docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
https://brazetechnology.slack.com/archives/C01M8088JLX/p1630525211033800
=> Remove geofence specific analytics claim

_docs/_api/objects_filters/user_attributes_object.md
From the context where this link is given (first text block at https://www.braze.com/docs/api/objects_filters/user_attributes_object/), I expect that it should link to the table "Braze User Profile Fields" on the same page .
---
<details>
<br>
</details>
<details>
<br>
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page …
=> Update broken URL

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Add missed instruction on IOS react native SDK initial setup:
https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/#step-1-integrate-the-braze-library
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Missed instruction on react-native sdk IOS setup

_docs/_api/endpoints/export/user_data/post_users_segment.md
> Add `push_opted_in_at`, `push_unsubscribed_at`, `email_opted_in_at`, `email_unsubscribed_at` to sample export response when exporting the `push_subscribe` and `email_subscribe` fields.
Closes #**BD-1061**
---
<details>
<br>
</details>
<details>
<br>
</details> …
=> BD-1061: Update /users/export/segment sample export

_docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md, _docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md, _docs/_partners/message_personalization/dynamic_content/playable.md, _docs/_partners/message_personalization/location/radar.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Alerts Cleanup - Technology Partners Section

_docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md, _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md, _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_user_ids.md, _docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md, _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md, _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/setting_user_ids.md, _docs/_user_guide/engagement_tools/campaigns/testing_and_more/conversion_events.md, _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md, _includes/archive/setting_user_ids/best_practices.md
Shifting around some "includes archive content" and including last couple 30 for 30 tips.
=> 30 for 30 Tips

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md, _docs/_developer_guide/platform_integration_guides/sdk_primer.md, _docs/_developer_guide/platform_wide/analytics_overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Alerts Cleanup - Developer Guide Section

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
Syntax fix for first Liquid tag in the "Most Recently Used Device Information" table at https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags/#most-recently-used-device-information
---
<details>
<br>
</details>
<details>
<br>
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/sty …
=> Liquid syntax quick fix

_docs/_user_guide/message_building_by_channel/in-app_messages/create.md
=> button 2 message

_docs/_user_guide/message_building_by_channel/push/ios/notification_options.md
=> push early access

_docs/_user_guide/administrative/company_settings/security_settings.md
Updates text to mention that the security event log has other activities.
The diff looks big because trailing whitespaces were removed by my editor.
---
<details>
<br>
</details>
<details>
<br> …
=> Update text for the security event download.

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Closes #**BD-1062**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1062: Clarify update of user alias alert

_docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Closes #**BD-1063**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1063: Fix broken link

_docs/_user_guide/onboarding_with_braze/data_points.md
Closes #**BD-1041**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1041: Remove duplicate data points listed under Engagement tab

_includes/search_page.html
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Search page returns description

_docs/_home/styling_test_page.md
> Adding entry for custom anchor text to **styling_test_page.md**
=> Add entry for anchor text to styling_test_page.md

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
> I'm changing React Native SDK documentation because this missing information has caused users some issues.
- [x ] No
---
<details>
<br>
- [x ] Check that all links work.
- [x ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [x ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [x ] Tag others as reviewers as necessary.
- [x ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`
</details>
<details>
<br>
- …
=> [SDK-1827] Update react_sdk_setup.md

_docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Closes #**BD-1065**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1065: Fix typo

_docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md
> Add note that triggering messages and segmenting users based on nested object data is in EA.
Closes #**BD-1066**
=> BD-1066: Add beta note to nested_object_support.md

_docs/_developer_guide/platform_integration_guides/android.md, _docs/_developer_guide/platform_integration_guides/cordova.md, _docs/_developer_guide/platform_integration_guides/flutter.md, _docs/_developer_guide/platform_integration_guides/macOS.md, _docs/_developer_guide/platform_integration_guides/react_native.md, _docs/_developer_guide/platform_integration_guides/roku.md, _docs/_developer_guide/platform_integration_guides/tvos.md, _docs/_developer_guide/platform_integration_guides/unity.md, _docs/_developer_guide/platform_integration_guides/unity/sdk_integration.md, _docs/_developer_guide/platform_integration_guides/unreal_engine.md, _docs/_developer_guide/platform_integration_guides/web.md, _docs/_developer_guide/platform_integration_guides/windows_universal.md, _docs/_developer_guide/platform_integration_guides/xamarin.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Adding Redirects for Platform Toggle

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-1067: Clarify references to user alias import and templates

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add redirect for Android troubleshooting scenarios

_docs/_api/api_key.md, _docs/_api/basics.md, _docs/_api/endpoints/export/user_data/post_users_identifier.md, _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md, _docs/_api/endpoints/user_data/post_user_alias.md, _docs/_api/endpoints/user_data/post_user_identify.md, _docs/_api/endpoints/user_data/post_user_track.md, _docs/_api/objects_filters/user_attributes_object.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Alerts Cleanup - API Section

_docs/_user_guide/message_building_by_channel/push/best_practices.md, assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add redirect and fix broken link

_docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
This link appears to originate in https://github.com/braze-inc/braze-docs/commit/dc60bbea7a6f02f012dc467de59596ff5e000bdb from before the introduction of a page about [SMS subscription groups](https://www.braze.com/docs/user_guide/message_building_by_channel/sms/sms_subscription_group/) ([message_building_by_channel/sms/sms_subscription_group.md](https://github.com/braze-inc/braze-docs/blob/564b1fa6200c849125e79eba7424548e96239373/_docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md)). At that time, targeting a page about keyword processing seems like a best fit, but now the page about subscription groups is better, I would argue.
---
<details> …
=> Correct link target for "Subscription Groups"

_docs/_user_guide/engagement_tools/canvas.md, _docs/_user_guide/engagement_tools/canvas/canvas_components.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Closes #**BD-1070**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1070: Remove beta note

_docs/_api/basics.md, _docs/_api/endpoints/export/custom_events/get_custom_events.md, _docs/_api/endpoints/user_data/post_user_alias.md, _docs/_api/endpoints/user_data/post_user_delete.md, _docs/_api/endpoints/user_data/post_user_identify.md
> I'm updating the API Limits table, as well as adding notes to the endpoint-specific pages calling out the change.
Closes #**BD-1068**
---
=> BD-1068: Update API rate limits

_docs/_developer_guide/platform_integration_guides/ios/ios_15.md
=> ios 15 docs

_docs/_developer_guide/platform_integration_guides/ios/ios_15.md
=> Add site.baseurl prefix to URLs

_docs/_user_guide/introduction.md
=> Update User Guide popular topics for Aug - Sept

_docs/_help/release_notes.md, _docs/_help/release_notes/2021.md, _docs/_help/release_notes/2021/october.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> October 2021 Braze Release Notes

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_push_notifications.md
Closes #**BD-1075**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1075: Clarify information on Sending Test Messages page 

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
> Add frequency capping limitation of 30 days and minor article cleanup for style.
Closes #**BD-1079**
=> BD-1079: Add frequency capping limitation and minor doc cleanup

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/rate-limiting.md
Closes #**BD-1078**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1078: Clarification for rate-limiting

_docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md
Fixing a typo
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix typo in title

_docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
=> Minor typo fix in code sample

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/ab_testing_with_random_buckets.md, _docs/_user_guide/message_building_by_channel/push/best_practices/additional_android_best_practices.md
=> Minor grammar updates and link fixes

_docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
> Hardcoding code snippet due to gist-it.appspot.com being continuously down.
Closes #**BD-1081**
=> BD-1081: Manually add service worker configuration content

_docs/_user_guide/engagement_tools/testing/race_conditions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Adding Shortened Link for Race Condition Braze Bite

_docs/_help/help_articles/account/locked_out.md, _docs/_help/help_articles/api/delete_user.md, _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md, _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md, _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md, _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md, _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md, _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md, _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md, _docs/_help/help_articles/content_cards/empty_content_card_feed.md, _docs/_help/help_articles/data/change_custom_data_type.md, _docs/_help/help_articles/data/dispatch_id.md, _docs/_help/help_articles/docs/contribution.md, _docs/_help/help_articles/docs/hacktober_2019.md, _docs/_help/help_articles/docs/scroll_bar_overlap.md, _docs/_help/help_articles/email/html_looks_strange.md, _docs/_help/help_articles/in-app_messages/in-app_message_impressions_appear_lower_than_expected.md, _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md, _docs/_help/help_articles/push/no_push_notification_was_received.md, _docs/_help/help_articles/push/push_error_codes.md, _docs/_help/help_articles/push/push_token_migration.md, _docs/_help/help_articles/segments/my_filter_options_have_changed.md, _docs/_help/help_articles/segments/over-segmentation.md, _docs/_help/help_articles/segments/segment_showing_0_users.md, _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md, _docs/_help/help_articles/segments/segmentation_logic_with_negative_or_filters.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Help Articles - YAML Edits

_docs/_developer_guide/platform_integration_guides/web/amp_support.md, _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md, _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
* removed gist-it since they are broken and no longer maintained.
=> removed gist-it

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/onboarding_with_braze/data_points.md
=> BD-1082: Clarify data point usage for custom event properties

_docs/_developer_guide/platform_integration_guides/react_native/sample_app.md
Adding a sample app page to the React Native documentation to shout out an already existing sample application in the React SDK source code.
I thought it would be a great idea to include an explicit link to the application. I found it very useful myself as I was integrating the SDK within a React Native application.
---
<details>
<br>
</details>
<details>
<br>
- [Styling …
=> Add React Native sample app page

_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
=> BD-1088: Clarify segment membership calculation with all apps selected

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> BD-1090: Add SMS/MMS to description for Subscription Groups

_docs/_api/objects_filters/event_object.md, _docs/_api/objects_filters/user_attributes_object.md
=> BD-1089: Add note on _update_existing_only to Event Object

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
Closes #**BD-1091**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1091: Clarify sha2 and sha256 support

_docs/_user_guide/onboarding_with_braze/data_points.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Data Point Calculation Updated

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
=> Fix typo in triggered_delivery.md

_docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
=> BD-1073: Add standard attribute information to GTM for Web

_docs/_user_guide/administrative/access_braze/portal.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Product Roadmap Dashboard Update

_docs/_user_guide/onboarding_with_braze/email_setup.md, _docs/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md, _docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Adding Email Onboarding Videos to Docs

_docs/_user_guide/data_and_analytics/braze_currents.md
Currents change log removed; using platform release notes instead
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Currents change log removed; using platform release notes instead

_docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
Closes #**BD-1093**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1093: Update Apple Private Relay Doc

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
=> BD-1095: Specify segmentation filters for subscription usage

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
> Add `Update Subscription Group Status` trigger to attribute_triggers.md, and other minor style cleanup.
Closes #**BD-1096**
---
=> BD-1096: Add Update Subscription Group Status trigger

_docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
=> BD-1097: Clarify silent push behavior

_docs/_user_guide/message_building_by_channel/push/about.md, _docs/_user_guide/message_building_by_channel/push/ios/notification_options.md, _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
=> BD-1098: Update text specifications for push notifications

_docs/_docs_pages/index.md, _docs/_hidden/other/dp-technical-assistance.md, _docs/_hidden/other/innovation_statement.md, assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Adding Help Section Links to Main Docs Page

_docs/_user_guide/message_building_by_channel/push.md, _docs/_user_guide/message_building_by_channel/push/best_practices.md, _docs/_user_guide/message_building_by_channel/push/push_reporting.md, assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Move push reporting out of best practices

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add additional IPs to whitelist in EU for webhooks

assets/js/algolia_header_search.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix header search

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Unity dependencies have changed in (unreleased) version 3.6.0 of the SDK 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> swapped appcompat for kotlin in unity android

_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
> I'm changing the hyperlink in the Making an API Call docs page as it no longer links to a section within the same page
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fixed broken hyperlink

_docs/_api/api_campaigns/api_campaigns.md, _docs/_partners/isv_partners/api_partner.md
> Fixing some duplicate alias links that Z pointed out
=> Fixing duplicate alias URLs

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
> I'm fixing a broken link.
Closes #**BD-1135**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1135: Fix broken link

_docs/_user_guide/data_and_analytics/report_metrics.md
Closes #**BD-1137**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1137: Fix duplicate report metric

_docs/_user_guide/message_building_by_channel/content_cards/testing.md
Closes #**BD-1138**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1138: Add iOS-specific caveat for testing Content Cards

_docs/_api/endpoints/user_data/post_user_track.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md, _docs/_user_guide/engagement_tools/segments/using_user_search.md
=> Various edits based on customer and internal feedback

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
Closes #**BD-1141**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1141: Change campaign_id to optional in create scheduled messages endpoint

_docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix link on Partners page

_docs/_hidden/other/tour.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Minor doc edits

_docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
> I'm changing setting_up_currents.md to fix a typo.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix typo "Cconfigure" -> "configure"

_docs/_user_guide/administrative.md, _docs/_user_guide/data_and_analytics.md, _docs/_user_guide/engagement_tools.md, _docs/_user_guide/intelligence.md, _docs/_user_guide/introduction.md, _docs/_user_guide/message_building_by_channel.md, _docs/_user_guide/onboarding_with_braze.md, _docs/_user_guide/personalization_and_dynamic_content.md, _docs/_user_guide/predictive_suite.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Clean up landing pages

_docs/_api/endpoints/templates/email_templates/post_update_email_template.md, _docs/_hidden/private_betas/post_user_identify_merge_behavior.md, _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Documenting merge behavior on /users/identify/ endpoint - hidden page

_docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
=> BD-1146: Fix typos and minor formatting changes

_docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md
=> BD-1147: Add Content Cards to list of supported messaging channels for content test groups

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
=> Update permissions definitions to show requirements for launching existing content blocks

_docs/_developer_guide/platform_wide/sending_test_messages.md
=> BD-1151: Remove references to testing IAM with cURL

_docs/_api/api_campaigns.md, _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Closes #**BD-1142**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1142: Clarify API-triggered vs. API campaign 

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
=> BD-1152: Clarify `dispatch_id` inclusion in Currents events

_docs/_hidden/private_betas/catalog.md
=> BD-1150: Update Catalogs with templating support

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Closes #**BD-1154**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1154: Clarify HTML Preference Center snippet   

_docs/_developer_guide/platform_integration_guides/android/content_cards/read_unread_indicators.md
Makes it clearer how to customize this indicator color.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update read_unread_indicators.md android docs

_docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1099: In-Browser Message

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix missing bracket

_docs/_api/endpoints/export/user_data/post_users_segment.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1115: Post User Segment Export Options

_docs/_api/api_campaigns/transactional_api_campaign.md, _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Closes #**BD-1155**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1155: Clarify Transactional Email feature

_docs/_api/endpoints/export/campaigns/get_campaign_details.md
> I'm changing the `type` description in the response from `GET /campaigns/details` to match the reality that we don't return any value other than `survey` currently.
Closes [CH-3694](https://jira.braze.com/browse/CH-3694)
---
<details>
<br>
- [ x] Check that all links work.
- [ x] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
</details>
<details>
<br>
- [Technical Documentation Style …
=> [CH-3694] Remove references to other IAM "type"s besides survey

_docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
> Adding some example use cases for Tags in Braze based on Bonfire feedback
=> Add tagging use cases

_docs/_help/release_notes.md, _docs/_help/release_notes/2021.md, _docs/_help/release_notes/2021/december.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> December 2021 Release Notes

_plugins/details_tag.rb, assets/css/_content.scss, assets/css/main.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Details style update

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add alert for User Import doc

_docs/_user_guide/engagement_tools/testing/global_control_group.md
=> Add additional details to Global Control Group and minor reformatting

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
=> Fix liquid syntax error

_docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
=> Edits based on customer/internal feedback

_docs/_user_guide/data_and_analytics/report_metrics.md
=> BD-1158: Updating Total Clicks definition 

Gemfile, Gemfile.lock
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Remove minima

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
Closes #**BD-1157**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1157: Clarify expected behavior in persistent entry properties

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md, _docs/_partners/message_personalization/dynamic_content/playable.md, _includes/archive/android/universal_deep_link_delegate.md
=> Fix capitalization for YouTube

_docs/_api/endpoints/export/user_data/post_users_segment.md
Updating docs to reflect changes to endpoint beginning Dec 1
> I'm changing these docs to reflect changes to the endpoint occurring on December 1.
- [ x] Yes (12/1/21)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update post_users_segment.md [MERGE 11/30]

_docs/_user_guide/data_and_analytics/your_reports/report_builder.md
Adding section in Report Builder for new charting functionality
> Adding a new section on building charts in Report Builder. We anticipate this being released during the week of 11/16 or 12/1. We should NOT publish these doc updates until this feature is available. Reporting's PM will reach out during the prior week to confirm release time. 
We are also waiting for a screenshot for this feature, which Reporting's PM can send over once we have it.
---
<details>
<br>
</details>
<details>
<br>
- [Technical Documentation …
=> Update report_builder.md [MERGE 11/30]

_docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md, _includes/campaign_analytics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Update Email Reporting with new analytics fields

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1164: Typo Fix

_docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1165: Company Wide Setting Removed

_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1074: CC Retry Logic

_docs/_user_guide/message_building_by_channel/content_cards/about.md, _includes/campaign_analytics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1045: Content Card Custom Reporting Warning

_docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1046: Add Method Links for SMS Subscription Group Setting

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
> I'm updating the Amplitude rate limit and link because it changed on their end
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update note about Amplitude rate limit

_docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
=> Fix duplicate descriptions in "Data doctor" learning path

_docs/_help/faqs.md, assets/js/broken_redirect_list.js
=> BD-1167: Redirect broken dashboard link

_docs/_partners/message_personalization/dynamic_content/certona.md, _docs/_partners/message_personalization/dynamic_content/judo.md, _docs/_partners/message_personalization/dynamic_content/liftigniter.md, _docs/_partners/message_personalization/dynamic_content/movable_ink.md, _docs/_partners/message_personalization/dynamic_content/worthy.md, _docs/_partners/message_personalization/localization/crowdin.md, _docs/_partners/message_personalization/localization/transifex.md, _docs/_partners/message_personalization/location/bluedot.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Partners Cleanup Pt. 3

_docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
Closes #**BD-1160**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1160: Clarify alert

_docs/_user_guide/engagement_tools/segments/regex.md
=> BD-1173: Update callout in regex tool

_docs/_help/help_articles.md, _docs/_user_guide/data_and_analytics.md, _docs/_user_guide/data_and_analytics/export_braze_data.md, _docs/_user_guide/engagement_tools/canvas.md, _docs/_user_guide/message_building_by_channel/content_cards.md, _docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/push/best_practices.md, _docs/_user_guide/message_building_by_channel/sms.md
> Content after the ending YAML in docs with `layout: dev_guide` does not generate. If possible, changed layout to `featured`, otherwise distributed missing content accordingly
---
=> Fix content not generating after YAML

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
=> BD-1172: Clarify email address validation in addition to RFC 2822 standards

_docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix capitalization issues

_docs/_user_guide/administrative/company_settings/security_settings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1175: Clarify how to turn on 2FA for a single user

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1174: Update Shopify field

_docs/_developer_guide/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Reordering Dev guide platform tiles

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1177: CC abort reason cannot be Liquid

_docs/_help/release_notes.md, _docs/_help/release_notes/2021/december.md, _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md, _includes/campaign_analytics.md
=> BD-1176: Add new analytic (Machine Opens) to December 2021 release notes 

_docs/_developer_guide/home.md, _layouts/dev_guide.html, assets/js/developer_nav.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Remember dev platform selection

_docs/_hidden/private_betas/catalog.md
Followup to https://github.com/braze-inc/braze-docs/pull/2950
Closes [ING-2759](https://jira.braze.com/browse/ING-2759)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> [ING-2759] Update Catalogs Filtered Sets Docs

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
Closes #**BD-1180**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1180: Add spacer content block

_docs/_user_guide/data_and_analytics/custom_data/nested_object_support.md, _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
Closes #**BD-1182** and #**BD-1183**
---
=> BD-1182 and BD-1183: Remove migrating ZIP file instructions and clarify Nested Objects EA

_lang/_config_fr.yml, crowdin.yml
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Update crowdin config

_docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md, _docs/_partners/message_orchestration/learning/edume.md, _docs/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md, _docs/_partners/message_personalization/dynamic_content/judo.md, _docs/_partners/message_personalization/dynamic_content/liftigniter.md, _docs/_partners/message_personalization/dynamic_content/movable_ink.md, _docs/_partners/message_personalization/dynamic_content/playable.md, _docs/_partners/message_personalization/dynamic_content/worthy.md, _docs/_partners/message_personalization/localization/crowdin.md, _docs/_partners/message_personalization/localization/transifex.md, _docs/_partners/message_personalization/location/accuweather.md, _docs/_partners/message_personalization/location/bluedot.md, _docs/_partners/message_personalization/location/foursquare.md, _docs/_partners/message_personalization/location/gimbal.md, _docs/_partners/message_personalization/location/neura_actions.md, _docs/_partners/message_personalization/location/radar.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Partner cleanup: EduMe, Rokt Calendar

_docs/_api/postman_collection.md
Closes #**BD-1181**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1181: Add link to Braze Public Workspace in Postman

_docs/_user_guide/administrative/company_settings.md, _docs/_user_guide/message_building_by_channel/email/best_practices/email_services.md, _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md, _docs/_user_guide/message_building_by_channel/email/best_practices/sunset_policies.md, _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Vertical Edits - Email Pt. 1

_docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
Closes #**BD-1185**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1185: Clarify custom keywords

_docs/_hidden/wip_partnerships/WIP_guidelines.md, _docs/_hidden/wip_partnerships/partnership_template.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Updating partner DIY template

_docs/_help/release_notes.md, _docs/_help/release_notes/2016.md, _docs/_help/release_notes/2017.md, _docs/_help/release_notes/2018.md, _docs/_help/release_notes/2019.md, _docs/_help/release_notes/2020.md, _docs/_help/release_notes/2021.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/january.md
Release notes for January 2022
=> January 2022 release notes

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/ab_testing_with_random_buckets.md
Closes #**BD-1192**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1192: Move and clarify section on campaign variant percentages

_docs/_user_guide/administrative/app_settings/developer_console/message_activity_log_tab.md
Closes #**BD-1191**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1191: Add more information about Message Activity Logs for email

_docs/_api/basics.md
Closes #**BD-1194**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1194: Add EU-02 endpoint to API Overview

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Closes #**BD-1193**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1193: Clarify frequency capping by tag

_docs/_developer_guide/platform_integration_guides/sdk_primer.md, _docs/_user_guide/data_and_analytics/tracking/email_tracking.md, _docs/_user_guide/intelligence/intelligent_channel.md, _docs/_user_guide/intelligence/intelligent_selection.md, _docs/_user_guide/intelligence/intelligent_timing.md, _docs/_user_guide/message_building_by_channel/content_cards.md, _docs/_user_guide/message_building_by_channel/content_cards/about.md, _docs/_user_guide/message_building_by_channel/push.md, _docs/_user_guide/message_building_by_channel/push/about.md, _docs/_user_guide/message_building_by_channel/sms.md, _docs/_user_guide/message_building_by_channel/sms/about_sms.md, _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md, _docs/_user_guide/onboarding_with_braze/email_setup.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content.md, _docs/_user_guide/personalization_and_dynamic_content/liquid.md
Adding links to various LAB courses in relevant articles.
=> Add links to LAB courses Pt.2

_docs/_user_guide/message_building_by_channel/in-app_messages.md, _docs/_user_guide/message_building_by_channel/in-app_messages/about.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/sms.md, _docs/_user_guide/message_building_by_channel/webhooks.md
Creating a new overview article for in-app messages
=> About in-app messages

_docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
Changing capital "A" to lowercase "a"
=> Fix capitalization of nav_title for Creating a Churn Prediction

_docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
Closes #**BD-1199**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1199: Clarify note on Total Reachable Users metric

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md, _docs/_user_guide/engagement_tools/testing/race_conditions.md
Closes #**BD-1198**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1198: Clarify `send_to_existing_only` flag can't be used with user aliases

Gemfile, Gemfile.lock
Adjusting the gemfile ruby version for vercel testing
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Adjust ruby version for Vercel

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
> Updated troubleshooting section in User Import article.
Closes #**BD-1202**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1202: Add reason for Malformed Row for User Import

_docs/_help/help_articles/email/html_looks_strange.md
> Help article refresh
Closes #**BD-1205**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1205: Update HTML help article

_docs/_partners/isv_partners/cohort_import.md
=> BD-1207: Add EU-02 endpoint to Cohort Import

_docs/_help/release_notes.md, _docs/_help/release_notes/2021/november.md, _docs/_user_guide/engagement_tools/segments/segment_extension.md
=> BD-1208: Update date for disabling extension regeneration 

_docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/email/about.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Create About page for Email

_docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
Clearer docs that would have helped for [this public issue](https://github.com/Appboy/appboy-ios-sdk/issues/328).
Rather than requiring the integrator to create their own enums, this explains the more realistic approach of defining the `appboyOptions` dictionary right before initializing the SDK
---
<details>
<br>
</details>
<details>
<br> …
=> [iOS] More direct docs for setting `ABKRequestProcessingPolicy`

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md
Closes #**BD-1212**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1212: Fix typo

_docs/_api/objects_filters/user_attributes_object.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Closes #**BD-1210**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1210: Remove mention of Braze user profile picture

_docs/_user_guide/engagement_tools/segments.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix broken tile to segment extensions page

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Removes beta banner from Exp Paths Step page for GA release on 1/11
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove beta banner

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md, _includes/rate_limits.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Update rate limit for Subscription Group endpoint

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/february.md
Release notes for February 2022
=> February 2022 Release Notes

_docs/_user_guide/engagement_tools/canvas/canvas_components.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add tile for Experiment Paths Step

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Closes #**BD-1217**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1217: Remove EA banner for Action Paths

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
Closes #**BD-1211**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1211: Clarify audience changes to scheduled campaigns

_docs/_developer_guide/platform_integration_guides/flutter.md, _docs/_hidden/private_betas/catalog.md, _docs/_partners/message_personalization/localization/crowdin.md, _docs/_partners/message_personalization/location/radar.md, _docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/engagement_tools/segments/location_targeting.md
BD-1218: Typo fixes
BD-1213: Crodwin prerequisite clarfiication
BD-1201: Updates to radar documentation
=> BD-1218, BD-1213, BD-1201

_docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
BD-1219: Temporary actions paths note added
BD-1220: Updating Audience sync images
BD-1221: Removal of docs tour links
=> BD-1219, BD-1220, BD-1221

_docs/_api/endpoints/user_data/post_user_track.md
I could be wrong, but I think `partner` is only used by Braze partners (for example Segment) and shouldn't be referenced in our public facing documentation.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Remove partner from sample /users/track payload

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md, _docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md, _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md, _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md, _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Vertical Edits - M&A Pt. 1

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md, _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
Closes #**BD-1162**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Inbox Vision for D&D Editor EA - MERGE 1/13

_docs/_api/endpoints/sms/get_query_invalid_numbers.md, _docs/_api/endpoints/sms/post_remove_invalid_numbers.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> SMS Partner updates, postman

_docs/_api/endpoints/user_data/post_user_identify.md
Updating working to be a bit more clear, following a [question from support](https://brazetechnology.slack.com/archives/C01DB7JAL1Y/p1642520269064900).
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update `/users/identify` Orphaning Docs for Clarity

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/api_triggered_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/retargeting_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Vertical Edits - M&A

_docs/_developer_guide/disclosures/security_qualifications.md
> Updating the SOC 2 review period in `security_qualifications.md` to reflect the most recent SOC 2 examination dates.
Closes #**BD-1228**
=> BD-1228: Update SOC 2 review period

assets/css/_navigation_menu.scss
=> update developer nav dropdown style

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> BD-1230: Clarify that `Converted from Canvas` filter doesn't include control group users

_docs/_api/endpoints/user_data/post_user_identify.md
=> BD-1231: Call out case sensitivity of `external_id`

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
=> BD-1229: Add platform field to Currents docs

_docs/_user_guide/engagement_tools/canvas/canvas_components/about.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
Updates to Canvas components section.
Closes #**BD-1224**
=> M&A Edits - Canvas Components

_docs/_user_guide/engagement_tools/locations_and_geofences.md, _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md, _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md, _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md, _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md, _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md, _docs/_user_guide/engagement_tools/templates_and_media.md, assets/js/broken_redirect_list.js
- Adds additional information to FAQs
- Adds cross-links to related articles
- Edits for formatting and style
- Fixes broken dashboard link
=> Location and geofence edits

_docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
Closes #**BD-1232**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1232: Update identified vs anonymous users note

_docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md, _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md, _docs/_api/endpoints/messaging/send_messages/post_create_send_ids.md
=> BD-1233: Remove section on batching from select API messaging endpoints

_docs/_hidden/other/ephemeral_custom_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Ephemeral Custom Events updates

_docs/_developer_guide/platform_wide/platform_features.md, _docs/_user_guide/message_building_by_channel.md, _docs/_user_guide/onboarding_with_braze/integration.md
=> Add blurb about messaging accessibility

_docs/_user_guide/message_building_by_channel/push/types.md
=> BD-1235: Fix silent push notification tags

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
=> BD-1234: Update IP whitelisting to make opt-in functionality more explicit

_docs/_developer_guide/platform_integration_guides/android/storage.md
=> BD-1236: Update Android SDK automatically collected data

_docs/_help/help_articles.md, _docs/_help/help_articles/api/delete_user.md, _docs/_help/help_articles/campaigns_and_canvas.md, _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md, _docs/_help/help_articles/campaigns_and_canvas/locations_data_in_campaigns.md, _docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md, _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md, _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md, _docs/_help/help_articles/push.md, _docs/_help/help_articles/push/no_push_notification_was_received.md, _docs/_help/help_articles/push/push_enablement.md, _docs/_help/help_articles/push/push_error_codes.md, _docs/_help/help_articles/push/push_token_migration.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
Updating articles based on Guru and sourcing customer feedback.
Closes #**BD-1225**
=> Article improvements

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
Update conversion tracking description sentence
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update conversion tracking

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
=> BD-1242: Add expected behavior for 0 remaining promo codes

_docs/_api/objects_filters/messaging/webhook_object.md
=> BD-1244: Update webhook object specification to recommend supplying the Content-Type header

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
=> Add web push to Push Enablement and Subscriptions page

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
https://jira.braze.com/browse/SDK-2147
- [ X] Yes (SDK 16.0.0 Sept 2, 2021)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> SDK-2147/Update deeplink docs to use BrazeDeeplinkHandler

_docs/_api/endpoints/export/user_data/post_users_segment.md, _docs/_help/help_articles/account.md, _docs/_help/help_articles/api.md, _docs/_help/help_articles/api/delete_user.md, _docs/_help/help_articles/campaigns_and_canvas.md, _docs/_help/help_articles/campaigns_and_canvas/using_event_logging.md, _docs/_help/help_articles/content_cards.md, _docs/_help/help_articles/content_cards/empty_content_card_feed.md, _docs/_help/help_articles/data.md, _docs/_help/help_articles/data/change_custom_data_type.md, _docs/_help/help_articles/data/dispatch_id.md, _docs/_help/help_articles/docs.md, _docs/_help/help_articles/email.md, _docs/_help/help_articles/email/email_bounces.md, _docs/_help/help_articles/email/html_looks_strange.md, _docs/_help/help_articles/in-app_messages.md, _docs/_help/help_articles/in-app_messages/in-app_message_impressions_appear_lower_than_expected.md, _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md, _docs/_help/help_articles/push.md, _docs/_help/help_articles/segments.md, _docs/_user_guide/message_building_by_channel/email/best_practices/email_services.md, _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md, _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md, _docs/_user_guide/message_building_by_channel/email/faq.md, _docs/_user_guide/message_building_by_channel/email/templates/email_template.md, _docs/_user_guide/message_building_by_channel/email/templates/faq.md, _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md, _docs/_user_guide/message_building_by_channel/sms/faqs.md
Article improvements that include:
- Updating Help section landing pages
- New Help articles
- More edits from customer feedback
=> Article improvements - Pt. 2

_layouts/glossary_page.html, assets/css/_glossary_page.scss, assets/js/highlight.js
Simple share option when hovering over a glossary term
Closes #**BD-1239**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Glossary share

_docs/_hidden/private_betas/catalog.md
=> BD-1248: Clarify case sensitivity in catalogs personalization

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> BD-1249: Clarify delay step expected behavior

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md, _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md, _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md, _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md, _docs/_developer_guide/platform_integration_guides/android/news_feed/read_unread_indicators.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/html_rendered_push.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md, _docs/_developer_guide/platform_integration_guides/android/sample_apps.md, _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md, _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md, _docs/_developer_guide/platform_integration_guides/unity/news_feed.md, _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md, _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md, _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
> Updating references to "com_appboy_" to "com_braze_", but only for places that would be non-breaking (mostly the braze.xml since we can fallback and look for com_appboy_)
Closes #SDK-2219
- [ x ] No
---
<details>
<br>
- [ x ] Check that all links work.
- [ x ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ x ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [ x ] Tag others as reviewers as necessary.
- [ x ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`
</details>
<details> …
=> [SDK-2219] Update all docs com_appboy xml fields to com_braze

_docs/_hidden/private_betas/catalog.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update the Max Number of Items Returned in a Filtered Set

_docs/_hidden/private_betas/link_aliasing101.md
> Creating a hidden page for Link Aliasing 101 
Closes #**BD-1247**
=> BD-1247: Link Aliasing 101

_docs/_api/objects_filters/messaging/email_object.md
=> BD-1251: Add example of attachment syntax for email object

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1241: Deltas call out

_docs/_api/endpoints/user_data/post_user_track.md
> Clarifying User Track endpoint messages for fatal vs. non-fatal
Closes #**1252**
=> BD-1252: Clarify User Track endpoint messages

_docs/_partners/message_personalization/localization/transifex.md
=> BD-1253: Add callout for Transifex API deprecation

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-1255: Add note for new data types coming this spring

_docs/_user_guide/administrative/access_braze/braze_instances.md
> Adding EU-02 to the Braze instances article in the Administrative section of the User Guide.
Closes #**BD-1258**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1258: Add missing Braze instance

_plugins/markdown_embed.rb
Change variable to determine markdown fetch
Closes #**BD-1260**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1260: Fix changelog embed config

_docs/_api/basics.md
Closes #**BD-1263**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1263: Fix link URL

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1262: Update BlueConic data syncing behavior

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-1267: Clarify custom attribute array length increase

_docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
=> BD-1264: Add definitions for Contract Details metrics

_docs/_hidden/private_betas/get_app_group_apps.md
=> BD-1261: Hidden endpoint doc for GET App Group Apps

_docs/_partners/data_and_infrastructure_agility/analytics/looker.md
Update Looker action documentation with more troubleshooting steps
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Add looker action troubleshooting

_docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Remove the opt-in note about HTML V2 which is GA

_docs/_partners/message_personalization/dynamic_content/movable_ink.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1269: Updates to Movable Ink

_docs/_hidden/private_betas/canvas_user_update.md
> Updating Canvas User Update Step article
Closes #**BD-1273**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> BD-1273: Update User Update Step

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
> I'm changing the CSV import docs to add a new section for braze_id imports because our customers often use braze_id to reimport users with a new custom attribute added as a result of exporting this data from the segmenter but sometimes get stuck on how best to do this
---
<details>
<br>
</details>
<details>
<br> …
=> Added braze_id CSV import option

_docs/_developer_guide/platform_integration_guides/ios/content_cards/data_model.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1274: Updating iOS CC property caveats

_docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1275: Updates to get_campaign_analytics example

_docs/_api/basics.md
=> BD-1278: Add Ruby client library to API docs

assets/css/_docs_search.scss, assets/css/_header.scss, assets/css/_header_search.scss, assets/css/_navigation_menu.scss, assets/css/main.scss, assets/css/search_main.scss, assets/css/search_page.scss
Adjust some colors for contrast
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Site contrast update

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Fix broken push data key links

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md, _docs/_help/help_articles/push/push_error_codes.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1280: Android Push Error Link Fix

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
> Updating Push enablement and subscription article with CSM feedback + closes straggler ticket
Closes #**BD-1200**
=> Push subscription state and enablement edits

_docs/_api/data_retention.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1283: Updates to data retention page

_docs/_developer_guide/platform_integration_guides/macOS/initial_sdk_setup.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1282: MacOS support update

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-1279: CC Cache caveat

.github/PULL_REQUEST_TEMPLATE.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Updates to pull request template

_docs/_hidden/private_betas/post_user_identify_merge_behavior.md
Closes #**BD-1288**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1288: Update user merge behavior

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Closes #**BD-1290**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1290: Remove rollout note

_docs/_partners/message_orchestration/learning/edume.md
Changing the base URL to `connect.edume.com`
Removing the carets (`<`) around variables because some customers were getting confused
@KellieHawks @timothy-kim ready for review 🙂 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update base URL & improve clarity.

_docs/_hidden/private_betas/link_aliasing.md, _docs/_hidden/private_betas/link_aliasing101.md
Closes #**BD-1287**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1287: Update Link Aliasing docs for infinite links

_docs/_user_guide/message_building_by_channel/content_cards/about.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md, _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md, _docs/_user_guide/message_building_by_channel/content_cards/testing.md
Updating image alt text and link text for Content Cards in Message Building by Channel section of User Guide
=> Alt and link text edits - Message Building by Channel - Pt. 1

Gemfile.lock
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update nokogiri to 1.13.2

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Closes #**BD-1295**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1295: Fix typo in Currents event glossary

_docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> Updating preview.md with copy from PM plus minor formatting changes
=> Update HTML preview

_docs/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md, _docs/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md, _docs/_partners/message_personalization/dynamic_content/certona.md, _docs/_partners/message_personalization/dynamic_content/judo.md, _docs/_partners/message_personalization/dynamic_content/liftigniter.md, _docs/_partners/message_personalization/dynamic_content/movable_ink.md, _docs/_partners/message_personalization/dynamic_content/wyng.md, _docs/_partners/message_personalization/localization/crowdin.md, _docs/_partners/message_personalization/localization/transifex.md, _docs/_partners/message_personalization/location/accuweather.md, _docs/_partners/message_personalization/location/bluedot.md, _docs/_partners/message_personalization/location/foursquare.md, _docs/_partners/message_personalization/location/radar.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Partners - Alt Text Pt. 1

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
We're done with the program where we were offering assistance for customers trying to upload CSVs over the size limit, so I've removed it.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove large CSV upload help offer banner

_docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
Added descriptions for prediction window and full filter mode. Changed description for Last used filters' time window constraint.
> I'm changing the sections for prediction window, full filter mode, and time window constraint because we made the changes to the product
---
<details>
<br>
</details>
<details>
<br> …
=> Updated docs for filter expansion (purchase)

_docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
Added descriptions for churn window and full filter mode. Changed description for Last used filters' time window constraint.
> I'm changing the sections for churn window, full filter mode, and time window constraint because we made the changes to the product
---
<details>
<br>
</details>
<details>
<br> …
=> Updated docs for filter expansion

_docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
Reverts braze-inc/braze-docs#3279
=> Revert "Updated docs for filter expansion"

_docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
Reverts braze-inc/braze-docs#3280
=> Revert "Updated docs for filter expansion (purchase)"

_docs/_user_guide/message_building_by_channel/sms/faqs.md
Closes #**BD-1299**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1299: Add question to SMS FAQs

_docs/_api/data_retention.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updates to the data retention doc

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1298: Adding emphasis to Amazon S3 step

_docs/_api/errors.md
Adding a warning and bolding text of the most common error code. This important code gets overlooked as it is listed last. This update will help solcons and io receive fewer support q's. co-signed by jamie
=> Fatal error code updates

_docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1281: Clarifying Roku IAM is not OOTB

_docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md, _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md, _docs/_user_guide/message_building_by_channel/email/best_practices/sunset_policies.md, _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/email/css_inline.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md, _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md, _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md, _docs/_user_guide/message_building_by_channel/email/inbox_vision.md, _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md, _docs/_user_guide/message_building_by_channel/email/templates/email_template.md, _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md, _docs/_user_guide/message_building_by_channel/email/templates/link_template.md, _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
Updating image alt text and link text for Email in Message Building by Channel section of User Guide
=> Alt and link text edits - Message Building by Channel - Pt. 2

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
Adds a note about bundle ID uniqueness to the iOS Rich Push [instructions](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/rich/).
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> iOS Rich Push instructions - add note for Bundle ID

_docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md, _docs/_partners/message_orchestration/additional_channels/direct_mail/lob.md, _docs/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md, _docs/_partners/message_orchestration/additional_channels/messaging/line.md, _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md, _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md, _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md, _docs/_partners/message_orchestration/additional_channels/retargeting/jampp.md, _docs/_partners/message_orchestration/additional_channels/retargeting/remerge.md, _docs/_partners/message_orchestration/attribution/adjust.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer_audiences.md, _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md, _docs/_partners/message_orchestration/attribution/kochava.md, _docs/_partners/message_orchestration/attribution/singular.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Message Orchestration/Canvas Sync Alt Text

_docs/_partners/message_orchestration/additional_channels/retargeting/jampp.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix link syntax issue

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/april.md
Add release notes for April 2022
=> Add April 2022 release notes

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
=> BD-1302: Fix broken link to tabbed content

_docs/_user_guide/engagement_tools/news_feed/best_practices.md, _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md, _docs/_user_guide/engagement_tools/news_feed/news_feed_analytics_and_retargeting_data.md, _docs/_user_guide/engagement_tools/news_feed/news_feed_categories.md, _docs/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
Updating image alt text and link text for News Feed in the Engagement Tools section of User Guide
=> Alt and link text edits - Engagement Tools - Pt. 1

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
Update throughput for 10DLC based on Twilio Documentation:
https://support.twilio.com/hc/en-us/articles/1260803225669-Message-throughput-MPS-and-Trust-Scores-for-A2P-10DLC-in-the-US#h_01FAKRGP4EF1X4DF02X4JCEAP0
@KellieHawks 
Closes https://brazetechnology.slack.com/archives/C01E86ZP89F/p1646764196966789
---
<details>
<br>
</details>
<details>
<br> …
=> Update 10dlc throughput.md

_docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Xamarin metadata

_docs/_home/styling_test_page.md, _includes/video.html, _layouts/redirect.html
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Loom video option

_docs/_hidden/private_betas/link_aliasing101.md
adding caveat around messages containing link templates
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> existing link templates

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
Closes #**BD-1305**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1305: Clarify frequency capping for campaigns and Canvases

_docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md, _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md, _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md, _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md, _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md, _docs/_user_guide/engagement_tools/segments/beacon_support.md, _docs/_user_guide/engagement_tools/templates_and_media/archive.md, _docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md, _docs/_user_guide/engagement_tools/templates_and_media/duplicate.md, _docs/_user_guide/engagement_tools/templates_and_media/faqs.md, _docs/_user_guide/engagement_tools/templates_and_media/media_library.md, _docs/_user_guide/engagement_tools/testing/conversion_correlation.md, _docs/_user_guide/engagement_tools/testing/global_control_group.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing.md, _docs/_user_guide/engagement_tools/testing/race_conditions.md
Updating image alt text and link text for the Engagement Tools section of User Guide
=> Alt and link text edits - Engagement Tools - Pt. 2

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Adding Amplitude loom video

_docs/_partners/message_orchestration/attribution/airbridge.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1308: Adding Facebook note on Airbridge docs

_docs/_user_guide/message_building_by_channel/sms/about_sms.md, _docs/_user_guide/message_building_by_channel/sms/campaign/create.md, _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md, _docs/_user_guide/message_building_by_channel/sms/campaign/segments.md, _docs/_user_guide/message_building_by_channel/sms/faqs.md, _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md, _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md, _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md, _docs/_user_guide/message_building_by_channel/sms/mms/create.md, _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md, _docs/_user_guide/message_building_by_channel/sms/non_native/custom_keyword_handling.md, _docs/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md, _docs/_user_guide/message_building_by_channel/sms/non_native/handling_unkown_phone_numbers.md, _docs/_user_guide/message_building_by_channel/sms/non_native/user_data_migration.md, _docs/_user_guide/message_building_by_channel/sms/phone_numbers/best_practices/multi_country_sms_sending.md, _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md, _docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md, _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md, _docs/_user_guide/message_building_by_channel/sms/user_data_migration.md, _includes/archive/short_and_long_codes.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Alt text and link text edits for SMS

_docs/_api/errors.md, _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1297: Better documentation on error codes

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
A simpler style of manifest registration for the braze push intent was made a while ago but this doc wasn't updated.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> notix/ unity android manifest update

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Gmail custom font caveat for Global Styling Settings

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
Closes #**BD-1310**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1310: Update segmentation filters for time custom attributes

vercel.json
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Set vercel cache settings

_docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1312: Update to Mixpanel cohort sync time

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Clarify Gmail custom font for GSS

_docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Removal of swift doc

_docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> IDFA is not automatically collected by Braze. It should not be in this list.

_docs/_user_guide/onboarding_with_braze/data_points.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1315: Add "Contact Settings" as subscription group data point type

_docs/_api/endpoints/user_data/post_user_delete.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1316: Update post user delete example request

_docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1320: Update SDK Links for SMS docs

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1318: Remove line from campaign endpoint example

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/api_triggered_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md, _docs/_user_guide/engagement_tools/campaigns/faq.md, _docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/active_user_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/getting_high_ratings.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/retargeting_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md, _docs/_user_guide/engagement_tools/campaigns/testing_and_more/ab_testing_with_random_buckets.md
> Updating image alt text and link text for Campaigns in Engagement Tools section of User Guide
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …
=> Alt and link text edits - Campaigns

_docs/_user_guide/engagement_tools/news_feed/news_feed_use_cases.md
I'm changing `news_feed_use_cases.md` because there was a line of copy that appeared out of place. I cleared my change with @bre-fitzgerald prior to opening this PR.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix misplaced copy in news_feed_use_cases.md

_plugins/jekyll_asset_pipeline.rb
Should prevent broken css from happening due to CDN caching unless we change the css or javascripts.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Jekyll Asset Pipeline's hash method

_docs/_developer_guide/platform_wide/sdk_authentication.md
> I'm changing some text in SDK Auth docs because of typos
No issue for this change
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Tweak sdk auth typos

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Broken link redirect fix

assets/css/_dev_guide.scss
Fix link styling for features page.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix feature link styling

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/zeotap.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1322: Add Zeotap Output identifier

_docs/_partners/message_orchestration/learning/edume.md
Three changes being made:
1. Change capitalisation from EduMe to eduMe following our rebrand
2. Add clarity on the group vs team ID parameter to be provided 
3. Minor copy tidy up
@timothy-kim @KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Amend edume.md

.github/PULL_REQUEST_TEMPLATE.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Vertical Updates in PR Issue Template - MERGE 3/31

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
Closes #**BD-1306**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1306: Clarify Canvas advancement

_docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1326: Fix Liquid Example

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md, _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
> Adding sections on "Managing custom attributes" and "Managing custom events" to the respective articles based on a user question on how to create them in Braze.
---
=> Add how to create events and attributes in Braze

_docs/_user_guide/engagement_tools/segments/regex.md
=> BD-1333: Clarify regex modifiers in regex debugger callout

_docs/_api/objects_filters/user_attributes_object.md
Closes #**BD-1331**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1331: Clarify supported time formats for User attributes object

_docs/_api/endpoints/export/user_data/post_users_segment.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1332: Add note about GCS to users export segment endpoint

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/may.md, _docs/_help/release_notes/deprecations.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add May 2022 release notes

_docs/_partners/message_personalization/localization/crowdin.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Crowdin prerequisites endpoint type

_docs/_api/objects_filters/purchase_object.md
=> BD-1327: Update webhooks link in purchase_objects.md to direct to Braze to Braze webhooks

_docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
=> Clarify tile metric layout in email performance dashboard

_docs/_docs_pages/404_api.md
Fix issue with 404 page in API directory
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> 404 Page for API

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md
=> BD-1335: Add image specifications for each channel to Media Library

_docs/_partners/message_personalization/localization/transifex.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Transifex version update language edits

_docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1338: Talon.One platform updates

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
=> BD-1339: Update email parameter description in /subscription/status/set endpoint

_docs/_hidden/misc_reference/x-in-y-behavior.md, _docs/_hidden/other/airship_migration.md, _docs/_hidden/other/braze faqs.md, _docs/_hidden/other/core_endpoints.md, _docs/_hidden/other/generations.md, _docs/_hidden/other/user_csv_lambda.md, _docs/_hidden/private_betas/canvas_in-app_messages.md, _docs/_hidden/private_betas/canvas_user_update.md, _docs/_hidden/private_betas/get_campaign_url_info.md, _docs/_hidden/private_betas/get_canvas_url_info.md, _docs/_hidden/private_betas/link_aliasing.md, _docs/_hidden/private_betas/view_pii.md
=> Alt link and text edits - Hidden folder

_docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/handing_in_app_display.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1168: Add Swift Methods for iOS IAM display handling

_docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md, _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md, _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md, _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1336: Update SAML SSO setup steps to include RelayState parameter

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1254: Segment FAQ Update

_docs/_user_guide/engagement_tools/campaigns/getting_started/campaign_basics.md, _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
> I'm changing https://www.braze.com/docs/user_guide/engagement_tools/campaigns/getting_started/campaign_basics/ and https://www.braze.com/docs/user_guide/engagement_tools/canvas/get_started/the_basics/ because they list Action-Based under the bullet for Scheduled sending, which will be confusing to users
Closes n/a
---
<details>
<br>
</details>
<details>
<br> …
=> Remove Action-Based examples from Scheduled bullet

_docs/_api/postman_collection.md, _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/read_and_unread.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md, _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md, _docs/_developer_guide/platform_wide/sdk_authentication.md, _docs/_developer_guide/platform_wide/sending_test_messages.md, _docs/_hidden/wip_partnerships/partnership_template.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md, _docs/_partners/data_and_infrastructure_agility/support/zendesk.md, _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md, _docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md, _docs/_partners/message_orchestration/additional_channels/direct_mail/optilyz.md, _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md, _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md, _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md, _docs/_user_guide/engagement_tools/segments/creating_a_segment.md, _docs/_user_guide/engagement_tools/segments/segment_extension.md, _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove directional language: left

_docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
Minor updates to the required permissions Hightouch require and the updated setup process in Hightouch as per conversations I've had with @ernestcheng (Hightouch head of platforms).
---
<details>
<br>
</details>
<details>
<br> …
=> Update Hightouch permissions and setup instructions

_docs/_api/endpoints/email/get_list_hard_bounces.md, _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md, _docs/_api/endpoints/sms/get_query_invalid_numbers.md, _docs/_api/endpoints/user_data/post_user_track.md, _docs/_api/objects_filters/connected_audience.md, _docs/_developer_guide/platform_integration_guides/android/content_cards/implementation_guide.md, _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md, _docs/_developer_guide/platform_wide/analytics_overview.md, _docs/_hidden/other/user_csv_lambda.md, _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_user_profile_api.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe.md
=> Table edits for accessibility

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md
=> BD-1348: Clarify Inbox Vision requirements

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1347: Update Liquid templating example for nested custom attribute

_docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
Closes #**BD-1346**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1346: Add warning to external ID migration process

_docs/_hidden/private_betas/email_history.md
Fixing a typo
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general …
=> Fix a typo

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/implementation_guide.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/custom_styling.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/read_and_unread.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/defining_a_news_feed_category.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md, _docs/_hidden/other/braze_support.md, _docs/_partners/message_orchestration/learning/edume.md, _docs/_partners/message_personalization/localization/transifex.md, _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
=> Fix YAML typos

_docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md, _docs/_developer_guide/platform_wide/sending_test_messages.md
Caught one more instance I needed to update.
=> BD-1349 Pt. 2

_docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
=> Update Email settings doc

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md, _docs/_api/objects_filters/canvas_entry_properties_object.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
=> BD-1355: Clarify Canvas entry properties object size limit 

_docs/_user_guide/engagement_tools/campaigns/faq.md, _docs/_user_guide/engagement_tools/canvas/faqs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add FAQ entry about audience vs. trigger behavior

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Email preference center documentation

Gemfile, Gemfile.lock
Update to Jekyll 4.2.2
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Jekyll 4 update

_docs/_api/api_campaigns.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update api_campaigns.md, fixing redundant alias link

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Noting "equals" string filter is case sensitive

_docs/_api/endpoints/export/user_data/post_users_identifier.md
Closes #**BD-1366**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1366: Typo in /users/export/ids endpoint

_docs/_developer_guide/platform_wide/analytics_overview.md
=> BD-1364: Fix typo in Analytics overview doc

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md, _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/troubleshooting.md, _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md, _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md, _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md, _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
I'm changing referenced to certain "Appboy" classes that have now been removed and replacing them with the correct "Braze" classes. These were deprecated before, but are now removed, so doc updates could occur at anytime.
Closes # SDK-2501
- [X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Replace removed Appboy classes with Braze classes in docs

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1371: Remove header references for email preference center

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> xml example for notification channel name and description

_docs/_help/release_notes.md, _docs/_help/release_notes/2022/april.md, _docs/_help/release_notes/deprecations.md, _docs/_help/release_notes/deprecations/grouparoo.md, _docs/_partners/data_and_infrastructure_agility.md, _docs/_partners/data_and_infrastructure_agility/workflow_automation.md, _docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Removal of Grouparoo partnership

_docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md
https://github.com/braze-inc/in-app-message-templates
=> replaced html template link

_docs/_user_guide/onboarding_with_braze/data_points.md
=> BD-1368: Update Data Points to differentiate manually and automatically collected consumption

_docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
=> BD-1374: Clarify time zone for <date> field

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Users with campaign access permissions can now duplicate campaign and canvas drafts, a privilege that was previously reserved for users with send campaign permissions.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update permissions for campaign duplication - MERGE 5/3

_includes/header.html, assets/css/_braze_header.scss, assets/css/_doc_guide.scss, assets/css/_header.scss, assets/css/main.scss, assets/js/documents.js
Update header to match braze.com closer
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update header to match braze.com

_docs/_partners/message_personalization/dynamic_content/movable_ink.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Clarify Movable Ink Step: BD-1373, BD-1376

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
> Fixing broken tabs on Android integration page 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add local to tab

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/june.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> June 2022 Release Notes

assets/css/_docs_search.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix main search results overlap

_docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
=> BD-1377: Remove extraneous brackets from request body in transactional email endpoint

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
=> BD-1358: Update Message Steps doc GA

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
=> BD-1370: Clarify dispatch_id in response details of /campaigns/trigger/send

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/duplicating_segments_and_campaigns.md
=> Move Campaign approval doc

_docs/_help/release_notes.md, _docs/_help/release_notes/2022/june.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add campaign approval to release notes

_docs/_user_guide/engagement_tools/canvas/canvas_components.md
=> Remove Canvas LAB Playbook mention

_docs/_hidden/private_betas/link_aliasing.md
=> Clarify link templates for link aliasing

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
=> Clarify feature availability for Persistent entry properties 

_docs/_developer_guide/platform_wide/braze_actions.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
=> web versions

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add kotlin coroutines dependency

_docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
=> BD-1382: Add tip for email editor selection

_docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
Closes #**BD-1383**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1383: Update recipient within Transactional API endpoint

_docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
Updating Heap data import/export description
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or …
=> Heap: update data import/export descriptions

_docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/badges.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/customization/key_value_pairs.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/multiple_feeds.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/custom_styling.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/message_dismissal.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/badges.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/customization/key_value_pairs.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md, _docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md, _docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> WebSDKv4 updates

_includes/analytics.html, assets/js/contentcards.js
@davidbielik does this look good? 
Think my main question is if this is correct:
appboy.display.automaticallyShowNewInAppMessages => braze.automaticallyShowInAppMessages
---
<details>
<br>
</details>
<details>
<br> …
=> Update Braze Web SDK

_docs/_help/help_articles/api/delete_user.md
Closes #**BD-1384**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1384: Fix broken link

_docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
clarify `serviceWorkerLocation` option
=> serviceWorkerLocation

_docs/_hidden/private_betas/canvas_v2_cloning.md
=> Update Cloning Canvases doc with CSM feedback

_docs/_user_guide/message_building_by_channel/email/faq.md
=> BD-1387: Remove troubleshooting info from Email FAQ

_docs/_user_guide/onboarding_with_braze/email_setup/ip_warming.md
=> BD-1389: Clarify not to use Intelligent Timing for IP warming

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
=> Fix typo for Update users’ subscription group status doc 

_docs/_api/api_key.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
We renamed constants from APPBOY_ to BRAZE_, and updating the corresponding docs.
Closes # SDK-2496
- [ X ] Yes (Next Android Release (June?))
---
<details>
<br>
- [ x ] Check that all links work.
- [ x ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ x ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the interal reviewing chart to tag the appropriate reviewer.
- [ x ] Tag others as reviewers as necessary.
- [ x ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`
</details>
<details> …
=> Sdk 2496 update to braze constants

_docs/_hidden/private_betas/canvas_v2_101.md
=> Update Canvas V2 101 doc with customer feedback

_docs/_developer_guide/platform_wide/braze_actions.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
=> braze actions

_docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md
=> BD-1395: Clarify Archiving Canvases doc

_docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md, assets/js/broken_redirect_list.js
Closes #**BD-1397**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1397: Fix broken link

_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh.md
=> BD-1396: Clarify webhook template for Punchh doc

_docs/_api/endpoints/export/user_data/post_users_segment.md
=> BD-1394: Clarify data export for Users by segment endpoint

Gemfile.lock
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update rack ver

_docs/_user_guide/onboarding_with_braze/data_points.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Data Points doc

_docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> Adding alerts for updates to the underlying engine for the Drag & Drop Editor.
---
=> Add updated HTML engine info for DND doc

_docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md, _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1385: Update keyword category value - MERGE 5/18

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/july.md
=> July 2022 Release Notes

_docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1404: Update AppsFlyer code snippets

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1403: Clarify promotion code behavior for multichannel campaigns

_docs/_hidden/private_betas/save_messages.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Save Messages Feature - EA

_docs/_help/release_notes/2022.md
=> Fix link for release notes

_docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md, _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md, _includes/rate_limits.md
=> Update transactional email docs based on NPS feedback

assets/css/_braze_header.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update header spacing

_docs/_hidden/private_betas/post_user_identify_merge_behavior.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1406: Updated post user identify merge behavior

_docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1372: Adding integration specifications for CC Web SDK

_docs/_partners/message_personalization/dynamic_content/movable_ink.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1409: Clarifying Movable Ink integration steps

_docs/_help/help_articles/api.md, _docs/_help/help_articles/api/attribute_name_id_across_sources.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
=> BD-1413: New help article for how campaign and Canvas attributes name/IDs differ across sources

_docs/_user_guide/message_building_by_channel/email/templates/faq.md, _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md, _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
=> Move Link aliasing doc to left nav

_docs/_hidden/private_betas/save_messages.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Minor tweak to rendered messages.

_docs/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md
> Reformats list of possible errors as a table. Slightly rewords troubleshooting to be imperative rather than descriptive (i.e., "Change X to Y" instead of "X must be Y").
=> Reformat error list as table for readability

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1416: Update required BlueConic API key permissions

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/archiving_campaigns.md
=> BD-1414: Clarify Archiving campaigns

_docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md, _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md, _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
> Continuation of #3637. Also resolves discrepancy for `include_inclusion_data` value in `/content_blocks/info`.
=> Reformat error list as table for readability pt.2

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
=> BD-1415: Clarify push enabled segmentation filter

_docs/_api/endpoints/export/segments/get_segment_analytics.md, _docs/_api/endpoints/export/segments/get_segment_details.md, _docs/_api/endpoints/export/user_data/post_users_segment.md, _docs/_api/endpoints/sms/post_remove_invalid_numbers.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md, _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Misc endpoint edits

_docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md, _docs/_api/endpoints/templates/email_templates/post_create_email_template.md, _docs/_api/endpoints/templates/email_templates/post_update_email_template.md
> Continuation of #3637 and #3640
=> Reformat error list as table for readability pt.3

_docs/_user_guide/engagement_tools/canvas/canvas_components.md
=> Add Canvas components tile

_docs/_developer_guide/platform_integration_guides/android/android_13.md, _docs/_developer_guide/platform_wide/braze_actions.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
updates braze action version and release date
=> update android versions

_docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Fixing a broken link to the embedded github code in Step 1 (correct link is https://raw.githubusercontent.com/braze-inc/braze-web-sdk/master/sample-builds/cdn/service-worker.js, current link is https://raw.githubusercontent.com/braze-inc/braze-web-sdk/master/sample-build/service-worker.js)
> I'm changing the link to the embedded github code in step 1
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB- …
=> Fixing Broken Link

_docs/_hidden/private_betas/post_update_user_subscription_group_status_v2.md
=> BD-1388: Create doc for Update users’ subscription group status V2 endpoint

_docs/_hidden/private_betas/catalog.md, _docs/_user_guide/personalization_and_dynamic_content.md, _docs/_user_guide/personalization_and_dynamic_content/catalog.md, _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md, _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md, assets/download_file/sample_sunglasses_catalog.csv
Closes #**BD-1418**,  #**BD-1420**, #**BD-1421**, #**BD-1423**
---
=> Move Catalog EA docs out from hidden folder

_docs/_api/endpoints/export/user_data/post_users_global_control_group.md, _docs/_api/endpoints/export/user_data/post_users_identifier.md, _docs/_api/endpoints/export/user_data/post_users_segment.md, _docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases.md, _docs/_api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md, _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md, _docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md, _docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_messages.md, _docs/_api/endpoints/messaging/send_messages/post_create_send_ids.md, _docs/_api/endpoints/messaging/send_messages/post_send_messages.md, _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md, _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md, _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md, _docs/_api/endpoints/user_data/post_user_alias.md, _docs/_api/endpoints/user_data/post_user_delete.md, _docs/_api/endpoints/user_data/post_user_identify.md, _docs/_api/endpoints/user_data/post_user_track.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> fixing coding syntax on API endpoints

_docs/_api/api_limits.md, _docs/_api/objects_filters/purchase_object.md, _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md, _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md, _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md, _docs/_help/help_articles/account/locked_out.md, _docs/_help/release_notes/2018/april.md, _docs/_help/release_notes/2020/august.md, _docs/_hidden/other/braze faqs.md, _docs/_hidden/private_betas/get_app_group_apps.md, _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md, _docs/_partners/message_personalization/dynamic_content/movable_ink.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md, _docs/_user_guide/message_building_by_channel/content_cards.md, _docs/_user_guide/message_building_by_channel/email/templates/link_template.md, _docs/_user_guide/message_building_by_channel/sms.md, _docs/_user_guide/message_building_by_channel/sms/non_native/custom_keyword_handling.md, _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
=> Standardize styling for "customer success manager" and "account manager"

_docs/_api/endpoints/export/campaigns/get_campaign_analytics.md, _docs/_api/endpoints/export/campaigns/get_send_analytics.md, _docs/_api/endpoints/export/canvas/get_canvas_analytics.md, _docs/_api/endpoints/export/canvas/get_canvas_analytics_summary.md, _docs/_api/endpoints/export/custom_events/get_custom_events_analytics.md, _docs/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md, _docs/_api/endpoints/export/kpi/get_kpi_dau_date.md, _docs/_api/endpoints/export/kpi/get_kpi_mau_30_days.md, _docs/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md, _docs/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md, _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
=> Update "max" to "maximum"

_docs/_developer_guide/platform_integration_guides/android/android_13.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Android upgrade guide link fix

_docs/_help/faqs.md, _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md, _docs/_user_guide/message_building_by_channel/content_cards/best_practices.md, _docs/_user_guide/message_building_by_channel/content_cards/best_practices/know_before_send.md, _docs/_user_guide/message_building_by_channel/email/best_practices.md, _docs/_user_guide/message_building_by_channel/email/best_practices/know_before_send.md, _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices.md, _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/know_before_send.md, _docs/_user_guide/message_building_by_channel/push/best_practices.md, _docs/_user_guide/message_building_by_channel/push/best_practices/know_before_send.md, _docs/_user_guide/message_building_by_channel/sms/best_practices.md, _docs/_user_guide/message_building_by_channel/sms/best_practices/know_before_send.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Know before send GA docs, added to best practices

_docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
=> BD-1424: Fix broken link

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Android 13 note in know before send doc

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
=> BD-1425: Clarify segmentation supports max one level of array nesting

_docs/_api/objects_filters/trigger_properties_object.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
This adds more nested properties to the documentation so it is more clear that it is supported.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Some more demonstrations of nested trigger properties in the documentation.

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-1428: Update max file size for CSV import to 500MB 

_docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1422: IAM Version callout

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
=> BD-1434: Fix typo

_includes/left_nav_menu.html, _layouts/doc_guide.html
=> Update LAB to Braze Learning pt.2

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md
> I'm changing the message schedule API docs to include a sample response to show the schedule_id value that can be used to cancel the scheduled message in the future
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Added response to schedule message endpoint

_docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md, _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1439: iOS dev deep link link fixes

_docs/_api/endpoints/user_data/post_user_identify.md
=> BD-1444: Clarify /users/identify merge behavior and link to data collection best practices

_includes/search_page.html, assets/js/algolia_header_search.js, assets/js/algolia_main_search.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update search learning image

_docs/_user_guide/engagement_tools/segments/regex.md
I'm changing this description and will link to the tooltip here https://github.com/Appboy/platform/pull/43608 because it was requested for clarity https://brazetechnology.slack.com/archives/C01E86ZP89F/p1655455058679589?thread_ts=1655199236.066719&cid=C01E86ZP89F. Instead of modifying the tooltip would rather update docs and link to docs. Would really like feedback on the wording.
Will tag SMS team reviewers once wording is finalized.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …
=> Update regex rules for custom trigger event properties

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
Closes #**BD-1445**, #**BD-1446**
---
=> BD-1445, BD-1446: Update campaign approval and add DND block type

_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1411: Archived nested segment behavior

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
=> Update segment filter for link aliasing

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
Reverts braze-inc/braze-docs#3710
=> Revert "Update segment filter for link aliasing"

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Canvas_entry_property clarifications

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
changed () to {} to fix typos
changed () to {} to fix typos
- [ X] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fixed Typos

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
Reverts braze-inc/braze-docs#3720
=> Revert "BD-1450: Fix brackets"

_docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1452: Add Integration demo video

_docs/_developer_guide/platform_wide/tv_and_ott.md
=> add note on HTLM IAM for fire/androidtv

_docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/ios_sdk_integration.md
I fix a title typo in the integration guide.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix typo from motification to notification

_docs/_hidden/private_betas/snowflake_integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Snowflake beta

_docs/_partners/isv_partners/currents_integration.md
=> BD-1457: Add missing comma to code snippet

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1459: Update shopify requirements

_docs/_developer_guide/platform_integration_guides/android/android_13.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix missed merge issues

_docs/_api/objects_filters/messaging/email_object.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1460: Add attachment types for email object

_docs/_developer_guide/platform_integration_guides/flutter/analytics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1448: Add Flutter analytics methods

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1461: Update CC Limits in know before send doc

_docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1468: Add note about Purchase events now supporting array event properties

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md, _docs/_hidden/misc_reference/x-in-y-behavior.md, _docs/_hidden/other/support_contact.md, _docs/_hidden/private_betas/canvas_in-app_messages.md, _docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md, _docs/_user_guide/engagement_tools/campaigns/faq.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md, _docs/_user_guide/engagement_tools/canvas/faqs.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md, _docs/_user_guide/intelligence/faqs.md, _docs/_user_guide/intelligence/intelligent_timing.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md, _docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Style edits for times

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-1471: Array of objects and nested custom attributes GA

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
=> Add fallback font section

_includes/feedback.html, assets/js/feedback.js
Update feedback to only have Yes and No, and always show feedback submission.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update feedback flow

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
=> BD-1476: Add EA banner

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Dashboard Redirect

_docs/_user_guide/intelligence/faqs.md
=> Fix capitalization and spelling in intel FAQ

_docs/_user_guide/intelligence/intelligent_timing.md
=> Add Canvas Flow info for Intelligent Timing doc

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
=> Clarify web font for email global style settings

_config.yml, _includes/html_include.html, assets/js/documents.js
Add option to limit or expand the right hand table of content header list.
Markdown Frontmatter Usage:
```
toc_headers: "h2"
```
Default is "h2, h3"
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Table of Content Header Feature

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
=> BD-1472: Update local part validation rules

_docs/_hidden/other/onboarding_faq.md, _docs/_user_guide/onboarding_faq.md, _layouts/onboarding_faq.html
> Filterable and searchable FAQ for post-onboarded customers. Categories are Analytics, Campaigns, Canvases, Segments, and Users.
Closes #**BD-1469**
---
=> BD-1469: Add filterable FAQ page

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1478: Update Shopify money property from string to number

_docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1477: Azure AD Update

_docs/_user_guide/administrative/manage_your_braze_users/adding_users_to_your_dashboard.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1483: Clarify admin expectations

_docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
=> BD-1484: Additional guidance on random bucket numbers in Audience Paths

_docs/_developer_guide/platform_wide/app_group_configuration.md, _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
=> BD-1475: Clarify sending to a single app

_docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
I'm adding clarification that users should not update the version of the Android SDK that is used by other SDK (Cordova, Flutter, etc).
Closes SDK-2683
- [X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Tell users to not change version of wrapper SDK's

_docs/_help/release_notes/2022/september.md, _docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1486: Update Azure AD user attributes & Release notes update

_docs/_help/help_articles/api/delete_user.md, _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md, _docs/_user_guide/administrative/manage_your_braze_users/deleting_users_from_your_account.md, _docs/_user_guide/engagement_tools/canvas/faqs.md
=> Doc edits for KB summary

_docs/_api/data_retention.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
I'm changing phrasing around data retention to be more descriptive. I will merge this in once approved, please don't merge it for me.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update the wording around data retention to be more descriptive.

.vercel/build.js, _data/l8n.yml, _lang/_config_fr.yml, _plugins/multi_lang_include.rb
Some changes to prep docs for translation.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Transperfect PR prep

_docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
Updated the capitalization for the logCustomEvent sample code to capitalize Braze to avoid errors when copying and pasting.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …
=> Fixing capitalization

_docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
“All in-app messages that a user is eligible for are delivered to the user’s device on session start.” alone makes it sound like session start is a special case where all eligible messages will be delivered. Including in cases where multiple in-app messages are triggered by the same event.
I think "All in-app messages that a user is eligible for are delivered to the user's device on session start. In the case of 2 in-app messages being triggered by 1 event the in-app message with the higher priority will be shown." is clearer and avoids confusion.
---
<details>
<br>
</details>
<details> …
=> Make the description slightly clearer

_docs/_user_guide/engagement_tools/campaigns/testing_and_more.md, _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md, _docs/_user_guide/message_building_by_channel/content_cards/best_practices.md, _docs/_user_guide/message_building_by_channel/email/best_practices.md, _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md, _docs/_user_guide/message_building_by_channel/email/css_inline.md, _docs/_user_guide/message_building_by_channel/email/faq.md, _docs/_user_guide/message_building_by_channel/email/inbox_vision.md, _docs/_user_guide/message_building_by_channel/email/templates/email_template.md, _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices.md, _docs/_user_guide/message_building_by_channel/push/best_practices.md, _docs/_user_guide/message_building_by_channel/sms/best_practices.md, _docs/_user_guide/onboarding_with_braze/integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> KB Article updates

_docs/_user_guide/engagement_tools/campaigns/faq.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> Doc edits for KB summary - Pt. 2

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_persistent_entry_properties.md
=> Remove beta alert

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md
=> Clarify devices for Inbox Vision

_docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
…e condition
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> BD-1479: Update user data colletion best practices to account for race conditions

_docs/_user_guide/message_building_by_channel/push/android/notification_channels.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1491: Clarify notification channel selection behavior

_docs/_developer_guide/disclosures/security_qualifications.md
> Additional edits per request
=> BD-1487: ISO certification updates (pt.3)

_docs/_user_guide/onboarding_with_braze/data_points.md
=> BD-1495: Restructure data point tables for clarity between billable and non-billable data points

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/12_14_21.md, _docs/_help/release_notes/2022/1_11_22.md, _docs/_help/release_notes/2022/2_8_22.md, _docs/_help/release_notes/2022/3_8_22.md, _docs/_help/release_notes/2022/4_5_22.md, _docs/_help/release_notes/2022/5_31_22.md, _docs/_help/release_notes/2022/5_3_22.md, _docs/_help/release_notes/2022/6_28_22.md, _docs/_help/release_notes/2022/7_26_22.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Swap release notes from month to release date

_plugins/sdk_min_versions_tag.rb
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updating sdk_min_version

_docs/_developer_guide/platform_wide/analytics_overview.md
=> BD-1500: Clarify max custom attribute array size
