_docs/_api/data_retention.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1502: Update data retention page

_docs/_hidden/private_betas/shopify/shopify_data.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1498: Add user alias object payload

_docs/_help/release_notes/2022/12_14_21.md, _docs/_help/release_notes/2022/1_11_22.md, _docs/_help/release_notes/2022/2_8_22.md, _docs/_help/release_notes/2022/3_8_22.md, _docs/_help/release_notes/2022/4_5_22.md, _docs/_help/release_notes/2022/5_31_22.md, _docs/_help/release_notes/2022/5_3_22.md, _docs/_help/release_notes/2022/6_28_22.md, _docs/_help/release_notes/2022/7_26_22.md, _docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md, _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md, _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md, _docs/_partners/message_personalization/localization/lokalise.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
=> Hidden partner fix and link fix

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
> I'm changing the Android Manual push registration because...
Android SDK 22.0.0 updated the method:
- Braze.registerPushToken()/Braze.getRegisteredPushToken() is now Braze.setRegisteredPushToken()/Braze.getRegisteredPushToken(). If using Kotlin, use the property Braze.registeredPushToken.
-
---
<details>
<br>
</details>
<details>
<br> …
=> Update Android manual push registration

_docs/_api/basics.md
=> replace windows with web link

_docs/_hidden/private_betas/snowflake_integration.md
The Cloud Ingestion product is now in EA instead of Beta, so updated docs accordingly. I also added additional IPs for the EU region as we expanded the product to support all regions.
> I'm changing references to beta to EA, and adding EU region info
Closes # N/A
- [X ] Yes (**8/4**) - not new release but changing status of release
---
<details>
<br>
- [X ] Check that all links work.
- [ X] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [X ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the interal reviewing chart to tag the appropriate reviewer.
</details>
<details>
<summary>⭐ …
=> Beta to EA update

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Broken link fixes

_docs/_user_guide/data_and_analytics/export_braze_data.md, _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Message archiving GA

_docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/android_tv_push.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_broadcast_receiver.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/customization/advanced_settings.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/silent_push_notifications.md, _docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md, _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
Updates docs for new SDK API method
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Android - updated docs for new push notification event callback

_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1504: Add Tealium to customer data partners

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Liquid use case library

_docs/_developer_guide/platform_wide/sending_test_messages.md
> I'm adding some of the limitations I have noticed when using Test Messages. to help others when troubleshooting.
Closes NO KNOWN ISSUE
- [ X ] No
---
<details>
<br>
- [ X ] Check that all links work.
- [ X ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
</details>
<details>
<br> …
=> Limitations of Test Messages

assets/js/broken_redirect_list.js
=> BD-1513: Broken dashboard link

_docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
=> Remove limitation for cloning Canvases feature

_docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
=> push tag manager

_docs/_user_guide/message_building_by_channel/sms/faqs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1518: Add additional context to SMS FAQ subscription

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
=> BD-1517: Clarify number of tracked links limitation

_docs/_user_guide/personalization_and_dynamic_content/liquid.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
Closes #**BD-1474**, #**BD-1506**
---
=> BD-1474: Add new filters and tags for Liquid 5 

_docs/_hidden/other/documentation_request.md
Add confirmation processing message to request submission
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Request submission process message

.vercel/build.js, _lang/_config_fr.yml
Fix build preview between languages
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix language build

_includes/header.html
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix banner overlapping search

_docs/_api/objects_filters/purchase_object.md, _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/cordova/cordova_integration.md, _docs/_developer_guide/platform_integration_guides/flutter/analytics.md, _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/react_native/analytics.md, _docs/_developer_guide/platform_integration_guides/roku/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/swift/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/unity/Analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/windows_universal/analytics/logging_purchases.md, _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md, _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
;:
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1509: Add order level guidance for logging purchases

_docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1511: Clarify Flex CSS Web behavior

_docs/_developer_guide/disclosures/security_qualifications.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1523: Update SOC 2 date and text

_docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md
Updating documentation to show new way to bring the api_key.txt into a project due to new Unity updates.
Closes # SDK-2811
- [ X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-2811] FireOS apikey document updates

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1526: Fix tabs and add more emphasis to capturing time properties

_docs/_api/api_limits.md
=> BD-1524: Make callout for optimal delay between endpoint calls more visible 

_docs/_developer_guide/platform_integration_guides/web/smart_tvs.md
> Adding a note to OTT documentation that using CDN version of web sdk is preferred (and reason why)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> Add web SDK note to OTT documentation

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
I noticed these casing errors while working on something else.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Correct uppercase/lowercase

_docs/_user_guide/intelligence/intelligent_channel.md
=> Update intelligent_channel.md for clarity

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md, _docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Braze capitalization fix

_docs/_partners/data_and_infrastructure_agility.md, _docs/_partners/data_and_infrastructure_agility/data_privacy.md, _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md, _docs/_partners/data_and_infrastructure_agility/data_privacy/transcend.md, _docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> DataGrail Partnership Documentation

_docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Hiding Datagrail for ad hoc deploy

_docs/_partners/data_and_infrastructure_agility/analytics/actionableme.md, _docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md, _docs/_partners/data_and_infrastructure_agility/data_privacy/datagrail.md, _docs/_partners/message_orchestration/channel_extensions/email_templates/iam_studio.md, _docs/_partners/message_personalization/localization/lokalise.md
GA: storyly, datagrail, lokalise, IAM studio, actionable.me
=> GA new Braze partners

_docs/_user_guide/personalization_and_dynamic_content/catalog.md
=> BD-1529: Update catalogs example

_docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases.md
> I'm changing request example because it's incorrect (see [doc](https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases/))
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> fix: correct request example

_docs/_api/objects_filters/purchase_object.md
=> BD-1534: Update purchase object example

_docs/_hidden/private_betas/canvas_user_update.md
=> BD-1535: Edit alert

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
=> Add alert for Canvas entry properties and event properties

_docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
=> BD-1539: Update money_with_currency to unsupported

_docs/_user_guide/personalization_and_dynamic_content/catalog.md
=> BD-1542: Update process for upgrading to Catalogs Pro

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
> I'm changing..... example request... because... the double quotes are invalid (see [doc](https://www.braze.com/docs/api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2/#example-request-email))
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> fix: correct double quotes in example request

_docs/_user_guide/message_building_by_channel/in-app_messages/testing.md
=> BD-1536: Clarify warning alert

_docs/_api/objects_filters/connected_audience.md, _docs/_api/objects_filters/event_object.md, _docs/_api/objects_filters/recipient_object.md, _docs/_api/objects_filters/trigger_properties_object.md, _docs/_api/objects_filters/user_alias_object.md, _docs/_api/objects_filters/user_attributes_object.md
=> Style edits for Objects docs

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
> I'm changing Currents documentation to reflect currently supported event types and fields
- Adds canvas information to Amplitude events
- Adds email.SoftBounce for mParticle
~Closes #**ISSUE_NUMBER_HERE**~
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add soft bounce for mParticle, canvas information for Amplitude

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
=> Edit custom font with feedback

_docs/_hidden/private_betas/patch_catalog_items.md, _docs/_hidden/private_betas/post_catalog_items_patch.md, assets/css/_api.scss
=> BD-1531: Hidden doc for Catalogs API

_docs/_api/objects_filters/purchase_object.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1547: Update variable requirement for purchase object

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1540: Clarify filter behavior

_docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
Just fixing some typos
- [ X] No
---
<details>
<br>
- [X ] Check that all links work.
- [ X] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
</details>
<details>
<br> …
=> Fix Typos in Liquid

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md, _includes/archive/in_app_message.md
=> BD-1552: Explicitly state that IAMs can't be triggered by purchase events

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Added instructions on setting google-services.json file for expo
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> updated expo android config docs

_docs/_hidden/private_betas/card_creation.md
objc-4.5+ and all versions of swift that have content cards are now supported. so simplifying this to just 4.5+ for ios
=> dynamic cards ios version

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-1556: Add that the regenerate schema option (NCA) will only be allowed once every 24 hours

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
=> fix permission options

.github/PULL_REQUEST_TEMPLATE.md, _docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
> I'm changing the Avro write threshold to inform customers that we can write files up to 100k events during heavy load to match expected behavior
~Closes #**ISSUE_NUMBER_HERE**~
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Clarify peak event counts

_docs/_user_guide/engagement_tools/canvas/best_practices.md, _docs/_user_guide/engagement_tools/canvas/faqs.md
> Updating docs related to Canvas Flow webinar Q&As
---
=> Doc edits related to Canvas Flow webinar questions

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
=> BD-1559: Clarify link aliasing requirements to track metrics

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
=> Edit description for Social Icon editor block

_docs/_hidden/private_betas/link_shortening.md
>I'm adding a new FAQ to question based on PMM feedback @KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update FAQ's for Link Shortening

_docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
=> Add caveat for cloning active Canvases

_layouts/self_help.html, assets/css/_self_help.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add self help FA support

_docs/_api/basics.md, _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_recommend.md, _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Site.baseurl link fixes

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1565: Update Local part requirements for email validation

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1566: Update Segment replays callout

_docs/_user_guide/engagement_tools/campaigns/faq.md
=> BD-1571: Clarify campaign eligibility for local time zone delivery

assets/css/_docs_search.scss, vercel.json
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix main search overlay

_docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
This is following the conversation I had with one of my customers who had trouble implementing custom content cards. They had trouble with user-2 seeing user-1's cards. This made it clearer for them
- [ X] No
---
<details>
<br>
- [ X] Check that all links work.
- [X ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [X ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`
</details>
<details>
<br>
- [Image Style …
=> Make Web Cust Content Card Implementation Clearer

_docs/_hidden/private_betas/shopify_create_update.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Shopify create update clarification

_docs/_developer_guide/platform_wide/braze_actions.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
=> braze actions ios version

_docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
=> BD-1573: Condense redundant content in Creating geofences

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1572: Updating Amplitude cohort segmentation filter

_docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify.md, _docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Voucherify updates

_docs/_hidden/private_betas/link_shortening.md
> Removing the warning about lack of non-ASCII support due to changes made in https://jira.braze.com/browse/SMS-775 @KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> Remove warning about ASCII characters

_docs/_developer_guide/platform_integration_guides/ios/changelog.md, _docs/_developer_guide/platform_integration_guides/ios/changelog/objc_changelog.md, _docs/_developer_guide/platform_integration_guides/ios/changelog/swift_changelog.md, _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md, _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md, _plugins/sdk_min_versions_tag.rb
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1576: Update Changelog - Swift

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> New type of DND Content Block **Video**, supported background image for row configurations, fallback fonts, dynamic image URL.
Closes #**BD-1567**
=> BD-1567: Updates to Drag & Drop Editor docs

_docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1579: Update avro parameters

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Closes #**BD-1584** #**BD-1586**
=> BD-1584 and BD-1586: Move uninstall event to message engagement glossary and add note

_docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md, _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Fuzzy Opt-Out to hidden

_includes/header.html, assets/css/_braze_header.scss, assets/js/documents.js
Move language selector to mimic main site closer.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Move Language Selector

_docs/_api/endpoints/email.md, _docs/_api/endpoints/email/post_blacklist.md, _docs/_api/endpoints/email/post_blocklist.md, _docs/_hidden/other/core_endpoints.md
=> BD-1545: Blocklist emails API

_docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
=> BD-1580: Clarify user data export for Canvas components

_docs/_api/endpoints/catalogs/delete_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/get_catalog_item_details.md, _docs/_api/endpoints/catalogs/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/post_create_catalog_items_bulk.md
=> Add feedback note for catalogs endpoints

_docs/_user_guide/personalization_and_dynamic_content/liquid.md
=> BD-1599: Liquid 5 GA

_docs/_home/templates/get_endpoint.md, _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> EA Link Shortening docs moved to public section

_docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md, _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fuzzy Opt-Out GA

_docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md, _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Reverts braze-inc/braze-docs#4084
=> Revert "Fuzzy Opt-Out GA"

_docs/_api/data_retention.md
=> BD-1585: Update data retention doc with Canvas Interactions [MERGE 9/21] 

_docs/_hidden/private_betas/card_creation.md
=> Clarify card creation for new and anonymous users in recurring campaigns

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1602: Preference Center test message behavior

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/9_20_22.md
=> September release notes

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Documenting anonymous user device_id

_docs/_help/release_notes.md, _docs/_help/release_notes/2022/9_20_22.md
=> Add period to sentence

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> BD-1603: Fix quotes in Liquid example

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
Reverts braze-inc/braze-docs#4067
=> Revert "BD-1595: Update Delay step with difference between days and calendar days"

_docs/_developer_guide/platform_wide/tv_and_ott.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1609: Fix LG Web OS Link

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Adding in the missing retargeting filters. 👀
=> BD-1583: Add new email open segmentation filters 

_docs/_hidden/private_betas/shopify_subscription_states.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Shopify Header Fix

_docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md, _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md, _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md
=> BD-1610: Add SMS properties for Message step callout

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
> Updating limited permissions table with changes from a recent update that decoupled publish cards from publish Content Blocks
Closes #**BD-1612**
=> BD-1612: Update user permissions table

_docs/_developer_guide/platform_wide/tv_and_ott.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1617: Clarify TvOS Push Support

_docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/custom_triggering.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1601: Update IAM behavior to account for Android 13

_docs/_developer_guide/platform_wide/tv_and_ott.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Custom UI -> Headless UI

_docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1615: Update channel performance dashboard with SMS metrics

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/canvas/faqs.md
=> BD-1616: Add Canvas Flow steps limit

_docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix Code Type

_docs/_user_guide/message_building_by_channel/in-app_messages/create.md
> I'm changing the alert in step 7 to read better so that customers understand that if an in-app message is stopped, it's possible that users will still receive the message and analytics will continue to increase for a short period of time.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Changed in-app message display considerations

_docs/_developer_guide/platform_integration_guides/react_native/analytics.md
=> react native docs

_docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
=> SSR and Vite

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
=> BD-1600: Content Blocks for Drag & Drop Editor GA

_docs/_user_guide/engagement_tools/testing/race_conditions.md
Adding a slight clarification to the documentation around race conditions.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Slightly Clarify Race Condition Docs

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
Adding "Most Recent Device Locale" to the list of available filters
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add locale filter

_docs/_hidden/private_betas/canvas_user_update.md
=> BD-1624: Add character limit for User Update

assets/css/_glossary_page.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updating API landing page

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Path Entry and Conversions Message Engagement Events

_docs/_help/release_notes/2022/9_20_22.md
=> BD-1627: Fix broken link

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-1628: Update maximum length for arrays

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
Nested custom attributes and targeting have been in GA for a while, these lines are out of date.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> I missed removing these mentions of early access.

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
=> BD-1632: Add delay limit

_docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
Updating user archival page based on feedback from @sambellbraze in https://github.com/braze-inc/braze-docs/pull/4038
=> Updating user archival

_docs/_user_guide/engagement_tools/segments/segment_extension.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> More wordsmithing on Segment Extensions.

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
> Adding a FAQ that advises to not shorten Universal Links with link shortening. @KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Link Shortening FAQ

_docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> ContentCardsViewBindingHandler docs update

_docs/_api/home.md
=> BD-1640: Fix campaigns tag for API guide

_docs/_api/endpoints/scim.md, _docs/_api/endpoints/scim/delete_existing_dashboard_user.md, _docs/_api/endpoints/scim/get_see_user_account_information.md, _docs/_api/endpoints/scim/post_create_user_account.md, _docs/_api/endpoints/scim/put_update_existing_user_account.md, _docs/_api/home.md, _docs/_hidden/misc_reference/scim_api_apprendix.md, _docs/_user_guide/administrative/company_settings/automated_user_provisioning.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> SCIM Endpoint GA - MERGE 10/5

_docs/_user_guide/personalization_and_dynamic_content/catalog.md
=> BD-1642: Add mention of catalogs endpoints

_docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1636: App Uninstall Troubleshooting

_docs/_user_guide/engagement_tools/segments/segment_extension.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Reword segment extensions limit.

_docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updating no-code push primer messages

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-1650: Add limitation for nested custom attributes

_docs/_api/endpoints/preference_center.md, _docs/_api/endpoints/scim.md, _docs/_api/endpoints/sms.md, _docs/_api/endpoints/subscription_groups.md, _docs/_api/endpoints/templates.md, _docs/_api/endpoints/user_data.md
=> Update page order for Endpoints sections

_docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization/key_value_pairs.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md, _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Control iam

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1652: Clarify Device OS segmentation filter

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
=> BD-1653: Fix broken link

_docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
> Closes https://github.com/braze-inc/braze-docs/pull/4203
---
=> Edit Message doc

_docs/_hidden/private_betas/card_creation.md
=> BD-1643: Format card creation differences as table and add usage row

_docs/_user_guide/data_and_analytics/cloud_ingestion.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Move Cloud Ingestion to public docs

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-1658: Update user_alias to user_alias_name in user import docs

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-1658: Clarify that CSVs for user import can't contain a mix of external_ids and aliases

_docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_user_guide/message_building_by_channel/email/preference_center.md
=> Edits for Preference Center API docs

_docs/_hidden/other/handbooks.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Handbook fix

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
Updates unity android manifest instructions
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or …
=> removed broadcast receiver from unity android

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> Add link for Preference Center endpoints

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add missing dot for canvas_entry_properties

_docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
> I'm adding a reference to the Fuzzy Opt-Out docs to a different page of the SMS documentation so users are aware this is an option
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add reference to Fuzzy Opt-Out in SMS Opt-Out docs

_docs/_user_guide/message_building_by_channel/sms/keywords.md, _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> GA Fuzzy Opt-Outs

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
> Removing the Early Access warning now that Link Shortening is generally available.
@KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove Early Access Warning

_docs/_user_guide/message_building_by_channel/sms/keywords.md, _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
Reverts braze-inc/braze-docs#4238
=> Revert "GA Fuzzy Opt-Outs"

_docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Reverts braze-inc/braze-docs#4224
=> Revert "Add reference to Fuzzy Opt-Out in SMS Opt-Out docs"

_docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
Reverts braze-inc/braze-docs#4244
=> Revert "Revert "Add reference to Fuzzy Opt-Out in SMS Opt-Out docs"" - MERGE 10/17

_docs/_user_guide/message_building_by_channel/sms/keywords.md, _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
Reverts braze-inc/braze-docs#4245
=> Revert "Revert "GA Fuzzy Opt-Outs"" - MERGE 10/17

_docs/_user_guide/message_building_by_channel/sms/keywords.md, _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md, _docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md
#4246 - Revert "Revert "GA Fuzzy Opt-Outs""
#4248 - Revert "Revert "Add reference to Fuzzy Opt-Out in SMS Opt-Out docs""
=> Deploy Pt. 1 - October 17, 2022

_docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md, _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md
=> BD-1663: Edits for external ID rename and remove GA

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
=> BD-1666: Remove video block mentions

_docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
=> BD-1663: Part 2

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_event_callback.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_help/release_notes/deprecations.md, _docs/_help/release_notes/deprecations/custom_broadcast_receiver.md, assets/js/broken_redirect_list.js
> I'm deprecating the BroadcastReceiver for push and replacing with push events documentation
Closes #SDK-3018
- [X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove BroadcastReceiver replace with push events

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-1664: Remove coming soon notes for NCA and array of object 

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Shopify Payloads

_docs/_help/release_notes.md, _docs/_help/release_notes/2022.md, _docs/_help/release_notes/2022/10_18_22.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Release Notes October

_docs/_help/release_notes.md, _docs/_help/release_notes/2022/9_20_22.md
=> BD-1671: Remove video block mentions

_docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
Stream example was pointed at the private repo, not https://github.com/braze-inc/braze-flutter-sdk/blob/master/example/lib/main.dart
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update flutter data stream example to point to public repo

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> update to reflect PII changes

_docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md, _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md, _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
=> BD-1679: Remove email references from Content Block endpoints

_docs/_user_guide/data_and_analytics/cloud_ingestion.md
This just adds a sentence about CDI's time sync. Look at this with `?w=1`, my editor removed excess whitespace.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Updates around CDI 15m sync.

_docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
=> Clarify filtered sets usage

_docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Added IAM request IAM display to IAM unity docs
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim …
=> added display later to unity config

_docs/_user_guide/message_building_by_channel/sms/faqs.md
> Referencing Link Shortening in SMS FAQs
@KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Reference Link Shortening in FAQs

_docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
> Updating Voucherify (partner) documention; adding notes to referral section and truncating API call in Connected Content example because of a newly available endpoint for loyalty members.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Updating Voucherify (partner) documention

Gemfile.lock
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Change nokogiri platform

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1675: Add capture example to connected content docs

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md, _lang/fr/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
=> BD-1686: Fix broken KDoc link

_docs/_partners/data_and_infrastructure_agility/workflow_automation/hightouch.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1689: Link out to Hightouch docs

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Segment Personas to Segment Engage

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
> Import fields are case-sensitive and the table example caused confusion as our table headers are automatically capitalized
Closes #**BD-1691**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1691: Transform table heading to lowercase in user import example

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add CDI reference to user data collection page

_docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md, _docs/_api/endpoints/catalogs/catalogs/synchronous/post_create_catalog.md
=> Edits for catalog endpoint docs

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
=> Step not ftep

_docs/_help/help_articles/api/delete_user.md, _docs/_help/help_articles/segments.md, _docs/_help/help_articles/segments/exporting_large_segments.md, _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md, _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md, _docs/_user_guide/engagement_tools/campaigns/faq.md, _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md, _docs/_user_guide/engagement_tools/canvas/faqs.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md, _docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md, _docs/_user_guide/engagement_tools/locations_and_geofences/geofence_configuration.md, _docs/_user_guide/engagement_tools/testing/race_conditions.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md, _includes/campaign_analytics.md
> Various doc edits based on KB summaries for bugs/fixes
---
=> Edits from KB reports

_docs/_user_guide/message_building_by_channel/in-app_messages/create.md
=> BD-1695: Clarify 200 active IAM limit doesn't apply to Canvases

_docs/_user_guide/data_and_analytics/your_reports/report_builder.md
=> BD-1697: Update report eligibility time

_docs/_user_guide/message_building_by_channel/sms/campaign/segments.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1699: Update SMS message and segment distinction

_data/i18n.yml, _docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md, _docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1698: Clarify email whitespace caveat

_includes/campaign_analytics.md
=> BD-1702: Remove Content Cards not available OOTB warning

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md, _docs/_user_guide/personalization_and_dynamic_content/catalogs/filtered_sets.md
> Clarify free and paid tier info for filtered sets, add filtered set limitation
Closes #**BD-1700**, **BD-1703**
---
=> BD-1700 and BD-1703: Update catalogs and filtered sets docs

_docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1704: Typo fix

_docs/_user_guide/engagement_tools/canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md, assets/js/broken_redirect_list.js
=> Exit criteria GA - MERGE 10/31

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md, assets/js/broken_redirect_list.js
=> Remove redirect for exit criteria, change permalink to alias

_docs/_hidden/private_betas/datadog.md
and i'm fixing the datadog branding
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> I had the wrong API key reference..

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
=> BD-1709: Clarify Content Blocks for Drag & Drop Editor functionality

_docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
=> BD-1712: Update entry properties wording

_docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
With the introduction of our in-app messaging feature, revamped the documentation copy, prerequisites, and integration instructions. Thanks.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Updated Iterate documentation for Braze

_docs/_hidden/private_betas/datadog.md
removing
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …
=> updating for something jon had to strip out

_docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md
> I'm changing GCS docs to include optional permissions for the cleanup of incomplete files
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add note about GCS permission

_docs/_api/objects_filters/user_attributes_object.md
=> BD-1715: Add case sensitive user fields

_docs/_api/api_campaigns.md, _docs/_user_guide/engagement_tools/testing/global_control_group.md
=> BD-1716: Clarify that all users are eligible for API campaigns  

assets/js/documents.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix japanese scroll after changing language

_docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1722: Clarify Conversion and Funnel Report Discrepancy

_docs/_user_guide/data_and_analytics/cloud_ingestion.md
This adds a small section to recommend UTC timestamps.  Also changes our example view to be UTC instead of locally configured timezone
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> DLK-529: add UTC recommendation to cloud ingestion doc

_docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md
=> BD-1724: Update Migrating from News Feed

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1725: Update user permissions

_docs/_user_guide/engagement_tools/canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
=> Update exit criteria doc to hidden

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1723: Update conversion_index field name

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
Closes #**BD-1713**
Closes #**BD-1714**
=> BD-1713 and BD-1714: Fix Liquid use case examples

_docs/_user_guide/message_building_by_channel/email/preference_center.md
added an alert to make sure people are aware how to test the liquid tag properly.
=> Clarify Preference Center Liquid Tag Functionality

_docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
=> Differentiate between DND editors for email and IAM

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-1735: Clarify updating via user import with alias needs both name and label

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/dynamics_365_customer_insights.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1732: Update Dynamics 365 segment instructions

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add redirects for catalog management links

_docs/_user_guide/message_building_by_channel/push/ios/utilizing_badge_count.md
=> BD-1690: Add note that app badging is handled automatically by Android for push

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
> Also adds some more structure and rearranges content in the "custom event properties" section
=> BD-1733: Add info about integer data types being rounded at large numbers

_docs/_hidden/private_betas/canvas_version_history.md
=> BD-1720: Update Canvas version history doc

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md
=> Add calendar days vs. days blurb for Delay step

_docs/_partners/data_and_infrastructure_agility/analytics/looker.md
Update Braze Looker Action docs with some clarifications.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update Braze Looker Action docs

_docs/_api/endpoints/scim/post_create_user_account.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1739: Update SCIM endpoint

_docs/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
> Also introduces some structure to the page to remove alerts
Closes #**BD-1738**
---
=> BD-1738: Add note about reasonable network speed for videos in IAMs

_docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
=> Edit tip alert for dark mode preview for DND email

.github/CODEOWNERS
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove code owners auto-tag

_docs/_user_guide/engagement_tools/campaigns/faq.md
=> BD-1746: Fix typo

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-1745: Fix broken link

_docs/_help/help_articles/data.md, _docs/_help/help_articles/data/blocklisting_deletion.md, _docs/_hidden/other/user_csv_lambda.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md, _docs/_user_guide/message_building_by_channel/email/faq.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> CSM repository doc edits 2 - Pt.1

_docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fixed links

_docs/_api/endpoints/scim/get_see_user_account_information.md, _docs/_api/endpoints/scim/post_create_user_account.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1744: Update SCIM endpoints, id field

_docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1749: Remove irrelevant uninstall screenshot

_docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
updating the metric definitions of Opt-in and Opt-out
> I'm updating the definition of the Opt-in and Opt-out metrics in the SMS Performance dashboard due to some confusion raised in slack:
https://brazetechnology.slack.com/archives/C01E86ZP89F/p1668557281411399
cc. @wendy-p @KellieHawks 
---
<details>
<br>
</details>
<details>
<br> …
=> Clarifying metric definition

_docs/_hidden/other/braze_support.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1736: Add developer console access instructions on support page

_docs/_api/endpoints/scim/post_create_user_account.md
You cannot specify the id as part of the request it is simply provided as part of the response.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix Sample SCIM Code

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
The Android Custom Click Handling link currently points erroneously to iOS docs. This would redirect it to the Android Custom Listener docs which I presume are the desired landing spot.
---
<details>
<br>
</details>
<details>
<br> …
=> Fix the Custom Click Handling Link in Android

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
=> BD-1754: Clarify advancement behavior for Canvas Flow

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
Closes #**BD-1756**, #**BD-1757**
---
=> BD-1756 and BD-1757: Fix typos

_docs/_user_guide/data_and_analytics/export_braze_data.md, _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md, _docs/_user_guide/data_and_analytics/tracking.md, _docs/_user_guide/message_building_by_channel/content_cards.md, _docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md, _docs/_user_guide/message_building_by_channel/email/templates.md, _docs/_user_guide/message_building_by_channel/in-app_messages.md, _docs/_user_guide/message_building_by_channel/push.md, _docs/_user_guide/message_building_by_channel/push/advanced_push_options.md, _docs/_user_guide/message_building_by_channel/push/android.md, _docs/_user_guide/message_building_by_channel/push/ios.md, _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md, _docs/_user_guide/message_building_by_channel/push/web.md, _docs/_user_guide/personalization_and_dynamic_content.md
=> Updating a few landing pages

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Shopify Email and SMS Subscriber GA

_docs/_user_guide/message_building_by_channel/content_cards/create.md
=> BD-1760: Remove line that Content Cards don't support vouchers

_docs/_user_guide/message_building_by_channel/content_cards/about.md
=> Clean up use cases section

_docs/_partners/data_and_infrastructure_agility/cohort_import/storyly.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove reference of Braze SDK in Storyly Partner Docs

_docs/_developer_guide/platform_wide/sdk_authentication.md
=> BD-1762: Broken links in note and tabs

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
=> BD-1766: Add note about event properties

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updating user install partners

_docs/_user_guide/data_and_analytics/your_analytics_dashboards/email_performance_dashboard.md
=> BD-1770: Remove mention of push dashboard

Gemfile.lock
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update sinatra version

_docs/_partners/message_personalization/localization/transifex.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Replace Transifex bearer key 

_docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
I was reading https://www.braze.com/docs/user_guide/data_and_analytics/braze_currents/how_braze_uses_currents/ and noticed the links to Looker are not operational: instead of going to the named blocks, the Looker Marketplace arrival page is shown.
In my proposed change, I preserved the values in the query strings of the URLs because these might be important for referral tracking. Someone should verify this.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZS …
=> Update defunct links to Looker

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md, _docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Snowflake Reader Accounts - MERGE 12/1

_docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1767: Add note about required MMS for Contact Cards

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
> I'm separating out the Text block into two distinct blocks: Title and Paragraph.
- Yes (2022-11-24)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> DND IAM Title and Paragraph blocks

_docs/_home/dp-technical-assistance.md
=> Remove left nav from Data Protection Technical Assistance

_docs/_help/help_articles/push/push_token_migration.md
- Edited for tone and clarity
- Fixed broken links
- Reordered information for a better flow
- Changed "warnings" to "important" alerts for tonal considerations
=> Edited Push Token Migration

_docs/_api/objects_filters/aliases_to_identify.md, _docs/_api/objects_filters/user_attributes_object.md, _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
Ensured that all the information from the associated KB article was clearly articulated in this article
=> 2717 user management

_docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1774: Update IAM Simple Survey Docs

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1779: Update Toovio

_docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1777: User archive threshold update

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1782: Update add-to-calendar-link additional options

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> ECOMP-Video-Block

_docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add alert for HTML sanitization 

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_alerts.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1784: Add campaign alert behavior

_docs/_api/endpoints/preference_center/get_view_details_preference_center.md, _docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_api/endpoints/preference_center/put_update_preference_center.md
This update will go out with the release week of Dec 12.
>Updating preference center pages with an additional field: preference_center_title
Closes #EINFRA-534
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add preference_center_title to pref center pages

_docs/_user_guide/administrative/company_settings/notification_preferences.md
=> BD-1789: Remove mention of webhook timeouts

_docs/_hidden/private_betas/link_shortening.md
1. Moved where length of URL is shown
2. Updated FAQ's
@KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Some small tweaks to link shortening docs

_docs/_user_guide/data_and_analytics/cloud_ingestion.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add one more mention of events and purchases

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
=> BD-1763: Catalogs endpoints GA

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md, _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md, _docs/_api/endpoints/user_data/post_user_track.md, _docs/_api/objects_filters/user_attributes_object.md
=> BD-1747: Update users/track docs to include setting subscription group status

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
removing confusion between 'custom attributes' and 'html attributes' which this feature supports
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> ecomp-custom-attribute-dnd

_docs/_user_guide/data_and_analytics/your_reports/report_builder.md
=> BD-1800: Update Report Builder limit from 50 to 250 campaigns

assets/js/broken_redirect_list.js
> Fix the issue I thought I fixed in #4533, but actually just broke in a different way.
=> Fix incorrect link fix

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md, _docs/_user_guide/engagement_tools/segments/segment_extension.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
=> Edits for data docs - Pt. 1

_docs/_partners/message_personalization/dynamic_content/dynamic_yield.md
Previous image made reference to our competitor Emarsys
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update Image 2 of Dynamic Yield integration

_docs/_api/objects_filters/user_attributes_object.md
> I'm updating the users/track attributes page with additional details about setting subscription group state. Sample body here: https://confluence.braze.com/pages/viewpage.action?pageId=184206730
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update user_attributes_object.md with subscription group changes

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
=> Add editing best practices to IAM DND

_docs/_user_guide/data_and_analytics/your_analytics_dashboards/conversions_dashboard.md
=> BD-1773: Conversions dashboard

_docs/_hidden/private_betas/card_creation.md
=> BD-1807: Update Card creation

_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Explicitly adding verbiage that global subscription status and subscription groups can also be updated via the Advanced JSON editor
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Adding subscription status + subscription groups

.vercel/build.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> fix language preview

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
consistent style
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general …
=> Prefer style "10DLC", not "10dlc"

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Trivial missing punctuation
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add missing punctuation to complete sentence.

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> updating to reflect how canvas fields are included

_docs/_hidden/private_betas/datadog.md, _docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove early access disclaimer 

_docs/_docs_pages/index.md, _lang/fr/_docs_pages/index.md, _layouts/doc_guide.html
Adjust Braze Learning description to support multi language options.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Braze Learning Language description

_docs/_user_guide/administrative/app_settings/manage_app_group/email_settings.md
=> BD-1811: Clarify Email Unsubscribe Header setting

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Closes #**BD-1812**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1812: Clarify Unsubscribe Event in Currents

_docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
Closes #**BD-1815**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1815: Fix broken link

_docs/_api/endpoints/user_data/post_user_track.md
Closes #**BD-1819**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1819: Add use case for /users/track

_docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Closes #**BD-1818**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1818: Clarify iOS integration for attribution partner doc

_docs/_api/objects_filters/schedule_object.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1821: Update "in_local_time" behavior

_docs/_api/api_limits.md, _docs/_api/endpoints/user_data.md, _docs/_api/endpoints/user_data/post_users_merge.md, _docs/_api/home.md, _includes/rate_limits.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> first pass of users merge documentation

_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Adding note that Connected Content requests only support GET requests, to clarify issue raised here: https://brazetechnology.slack.com/archives/C0181S1SSSY/p1671106478650359
---
<details>
<br>
</details>
<details>
<br> …
=> Connected Content only supports GET

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Minor rewording

_docs/_docs_pages/index.md, _docs/_user_guide/introduction.md
=> BD-1804: Remove home top text and update user guide top text

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md, _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Adding information about the Braze location module for Android
Closes #SDK-3299
- [X ] Yes Android SDK 24.0.0, released today.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …
=> Add location module information.

_docs/_user_guide/onboarding_with_braze/data_points.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1824: Update Appsflyer Datapoint

_docs/_hidden/private_betas/creating_feature_flags.md
Swift code snippets for the FF documentation page
=> Add FF Swift code snippets

_docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_api/endpoints/preference_center/put_update_preference_center.md
> I'm adding the new 'state' field to the preference center pages. 
Closes [EINFRA-537](https://jira.braze.com/browse/EINFRA-537)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> Add 'state' to preference center API

_docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_user_guide/message_building_by_channel/email/preference_center.md
Just some light cleanup of preference center API documentation
- fixes broken link on preference center overview page: https://www.braze.com/docs/user_guide/message_building_by_channel/email/preference_center
- puts <> around ids that are supposed to be substituted by the user
---
<details>
<br>
</details>
<details>
<br> …
=> fix: preference center docs

_includes/header.html, _includes/html_include.html, assets/js/documents.js
Add french language dropdown. Will need to full test once live due to how wovn works.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Add french language dropdown

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md, _docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
=> BD-1822: Clarify email preference center details

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_partners/isv_partners/currents_integration.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Currents updates - 1/10

_docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/1_10_23.md
=> January 2023 release notes

_docs/_user_guide/message_building_by_channel/email/preference_center.md
=> BD-1833: Edit for preference center tile

_docs/_hidden/private_betas/post_user_identify_merge_behavior.md
=> BD-1831: Include session data for merge behavior

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1832: Expand on Braze Reader Accounts

assets/js/documents.js
Fix issue due to home page not always having the trailing slash, so changing languages didn't work.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix language selector with home page

_docs/_user_guide/engagement_tools/segments/segment_extension.md
We are increasing the default number of allowed segment extensions
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Increase segment extension limit

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
=> BD-1837: Minor edit

_docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md, _docs/_user_guide/data_and_analytics/creating_a_formula.md, _docs/_user_guide/data_and_analytics/tracking/email_tracking.md, _docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md, _docs/_user_guide/data_and_analytics/your_analytics_dashboards.md
> **Weekly docs audit for reporting**
> Minor cleanup and fixing issues found in docs feedback sheet
---
=> Reporting minor cleanup

_docs/_user_guide/intelligence/faqs.md, _docs/_user_guide/intelligence/intelligent_selection.md
Updating docs to reflect a functionality change with Intelligent Selection and campaign re-eligibility.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update intel select with re-eligiblity docs

_docs/_user_guide/predictive_suite/predictive_churn/creating_a_churn_prediction.md, _docs/_user_guide/predictive_suite/predictive_purchases/creating_a_purchase_prediction.md
> I'm changing the churn and purchase limits because they're out of date
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Change paid prediction limit from 3 to 5

_docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
Closes #**BD-1705**, #**BD-1835**
---
=> BD-1835: Clarify Apple Private Relay details

assets/js/developer_nav.js
Fix left navigation with non en languages.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix developer guide platform navigation for multi language

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
=> BD-1849: Fix mention of selections

_docs/_help/accessibility.md
> Adds general article for accessibility guidelines for marketers
=> Building accessible messages

_docs/_hidden/private_betas/canvas_drafts.md
=> Clarify save as drafts for Canvas

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
Documenting that a Subscription Group update can also be used to trigger a Campaign. I've only added `Subscription Group Update` due to SMS team adding functionality to it in SMS-900 but in comparing this docs page to the dashboard, it doesn't appear that this list is comprehensive.
@KellieHawks @lydia-xie  (adding Lydia as I believe this is technically Core Messaging even though SMS made the change?)
> Came across this when looking to see where the docs needed updating for https://jira.braze.com/browse/SMS-900
---
<details>
<br>
</details>
<details>
<br>
- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRo …
=> Adding trigger event type

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update canvas_api_id field definition in Currents exit events

_docs/_partners/isv_partners/cohort_import.md
=> BD-1850: Clarify cohort_changes for user cohort endpoint

_docs/_user_guide/message_building_by_channel/whatsapp/create.md, _docs/_user_guide/message_building_by_channel/whatsapp/overview.md, _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Minor WhatsApp updates to reflect new sign-up UI

Gemfile.lock
Update Rack version
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Rack version 2.2.6.2

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
=> BD-1856: Add quotation mark for POST example

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> BD-1852: Clarify Has App filter

_docs/_api/endpoints/preference_center/put_update_preference_center.md
=> BD-1858: Fix request example

_docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
=> BD-1843: Add note regarding event removal

_docs/_api/data_retention.md
> Updating the section organization for the [Data retention doc
](https://www.braze.com/docs/api/data_retention/) based on feedback from Jon Hyman
---
=> Data doc edits pt. 4

_docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md, _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/integration.md, _docs/_developer_guide/platform_integration_guides/web/push_notifications/soft_push_prompt.md, _docs/_developer_guide/platform_wide/app_group_configuration.md, _docs/_user_guide/administrative/app_settings/developer_console/internal_groups_tab.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md, _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/previous_in-app_message_generations.md, _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md, _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Massaged references to the SDK

_docs/_partners/message_personalization/location/radar.md
Closes #**BD-1866**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1866: Fix link

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
Updating links to point out that the SDK used is dependent on which Segment SDK is used.
Closes #SDK-3255
- [ X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Segment links

_docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
> Updating the GoogleTagManager docs to match the new Swift SDK release
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update GTM docs

_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add section article tile

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Liquid use case german to english

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove Treasure data hosted video

_docs/_api/endpoints/export/user_data/post_users_segment.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
BD-1871 - Clarify mixpanel event removal date
BD-1857 - Clarify segment export GZIP requirements
=> Minor backlog tickets

_docs/_api/endpoints/user_data/post_users_merge.md
Closes #**BD-1867**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1867: Add section about merge_updates behavior

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
> I'm changing a typo that said "Spotify" instead of "Shopify" - nothing else changed
- [ x] No
---
<details>
<br>
- [x ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
</details>
<details>
<br>
</details> …
=> Update shopify.md to replace Spotify typo

_docs/_user_guide/message_building_by_channel/email/preference_center/preference_center.md
>With SMS & WhatsApp now supported by the Preference Center Liquid tags, I'm calling out that the old version will only automatically list Email Subscription Groups (which was previously a given).
@tiffanyjlin @lydia-xie 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Specify Subscription Group Type

_lang/fr/_developer_guide/platform_integration_guides/cordova/content_cards.md, _lang/fr/_developer_guide/platform_integration_guides/ios/content_cards.md, _lang/fr/_developer_guide/platform_integration_guides/web/content_cards.md
Fix invalid yaml error for French content
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Fix invalid yaml for FR

_docs/_api/endpoints/export/canvas/get_canvas_details.md
=> BD-1847: Update Canvas details endpoint fields

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md
Closes #**BD-1873**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1873: Clarify delivery validation for Canvas advancement

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md, _lang/fr/_user_guide/onboarding_with_braze/email_setup/email_validation.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> update french documentation to be on par with English (based on BD-1472)

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Clarify link aliasing

_docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
=> BD-1882: Apple Private Relay for Sparkpost steps

_docs/_hidden/private_betas/idle_campaigns.md
=> BD-1879: Hidden doc for campaign status

_docs/_user_guide/data_and_analytics/braze_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md, _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md, _docs/_user_guide/message_building_by_channel/content_cards.md, _docs/_user_guide/message_building_by_channel/content_cards/about.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md, _docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/in-app_messages.md, _docs/_user_guide/message_building_by_channel/in-app_messages/about.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> More Algolia tweaks

_docs/_api/endpoints/user_data/post_users_merge.md
=> BD-1883: Fix info for merge update field

_docs/_user_guide/data_and_analytics/your_reports/reports_overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Search rank update

_docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md, _docs/_developer_guide/platform_integration_guides/ios/content_cards/integration.md, _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/overview.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md, _docs/_help/help_articles/api/delete_user.md, _docs/_help/release_notes.md, _docs/_help/release_notes/2022/4_5_22.md, _docs/_help/release_notes/2023/1_10_23.md, _docs/_help/support.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md, _docs/_user_guide/data_and_analytics.md, _docs/_user_guide/data_and_analytics/analytics.md, _docs/_user_guide/data_and_analytics/your_reports.md, _docs/_user_guide/message_building_by_channel/push/push_reporting.md, _docs/_user_guide/onboarding_with_braze.md, _docs/_user_guide/onboarding_with_braze/learning_to_use_braze.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Algolia Tweaks 3

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-1866: Fix custom attributes string character limit

_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1884: Add trigger conditions for Punchh events

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> BD-1872: Add custom opt-in info

_docs/_api/endpoints/export/canvas/get_canvas_details.md
=> Fix details for Canvas endpoint

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md, _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Algolia tweaks 5

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md
> Update the available update sources when triggering by a subscription group for the different channels
@KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update subscription group update sources - 2/7

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
> SMS added the ability to set subscription group status via /campaigns/trigger/send so making reference to this in the API docs
@KellieHawks @scott-braze 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Reference ability to set subscription group status - 2/7

_docs/_user_guide/engagement_tools/segments/sql_segments.md
=> Unhide SQL Segment Extensions

_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
Updating list of channels available with Personalized and Winning Variant optimizations
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update channel list for PV

_docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
Closes #**BD-1897**, #**BD-1898**
---
=> BD-1897 and BD-1898: Edits for email settings and fallback font

_docs/_api/endpoints/user_data/post_user_identify.md, _docs/_api/endpoints/user_data/post_users_merge.md
=> BD-1888: Clarify /users/merge behavior

_docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove TCPA as it is up for amendment

_docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/12_13_22.md, _docs/_help/release_notes/2023/1_10_23.md, _docs/_help/release_notes/2023/2_7_23.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Feb 7th 2023 release notes

_docs/_help/release_notes.md, _docs/_help/release_notes/2023/2_7_23.md
=> Fix typo in release notes

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
This image location is related to the Liquid method but it's current location makes it look like it is the Row method
There should also be an image for the row method but I am not sure how to add one
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Fix Image Location Dnd Content Block

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md, _docs/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
=> BD-1875: Add info about testing campaigns and Canvases

_docs/_developer_guide/platform_integration_guides/flutter/content_cards.md, _docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md, _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Follows up [this PR](https://github.com/braze-inc/braze-docs/pull/4759) with a few additional changes.
The main change is that we'll want to use our custom Flutter Braze initializer to get additional info on customer integrations for free [via this API](https://github.com/braze-inc/braze-flutter-sdk/blob/b054a756cb25f2661cec56c478a32f1e35f21f51/ios/Classes/BrazePlugin.swift#L557) (SDK Metadata, SDK Flavor).
Closes https://jira.braze.com/browse/SDK-3288
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …
=> [SDK-3288] Update Flutter SDK Swift docs - Part 2

_docs/_user_guide/data_and_analytics/braze_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md, _docs/_user_guide/intelligence.md, _docs/_user_guide/intelligence/intelligent_channel.md, _docs/_user_guide/intelligence/intelligent_selection.md, _docs/_user_guide/onboarding_with_braze.md, _docs/_user_guide/onboarding_with_braze/data_points.md, _docs/_user_guide/onboarding_with_braze/subscription_and_usage.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Algolia tweaks pt.5

_docs/_partners/message_orchestration/attribution/airbridge.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Airbridge formatting updates

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
=> BD-1901: Update frequency capping rules per app group limit

_docs/_api/endpoints/export/campaigns/get_campaign_analytics.md, _docs/_api/endpoints/export/canvas/get_canvas_analytics.md
https://jira.braze.com/browse/SMS-1118
https://jira.braze.com/browse/SMS-1119 
> I'm adding "clicks" metric for sms and adding sms stats into canvas analytics
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> adding click stat to campaign and sms stats to canvas api documentation

_docs/_developer_guide/platform_wide/analytics_overview.md, _docs/_home/static_video.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1903: Update string limit for custom attributes

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1900: Add nested object indexing guidance

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1902: Update experiment step conversion currents event

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Reverts braze-inc/braze-docs#4804 per comment on original ticket
=> Revert "BD-1901: Update frequency capping rules per app group limit"

_docs/_developer_guide/platform_wide/tv_and_ott.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1896, BD-1891: Update OTT support list

_docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1904: Add note about Android verbose logging

_docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updated JavaScript bridge note to include Swift

_docs/_user_guide/administrative/manage_your_braze_users.md
Closes #**BD-1908**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1908: Fix typo

_docs/_partners/message_orchestration/attribution/adjust.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md, _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md, _docs/_partners/message_orchestration/attribution/kochava.md, _docs/_partners/message_orchestration/attribution/singular.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Attribution code snippet updates

_docs/_api/endpoints/email/post_blacklist.md, _docs/_api/endpoints/email/post_blocklist.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1915: Add blocklist permission caveat

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/duplicating_segments_and_campaigns.md, _docs/_user_guide/engagement_tools/canvas.md, _docs/_user_guide/engagement_tools/canvas/canvas_components.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/branching.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/exception_events.md, _docs/_user_guide/engagement_tools/canvas/faqs.md, _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md, _docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Sunset alerts for creating and duplicating Canvases with original experience 

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
https://jira.braze.com/browse/CO-1261
=> [CO-1261] Updated documentations for catalog APIs to support JSON data type

_docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md
=> BD-1914: Update lifetime users description

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1918: Update abort Currents event

_docs/_developer_guide/platform_integration_guides/ios/storage.md, _docs/_developer_guide/platform_integration_guides/swift/storage.md
https://jira.braze.com/browse/SDK-3029
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or …
=> [SDK-3029] Swift SDK docs - Storage page

_docs/_developer_guide/platform_integration_guides/swift/sample_apps.md
https://jira.braze.com/browse/SDK-3030
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or …
=> [SDK-3030] Swift docs - Sample Apps

_docs/_user_guide/message_building_by_channel/content_cards/about.md
=> Edit to About Content Cards

_docs/_hidden/other/support_contact.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Reverting curly change

_docs/_hidden/other/support_contact.md, _docs/_user_guide/message_building_by_channel/content_cards/about.md
=> Unscheduled deployment February 17, 2023

_docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md, _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
https://jira.braze.com/browse/SDK-3403
Public Github issue: https://github.com/braze-inc/braze-react-native-sdk/issues/191
We only had an ObjC snippet but not a Swift snippet.
> Note: We have not completely verified by integrating the code snippet into a RN+Swift app since right now our sample app is a RN+ObjC app. The code seems sufficient and we can see if there are other requests for any syntax issues
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz1 …
=> [SDK-3403] Add Swift snippet to React Native - Initial SDK setup

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/campaigns_in_multiple_languages.md
=> BD-1923: Clarify internationalization is not available in IAM DND editor

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-1925: Fix typo

_docs/_user_guide/intelligence/intelligent_timing.md
Adding a note about machine opens with intelligent timing.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Note about machine opens

_docs/_user_guide/message_building_by_channel/sms/keywords/optin_optout.md, _includes/archive/short_and_long_codes.md
=> Long code timeline update

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1931: Update global state change currents event

_docs/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix alias links

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
@josh-mccrowell-braze feel free to adjust wording
=> warning for FCM api key

_docs/_partners/home.md, _docs/_partners/message_personalization.md, _docs/_partners/message_personalization/localization.md, _docs/_partners/message_personalization/localization/phrase.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Phrase Partnership Docs

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
=> BD-1932: Clarify multichannel promotion codes

_docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md
=> branch docs

_docs/_user_guide/message_building_by_channel/email/amphtml.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1937: Update AMP clients

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1943: Remove canvas exit detail schema 

_docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/testing.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/testing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1938: Update command line testing examples for iOS and Android

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-1940 part 2: Clarify custom attribute array default length

_docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
=> Removing original Canvas workflow images

_docs/_hidden/private_betas/tiktok.md, _docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
=> Fix Canvas alerts

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1939: Add currents state change source codes

_docs/_developer_guide/platform_integration_guides/sdk_changelogs.md, _docs/_developer_guide/platform_integration_guides/xamarin/analytics.md, _docs/_developer_guide/platform_integration_guides/xamarin/changelog.md, _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md, _docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md, _docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md, _docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md, _docs/_help/release_notes.md, _docs/_help/release_notes/2022/10_18_22.md, _docs/_help/release_notes/2022/11_15_22.md, _docs/_help/release_notes/2022/7_26_22.md, _docs/_help/release_notes/2023/12_13_22.md, _lang/fr/_developer_guide/platform_integration_guides/react_native/changelog.md, _lang/fr/_developer_guide/platform_integration_guides/react_native/content_cards.md, _lang/fr/_developer_guide/platform_integration_guides/react_native/inapp_messages.md, _lang/fr/_developer_guide/platform_integration_guides/react_native/sample_app.md, _lang/fr/_developer_guide/platform_integration_guides/sdk_changelogs.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/ changelog.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/analytics.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/changelog.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/news_feed.md, _lang/fr/_developer_guide/platform_integration_guides/xamarin/push_notifications.md, _lang/fr/_help/release_notes.md, _lang/fr/_help/release_notes/2022/10_18_22.md, _lang/fr/_help/release_notes/2022/11_15_22.md, _lang/fr/_help/release_notes/2022/7_26_22.md, _lang/fr/_help/release_notes/2023/12_13_22.md
~`appboy/appboy-ios-sdk` -> `braze-inc/braze-ios-sdk`~
`appboy/appboy-react-sdk` -> `braze-inc/braze-react-native-sdk`
`appboy/appboy-xamarin-bindings` -> `braze-inc/braze-xamarin-sdk`
=> SDK-3419 appboy to braze

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
> I'm replacing "IP Ranges" with "IPs" because users are whitelisting IPs, not a subnet as the term "range" would imply.
Jira Ticket: CH-4391
We had a client who got confused with the IP Ranges verbiage
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Reword IP Range to IPs for Webhook IP Whitelist

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Github public issue: https://github.com/braze-inc/braze-docs/pull/4869#issuecomment-1437936852
Slack thread: https://brazetechnology.slack.com/archives/GSNFELKQT/p1677007543119339?thread_ts=1676998405.128219&cid=GSNFELKQT
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> [Untracked] React Native docs - edit Swift snippet

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> WhatsApp credit ratios doc (hidden)

_docs/_developer_guide/platform_integration_guides/web/in-app_messaging/customization.md
Closes #**BD-1952**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1952: Add tile

_docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
=> BD-1948: Note that Push Story doesn't dismiss upon click on Android

_docs/_user_guide/message_building_by_channel/content_cards.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md, _docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
=> Card creation GA

_docs/_hidden/private_betas/pinterest_audience_sync.md, _docs/_hidden/private_betas/snapchat_audience_sync.md, _docs/_hidden/private_betas/tiktok.md, _docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/canvas_steps/google_audience_sync.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update the canvas entry criteria with text provided by legal

_docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
Was trying to make it work and checked the example project to find this was missing, otherwise I would get: `Swift Compiler Error (Xcode): Cannot find 'BrazePlugin'`
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Missing import for flutter (ios) set up

_docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
> Update Connected Content docs to provide context for :rerender. It's not immediately clear what the documentation is telling you to do or why -- this provides the additional context that you need to include the attributes somewhere in your request in order for them to get templated in the response.
---
<details>
<br>
</details>
<details>
<br> …
=> Update Connected Content docs to provide context for :rerender

_docs/_hidden/private_betas/pinterest_audience_sync.md, _docs/_hidden/private_betas/snapchat_audience_sync.md, _docs/_hidden/private_betas/tiktok.md, _docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_user_guide/data_and_analytics/analytics.md, _docs/_user_guide/data_and_analytics/custom_data.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Dashboard fix and legal text update for canvas audience sync

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
=> Add 500 active CC campaign note

_docs/_user_guide/administrative/access_braze/single_sign_on/okta.md, _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md, _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1951: Update Okta SSO steps

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1956: Updates to WA Credit page

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md, _includes/archive/short_and_long_codes.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> 10DLC Updates - 4-6 week review period

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> RudderStack for Currents - MERGE 3/7

_docs/_user_guide/data_and_analytics/reporting/report_builder.md
=> Remove EA note from report builder charts

_docs/_api/endpoints/preference_center/get_view_details_preference_center.md, _docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_api/endpoints/preference_center/put_update_preference_center.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> update docs with preference center options values

_docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/3_7_23.md
=> Add March 2023 release notes

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add additional dnd HTML attribute link use case 

_docs/_partners/data_and_infrastructure_agility.md, _docs/_partners/data_and_infrastructure_agility/business_intelligence.md, _docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Sisu data tile fix

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/action_buttons.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update deprecated link to new method

_docs/_user_guide/administrative/manage_your_braze_users/company-wide_settings_management.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Company notification preferences

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> WA Credit ratios legal updates

_docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Move changelog to bottom of navigation in dev guide

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
=> BD-1962: Remove EA note from IAM DND

_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1961: Add CC troubleshooting

_docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1965: Add audience export instructions for facebook

_docs/_developer_guide/platform_wide/feature_flags/create.md
Correcting the variable name to featureFlag
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Typo in javascript example

_docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md, _docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1967: Clarify Phrasee requirements

Gemfile.lock
Fix [4991](https://github.com/braze-inc/braze-docs/pull/4991)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update rack 2.2.6.3

_docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md, _docs/_partners/message_orchestration/attribution/singular.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1969: Updates to Singular and Branch code snippets

_docs/_partners/data_and_infrastructure_agility.md, _docs/_partners/data_and_infrastructure_agility/analytics.md, _docs/_partners/data_and_infrastructure_agility/analytics/merkury.md, _docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Merkury Partnership Docs

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference …
=> Note about audience limits and a/b tests

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> BD-1972: Add info about changing control variant percentage after launching Canvas

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Currents events for Currents partners, audit event dictionary

_docs/_help/release_notes.md, _docs/_help/release_notes/2023/2_7_23.md
git push origin kh/fix4
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> BD-1977: Currents release note fix

_docs/_api/endpoints/user_data/post_users_merge.md
Closes #**BD-1978**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove EA banner for /users/merge endpoint

_docs/_api/endpoints/messaging/send_messages/post_send_messages.md, _docs/_api/objects_filters.md, _docs/_api/objects_filters/messaging/android_object.md, _docs/_api/objects_filters/messaging/content_cards_object.md, _docs/_api/objects_filters/messaging/email_object.md, _docs/_api/objects_filters/messaging/whats_app_object.md
> I'm adding documentation for how to send a WhatsApp message using the `/messages/send` endpoint
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> WhatsApp API object documentation - MERGE 3/15

_docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add picture links to FB partner page

_plugins/details_tag.rb, assets/css/_content.scss, assets/css/main.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Adjust details styling

_docs/_api/api_limits.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_item_details.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/delete_catalog.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md, _includes/rate_limits.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Catalog updates API

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
Add CDI as alternate to CSV upload
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add CDI as option to upload user data instead of CSV

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1981: Update WA credit ratios doc

_docs/_hidden/private_betas/pinterest_audience_sync.md
=> Fix heading level

_docs/_help/release_notes/2023.md
=> Fix release note year

_docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/overview.md, _docs/_developer_guide/platform_integration_guides/web/news_feed/integration.md, _docs/_help/release_notes/2017/july.md, _docs/_help/release_notes/2019/august.md, _docs/_hidden/archive_docs/generations.md, _docs/_hidden/archive_docs/previous_in-app_message_generations.md, _docs/_user_guide/data_and_analytics/report_metrics.md, _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/in-app_messages/about.md, _docs/_user_guide/message_building_by_channel/in-app_messages/best_practices/prep_guide.md, _docs/_user_guide/message_building_by_channel/in-app_messages/create.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md, _docs/_user_guide/message_building_by_channel/push/best_practices/push_primer_messages.md, _docs/_user_guide/onboarding_with_braze/web_sdk.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1983: Update full-screen to fullscreen

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1980: Add alert to mParticle data types section

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update credit ratios permalink

_docs/_user_guide/data_and_analytics/report_metrics.md, _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updates to sends campaign analytics metric

_docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1990: Clarify Azure export step

_docs/_help/help_articles/content_cards/empty_content_card_feed.md
=> BD-1984: Update empty Content Card feed help article with Card Creation

_docs/_api/endpoints/user_data/post_user_identify.md, _docs/_api/endpoints/user_data/post_users_merge.md
Closes #**BD-1987**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1987: Clarify merge behavior for /users/identify and /users/merge

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md
Legal request to add note about ownership of images. Somewhat urgent so please merge today.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add DallE ownership note

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_backfill.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Shopify Historical Backfill GA

_docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1992: Update AppsFlyer Android and Unity snippets

_docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Issue #5056 - Update external_id_remove response

_docs/_partners/data_and_infrastructure_agility.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform.md, _docs/_partners/home.md, _docs/_partners/message_orchestration.md, _docs/_partners/message_orchestration/channel_extensions.md, _docs/_partners/message_orchestration/channel_extensions/email_templates.md, _docs/_partners/message_personalization/location.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Partner tile audit

_docs/_user_guide/intelligence/ai_copywriting.md
Removing references to specific GPT version number while we go through a series of upgrades to 3.5 and eventually GPT4
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove version references from GPT

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1998: Credit Ratios Doc with Meta Updates

_docs/_partners/canvas_steps/google_audience_sync.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1995: Add Google updates to google audience syncing, removing lookalike audiences

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
Closes #**BD-1996**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1996: Add caveat for action paths and in-app messages

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
=> BD-2001: Add FAQ to DND IAM on segmenting based on button clicks

_docs/_user_guide/message_building_by_channel/email/templates/email_template.md
Closes #**BD-2004**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2004: Fix link

_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
=> BD-2000: Add examples for User Update JSON editor

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
Closes #**BD-2007**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2007: Update alert for campaign approval

_docs/_hidden/private_betas/navigation.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2002: Remove devices and carriers crumbs

_docs/_partners/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add WhatsApp tile to partner page

_docs/_hidden/private_betas/message_extras.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
=> BD-1986: New article for message_extras Liquid tag

_docs/_partners/canvas_steps/facebook_audience_sync.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2006: Add troubleshooting scenario for FB Audience sync

_docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Make a note that we need special configuration for other DataDog sites

_docs/_hidden/private_betas/canvas_approval.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update to Canvas approval

_docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
=> BD-2012: Add SparkPost to key-value pairs

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update to Content Card Abort

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-1991: add message_extras to  Currents events - MERGE 3/28

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
=> BD-2018: Add domain requirements to custom domains

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2014: Add abort events to currents events and glossary

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2015 Add additional exception events to Canvas exit criteria

_docs/_api/endpoints/export/canvas/get_canvas_details.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2017: Update field type

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, _docs/_hidden/wip_partnerships/WIP_guidelines.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Josh Updates (TK->JM) 

_docs/_api/endpoints/messaging/send_messages/post_send_messages.md, _includes/rate_limits.md
=> BD-2022: Edit rate limit section for /messages/send

_includes/campaign_analytics.md
=> BD-2023: Unify glossary and IAM reporting page for unique impressions

_docs/_developer_guide/platform_integration_guides/sdk_primer.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add intro formatting

_docs/_api/endpoints/catalogs.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md, _docs/_api/home.md
=> BD-2013: New Update catalog items and Update catalog item endpoints

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md, _includes/campaign_analytics.md
=> BD-2025: Update DND IAM with body click analytics behavior

_docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add redshift example for JSON formatting

_docs/_api/endpoints/export/canvas/get_canvas_details.md
=> BD-2024: Clarify response for /canvas/details endpoint

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md, _lang/fr/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Updates the recommended integration code in public docs to match the changes in the React Native SDK 4.0.0 release
Close [SDK-3529](https://jira.braze.com/browse/SDK-3529)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> [SDK-3529] Update RN recommended integration in public docs

_docs/_api/endpoints/user_data/post_users_merge.md
=> Clarify /users/merge details

_docs/_user_guide/message_building_by_channel/whatsapp.md, _docs/_user_guide/message_building_by_channel/whatsapp/opt-ins_and_opt-outs.md, _docs/_user_guide/message_building_by_channel/whatsapp/overview.md, _docs/_user_guide/message_building_by_channel/whatsapp/quick_replies.md, _docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2026: Add WhatsApp Phone Number page

_docs/_user_guide/intelligence/intelligent_channel.md
> Adding SMS in the Intelligent channel docs
cc @KellieHawks cc @josh-mccrowell-braze cc @borisrev 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> Adding SMS to intelligent channel docs

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md
> When updating this page to include a new interaction `Clicked shortened SMS link`, I noticed that the rest of the list is out of date with what is available in the platform. Thus, I went through and added all the missing interactions by comparing the documentation to what is seen in Sweeney. It would be good to have the Docs team review that for accuracy, as I initially intended to just add 'Clicked shortened SMS link' as that is the only new interaction that I own, but figured I would make the additional updates while I was in this file.
@KellieHawks 
Closes 
---
<details>
<br>
</details>
<details>
<br>
- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwm …
=> Updating interactions list

_docs/_api/endpoints/user_data/post_user_track.md
Closes #**BD-2027**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2027: Add /users/track with email address EA

_docs/_user_guide/administrative/company_settings/security_settings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2033: Update 2FA SSO security settings

_docs/_help/home.md, _docs/_partners/data_and_infrastructure_agility.md, _layouts/api_glossary.html, _layouts/api_page.html, _layouts/customer_behavior_events_glossary.html, _layouts/doc_guide.html, _layouts/documents.html, _layouts/glossary_page.html, _layouts/liquid_use_case_glossary.html, _layouts/message_engagement_events_glossary.html, _layouts/partner_page.html, _layouts/self_help.html, _layouts/user_guide.html, assets/css/_api.scss, assets/css/_content.scss, assets/css/_dev_guide.scss, assets/css/_glossary_page.scss, assets/css/_partner_page.scss, assets/css/_self_help.scss, assets/css/_user_guide.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> breadcrumbs tweaks

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2035: Update campaign abort event to be included in checkboxes

_docs/_hidden/other/airship_migration.md, _docs/_hidden/other/core_endpoints.md, _docs/_hidden/other/credit_ratios.md, _docs/_hidden/other/devices_and_carriers.md, _docs/_hidden/other/ephemeral_custom_events.md, _docs/_hidden/other/handbooks.md, _docs/_hidden/other/user_csv_lambda.md, _docs/_hidden/private_betas/canvas_approval.md, _docs/_hidden/private_betas/canvas_drafts.md, _docs/_hidden/private_betas/canvas_version_history.md, _docs/_hidden/private_betas/data_transformation.md, _docs/_hidden/private_betas/dnd_content_blocks_preview.md, _docs/_hidden/private_betas/idle_campaigns.md, _docs/_hidden/private_betas/navigation.md, _docs/_hidden/private_betas/pinterest_audience_sync.md, _docs/_hidden/private_betas/preference_center.md, _docs/_hidden/private_betas/snapchat_audience_sync.md, _docs/_hidden/private_betas/sql_segments_tables.md, _docs/_hidden/private_betas/tiktok.md, _docs/_hidden/wip_partnerships/WIP_guidelines.md, _docs/_hidden/wip_partnerships/partnership_template.md, assets/css/_api.scss, assets/css/_dev_guide.scss, assets/css/_user_guide.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Breadcrumbs fixes, assign dev_guide layout to hidden pages

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2036: Add Shopify user checkout flow behavior explanation

_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2038: Documenting A/B testing caveat

_docs/_user_guide/onboarding_with_braze/email_setup/email_validation.md
> I'm changing https://www.braze.com/docs/user_guide/onboarding_with_braze/email_setup/email_validation because The extra requirement for Gmail addresses is 2 characters for the local part, not 5.
Closes EINFRA-697
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [EINFRA-697] Update note on gmail local part.  Requires 2 chars, not 5.

_docs/_help/help_articles/data/change_custom_data_type.md
=> BD-2040: Switch "date" to "time"

_docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
=> Include mentions of product carousel

_docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/locations_and_geofences.md, _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md, _docs/_user_guide/engagement_tools/locations_and_geofences.md
=> BD-2045: Remove note regarding Geofence package limitation

_docs/_user_guide/data_and_analytics/analytics.md
=> Fix incorrect article name in tile

_docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
made a change in 17.0.0 of the Android SDK for BrazeLogger where you can just set the logLevel property instead of calling a method (setLogLevel)
Updating kotlin documentation for verbose logging.
- [x ] Yes 11/2/2021, changelog here https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#-breaking-2
---
<details>
<br>
- [ x] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ x] Check that all links work.
- [ x] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ x] Tag @josh-mccrowell-braze and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you …
=> updated kotlin instructions for setting verbose logging

_docs/_user_guide/message_building_by_channel/push/about.md
> Updating push recommendations to include windows browsers
Closes #**[SDK-3621](https://jira.braze.com/browse/SDK-3621)**
=> Verify and update push recommendations

_docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md
=> BD-2037: Add specs to Push Stories

_docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> clarifying the FAQ for multiple WABA connections

_docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md, _docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md, _docs/_user_guide/data_and_analytics/creating_a_formula.md, _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md, _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md, _docs/_user_guide/engagement_tools/testing/global_control_group.md, _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md, _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Final Link Audit, User Guide

_docs/_developer_guide/platform_integration_guides/android/content_cards/customization/swipe_to_dismiss.md, _docs/_developer_guide/platform_integration_guides/android/storage.md, _docs/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md, _docs/_developer_guide/platform_integration_guides/unity/content_cards.md, _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
https://docs.google.com/document/d/1ezgrLr0YOod-Mk9Gaoy7c5QMpBZoQyCZySbkVN7IjbQ/edit#
=> fix broken links

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2048: Currents tweaks

_docs/_hidden/private_betas/data_transformation.md
Closes #**BD-2051**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2051: Fix typo

_docs/_user_guide/introduction.md, _docs/_user_guide/message_building_by_channel/in-app_messages/traditional.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> User guide Introduction -> Home, fix duplicate IAM alias

_docs/_user_guide/intelligence/intelligent_timing.md
=> BD-2050: Update "Sending messages within specific hours" Section for Intelligent Timing

_docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2049: Update AppsFlyer broken link

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add anchor link

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
Closes #**BD-2053**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2053: Add EA banner for updating subscription group status

_docs/_api/errors.md
Closes #**BD-2055**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2055: Add more info for 5XX errors

_includes/archive/android/gifs.md
Closes #**BD-2057**
Closes #**BD-2058**
=> BD-2057 and BD-2058: Updates to Android GIFs customization articles

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
=> Clarify Content Block behavior for drag and drop vs Liquid

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
Closes #**BD-2061**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2061: Fix broken link

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
Closes #**BD-2062**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2062: Update request to PUT

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Typo in RudderStack Docs

_docs/_help/help_articles/account/locked_out.md, _docs/_help/help_articles/campaigns_and_canvas/conversions_low.md, _docs/_help/help_articles/campaigns_and_canvas/know_before_send.md, _docs/_help/help_articles/campaigns_and_canvas/not_triggering.md, _docs/_help/help_articles/in-app_messages/in-app_message_impressions_appear_lower_than_expected.md, _docs/_help/help_articles/in-app_messages/in-app_messages_not_displaying.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Link Edits Pt. 2

_docs/_api/objects_filters/messaging/email_object.md
=> BD-2060: Include info for authentication for email file attachments

_docs/_api/objects_filters/messaging/android_object.md
Closes #**BD-2071**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2071: Clarify limit for time_to_live

assets/js/broken_redirect_list.js
=> BD-2063: Add redirect link for frequency capping

_docs/_user_guide/message_building_by_channel/push/web.md
=> BD-2067: Add link to Safari mobile web push in general web push doc

_docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md, _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
https://jira.braze.com/browse/SDK-3556
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze …
=> [SDK-3556] Add rate limiting note for `requestContentCardsRefresh` (iOS, Android, Web)

_docs/_user_guide/predictive_suite/predictive_churn/prediction_faq.md
World's shortest PR
Typo
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Typo in prediction_faq.md

_docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
Email (abort, bounce, click, delivery, markasspam, open, send, softbounce, unsubscribe)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Added missing mixpanel email events

_docs/_help/faqs.md, _docs/_user_guide/personalization_and_dynamic_content/liquid.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md
> Adding a Liquid FAQ and minor doc edits
---
=> Liquid FAQ and related edits

_docs/_hidden/wip_partnerships/WIP_guidelines.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update WIP_guidelines.md for new ISV partner prcoesses

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
=> BD-2077: Update "text" to "paragraph"

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
=> BD-1848: Link to push primers in Android push integration

_docs/_user_guide/engagement_tools/canvas/managing_canvases/archiving_canvases.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_duplication.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_version_history.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
=> BD-2081: Canvas version history GA

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2064: Updates to Treasure Data query building

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> BD-2074: Update Push Enabled filter to include provisional push users

_docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2056: Clarify CC first impressions requirements

_docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
=> BD-2066: Clarify null attribute values for Liquid

_docs/_partners/message_orchestration/additional_channels/direct_mail/inkit.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Updates to Inkit integration steps

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
I'm changing the wording to specify that this is accent color, not background color
Closes #SDK-3628
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-3628] Clarify color is accent color

_docs/_user_guide/personalization_and_dynamic_content/liquid.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
=> BD-2083: Update Braze Learning path links for Liquid

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> BD-2084: Fix mentions of user subscription state for email

_docs/_api/endpoints/export/user_data/post_users_identifier.md
=> BD-2075: Add "push_tokens" to fields_to_export chart 

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
To be merged in after the May 2 release.
Includes attachment details in email message archiving
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …
=> Include attachment details in email message archiving - MERGE 5/2

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md, _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [CO-1493] Mention that schema generation uses sampling

_docs/_user_guide/engagement_tools/testing/multivariant_testing.md
=> BD-2082: Add details about variant distribution 

_docs/_user_guide/message_building_by_channel/whatsapp.md
Noticed the User Phone Numbers link was broken here: https://www.braze.com/docs/user_guide/message_building_by_channel/whatsapp
Just removing that dangling `p`
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Remove extra P that was breaking WhatsApp phone number links

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/toovio.md
=> Add forward slash

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
https://jira.braze.com/browse/SDK-3535
**Verified the code changes [in this branch off of Christopher's Swifty test branch](https://github.com/braze-inc/swift-sdk/compare/cbowns/nca/swifty-tests...cbowns/nca/swifty-tests__testCodeSamples?expand=1):**
- You will need to comment in / out code to test all of the commands.
- Then, you can verify on the Dashboard that each of the expected user custom attributes appear
Base branch: https://github.com/braze-inc/braze-docs/pull/5082
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …
=> [SDK-3535] Add NCA code samples for iOS

_docs/_user_guide/data_and_analytics/cloud_ingestion.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add integration list to cloud_ingestion doc

.github/CODEOWNERS
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Code owners updates for support page

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md, _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2072: Add WhatsApp Events to Currents - MERGE 5/4

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Closes #**BD-2096**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2096: Update note for Message Extras tag

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
Emphasize the note asking users to allow access to RedShift at a specific port. This note is a common pitfall when setting up Cloud Data Ingestion for RedShift. Hopefully, the emphasis will make it less likely for users to miss this crucial step.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Emphasize RedShift security groups note

_docs/_user_guide/engagement_tools/canvas/faqs.md
Closes #**BD-2094**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2094: Update Canvas FAQ with IAM info

_docs/_user_guide/data_and_analytics/cloud_ingestion.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> fix broken link to integrations page for CDI

_docs/_user_guide/message_building_by_channel/whatsapp/faqs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2088: Document meta throughput limit in WhatsApp FAQ

_docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2100: Updates to heap

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md, _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
=> BD-2099: Selections and in-browser editing for catalogs GA

_docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
Closes #**BD-2102**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2102: Fix wording

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases.md, _docs/_api/objects_filters/trigger_properties_object.md
Closes #**BD-2089**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2089: Add alert and clarify support details for trigger_properties

_docs/_partners/isv_partners.md, _docs/_partners/isv_partners/api_partner.md, _docs/_partners/isv_partners/cohort_import.md, _docs/_partners/isv_partners/currents_integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Tweaking ISV docs for breadcrumb formatting

_docs/_hidden/private_betas/canvas_comments.md
=> Fix EA alert

assets/js/broken_redirect_list.js
Closes #**BD-2104**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2104: Add redirect

_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Rudderstack to currents partners

_docs/_hidden/private_betas/test_connectors.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2073: Hidden Test Currents Connector page

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> BD-2091: Add abort messages for Liquid Use Case Library

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md, _docs/_api/endpoints/user_data/external_id_migration.md, _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md, _docs/_help/help_articles/push/push_token_migration.md, _docs/_home/templates_old/api_glossary.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md, _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md, _docs/_user_guide/message_building_by_channel/email/templates/email_template.md, _docs/_user_guide/onboarding_faq.md
=> Edits for mentions of external ID

_docs/_user_guide/engagement_tools/segments/user_profiles.md
=> BD-2103: Merge user profiles EA

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-2108: Fix typo

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
> Updating the iOS code snippets for React Native to be more explicit with setup instructions.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update React Native iOS setup code snippets

_docs/_developer_guide/platform_integration_guides/sdk_primer.md, _docs/_developer_guide/platform_wide/sdk_authentication.md
Noticed these changes in #5235 got lost in the mix from the Swift docs epic. Re-adding them back in.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Re-add miscellaneous Swift docs

_includes/header.html, assets/js/documents.js
Add a French Maintenance banner.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add French Maintenance banner

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Updated expo docs to include new fields
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> SDK-3710 / expo update fields

_docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md, _docs/_user_guide/data_and_analytics/custom_data/blocklist_delete_custom_data.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-2097: Clarify details for blocklist and deleting custom data

_docs/_hidden/private_betas/canvas_drafts.md
=> BD-2115: Clarify details for Canvas drafts

_docs/_developer_guide/platform_wide/feature_flags/create.md
> I'm adding code samples for using Feature Flags in the Braze Cordova SDK.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Cordova samples for Feature Flag usage

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2122: Remove support of specific shopify data events

_docs/_user_guide/data_and_analytics/query_builder.md
=> Add access note to query builder

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
=> BD-2109: Message extras Liquid tag GA - MERGE 5/18

_docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
=> BD-2124: Clarify info on how to get on approved sender's list 

_docs/_user_guide/onboarding_with_braze/email_setup/ssl.md
=> Typo in SSL doc

_docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/action_buttons.md
> Updating for more clarity in the usage of iOS push notification action buttons. Push action buttons can come with action options, which can cause some confusion if not configured correctly.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add note about setting UNNotificationActionOptions in iOS action buttons

assets/css/_content.scss
Allows support for random start {:start="[Number]"} for order list up to 5.
If more is need, will need to update the scss counter
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ ATTN: For …
=> Fix markdown start index

_docs/_api/endpoints/catalogs/catalog_management/synchronous/get_list_catalogs.md
=> Fix heading

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
=> Fix heading pt. 3

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
=> Fixing trust score discrepancy on 10DLC

_docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
=> Fix heading pt. 2

_docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
=> BD-2121: Add templated IAM behavior to IAM FAQ

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
> Addresses https://github.com/braze-inc/braze-docs/pull/5461
---
=> Include Snowflake support for message_extras tag

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-2128: Add suggestions for time operator

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
=> BD-2127: Simple survey data type for multiple vs single choice

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
Closes #**BD-2134**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2134: Clarify Canvas and campaign user entry

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
sample files in our examples repro
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> add link to better examples

_docs/_user_guide/data_and_analytics/export_braze_data/exporting_revenue_data.md
=> BD-2131: Update exporting revenue report

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
=> BD-2144: Add sentence about catalogs storage limit

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
Closes #**BD-2142**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2142: Clarify CSV file size maximum

_docs/_user_guide/intelligence/ai_content_qa.md
=> Minor edits to Content QA with AI

_docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
=> BD-2147: Fix personalization links from raw tag
