- _docs/_developer_guide/rest_api/user_data.md
The documentation for the response returned from `users/track` endpoint was incomplete. This adds additional fields returned by the endpoint to the documentation.
This can be merged at any time.
---
---
---
---
> Add additional fields to the users/track response documentation

- _includes/search_page.html
- _plugins/algolia_hooks.rb
- assets/js/documents.js
Fix PreCode HTML breaking search page.
Strip html tags from search results
---
---
---
---
> Fix html tags in search

- _docs/_developer_guide/rest_api/user_data.md
Adding documentation to show customers that they can delete users by specifying an array of user alias objects in the `user_aliases` key.
This change was implemented quietly last sprint.
This functionality is live, so this can be merged at any time.
---
---
---
---
> Add user_aliases to the options for deleting users

- _docs/_user_guide/administrative/access_braze/sdk_endpoints.md
I've had instances where clients have included the full value "https://sda.fra-01.braze.eu" in their appboy.xml config file which has caused their integration to break as the SDK uses https by default so actually the sdk is sending "https://https://sda.fra-01.braze.eu". Removing this will make it clearer to developers that they should not include "https://" in their config.
Less confusing for developers.
---
---
---
---
> Removed https:// protocol from sdk endpoints

- _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
- _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
- _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
- _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
We're adding `dispatch_id` as a field on email events for all Currents connectors. This update to the docs represents that change.
This can be merged with the next weekly deploy.
---
---
---
---
> Add 'dispatch_id' to Currents documentation for email events across all connectors

- _docs/_developer_guide/platform_wide/analytics_overview.md
- _docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
- _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md
Custom Event properties are stored for 30 days, not 60. 
incorrect info.
> Custom Event Storage fix:

- _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
Added swift code to display content cards through table view controller and view controller as modal and in navigation controller.
There was no Swift code on the Customization page of Content Cards, so I added some
iOS: swift examples for content cards documentation (PC-970)
More work still to be done. Planning on adding more swift snippets and open source example app in near future.
---
---
---
---
> Add swift code to Content Cards Customization page

- _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization.md
- _docs/_developer_guide/platform_integration_guides/ios/news_feed/customizing_the_news_feed.md
https://jira.braze.com/browse/PC-942
Documentation for how to override our default images for News Feed's "read" indicator and placeholder (empty) image. Also, added docs for the placeholder image in Content Cards
---
---
---
---
> iOS Docs - Override default images for NF and Content Cards

- _docs/_api/endpoints/messaging.md
- Add `"message_variation_id"` to the Content Cad Object. Pattern matched the language to the other message objects (though I'm not sure if it's "must be a Content Card Message" or "must be a Content Card**s** Message".
- Should have been there from the start.
---
---
---
---
> Add variation ID to the Content Card Object for API campaigns

- _docs/_developer_guide/eu01_us3_sdk_implementation_differences/for_ios.md
- _includes/archive/apple/initial_setup.md
1) The old integration examples are now broken due to us changing the default backend endpoint. 
2) We should not expose the backend endpoint as a public interface, which this old integration style does, so we should not present the old integration as an acceptable alternative.
> Modernize ios custom endpoint docs

- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Notably, remove unnecessary references to deprecated methods
> Clean up IAM delegate docs on iOS

- _docs/_hidden/private_betas/amphtml.md
Typo: Braze is not responsible for the customer registering with Braze or meeting the necessary security requirements.
It should be "registering with Google..."
https://www.braze.com/docs/amphtml/#amp-for-email
> Braze/Google Typo in Amp Docs

- _docs/_api/postman_collection.md
api_key variable in JSON does require " " either side of the value. have removed the *not* from this paragraph.
The previous paragraph suggested that the variable of api_key did not require quotes, however, in Postman this value does require quotes.
Makes the setting up of the Postman environment more clear to the customer.
---
---
---
---
> Updated Postman Collection docs to include quotes

- .github/ISSUE_TEMPLATE.md
Issue template had a link for Labels which pointed to a new wiki page creation, instead of the labels page.
---
---
---
---
> Updating Labels link to point to label configuration page

- _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
This updates links in the [Android SDK Initial SDK Setup guide](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#step-3-add-required-permissions-to-android-manifest).
* Step 3 should include an example link to `AndroidManifest.xml` (not `appboy.xml`)
* Step 2 should include a link to `appboy.xml` 
---
---
---
---
> Updated links to example `appboy.xml` and `AndroidManifest.xml`

- _docs/_user_guide/engagement_tools/campaigns/testing_and_more/comparing_campaigns.md
Quick PR to remove the limited access banner note from Campaign Comparisons, since this feature is going GA on July 9th.
This PR should be merged in with the July 9th docs release.
---
---
---
---
> Remove limited access banner from campaign comparisons docs

- _layouts/glossary_page.html
Add image tag to glossary_page layout. use the addtional `image` parameter. Example:
```
image: /docs/assets/img_archive/rest-api-key.png?23c30d863f24a741e6837264a3491564```
> add image to glossary

- _docs/_api/endpoints/user_data.md
Replaces some en-spaces with normal spaces
I was using the docs, copy pasted a JSON post body example and had a bad time. It was invalid JSON because some of the whitespace was en-spaces instead of regular.
---
---
---
---
> Fix some en spaces -> spaces in JSON examples

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
https://jira.braze.com/browse/PC-1124
When creating a static library, by default the linker is unaware of the methods defined in Category classes. In order to link them together, we need to add a new flag to the target of the project to look for these methods in category files when constructing the executable.
More info on this topic here:
https://stackoverflow.com/questions/6820778/linking-objective-c-categories-in-a-static-library
We just need a docs update with this step rather than needing to re-release our SDK 👍
Closes https://jira.braze.com/browse/PC-1124
---
---
---
---
> Manual integration fix Docs update

- _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
https://jira.braze.com/browse/PC-1004
When showing an HTML in-app message in Android, users can override default action listener for their custom handling of certain events. 
The HTML in-app message custom action listener was not documented previously and a customer requested for information on how to implement it.
Closes https://jira.braze.com/browse/PC-1004
---
---
---
---
> Add documentation for custom handling of HTML IAMs actions in Android.

- _docs/_site_pages/api.md
Link should be https://www.braze.com/docs/api/basics/?redirected=true
> Fix API overview link referenece

- _plugins/alert_tag.rb
> I'm adding a Line Break between Alert Header and content
> I'm making this change because it will make the alerts easier to read. 
---
---
---
---
> Add Line Break between Alert Header and content

- _docs/_help/help_articles/data/dispatch_id.md
- _docs/_help/release_notes/2019/july.md
- _docs/_help/release_notes/2019/may.md
- _docs/_help/release_notes/most_recent.md
- _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
- _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment_for_currents.md
- _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
- _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
- _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
> I'm adding a section on Dispatch ID behavior in Campaigns vs. Canvas & Triggered vs. Scheduled - as well as update notes that link to said article. 
> I'm making this change because this is unexpected behavior due to a fundamental function of Canvas that users do not know about. 
> Dispatch ID Details

- _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
1. Code example had an extra square bracket
2. Updated phrasing of toggle method's description
3. Added parentheses for consistency in the table of methods
> Fixes typo in Content Cards code example

- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/localization.md
- _docs/_developer_guide/platform_integration_guides/android/customer_feedback.md
- _docs/_developer_guide/platform_integration_guides/android/news_feed/integration_overview.md
- _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/localization.md
- _docs/_developer_guide/platform_integration_guides/fireos/customer_feedback.md
- _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
- _docs/_developer_guide/platform_integration_guides/ios/customer_feedback.md
- _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/customer_feedback.md
- _docs/_developer_guide/platform_integration_guides/react_native/ios/customer_feedback.md
- _docs/_developer_guide/platform_integration_guides/unity/news_feed.md
- _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/customer_feedback.md
- _docs/_developer_guide/platform_integration_guides/xamarin/ios/customer_feedback.md
- _docs/_developer_guide/platform_wide/platform_features.md
- _docs/_partners/technology_partners/data_and_infrastructure_agility/customer_data_platform/segment.md
- _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Removing all references to feedback feature as we sunsetted it 7/31/19.
Feature is sunsetted and no longer available to customers. 
---
---
---
---
> remove-feedback

- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
By default, Braze Android SDK will not collect location information automatically. Developers will have to explicitly enable location collection by setting the com_appboy_enable_location_collection flag in appboy.xml
Android SDK is being updated to disable location collection by default. Updating Braze documentation to call out this change specifically for informing developers.
https://jira.braze.com/browse/PC-1105
---
---
---
---
> Android - Update docs for disable location collection by default.

- _docs/_hidden/private_betas/create_send.md
It seems we will not create a user alias with create and send if one does not exist, updated docs to reflect this information so that they are not confused.
> Edited to remove references to aliases

- _docs/_hidden/private_betas/create_send.md
> I'm changing some wording around Attributes Objects and Endpoints for clarify some informaiton.
> I'm making this change because I mistakenly called an Object an Endpoint in my initial edits.
---
---
---
---
> Wording Adjustment in Create_Send

- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
- _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
- _docs/_developer_guide/platform_integration_guides/fireos/analytics/location_tracking.md
- _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md
https://jira.braze.com/browse/PC-1271
> I'm changing https://jira.braze.com/browse/PC-1271
> Starting with Braze Android SDK version 3.6.0 Braze location collection is disabled by default. Updating documentation to reflect those changes.
Closes https://jira.braze.com/browse/PC-1271
---
---
---
---
> Update FireOS and Android docs for default location collection being disabled.

- _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
https://jira.braze.com/browse/PC-1249
> Adding to docs Android SDK Content Cards methods
> No docs present to highlight different methods present for Content Cards.
Closes https://jira.braze.com/browse/PC-1249
---
---
---
---
> Add to Android docs Content Cards methods.

- _docs/_api/endpoints/email_templates.md
Successful response properties for templates/email/info was missing a data type for should_inline_css. Added boolean and brief description. Have tested in Postman to confirm data type.
> I'm adding a data type for should_inline_css so that the response is clear to developers without them needing to test.
> I'm making this change because it will lead to less confusions for developers.
---
---
---
---
> Added data type for should_inline_css

- _docs/_hidden/other/documentation_request.md
Remove completion date from request form.
Remove completion date from doc request form.
Due date not needed
---
---
---
---
> remove completion date

- _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
> I'm adding a link where one wasn't. 
> I'm making this change because it was misleading users..
---
---
---
---
> Added link to Pre-populating Custom Data Types

- _docs/_hidden/other/support_contact.md
Added warning for firefox users on support page, and updated confirmation page to expect a confirmation email, or reach out directly.
> Support Contact: added firefox blocking banner, updated thank you message

- assets/css/_content.scss
Code in td wasn't wrapping, causing small width dimension (ie mobile) to render oddly.
Add word break to code with td.
Small width rendering issue.
> fix code in td not wrapping

- _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
Added docs for IAM blacklisting on Android
This can be released immediately
closes https://github.com/Appboy/braze-docs/issues/391
---
---
---
---
> added blacklist docs for android iams

- _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
- _docs/_developer_guide/platform_integration_guides/android/content_cards/data_models.md
- _docs/_developer_guide/platform_integration_guides/android/content_cards/multiple_feeds.md
Added docs for having a Content Cards Feed only display specific cards.
Highly requested documentation.
---
---
---
---
This can be merged at any time
> [Android] Content Card bespoke feed

- _docs/_partners/braze_currents/data_storage_events/message_engagement_events.md
- _docs/_partners/technology_partners/insights/behavioral_analytics/amplitude_for_currents.md
- _docs/_partners/technology_partners/insights/behavioral_analytics/mixpanel_for_currents.md
Coming in late, but this adds documentation for `dispatch_id` as a field for Currents Push events.
This can be merged immediately.
---
---
---
---
> Add dispatch_id for Currents Push events in all destinations

- _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
`appboy://action` schema is not supported by the web SDK. This updates the docs to clarify
https://www.braze.com/docs/user_guide/message_building_by_channel/in-app_messages/customize/#customization
> Clarify that `appboy://action` schema is only supported in mobile app SDKs

- _docs/_user_guide/data_and_analytics/report_metrics.md
Editing analytics definitions to make them more accurate. 
Ultimately, I think we need to allow stats to have different definitions based on the channel (this is higher LOE; I will discuss with Emily). 
For now, I'm making the stats "correct" to the extent of my knowledge.
We are adding these definitions as tooltips on the campaign analytics Dashboard page. I want to make sure they're accurate before doing so.
---
---
---
---
> Cleanup some analytics definitions

- _docs/_developer_guide/platform_wide/analytics_overview.md
> I'm swapping the definitions for the filters `blank` and `is not blank` because they were mixed up.
Closes internal request. 
---
---
---
---
> Swap Blank and Is Not Blank BD-236

- _docs/_help/help_articles/data/dispatch_id.md
> I'm adding a note about dispatch id behavior in Canvas steps. 
> I'm making this change because the information in the doc before was incomplete. 
---
---
---
---
> Dispatch ID Note

- _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
> `"logContentCardDismissed` - Manually log a dismissal to Braze for a particular card is present in the iOS documentation. However, this was missing from the Android one in the link posted below. https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/cards/Card.html#setIsDismissed-boolean-
Closes internal req.
---
---
---
---
> Set a Card as dismissed Method for Android- 235

- _docs/_developer_guide/platform_integration_guides/web/content_cards/customization.md
The "other methods to note" section linked to the wrong JS Docs methods. This PR fixes that.
> fixed wrong links

- _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
This callback usage is deprecated in the Web SDK because it is not required as of 2.3.1
---
---
---
---
> Remove example using deprecated callback

- _docs/_api/basics.md
Removed HTTPS:// from SDK endpoints as this is not required in mobile integrations - only web SDK integrations and this is specified in that documentation. 
It was wrong  :) 
No
---
---
---
---
> Remove HTTPS from SDK Endpoints

- _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Removed mention of Custom Endpoints as we no longer provide them to customers and they are not required even for customers who historically were provided them. Added in info on which endpoint to use.
we don't use custom endpoints with customers anymore
No
---
---
---
---
> Update initial_sdk_setup for Web SDK

- _docs/_api/endpoints/export.md
> I'm extending the Campaign Details Export Endpoint to include the json structure for content card messages.
> I'm making this change because I was looking this up for myself and had to execute the endpoint to find out the json structure and I think it would be easier to just read it in the docs.
---
---
---
---
> Include message structure for exported content cards

- _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
- _includes/archive/aliasing.md
Looking for feedback on
1) Pattern matching `context` on https://www.braze.com/docs/developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed/ (`YOUR_ACTIVITY.this` feels clunky and overly prescriptive)
2) `Appboy.getInstance(context).currentUser?` syntax
> Add kotlin to Setting User IDs page

- _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization.md
- _docs/_developer_guide/platform_integration_guides/android/news_feed/key-value_pairs.md
@radixdev thoughts on this? the method itself is defined in java, but could be useful to demonstrate the syntax that Kotlin users will use anyways, e.g.
```
val slideup = InAppMessageSlideup()
val extras = slideup.extras
```
> Add kotlin syntax for getExtras

- _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
Updated android uninstall docs
Docs were out of date
---
---
---
---
> PC-1437 - Updated Android uninstall tracking docs to mention firebase messaging service

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
I imagine there could be a more elegant solution, but this is at least more future proof.
> Make Carthage docs not dependent on outdated hardcoded version

- _docs/_api/endpoints/export.md
- _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/optional_gaid_collection.md
- _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
- added google, windows, and roku ad ids to liquid doc
- added google, windows, and roku fields within device object in export api doc 
We are adding google play, roku, and windows ad ids into: 
- user profile 
- liquid
- filters 
- export api 
- currents 
as part of our GAID epic > to expose the google play ad id (windows and roku were just bonuses). 
this will assist with making it easier partner integrations within ad tech. 
---
---
---
---
> [do not merge until 10/22] ad-ids-update

- _config.yml
Change github base url so it doesn't send it directly to the edit page, and force people to login to github for users who aren't signed up.
---
---
---
---
> Change github base url

- _docs/_user_guide/message_building_by_channel/content_cards/create.md
> I'm empasizing the 2KB limit on Content Card total size. 
---
---
---
---
> Content Cards 2KB Note Emphasis - BD-302

- _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
> I'm changing https://www.braze.com/docs/user_guide/personalization_and_dynamic_content/liquid/aborting_messages/
> I'm making this change because this doc was a bit misleading that the readers thought no error message would be logged when `abort_message()` is called without params. In fact, it will always log some default messages, so this change is to make it clearer.
---
---
---
---
> abort_message() always logs default error

- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
- _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
- _docs/_developer_guide/platform_integration_guides/fireos/advanced_use_cases/locations_and_geofences.md
- _docs/_developer_guide/platform_integration_guides/fireos/initial_sdk_setup.md
Currently they're buried in Geofences docs, which isnt ideal since location collection is relevant to more than just geofence implementors
> Move location enabling docs to initial sdk setup

- _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
- _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/localization.md
- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
- _docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md
Note that the docs no longer claim we use dry run or not based on the fact that both are theoretically possible.
> Remove references to iOS versions before 3.0.0 + remove dry run reference

- _docs/_user_guide/message_building_by_channel/content_cards/customize.md
> how to change language to indicate no cards	
---
---
---
---
> BD-222 : Content Cards Custom Language

- _docs/_user_guide/message_building_by_channel/in-app_messages/customize.md
The docs linked to mycompany.com when it was meant just as a visual example. I removed the link and changed the example to braze.com
> Removed link from abButtonId code example

- _docs/_user_guide/message_building_by_channel/in-app_messages.md
> I'm adding the dark mode block to the IAM main page now that dark mode docs are no longer hidden
> I'm making this change because #679 
---
---
---
---
> Adding Dark Mode Block to IAM main page

- _docs/_developer_guide/platform_integration_guides/android/content_cards/customization.md
Docs on how to disable the default swipe to dismiss functionality
---
---
---
---
> added content cards docs on disabling swipe to dismiss

- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
getActionWithIdentifier (to handle push notification action) which is currently deprecated, therefore we want to recommend users who use notification actions to implement the user notification framework.
The documentation should say to use didReceiveNotificationResponse:response IF users are using user notification framework for handling push. However, if not using user notification framework, getActionWithIdentifier is still required
> [PC-1646] update action buttons docs

- _docs/_api/endpoints/user_data.md
We don't want to say the external_id is required anymore right since you can create an alias without an external_id now?
> I'm changing the New User Alias Object Specification so that external_id is no longer required.
> I'm making this change because it can be confusing for clients when understanding this API spec.
---
---
---
---
> Updated users/alias/new

- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
`Less than` does not count the selected calendar date.
---
---
---
---
> Date of Custom Attribute, Less than BD-299

- _docs/_developer_guide/platform_integration_guides/react_native/ios/sdk_integration.md
Updated the broken links on the React Native page
---
---
---
---
> Fix links React Native iOS docs

- _docs/_api/errors.md
Changed the value from 50 > 75 as the limit of external_ids for the User Track endpoint.
Added an additional error as the other endpoints e.g. "user export" send a slightly different response when more than 50 external_ids are specified.
Added ANOTHER additional error as the other endpoints e.g. "user delete" send ANOTHER slightly different response when more than 50 external_ids are specified.
> I'm changing the Max Input Length Exceeded description since it's out of date and adding two additional errors.
> I'm making this change because it's unclear as to how many external_ids can be specified when POSTing data to User Track.
---
---
---
---
> Updated error codes

- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
The code now matches with the description beforehand, as the code is correct and references the property of `inAppMessageUIController`, not `inAppMessageController`
---
---
---
---
> Update to use `supportedOrientationMask` property for inAppMessageUIController

- _config.yml
- _includes/html_include.html
- _plugins/noindex.rb
Use `noindex: true` to hide page from SEO and YML description for SEO description.
---
---
---
---
> update SEO with noindex and description

- _docs/_user_guide/engagement_tools/canvas/create_a_canvas/change_your_canvas_after_launch.md
BD-335
Added " - You cannot edit or delete existing connections nor can you insert a step between existing connected steps once a Canvas is launched." to page.
> BD-335: Adding Steps Between Steps to a Canvas Post Launch Conditions

- _layouts/featured_video.html
> Removing Edit on Github Button from Vid Template

- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
willPresent is only for remote notifications received while the app is running in the fg. The UserNotifications framework is only used to handle Alert Payloads and  if you want to handle Silent Payloads, you will have to implement the application(_:didReceiveRemoteNotification:fetchCompletionHandler:).
> Update iOS Custom IAM triggering docs

- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
*Will merge after `iOS SDK 3.21.1` is released*
Corresponding docs changes for next release 3.21.1 - Feature to force hiding the status bar on Full and HTML IAMs
https://github.com/Appboy/AppboyKit/pull/3386/files#diff-1ec57d3fabcc6131bf28b8d9d117c3a7R10
---
---
---
---
> [iOS Docs] Feature to force hide status bar for Full & HTML IAMs

- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization.md
Update docs to reflect that code for custom inapp message triggerring should be added to application(_:didReceiveRemoteNotification:fetchCompletionHandler:) and not userNotificationCenter(_:willPresent:withCompletionHandler:)
> Update iOS Custom IAM trigger docs

- _docs/_partners/additional_channels/sms/twilio.md
Warning that this page and all support of twilio SMS webhooks will be deprecated in January.
> Twilio Webhook Support Deprecation

- _docs/_developer_guide/platform_integration_guides/xamarin/android_and_fireos/customer_feedback.md
The Xamarin SDK Integration for Android are missing the Cluster specification within the appboy.xml file. This is causing a default Xamarin integration to point to US-01. These should be updated to match the native Android documentation, which instructs the client to specify their specific Braze Cluster. The native Android documentation I'm referring to is this:
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#step-2-configure-the-braze-sdk-in-appboyxml
@KellieHawks 
<details>
- [ X] Check that all links work!
- [X ] Tag others as Reviewers as necessary.
- [ X] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.
</details>
> Xamarin Integration Instructions missing Cluster

- _docs/_api/endpoints/export/canvas/get_canvas_details.md
Reference: MA-1773
Released under a feature flipper on 4/6, will merge this after we flip it globally.
> Add variant id to canvas details

- .gitignore
- Rakefile
- _config.yml
- _incremental_config.yml
- _plugins/jekyll_asset_pipeline.rb
- assets/css/_404.scss
**Why**
Local builds that used to take 60 seconds now take 4.
Introduced incremental builds
The reason that https://github.com/Appboy/braze-docs/pull/605/files didn't work was because the `_config.yml` listed the documentation source directory as `.`, meaning that all files, including build temporary files, were treated as source by default and visible to the file watcher.
Thus, when the asset pipeline generated its css, js, etc. files, the file change watcher would pick them up as source changes, "regenerate" them and thus delete them. The end result was that those asset files would get deleted and break all the documentation pages. 
The _incremental_ fix in this PR was to move the asset pipeline folder out of the source tree. Since all files in this repo are …
> Incremental building of the documentation for debugging

- _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
based on a question raised by a customer
> Clarified all in-app messages don't display on session start

- _docs/_api/endpoints/user_data/post_user_track.md
Updating the wording for the API limits to be more concise and positive. 
I'm not sure how to link the API Limits page but that would be a good option here.
> Wording change for request limit

- _docs/_user_guide/administrative/app_settings/manage_app_group/custom_event_and_attribute_management.md
Added a table to describe how forced data type coercion behaves, specifically that you can pass in arrays as comma separated values, or `t`|`1` for booleans
> Added data type coercion table

- _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
BD-600: clarified shopify and braze money filter differences
> BD-600:clarified shopify and braze money filter differences

- _docs/_developer_guide/platform_integration_guides/web/in-app_messaging/in-app_message_delivery.md
- _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
clarifying that calling `appboy.display.showInAppMessage` and `appboy.display.automaticallyShowNewInAppMessages` may result in duplicate messages
> add warning about appboy.display.showInAppMessage

- _docs/_partners/advertising_technologies/attribution/adjust.md
- _docs/_partners/advertising_technologies/attribution/appsflyer.md
- _docs/_partners/advertising_technologies/attribution/branch_for_attribution.md
- _docs/_partners/advertising_technologies/attribution/kochava.md
- _docs/_partners/advertising_technologies/attribution/singular.md
BD-641: Remove/Update iOS/IDFA Docs
- Remove all instances of iOS IDFA
- Link out to iOS 14 upgrade guide
- provide additional blurbs about deeplinking/click tracking settings.
> BD-641: Remove/Update iOS/IDFA Docs

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
Fix probable typo, because mentioning tvOS apps on the iOS integration page seems wrong.
<details>
</details>
> doc: fix platform typo in bitcode section

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
clarified IDFA requirements so that it doesn't read like IDFA prompt is always required, rather it's required if you collect IDFA.
> clarify IDFA requirements

- _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/fine_network_traffic_control.md
- _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration.md
- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods.md
- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md
- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager.md
- _docs/_developer_guide/platform_integration_guides/ios/news_feed/requesting_unread_card_count.md
- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/action_buttons.md
- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization.md
- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/rich.md
- _docs/_developer_guide/platform_integration_guides/ios/sample_apps.md
- _docs/_developer_guide/platform_integration_guides/tvos/initial_sdk_setup.md
- _docs/_developer_guide/platform_integration_guides/tvos/news_feed.md
- _docs/_partners/insights/crash_analytics/apteligent.md
- _includes/archive/apple/initial_setup.md
- _includes/archive/in_app_message.md
This will help us develop Stopwatch more efficiently and future proof for future changes/migrations.
In the meantime, as we encounter customer confusion, we should provide embedded examples.
> Remove references to Stopwatch

- _docs/_developer_guide/platform_integration_guides/ios/push_notifications/integration.md
https://jira.braze.com/browse/SDK-1319
There's some ambiguity between the old objc docs, which recommended using `.alert` and the old swift implementation, which used `.alert, .badge, .sound`. For now, defaulting all to the old objc implementation
> [SDK-1319] Use banner+list instead of alert in iOS fg push delegate for iOS 14+

- _docs/_developer_guide/platform_integration_guides/react_native/android_and_fireos/analytics/revenue_tracking.md
- _docs/_developer_guide/platform_integration_guides/react_native/ios/analytics/revenue_tracking.md
`ReactAppboy.logPurchase` has different parameter type. I updated it based on [appboy-react-sdk](https://github.com/Appboy/appboy-react-sdk/blob/master/index.d.ts#L200) and [example](https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/AppboyProject.js#L378).
Closes #**nothing**
---
---
<details>
</details>
<details>
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, …
> Update revenue_tracking.md for React Native

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
https://jira.braze.com/browse/SDK-1443
Clarifies iOS [manual integration instructions](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options/) by:
- specifying which file should be downloaded in step 1
- telling people to use SDWebImage's instructions
<details>
</details>
<details>
- Always speak to …
> [SDK-1443] iOS Docs SDWebImage manual integration

- _docs/_developer_guide/platform_integration_guides/android/push_notifications/troubleshooting.md
> Remove genymotion reference

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options.md
https://jira.braze.com/browse/SDK-1443
Follow-up to https://github.com/braze-inc/braze-docs/pull/2195
Cleans up iOS [manual integration instructions](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options/) by removing unneeded SDWebImage steps.
Looking for some help doing QA on this to ensure we can safely remove these integration steps.
Based on the QA steps below, GIFs seem to continue to display correctly after omitting these SDWebImage installation instructions.
QA:
1. Create a new iOS project in Xcode
2. Follow the manual integration instructions according to this PR
3. View an IAM, CC, or NF card containing a gif.
Example code to view an IAM:
```
Appboy.start(withApiKey: "1fbb9af3-93e0-43a2-920c-c6d867dab72a", // …
```
> [SDK-1443] iOS Docs SDWebImage remove extra steps

- _docs/_hidden/private_betas/amphtml.md
- _docs/_hidden/private_betas/canvas_in-app_messages.md
- _docs/_hidden/private_betas/get_campaign_url_info.md
- _docs/_hidden/private_betas/get_canvas_url_info.md
- _docs/_hidden/private_betas/link_aliasing.md
- _docs/_hidden/private_betas/nested_object_support.md
- _docs/_hidden/private_betas/shopify.md
- _docs/_hidden/private_betas/twilio.md
- _docs/_hidden/private_betas/view_pii.md
@bre-fitzgerald 
After some thought, permalinks for hidden docs are best. 
Once removed from hidden, must switch permalink to alias link so beta customers can still use old link.
> Permalink Fix

- _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
creating new cohort imports section in the partner docs to add misc partners that offer cohort imports, will redirect to the appropriate section if partner integration fits in an existing category.
> Cohort Import Section - Partner Docs

- _docs/_help/help_articles/segments/segmentation_logic_with_negative_or_filters.md
> Updating to mention the filter `does not match regex` should also not be used with overlapping `OR` filters, style clean up, and removing outdated warning message.
Closes #**BD-1072**
---
> BD-1072: Update Segmentation Logic with Negative OR Filters

- _docs/_developer_guide/platform_integration_guides/android/analytics/disabling_tracking.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/logging_purchases.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/social_data_tracking.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_custom_events.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/tracking_sessions.md
- _docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/disabling_tracking.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/location_tracking.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/logging_purchases.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_custom_attributes.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/setting_user_ids.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/social_data_tracking.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_custom_events.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/tracking_sessions.md
- _docs/_developer_guide/platform_integration_guides/ios/analytics/uninstall_tracking.md
- _docs/_developer_guide/platform_integration_guides/web/analytics/location_tracking.md
- _docs/_developer_guide/platform_integration_guides/web/analytics/logging_purchases.md
- _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md
- _docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
- _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md
- _docs/_developer_guide/platform_integration_guides/web/analytics/tracking_sessions.md
> Updating the `h1` tags of some articles in the Developer Guide to match their `article_title` tag. Received internal feedback that they thought there were duplicate links in LAB content because the Android, iOS, and Web analytics articles have the same name (and very similar content).
---
> Update Analytics article titles

- _docs/_hidden/redirects/canvas_in-app_messages.md
> Removing redirect for `/canvas_in-app_messages` permalink, since it's also used in [canvas_in-app_messages.md](https://github.com/braze-inc/braze-docs/blob/14f3e43d6d125a6417d3e06b617abb8c6011a[…]7/_docs/_hidden/private_betas/canvas_in-app_messages.md?plain=1).
> Remove unnecessary redirect

- _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
> I'm updating the list of IPs on Making an API Call that customers need to whitelist in EU for connected content
Closes #**BD-1143**
> BD-1143: Update list of IPs that customers need to whitelist in EU for connected content

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/completing_integration.md
https://jira.braze.com/browse/SDK-2080
Updating docs to accurately represent how to import the files. Here are sample apps following the integrations:
- [Swift sample app](https://drive.google.com/file/d/1LtTG2HQibS79Yfu6dOSw91sf_xm-C3nN/view?usp=sharing)
- [ObjC sample app](https://drive.google.com/file/d/1YV50NZ_S5_1vqFdemQw4D5k73QESz7wX/view?usp=sharing)
---
<details>
<br>
</details>
<details>
<br>
- [Technical Documentation Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24 …
> [SDK-2080] Manual Dynamic XCFramework Integration docs update

- _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
Removing bullet about Zip File feature in Backward Incompatible Features section
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
> Update preview.md to remove ZIP files backward incompatible feature

- _docs/_help/release_notes.md
- _docs/_help/release_notes/2022/january.md
- _docs/_user_guide/message_building_by_channel/content_cards/about.md
- _docs/_user_guide/message_building_by_channel/push/about.md
- _docs/_user_guide/message_building_by_channel/sms/about_sms.md
- _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
- _docs/_user_guide/message_building_by_channel/webhooks.md
- _docs/_user_guide/message_building_by_channel/webhooks/understanding_webhooks.md
Changing overview article names to be consistently named between messaging channels ("About [channel]").
> Standardize overview article naming for channels

- _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
- _includes/campaign_analytics.md
Updating Email Reporting and the Email Analytics Glossary to clarify "Machine opens" vs. "Other opens"
> Clarify email analytics

- assets/js/broken_redirect_list.js
Fixing the following broken links:
- https://www.braze.com/docs/developer_guide/platform_integration_guides/xamarin/ios/sdk_integration/
- https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup/
- https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/ios/sdk_integration/
- https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/ios/sdk_integration/
> Add redirects for broken SDK links

- _docs/_user_guide/administrative/app_settings/manage_app_group/tags.md
Since we're moving away from News Feed and towards Content Cards, removing mention of News Feed as an example of content to use tags on.
> Remove mention of News Feed from tags.md

- _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
Since Content Cards is recommended over News Feed, replacing mentions of News Feed in the description and intro with Content Cards.
> Update key-value pairs to replace News Feed with Content Cards

- _docs/_api/api_limits.md
- _docs/_api/basics.md
- assets/js/broken_redirect_list.js
Customers and internal team members say our rate limits are in a weird place, and difficult to reliably reference. This PR pulls the **API limits** section of the API overview article into its own separate article in the API docs. This also includes minor restructuring and additional information to clarify batching API requests and monitoring your rate limits. 
@lydia-xie and @KellieHawks, tagging both of you for review to see if this change works for you—any feedback would be great! Next step is adding a section/callout to each endpoint article specifically mentioning the API limit for that endpoint.
> Add dedicated API rate limits article

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
- _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
> Reverts #3120. Specifies the values that are populated in the `platform` field in Currents data. Information is added in two places:
1. As a table in the details dropdown at the top of both glossary pages.
2. As a list of devices in the `platform` field of respective event entries of both glossary pages.
Closes #**BD-1229**
---
> BD-1229_pt2: Specify `platform` values for Currents glossaries

- _docs/_api/endpoints.md
Adds an API endpoint index, replacing the current `config_only` endpoint page in the API docs. This page lists all available Braze endpoints grouped by category.
> API endpoint index 

- _docs/_api/objects_filters/aliases_to_identify.md
- _docs/_api/objects_filters/event_object.md
- _docs/_api/objects_filters/messaging/email_object.md
- _docs/_api/objects_filters/purchase_object.md
- _docs/_api/objects_filters/user_attributes_object.md
> Some objects include "See External User ID" or "See App Identifier" but nowhere on the page linked to the relevant docs. This adds those links.
Closes #**BD-1268**
--
> BD-1268: Update objects with missing doc links

- _docs/_hidden/private_betas/email_history.md
> Adds hidden doc for Email History tab FAQ
Closes #**BD-1337**
> BD-1337: Email History tab FAQ

- _docs/_api/objects_filters/messaging/android_object.md
- _docs/_api/objects_filters/messaging/apple_object.md
- _docs/_api/objects_filters/messaging/content_cards_object.md
- _docs/_api/objects_filters/messaging/email_object.md
- _docs/_api/objects_filters/messaging/kindle_and_fireos_object.md
- _docs/_api/objects_filters/messaging/sms_object.md
- _docs/_api/objects_filters/messaging/web_objects.md
- _docs/_api/objects_filters/messaging/webhook_object.md
- _docs/_api/objects_filters/messaging/windows_objects.md
> Customer was confused on the email object page (thought it was for use in the dashboard when building an email campaign). Adding a standardized introductory sentence to the messaging objects to make it clear that they are for use with the messaging endpoints. This also specifically calls out the name of the object (ex: `content_card` object) for added clarity on expected format.
> Clarify messaging object usage

- _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/sample_queries.md
@jayhahn @jeffreystutz 
We recently received a docs request asking for a clarification of the year on this note found in our snowflake docs:
"The value of `sf_created_at` is reliable only for events that were persisted after `Nov 15th, YEAR 9:31 pm UTC`."
Any help is much appreciated.
> BD-1367: Add year to sf_created_at note

- _docs/_user_guide/message_building_by_channel/sms/non_native/double_opt_in.md
Add missing context to link:
https://www.braze.com/docs/user_guide/message_building_by_channel/sms/non_native/double_opt_in/
For section 
`We suggest setting a triggered entry in Canvas whenever there’s an incoming event sms_response_subscriptionGroupName_custom`
> Add reference to custom-keyword-messaging-handling

- _docs/_developer_guide/platform_integration_guides/android/android_13.md
android 12 now provides permanent exemption instead of temporary exemption for upgraded users.
> remove temporary exemption

- _docs/_api/basics.md
seems we can get rid of a 9 year old deprecated field with no reference in docs or slack
> remove company_secret note

- _docs/_hidden/private_betas/canvas_user_update.md
> BD-1541: Clarify deprecation of /users/track B2B webhooks in User Update

- _docs/_help/help_articles/segments.md
- _docs/_help/help_articles/segments/search_exact_text.md
- _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md
> Adds article with workaround to **Help** > **Segments**
> Adds instructions for finding exact text to **Searching for campaigns**
Closes #**BD-1549**
---
> BD-1549: Add instructions for searching exact text

- _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
Often when dealing with devs that are inexperienced with push notifications I find that they follow some guide they find online and request push permissions in the startup code. We often need to tell them not to do this. This is more of a problem when the Braze SDK will be handling this for them now.
- [ X] No
---
<details>
<br>
- [X ] Check that all links work.
- [ X] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [X ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`
</details>
<details>
<br>
- [Writing Style …
> Clarification for Devs Inexperienced with Push

- _docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-1537: Using JSON in KVP to access extras

- _docs/_developer_guide/platform_integration_guides/flutter/changelog.md
- _docs/_developer_guide/platform_integration_guides/react_native/changelog.md
- _docs/_developer_guide/platform_integration_guides/sdk_changelogs.md
- _docs/_developer_guide/platform_integration_guides/xamarin/ changelog.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-1558: Update Changelog list

- _docs/_hidden/private_betas/amphtml.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
> Removed duplicate field for Canvas entry event, style edits for AMP for Email doc
Closes #**BD-1564**
---
> BD-1564: Remove duplicate field and doc edits

- _docs/_user_guide/engagement_tools/segments/segment_extension.md
Now that we're 7 months post-Feb 1st (change being in effect) we can remove that wording.
Part of: https://jira.braze.com/browse/UT-37
> Segment extension disable daily regeneration notice update

- _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
> Edit limitations for Cloning Canvases doc

- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Update custom attribute filters

- _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> BD-1692: Add callout that link templates in drag and drop editor require link aliasing enabled

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
>  Plus add some line breaks for readability
Closes #**BD-1701**
> BD-1701: Note that Inbound SMS attribution has a one-minute cache

- _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md
- _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Update Shopify Payload Examples

- _includes/campaign_analytics.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-1734: Update push campaign analytics

- _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
> It was pointed out that the user docs for /v2/subscription/status/set are missing the warning that the docs for /subscription/status/set have (https://brazetechnology.slack.com/archives/CAA0V6Z7Y/p1668080206166959). They should both have the warning.
Closes EINFRA-518
---
<details>
<br>
</details>
<details>
<br>
</details> …
> [EINFRA-518] Adds the warning to wait two min after /users/track

- .github/PULL_REQUEST_TEMPLATE.md
- _docs/_docs_pages/cla.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Clarify CLA field and Update Pull Request Template

- _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
- _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
- _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
- _docs/_api/endpoints/scim/get_see_user_account_information.md
- _docs/_api/endpoints/scim/post_create_user_account.md
- _docs/_api/endpoints/scim/put_update_existing_user_account.md
- _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
- _docs/_api/endpoints/templates/email_templates/post_create_email_template.md
- _includes/rate_limits.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Misc API updates

- assets/js/broken_redirect_list.js
> Fixing a few redirects that point `/docs/frequency_capping_tag/` to conflicting places. All now point to `/docs/user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting/#frequency-capping`
> Fix redirects pointing at different locations for the same URL

- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md
- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences.md
- _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/custom_styling.md
- _docs/_developer_guide/platform_integration_guides/android/content_cards/customization/default_feed.md
- _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/message_dismissal.md
- _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/implementation_guide.md
- _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
- _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/click_listener.md
- _docs/_developer_guide/platform_integration_guides/android/news_feed/customization/custom_styling.md
- _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md
- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Appboy -> Braze docs updates

- _docs/_api/data_retention.md
- _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
- _docs/_user_guide/onboarding_with_braze/data_points.md
> Data doc edits pt. 3

- _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
"legal law" seems too redundant, and "legal requirement" is more accurate because it includes regulations that are rules created by entities with legal authority but are not laws per se.
Also, note that this text is linked to <https://www.braze.com/docs/user_guide/message_building_by_channel/sms/sms_laws_and_regulations/>, which has the term "legal requirements".
This is not a strong recommendation on my side, but I am curious why "legal law" is better if you prefer to keep it.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …
> Proposed style change

- _docs/_user_guide/data_and_analytics/your_reports/funnel_reports.md
> Removes incorrect reference to API-triggered campaigns, should be API campaigns.
Closes #**BD-1813**
Closes #**BD-1864**
> BD-1813_1864

- _docs/_api/api_limits.md
- _includes/rate_limits.md
Finessed the user/track rate limit based on the fact that you can use arrays , nested objects, and segmentation extensions to circumvent or exceed the "225 data points" claim
> Finessed the user/track rate limit

- _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
The previous version of the docs made it seem like user attributes and events are merged when they are not.
---
<details>
<br>
</details>
<details>
<br>
</details>
> Clarify User Merge Behaviour

- _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
- _docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
- _docs/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md
> BD-1876: Add tips for cloning Canvases 

- _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
- _docs/_user_guide/message_building_by_channel/in-app_messages/templates/simple_survey.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-1889: Update requirements for simple survey

- _docs/_user_guide/onboarding_with_braze/email_setup/import_your_email_list.md
- _docs/_user_guide/onboarding_with_braze/email_setup/setting_up_ips_and_domains.md
> Followup for email edits

- _docs/_user_guide/message_building_by_channel/push/push_primer_messages.md
From a ticket:
> The section "MANUAL CODE REMOVAL" in the Push Primer documentation (URL attached) makes a reference to a snippet of code that seems to be invalid. The documentation instructs the user to remove the line:
UIApplication.shared.registerForRemoteNotifications()
However, I checked this with an iOS mobile developer that thinks that the code that needs to be removed is actually lines 23, 24 and 25 from Step 8 of the Instructions in the Swift documentation:
> https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b1-standard-push-notifications
> Could you please double check?
Finessed the language around this to be a bit more open ended, make it clearer what needed doing, and by whom. 
I do need help with the **code snippets**. Either we should go broad (remove code _like_ …
> Finessed manual code removal

- _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
added Kotlin to react init docs 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks …
> Android docs/ update react docs to explicitly add Kotlin

- _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
- _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
- _lang/fr/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
- _lang/fr/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
https://jira.braze.com/browse/CO-1330
* Updates braze docs related to https://github.com/Appboy/platform/pull/53533
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
> CO-1330 updates catalog endpoint docs to remove fields-do-not-match error

- _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md
- _docs/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Fixes for CDI docs

- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
- _docs/_developer_guide/platform_integration_guides/swift/push_notifications/testing.md
- _docs/_developer_guide/platform_wide/sending_test_messages.md
Hey @lydia-xie I noticed that three files had instances of using double curly braces for placeholder text and these weren't being rendered in code blocks on the site, so I removed them. Just a weird quirk to be aware of!
> Removed double curly braces in examples, since they were not rendering

- _docs/_user_guide/intelligence/faqs.md
- _docs/_user_guide/intelligence/intelligent_timing.md
> Part of Kiribati observes a time zone of UTC+14, which is actually the first time zone in the world. Updating references of Samoa time (Samoa not Samoan) to say "one of the first time zones in the world" instead of "the first".
Closes #**BD-1971**
---
> BD-1971: Update references to Samoa time as "one of the first" instead of "the first" time zone 

- assets/js/developer_nav.js
Please review and double check everything is working. Had to make a few more adjustments then I initially thought.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
> Adjust left nav expand level

- _docs/_user_guide/data_and_analytics/query_builder/custom_sql.md
> BD-1976: Custom SQL in query builder EA

- _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
> Original ticket reporter for BD-2000 reached out to request JSON snippets have variables used instead for the `app_id` and `subscription_group_id`. I also ran the snippets through a JSON pretty print to make it a bit easier to read.
Closes #**BD-2000**
> BD-2000 pt2: Replace app_id and subscription_group_id with variables

- _docs/_developer_guide/platform_integration_guides/android/analytics/location_tracking.md
Updated:
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/analytics/location_tracking#disabling-automatic-location-tracking
Not Updated:
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/locations_and_geofences/#step-3-enable-braze-location-collection
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#step-5-enable-location-tracking
Reasoning: For enablement use-cases, using braze.xml will be simpler and less error prone. For disablement use cases, customers will often need a runtime option.
> [SDK-3595] Add BrazeConfig to disable location collection docs

- _docs/_help/help_articles/push/push_token_migration.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-2016: Clarify push token requirements for migration

- _docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
Closes #**BD-2030**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-2030: Update Manage Approval Settings details

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-2032: Updates to currents fields

- _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
> BD-2041: Clarify details about Message step

- _docs/_developer_guide/platform_integration_guides/sdk_primer.md
- _docs/_developer_guide/platform_wide/sdk_authentication.md
These changes include updates for the Swift SDK that are outside the `Swift SDK` platform integration guide, particularly with
* SDK Authentication ([Preview Link](https://braze-docs-67v2bl4s5-braze.vercel.app/docs/developer_guide/platform_wide/sdk_authentication/))
* Device Allowlist Configuration ([Preview Link](https://braze-docs-67v2bl4s5-braze.vercel.app/docs/developer_guide/platform_integration_guides/sdk_primer/))
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …
> [SDK-3289] Update miscellaneous references and code snippets for Swift SDK

- _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
> Support for Push Primer actions is not yet available
-
> Remove push primer prerequisites

- _docs/_user_guide/engagement_tools/testing/race_conditions.md
>  Add that the race condition for targeting new users also occurs when simultaneously creating a user and logging events or attributes for that new user in separate requests.
Closes #**BD-2068**
---
> BD-2068: Clarify race conditions scenario

- _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
- _docs/_developer_guide/platform_integration_guides/ios/content_cards/refreshing_the_feed.md
- _docs/_developer_guide/platform_integration_guides/web/content_cards/refreshing_the_feed.md
Reverts braze-inc/braze-docs#5277
> Revert "[SDK-3556] Add rate limiting note for `requestContentCardsRefresh` (iOS, Android, Web)"

- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> BD-2079: Update Segment.io docs links

- _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Punchh broken link fix

- _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md
Fix incorrect documentation which stated that the name and content fields in the update content block api call were required. After testing this against the Braze api the following api request will work, showing that the only required field is content_block_id:
curl --location -g 'https://{{instance_url}}/content_blocks/update' \ --header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{api_key}}' \
--data '{
"content_block_id" :"content_block_id"
}'
>I'm updating the documentation readme of the update content block request to properly indicate which fields are optional.
---
<details>
<br>
</details>
<details>
<br>
- [Writing Style …
> Update post_update_content_block.md to fix optional parameters

- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
this is causing new integrating customers to get yelled at by google play for using ad_id, which we don't need
Removing firebase-core as a dependency in our push messaging docs. We don't need it for push.
> remove firebase-core dependency from android push docs

- _docs/_hidden/other/airship_migration.md
- _docs/_hidden/other/credit_ratios.md
- _docs/_hidden/other/devices_and_carriers.md
- _docs/_hidden/other/ephemeral_custom_events.md
- _docs/_hidden/other/handbooks.md
- _docs/_hidden/other/user_csv_lambda.md
- _docs/_hidden/private_betas/canvas_approval.md
- _docs/_hidden/private_betas/canvas_comments.md
- _docs/_hidden/private_betas/canvas_drafts.md
- _docs/_hidden/private_betas/criteo_audience_sync.md
- _docs/_hidden/private_betas/data_transformation.md
- _docs/_hidden/private_betas/dnd_content_blocks_preview.md
- _docs/_hidden/private_betas/idle_campaigns.md
- _docs/_hidden/private_betas/linkedin_audience_sync.md
- _docs/_hidden/private_betas/recommendations.md
- _docs/_hidden/private_betas/sql_segments_tables.md
- _docs/_hidden/private_betas/test_connectors.md
Remove `layout: dev_guide` workaround for padding issue in hidden docs that caused images to have no border. Padding issue resolved in #5551
> Remove dev_guide from hidden docs

- _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
> I changed the description of how to edit links in Content Blocks that were created before link aliasing was enabled. The prior version was incorrect."
Closes #**[BD-2230](https://jira.braze.com/browse/BD-2230?jql=project%20%3D%20BD%20AND%20status%20%3D%20Backlog%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)**
> BD-2230 Editing old Content Blocks with Link Aliasing enabled

- _includes/campaign_analytics.md
> This information being nested in a `details` dropdown has caused many users to skip over it. Support noted this information is very helpful so should be immediately visible for search
> Pull Content Card metric dropdown into main article

- _docs/_hidden/other/user_archival.md
- _docs/_user_guide/data_and_analytics/user_data_collection.md
- _docs/_user_guide/privacy_portal.md
- assets/js/broken_redirect_list.js
> Per discussion in #docs-writing-thoughts-re-competitive, removing the User Archival doc from User Data Collection and making it so that the only place it can be accessed from is the Privacy Portal
Closes #**BD-2244**
> BD-2244: Remove User Archival from Data section

- _docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
Add a warning about using connected content in the user update step because user update step does not respect the canvas rate limit and will execute in excess of 200K requests per min.
Link to Case where this was discoivered
https://braze.lightning.force.com/lightning/r/Case/5003o00001drHn3AAE/view
- [ X ] No
> User Update Step Connected Content Warning

- _docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
Got some feedback that the language we chose here was no bueno (Should not use the term "ensures" for legal purposes), putting in a fix
> Spelling error, legal tweak

- assets/js/broken_redirect_list.js
> Some links from the dashboard to docs are broken, troubleshooting redirects while product updates dashboard links 
---
> Update older intel redirects

- _docs/_developer_guide/platform_integration_guides/ios/content_cards/customization/custom_styling.md
- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/handling_in_app_display.md
https://jira.braze.com/browse/SDK-4023
This is the product of a [client ask](https://brazetechnology.slack.com/archives/CBU9BRKHA/p1690996279416599?thread_ts=1690967303.424139&cid=CBU9BRKHA). For both IAMs and CCs, there are new docs for disabling light mode that cover using the AppboyKit/ObjC SDK in both ObjC and Swift.
QA:
For both IAMs and content cards, try following the Swift tab of the new docs to disable dark mode in HelloSwift in the Appboykit repo.
For content cards: try following the docs to edit the content cards section of `FeedUIViewController.m` in Stopwatch. Verify that the content card UIs you edit display content cards in light mode when the sim is both in light and dark mode.
For IAMs: try following the docs to edit the Stopwatch AppDelegate. Verify that [this …
> [SDK-4023] Public docs for disabling dark mode in Content Cards and IAMs in ObjC

- _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
- _docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
> - Catalogs can now return up to 50 results
> - Customers can now have 30 selections per catalog
Closes #**BD-2390**
---
> BD-2390: Update catalog results and selections limits

- _docs/_user_guide/message_building_by_channel/push/android/notification_channels.md
> Revising based on feedback from Chris Rued, specifically "Choosing a Notification Channel will not update the reachable users count, instead it will include this channel information with the push sent to the device."
Closes #**[BD-2330](https://jira.braze.com/browse/BD-2330)**
---
> BD-2330: Correcting behavior for selecting a notification channel

- _docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
[CLIP-751](https://jira.braze.com/browse/CLIP-751)
Currently the generic SAML SSO docs refer to setting the “Sign-On URL” to `https://<SUBDOMAIN>.braze.com`. However, the term “Sign-On URL” is not a standardized SAML term and is used differently for different identity providers. For instance, on Okta and OneLogin, “Sign-On URL” refers to the Assertion Consumer Service URL, which looks like `https://<SUBDOMAIN>.braze.com/auth/saml/callback`. Azure AD does use “Sign-On URL” to mean the ACS URL, so maybe this was derived from that.
This change updates the generic SAML SSO docs to not explicitly suggest setting Sign-On URL to anything specific or implying that it’s a distinct field from the ACS URL. Instead, a note is added to the ACS URL mentioning that it may be called “Sign-On URL” on some …
> [CLIP-751] SAML SSO: Clarify ‘Sign-on URL’ for different providers

- _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
> reverts #6062

- _docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
renamed Developer Console Log to match dashboard "Message Activity Log".
Might exist elsewhere too
> Message Activity Log

- _docs/_help/release_notes/deprecations.md
> Updating deprecations page to be formatting as a reference article so that the TOC will auto-populate with anchor links for PMs to grab in comms.
Closes #**BD-2445**
> BD-2445: Change deprecations from landing page to reference

- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
> Changed "Exists / Does not exist" to the correct "Is blank / Is not blank" and reordered the list of filters to match the order they appear in the UI.
Closes #**BD-2454**
> BD-2454: Fixed incorrect filter options for number attributes

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
- _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Merged in haste, repent in leisure. 
Reverting this merge pending the release date.
> Revert "Add note about IDFV being disabled by default in Swift SDK 70.0"

- _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md
- _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Reverts the previous reversal of the PR (braze-inc/braze-docs#6259) to actually publish the IDFV note.
> Add note about IDFV being disabled by default in Swift SDK 70.0

- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
> Adds missing links for supported side-by-side integrations, as well as some general cleanup to improve the flow and structure of the content.
> - Moves supported methods into tabs and outside of the regular "step" flow, as it's only a reference
> - Removes step 3a/3b/3c because they are not connected substeps, but rather 3 separate options for step 3
> - Gives the additional settings content an actual step
Closes #**BD-2482**
> BD-2482: Add side-by-side integration links for Rudderstack

- _docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
> Remove old FAQ about custom domains in the Link Shortening article
Closes #BD-2492
> BD-2492 Remove old FAQ on link shortening custom domain

- _docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
> The time limit for the evaluation window for an Action Path step is 31 days.
Closes #**BD-2494**
---
> BD-2494: Add time limit for evaluation window for action paths

- _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
> Add example for how to update a field in an existing array of objects in Cloud Data Ingestion
Closes #**BD-2402**
---
> BD-2402: Add example for updating field in an existing array of objects 

- assets/css/_api.scss
Updates font size of pages using API format (glossaries, API references) to use the same font size as the rest of docs (16px) rather than a smaller size (14px). This does not change the size of API methods or URLs.
> Update font size of API

- _docs/_api/endpoints/user_data/post_users_merge.md
> All existing custom attributes on the target profile are retained and will include any attributes that didn't exist on the target profile.
Closes #**BD-2505**
---
> BD-2505: Clarify merge behavior for custom attributes in user profiles

- _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
> Clarification for how unsubscribes work with duplicate emails present: 
> if one email unsubscribes, other profiles (up to 100 profiles) with that email address are updated to reflect the same subscription state. This applies for unsubscribes as well as other changes to the subscription state (global email subscription state, individual subscription group statuses)
Closes #**BD-2486**
---
> BD-2486: Clarifying unsubscribes behavior with duplicate emails

- _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> Adding workaround detail for viewing all link templates in the Link Management tab of the HTML editor. Will submit a product bug to fix the UI so that the **Add a Link Template** button is persistent.
---
> BD-2507: Add workaround for viewing all link templates 

- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
[https://jira.braze.com/browse/SDK-4256](https://jira.braze.com/browse/SDK-4256)
Implements changes to reflect [this SDKs story](https://jira.braze.com/browse/SDK-4169).
I'll remember to mark this as `on hold/do not merge` when I open it for review since we haven't released the document change yet.
I have to say I was pretty surprised and continue to be a little suspicious of how little needed to be changed.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZ …
> [SDK-4256] IAM Display Option .later deprecated for .reenqueue

- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Reverts braze-inc/braze-docs#6324
> Revert "[SDK-4256] IAM Display Option .later deprecated for .reenqueue"

- _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery.md
- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
[https://jira.braze.com/browse/SDK-3429](https://jira.braze.com/browse/SDK-3429)
I pretty much just copied the comment describing the delegate function being documented. I wasn't totally sure what else to say to be honest.
>   /// Notifies the delegate that Braze did not find a matching trigger for the event.
>   ///
>   /// This delegate method is called every time the SDK processes an event but no in-app message
>   /// campaign is setup for that event.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …
> [SDK-3429] Swift - Document BrazeDelegate.(_:noMatchingTriggerForEvent)

- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
> Updated **Huawei App Secret** to **Huawei Client Secret**. The UI hasn't been updated, so the screenshot remains showing **Huawei App Secret**. (I contacted David about the UX copy needing an update.)
Closes #BD-2554
> BD-2554 Huawei Client Secret renaming

- _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> BD-2573: Clarify that confidence only shows up when an optimization is selected

- assets/js/broken_redirect_list.js
An incorrect link was added in the dashboard and can't be updated because of the code freeze—adding a redirect to address.
> Add redirect for incorrect dashboard link

- _docs/_partners/data_and_infrastructure_agility/analytics/heap.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
> Per Alex Wiseman's request, I placed the "data export integration" section of Heap into a new dedicated article in the Analytics section. The main Heap article is in the Cohort Import section.
Closes #BD-2567
> BD-2567 Create Heap analytics article

- _docs/_partners/isv_partners/currents_integration.md
> Add 404 HTTP status code and this sentence: "Note that any HTTP error code that is not explicitly listed below will be treated as an HTTP 5XX error."
Closes #**BD-2598**
---
> BD-2598: Add 404 HTTP status code

- _docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
- _docs/_developer_guide/platform_wide/feature_flags/about.md
- _docs/_developer_guide/platform_wide/feature_flags/create.md
- _docs/_developer_guide/platform_wide/getting_started/analytics_overview.md
- _docs/_help/release_notes/2021/december.md
- _docs/_help/release_notes/2021/october.md
- _docs/_help/release_notes/2022/5_31_22.md
- _docs/_home/static_video.md
- _docs/_partners/data_and_infrastructure_agility/analytics/wunderkind.md
- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
- _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
- _docs/_partners/home.md
- _docs/_partners/message_orchestration.md
- _docs/_partners/message_orchestration/channel_extensions/ecommerce.md
- _docs/_partners/message_orchestration/channel_extensions/ecommerce/yotpo.md
- _docs/_partners/message_personalization/dynamic_content/amazon_personalize/workshop.md
- _docs/_user_guide/administrative/app_settings/tags.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
- _docs/_user_guide/data_and_analytics/custom_data/events.md
- _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
- _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
- _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/install_attribution.md
- _docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
- _docs/_user_guide/engagement_tools/segments/segment_insights.md
- _docs/_user_guide/getting_started/workspaces.md
- _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
> Fixing mentions of "e-commerce" to "ecommerce" to align with Braze Marketing glossary.
---
> Style edit: "ecommerce" not "e-commerce"

- _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
Removed `sessionHandlingEnabled` and `inAppMessagingRegistrationEnabled` since they are included by default and recommended
> Removed arguments from BrazeActivityLifecycleCallbackListener 

- _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> Feature is not in GA
Closes #**BD-2655**
---
> BD-2655: Remove "Launch and Manage Content Blocks" permission

- _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
- _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md
Some aspects of the phone number capture doc were populated in the email capture doc, such as the page title and some headings, which made it look like the two docs were merged. This fixes that issue.
> Fix issue with email capture hidden doc

- _docs/_api/objects_filters/messaging/whats_app_object.md
Updates WhatsApp object specification for `/message/send` to support response messages.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> [SMS-1368] Update WhatsApp object specification to support repsonse messages

- _docs/_hidden/private_betas/sql_segments_tables.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
- _lang/fr/_hidden/private_betas/sql_segments_tables.md
- _lang/fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
The SHARE button is not implemented (maybe never was), so should not be in docs
Part of CH-5171
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Remove SHARE button types from docs

- _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
> BD-2688: Add note for Experiment Paths step not editable after Canvas launch

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
> BD-2704: Remove `canvas_step_id` and `canvas_step_name` from Canvas entry events

- _docs/_api/endpoints/user_data/post_user_track.md
> Clarifying that each event in Braze is considered unique and separate (even if there is a "duplicate" event, it has its own event ID)
Closes #**BD-2656**
---
> BD-2656: Add detail for "duplicate" events

- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization.md
Making sure the comment from https://github.com/braze-inc/braze-docs/pull/6677 doesn't fall through the cracks
> Removing a link to iOS legacy content from a Swift landing page

- _docs/_help/release_notes/2023/2_7_23.md
- _docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
- _docs/_partners/data_and_infrastructure_agility/analytics/mixpanel_for_currents.md
- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md
- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Removes the following deprecated events:
- users.messages.newsfeedcard.Click
- users.messages.newsfeedcard.Abort
- users.messages.newsfeedcard.Impression
- users.behaviors.app.NewsFeedImpression
- users.messages.sms.CarrierSend
Closes #**BD-2750**
> BD-2750: Remove deprecated events

- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Adds some detail on how IAM display options .reenqueue and .later work and their consequences for IAM display. Previously, some customers were confused about discarded IAMs being triggered and displayed later. This makes it more explicit that the IAM is only discarded for that attempt at display and that the IAM can still be triggered later on. 
Closes https://jira.braze.com/browse/SDK-4425
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhv …
> [SDK-4425] iOS - Add more documentation around the usage of IAM display options

- _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
> BD-2773 Remove Early Access banner for Custom Code Blocks

- _docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
> Added a filter to the table. There is no link for `hmac_sha512`.
Closes #**BD-2845**
> BD-2845 Update Liquid string filters

- .github/ISSUE_TEMPLATE/report_an_issue.md
- .github/ISSUE_TEMPLATE/request_a_feature.md
Updating issue templates to automatically assign Josh and Isaiah + assign the related label. Since GitHub automatically lists all issue template types under the **Issues** tab, it's helpful to have different labels for each kind of issue ("Issue," "Feature," etc.).
> Update issue templates

- _docs/_hidden/misc_reference/scim_api_appendix.md
- _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> I'm adding a new permission for Catalogs based on https://confluence.braze.com/pages/viewpage.action?spaceKey=CLIP&title=Dashboard+Permissions+Guidance
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
> CO-2350 Add catalog permissions.

- _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
[As of 4.0.0](https://github.com/braze-inc/braze-unity-sdk/releases), our Unity release assets no longer have a `Appboy-nodeps.unitypackage` because instead you'd download `Appboy.unitypackage`. If you want to import SDWebImage, you can toggle in the Unity UI to opt-in and import SDWebImage
> (You can compare the current 3 assets attached to the release vs the 4 assets in [3.x and before](https://github.com/braze-inc/braze-unity-sdk/releases/tag/3.11.0))
https://jira.braze.com/browse/SDK-4760
---
<details>
<br>
</details>
<details>
<br>
- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V …
> [SDK-4760] Update Unity docs around release assets

- _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
> Notes from Ian: <br> - We don't actually remove the spaces on the inbound messages.<br> - We do remove the spaces when we are evaluating against a trigger condition.
Closes #**BD-2904**
> BD-2904 Leading and trailing spaces are removed from inbound messages

- _docs/_api/errors.md
> Fix capitalization

- _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/push_notifications/customization/badges.md
- _docs/_developer_guide/platform_integration_guides/swift/push_notifications/customization/badges.md
https://jira.braze.com/browse/SDK-4799
- [New API](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/setbadgecount(_:withcompletionhandler:)?language=objc) (iOS 16+)
- [Old deprecated API](https://developer.apple.com/documentation/uikit/uiapplication/1622918-applicationiconbadgenumber) (deprecated in iOS 17)
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDa …
> [iOS docs] Use non-deprecated API to set badge count

- _docs/_help/release_notes.md
- _docs/_help/release_notes/2024.md
- _docs/_help/release_notes/2024/4_2_24.md
April 2, 2024 release notes, which includes:
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> April 2, 2024 release notes

- _docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
- _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> Remove Braze Learning link template course link, add new course link for link aliasing article
Closes #**BD-2978**
---
> BD-2978: Update Braze Learning course links

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
- _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Adding context for required minimum SDK versions to use `message_extras` in IAM impression events
Closes #**BD-2981**
---
> BD-2981: SDK versions for IAM message extras

- _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md
> Removing email capture forms from Shopify back-in-stock
Closes #**NONE**
> Remove Shopify email capture forms from back-in-stock

- _docs/_api/endpoints/export/campaigns/get_campaign_details.md
> BD-2948: Update email message response example

- _docs/_api/endpoints/preference_center/post_create_preference_center.md
> BD-2916 Add form inputs example response

- _docs/_partners/canvas_steps/google_audience_sync.md
> Clarify EU consent policy and DMA requirements for Google Audience Sync by removing some mentions of UK users
Closes #**BD-3021**
---
> BD-3021: Clarify EU consent policy and DMA requirements for Google Audience Sync

- _docs/_developer_guide/platform_wide/sdk_authentication.md
We fully removed the deprecated `BrazeDelegate.braze(_:sdkAuthenticationFailedWithError)` method, so we thought we would remove these warning reference the eventual switch to the newer `BrazeSDKAuthDelegate.braze(_:sdkAuthenticationFailedWithError)`.
---
<details>
<br>
</details>
<details>
<br> …
> [SDK-4885] Remove warnings about deprecated sdk auth method

- _docs/_help/release_notes.md
- _docs/_help/release_notes/2024.md
- _docs/_help/release_notes/2024/4_30_24.md
> April 30, 2024 release notes

- Rakefile
- _lang/_config_ja.yml
Add support for Japan docs generation and make it easier to run the generation process on multiple languages.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Add multi lang generation support

- _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
Adding the documentation associated with https://github.com/braze-inc/unity-sdk/pull/447
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> Matching iOS documentation line

- _docs/_help/help_articles/email/email_bounces.md
Added context about the 72 hour retry period, which exists in the [Message Activity Log](https://www.braze.com/docs/user_guide/administrative/app_settings/message_activity_log_tab/#common-messages)  article.
> Minor clarification to Email Bounces article

- _docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
> BD-3078 Fix run-on sentence in Rich Notifications

- _docs/_user_guide/data_and_analytics/export_braze_data/export_troubleshooting.md
> BD-3081 Update export troubleshooting

- _docs/_hidden/redirects/okta.md
- _docs/_partners/message_personalization.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
- _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
- _docs/_user_guide/data_and_analytics/query_builder.md
- _docs/_user_guide/data_and_analytics/query_builder/query_templates.md
- _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
- _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
- _docs/_user_guide/engagement_tools/canvas.md
- _docs/_user_guide/engagement_tools/canvas/canvas_components.md
- _docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
- _docs/_user_guide/engagement_tools/canvas/get_started.md
- _docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
- _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
- _docs/_user_guide/engagement_tools/canvas/testing_canvases.md
> Revert changes from undoing config change PR

- _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
> BD-3115: Add maximum 50 preference centers per workspace

- _docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/faqs.md
- _docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md
- _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
[DLK-1848](https://jira.braze.com/browse/DLK-1848)
- add FAQs
> [DLK-1848] add faqs for CDI and data sharing

- _docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Message Archiving docs have a typo when referring to `campaign_id`, `canvas_id`, `canvas_step_id`, `canvas_variation_id` and `message_variation_id`. All of these actually refers to `API Ids`, I double checked it in source code.
In this PR, fixing typo. Also, changed `ID` -> `Id` for consistency.
> I'm changing [Message Archiving](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/message_archiving/?tab=email) because it has a typo which leads to confusion while reading docs
- [ ✔️] No
---
<details>
<br>
- [✔️ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ✔️] Check that all links work.
- [ ✔️] Ensure you have completed [our …
> Fix typo in Message Archiving Docs

- _docs/_api/endpoints/catalogs.md
- _docs/_api/endpoints/catalogs/catalog_fields.md
- _docs/_api/endpoints/catalogs/catalog_fields/asynchronous.md
- _docs/_api/endpoints/catalogs/catalog_fields/asynchronous/delete_catalog_field.md
- _docs/_api/endpoints/catalogs/catalog_fields/asynchronous/post_create_catalog_fields.md
- _docs/_api/endpoints/catalogs/catalog_selections.md
- _docs/_api/endpoints/catalogs/catalog_selections/asynchronous.md
- _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
- _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
- _docs/_api/home.md
- _includes/rate_limits.md
> Relates to https://github.com/braze-inc/braze-docs/pull/6700
---
> Catalog field and selection endpoints EA

- README.md
- _docs/_contributing/home.md
Update docs for ruby version `3.3.0`.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or …
> Update docs for ruby version 3.3.0

- _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> BD-3138: Expected behavior for updated email address

- _docs/_developer_guide/platform_integration_guides/cordova/push_notifications.md
Updating the Cordova push docs to be clearer. We got some confusion around the necessary integration steps. Clarifying:
1. Basic push is automatically enabled for both iOS and Android but can be disabled via XML configurations
2. If people want to further customize their native push, they can disable the XML configurations and implement them following the native SDK instructions.
3. Android rich push and push stories are available out of the box but iOS can be configured via the steps detailed on this page.
---
<details>
<br>
</details>
<details>
<br>
- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDd …
> Clarifying updates to Cordova push documentation

- _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> Fixed a use case and added an alternative version
Closes #**BD-3162**
> BD-3162 Fix Liquid use case

- _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
/campaigns/trigger/send support attachments in the same way as  /messages/send for emails. The support was rolled out today, we are ready to update public docs.
> I'm changing https://www.braze.com/docs/api/endpoints/messaging/send_messages/post_send_triggered_campaigns because attachments support is now available to all Braze Customers
- [ ✔️] No
---
<details>
<br>
- [ ✔️] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ✔️] Check that all links work.
- [ ✔️] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ✔️] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and …
> Updated /campaigns/trigger/send docs to include newly supported attachments feature

- _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
> Closes https://github.com/braze-inc/braze-docs/pull/7328/ and includes additional edits
Closes #**BD-3059**
---
> BD-3059: Canvas target audience clarifications

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
This updates the event payload documentation for Currents with one automatically generated from the event config. Aside from fixing some inconsistencies, this allows accurate event structures for all destinations, not merely storage ones.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
> [DI-6248] Update event documentation

- _docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md
Follow up to [this](https://github.com/braze-inc/braze-swift-sdk/issues/130) GitHub issue.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
> [SDK Untracked] Clarify subscribeToSessionUpdates behavior

- _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
> Adds integration instructions for using Expo iOS app extensions (rich push and push stories) with Expo Application Services.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …
> Add bundle ID configurations for Expo app extensions

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
> BD-3186 Add unsubscribe note to global state change events

- _docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
> BD-3214 Export all user data in a segment

- _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
- _docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md
[CO-2618](https://jira.braze.com/browse/CO-2618)
The `catalog-in-process` error is being removed from selections api endpoints. This updates the documentation to reflect that.
> [CO-2618] Remove references to the catalog-in-process-error

- _docs/_api/endpoints/messaging/live_activity/start.md
- _docs/_api/objects_filters/messaging/android_object.md
- _docs/_api/objects_filters/messaging/apple_object.md
- _docs/_api/objects_filters/messaging/web_objects.md
- _docs/_contributing/content_management.md
- _docs/_contributing/content_management/images.md
- _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/android_google_tag_manager.md
- _docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/font_customization.md
- _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/in-app_message_delivery.md
- _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
- _docs/_help/release_notes/2020/december.md
- _docs/_partners/canvas_steps/criteo_audience_sync.md
- _docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
- _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
- _docs/_user_guide/data_and_analytics/creating_a_formula.md
- _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
- _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
- _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
- _docs/_user_guide/message_building_by_channel/sms/sms_setup/terms.md
- _docs/_user_guide/sage_ai/intelligence/faqs.md
- _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md
- _docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md
- _docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md
Part 1 of the glossary audit, up to the end of "I". 
#BD-3237
- N/A …
> BD-3237 Glossary Audit - Part 1

- _docs/_user_guide/message_building_by_channel/whatsapp/overview/multiple_subscription_groups.md
GA for multiple WhatsApp Business Accounts and phone numbers
#BD-3240
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managem …
> BD-3240 GA Multiple WhatsApp Business Accounts

- _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md
- _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md
- _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
- _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md
- _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md
- _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
- _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
My PR adds some examples of using array fields with the catalogs API.
- [BD-3247](https://jira.braze.com/browse/BD-3247)
- [CO-2702](https://jira.braze.com/browse/CO-2702)
- N/A …
> CO-2702 Update catalog documentation with array type support examples.

- _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
- Mark the theme.liquid matrix for checkout user reconcilability to no support
- Remove `during` checkout in paragraph to reconcile user
> [PP-3841] Mark no checkout reconcileEmail support for liquid

- _docs/_help/release_notes/deprecations/shopify_checkout.md
- _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
- _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md
- _lang/fr/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
This change is to remove the text mentioning `reconcileEmail` or `email_user_reconcile`, and replaces with `setEmail`/Bulk Merge User Tool (if applicable). The changes made are reflected in this doc: https://docs.google.com/document/d/1CZh_mLg-AoFm4RjXAdJryZcjYU6thK5_XHYANA7vEYc/edit
There are 4 files being changed:
1. Getting Started - remove `reconcileEmail` and replace with `setEmail`
2. Shopify Identity Management - add bulk merge user tool
3. Checkout.liquid updates - remove `email_user_reconcile` and replace with `setEmail` and bulk merge user tool
4. FR:Shopify Data Processing - remove `reconcileEmail`
> [PP-3871] remove reconcile email from docs

- _docs/_user_guide/engagement_tools/templates_and_media/managing_templates.md
Addresses #7736 
- N/A
- N/A
- If my PR is …
> Clarify archived campaign template behavior

- _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
My PR...
- Closes [BD-3294](https://jira.braze.com/browse/BD-3294)
- N/A …
> BD-3294: Add workaround for Liquid abort tag in conversion events

- _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
- _docs/_user_guide/message_building_by_channel/in-app_messages/faq.md
My PR...
#BD-3302
- N/A
- If my PR is …
> BD-3302 Update Liquid tags that trigger templated IAMs

- _docs/_developer_guide/platform_integration_guides/swift/content_cards/tvos.md
- _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/tvos.md
- _docs/_developer_guide/platform_integration_guides/tv_and_ott.md
Making it more clear that users can use the Swift SDK to implement in-app messaging for Apple TV (along with other Headless UI features), however Braze doesn't provide any out of the box UI for tvOS within the Swift SDK. Customers will need to implement their own UI, but they do have access to the messaging data models.
- [BD-3202](https://jira.braze.com/browse/BD-3202)
- N/A …
> [BD-3202] Clarifying headless UI for Apple TV

- _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md
My PR...
- N/A
- Closes [BD-3257](https://jira.braze.com/browse/BD-3257) …
> BD-3257: Clarify conversion tracking rules for multiple devices

- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
My PR...
#BD-3352
- N/A
- If my PR is …
> BD-3352 Update broken links in Segment

- _docs/_developer_guide/platform_integration_guides/cordova/content_cards.md
- _docs/_developer_guide/platform_integration_guides/cordova/other_integrations.md
- _docs/_developer_guide/platform_integration_guides/flutter/content_cards.md
- _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
- _docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
- _docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
- _docs/_developer_guide/platform_integration_guides/unity/content_cards.md
- _docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
- _docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
- _docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
- _includes/wrappers/gif_support/content_cards.md
- _includes/wrappers/gif_support/in_app_messaging.md
Adding Gif Support documentation for **all** wrappers. If you notice I'm missing a wrapper during your review, please let me know so I can add it. Thanks!
- [BD-2667](https://jira.braze.com/browse/BD-2667)
- N/A
- If I updated or replaced an image, I did not remove the …
> [BD-2667] Gif Support for all wrappers

- _docs/_api/endpoints/translations/get_bulk_translations_campaigns.md
- _docs/_api/endpoints/translations/get_bulk_translations_canvases.md
- _docs/_api/endpoints/translations/get_translation_campaign.md
- _docs/_api/endpoints/translations/get_translation_canvas.md
- _docs/_api/endpoints/translations/put_update_translation_campaign.md
- _docs/_api/endpoints/translations/put_update_translation_canvas.md
My PR...
- Closes [BD-3349](https://jira.braze.com/browse/BD-3349)
- N/A …
> BD-3349: Updates to translation API docs

- _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
Relevant page: https://braze-docs-j2admcsrq-braze.vercel.app/docs/partners/message_orchestration/attribution/appsflyer/appsflyer/?tab=swift
Follow up to [this support issue](https://servicedesk.braze.com/browse/PQ-3781). The `deviceId` method used in these code snippets [was deprecated in 5.13.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.13.0). …
> [SDK Untracked] Update Appsflyer integration code snippet

- _docs/_developer_guide/platform_wide/feature_flags/create.md
My PR adds code examples for the Wrapper SDKs (React Native, Cordova, Unity, Flutter, Roku) for accessing the expanded Feature Flag properties. Also updated the comments to be consistent and easier to read.
- [SDK-5070](https://jira.braze.com/browse/SDK-5070)
- Next week (Week of July 22-26)
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) …
> [SDK-5070] Add Feature Flag expanded properties for Wrapper SDKs

- _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
My PR...
[#BD-3368](https://jira.braze.com/browse/BD-3368)
- N/A …
> BD-3368 Add catalog views details

- _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
My PR...
[#BD-3385](https://jira.braze.com/browse/BD-3385)
- N/A …
> BD-3385 Updates to Personalized Paths

- _docs/_help/release_notes.md
- _docs/_help/release_notes/2024.md
- _docs/_help/release_notes/2024/8_20_24.md
August 2024 release notes
- N/A
- N/A
- If …
> August 2024 release notes

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
My PR...
- Closes [BD-3401](https://jira.braze.com/browse/BD-3401)
- N/A …
> BD-3401: Updates to Currents

- _docs/_user_guide/message_building_by_channel/push/best_practices.md
- _docs/_user_guide/message_building_by_channel/push/ios/rich_notifications.md
My PR...
- Closes [BD-3407](https://jira.braze.com/browse/BD-3407)
- N/A …
> BD-3407: Add push character count reccomendation to Best practices

- _docs/_partners/message_personalization/dynamic_content/movable_ink.md
- _docs/_partners/message_personalization/dynamic_content/movable_ink/dynamic_sms_link.md
- _docs/_user_guide/message_building_by_channel/sms/campaign/create.md
- _docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
- _docs/_user_guide/message_building_by_channel/sms/mms/create.md
- Fixes typo for "Braze content card" to "contact card" in Movable Ink partner doc
- Updates mentions of "Contact Card" to "contact card"
- Closes [BD-3443](https://jira.braze.com/browse/BD-3443)
- N/A …
> BD-3443: Fix typo and update "Contact Card" to "contact card"

- _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_event_callback.md
- _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
Adds some notes around a specific use case where a client wants to subscribe to push notifications and have that be triggered upon a Push click from Terminated state.
- N/A
- No release, can be merged whenever …
> [SDK-5171] Push subscription when clicking a notification from Terminated state

- _docs/_contributing/content_types.md
I was using the templates a lot today and realized I kept scrolling past the "template" drop down. I made this change to make it easier to identify on the change. I'm open to alt method though if you think there's a better one.
- N/A
- N/A
- If I updated or replaced an image, …
> Making template dropdown more visible

- _docs/_hidden/private_betas/idle_campaigns.md
Add FAQ for feature flags in Canvas
- N/A
- N/A …
> Add FAQ for feature flags in Canvas

- _docs/_user_guide/data_and_analytics/reporting/report_builder.md
Change time window description when creating a report with campaigns / canvases to be within the last 12 months and not the last 6 months. This is the behavior of the product, so matching the description in the doc to the product. See https://jira.braze.com/browse/REP-3127 for more details
> [REP-3127] Update time window description for creating a report

- _docs/_developer_guide/customization_guides/content_cards/creating_custom_content_cards.md
- _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/in-app_messaging/customization/behavior_on_click.md
- _docs/_hidden/archive_docs/previous_in-app_message_generations.md
- _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
Update mentions of "on click behavior" to "on-click behavior"
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managemen …
> Update on click to on-click behavior

- _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
My PR links nested custom attributes to the Using Liquid article
[BD-3466](https://jira.braze.com/browse/BD-3466)
- N/A …
> BD-3466 Add nested custom attributes to Using Liquid

- bdocs
- scripts/list_redirect_urls.sh
For each new redirect in the current branch, this script uses the user-supplied base URL to list all old URLs so the user can open old links directly from the terminal to test redirects.
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file …
> Script: generate list of redirect URLs

- _docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
Clarifying that the segment "Messaging Use" section only include currently enabled campaigns / canvases. This came up in a PQ: https://servicedesk.braze.com/browse/PQ-5204
Also separating out the "Messaging use" and "Historical membership" sections since they're unrelated.
Ticket: [UT-2091](https://jira.braze.com/browse/UT-2091)
PR that introduced this change: https://github.com/Appboy/platform/pull/55394
- N/A
- If I renamed or moved …
> [UT-2091] Update Segment "Messaging Use" Docs

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
My PR updates `send_id` for a few SMS message engagement events
[BD-3477](https://jira.braze.com/browse/BD-3477)
- N/A …
> BD-3477 Remove "send_id" for several message events

- _docs/_user_guide/engagement_tools/segments/segment_extension.md
Add note that hourly refreshes aren't available for form-based Segment Extensions
[BD-3508](https://jira.braze.com/browse/BD-3508)
- N/A …
> BD-3508 Add note about hourly Segment Extension refreshes

- _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
Add suggestion to use Liquid tag for unsubscribe link
- Closes BD-3523
- N/A …
> BD-3523: Add suggestion to use Liquid tag for unsubscribe link

- _docs/_partners/canvas_steps/google_audience_sync.md
Add new section "Setting up your Canvas" to Google Audience Sync
- Closes [BD-3535](https://jira.braze.com/browse/BD-3535)
- N/A …
> BD-3535: Add new section to Google Audience Sync

- _docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
Clarify a consideration for using Liquid with `message_extra`
[BD-3528](https://jira.braze.com/browse/BD-3528)
- N/A …
> BD-3528 Docs feedback - Clarify message_extras Liquid

- _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
Add tip about making sure the `UPDATED_AT` time isn't the same as the sync time, or CDI data might be duplicated
[BD-3537](https://jira.braze.com/browse/BD-3537)
- N/A …
> BD-3537 Add tip to CDI about UPDATED_AT time

- _docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
- _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
Update SMS tip and add WhatsApp tip that SMS/WhatsApp properties can be referenced until the next action step.
[BD-3520](https://jira.braze.com/browse/BD-3520)
- N/A …
> BD-3520 Update tips for SMS and WhatsApp Canvas properties

- _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
- _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
- _docs/_api/objects_filters/recipient_object.md
Core Objects is adding a feature to allow requests to the `/campaigns/trigger/send` and `/canvas/trigger/send` endpoints to specify the recipient(s) by email address (instead of by external ID or user alias).
- [BD-3526](https://jira.braze.com/browse/BD-3526)
- [CO-2975](https://jira.braze.com/browse/CO-2975)
- Most likely 8 October 2024 …
> CO-2975: Allow recipients to be specified via email - MERGE 10/8

- _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide.md
- _docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup/ios_sdk_integration.md
- _docs/_developer_guide/platform_integration_guides/roku/analytics/setting_custom_attributes.md
- _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/delayed_initialization.md
- _docs/_hidden/archive_docs/windows_universal/analytics/setting_custom_attributes.md
- _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
- _docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
- _docs/_partners/message_personalization/dynamic_content/future_anthem.md
- _docs/_partners/message_personalization/dynamic_content/komo.md
- _docs/_user_guide/data_and_analytics/reporting/data_by_segments.md
- _docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
- Removing the parentheses and periods and forward slashes for tab headings so the content doesn't break
- N/A
- N/A …
> Fix tab headings

- _docs/_api/endpoints/scim/delete_existing_dashboard_user.md
- _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
- _docs/_api/endpoints/scim/get_see_user_account_information.md
- _docs/_api/endpoints/scim/post_create_user_account.md
- _docs/_api/endpoints/scim/put_update_existing_user_account.md
- _docs/_hidden/misc_reference/scim_api_appendix.md
Updates to SCIM endpoint docs (request body, request parameters, other details)
- BD-3655
- BD-3708
- BD-3706
- N/A …
> BD-3655: Updates to SCIM endpoint docs

- _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
Update the message engagement events definition for "abort_type" to remove example values. There are currently about 30 example values, and the current definition implies there are only a few.
[BD-3712](https://jira.braze.com/browse/BD-3712)
- N/A …
> BD-3712 Update message engagement event abort type

- _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
This has been wrong for years, and it's confusing customers.
- [DI-6829](https://jira.braze.com/browse/DI-6829)
- N/A  …
> [DI-6829] Correct field transformation documentation

- _docs/_developer_guide/platform_integration_guides/web/content_security_policy.md
From ticket:
We list the braze CDN url as required for `img-src` but if a user is using custom fonts, for example, in In-App Messages, they'll need `font-src` to include the braze CDN url as well.
> **Note:** I converted the sections to use tables instead as it makes copying and pasting much easier for readers (now you just need to triple-click in the cell instead of manually highlighting with mouse).
- [BD-3303](https://jira.braze.com/browse/BD-3303)
- N/A
- All links …
> [BD-3303] Clarify CDN directives for Web SDK

- _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
We had a PQ come in that was asking about dynamic allow listing for Currents. This ends up being confusing for customers since it seems to imply features that our partners would have to provide. 
And since our partners do not provide this feature, we definitely should not claim that it exists.
https://servicedesk.braze.com/browse/PQ-6789 …
> [Currents] Remove claim about dynamic allow listing from Currents documentation - PQ-6789

- _docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md
Miscellaneous grammatical edits to Location tracking article
- N/A
- N/A …
> Minor grammatical edits

- _docs/_user_guide/data_and_analytics/report_metrics.md
- _includes/campaign_analytics.md
- _includes/metrics.md
We're missing the "Close Message" metric, so this adds it.
[BD-3747](https://jira.braze.com/browse/BD-3747)
- N/A …
> BD-3747 Add Close Message metric

- _plugins/tabs.rb
Currently, tabs break and display no content if you use special characters (such as `.`) in a tab name. This is an issue because some tabs that reference filenames (like in the following example), will break. Here's a tab from [Other SDK customizations for Android and FireOS](https://braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration), that will currently break when selected:
```
{% tab Braze.xml %}
```
- N/A
- N/A
- My content contains correct …
> normalize tab names better

- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
- _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
- _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
- _docs/_user_guide/data_and_analytics/custom_data/events.md
- _docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
- _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
Apply Diataxis standards to Custom Data.
[BD-3790](https://jira.braze.com/browse/BD-3790)
- N/A …
> BD-3790 Apply template standards to Custom Data

- _includes/archive/android/gifs.md
Some langs are breaking due to this file:
```bash
_includes/archive/android/gifs.md
```
Being renamed and moved to this location:
```bash
_includes/developer_guide/android/_global/gifs.md
```
This PR re-adds that file (with the latest changes).
- N/A
- N/A …
> Re-adding include to fix some langs

- _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
- _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
- _docs/_api/objects_filters/recipient_object.md
Using an email address to trigger campaigns or Canvases GA
- BD-3757 …
> BD-3757: Using an email address to trigger campaigns or Canvases GA [MERGE JAN 13]

- _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
- _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
Removing EA notes for price drop notifications and back-in-stock notifications
- BD-3752 …
> BD-3752: Price drop notifications and back-in-stock notifications GA [MERGE JAN 13]

- _docs/_user_guide/data/report_metrics.md
Several customers were confused by /sends/data_series stats because we include a unique_recipients stat for each send identifier, but unique recipients are counted at the campaign level, not the send ID level. This behavior is noted in the /sends/data_series response, but it can also be helpful to document it here.
- N/A
- N/A …
> [PQ-7055] Clarify Unique Recipients

- _docs/_user_guide/data/user_data_collection/user_import.md
Update behavior when external_id and alias aren't included in CSV import for email address identifiers
- BD-3837
- N/A …
> BD-3837: Update behavior when external_id and alias aren't included

- _docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md
Add more details for sending emails for SparkPost and add link to Apple's documentation
- BD-3726
- N/A …
> BD-3726: Add more details for sending emails for SparkPost

- _docs/_developer_guide/content_cards/creating_custom_content_cards.md
Feedback from a mobile dev using the SDK: I think many other people would be implementing content cards in this manner. It would be great if the SDK used a `UICollectionView` instead of a `UITableView` so that you can easily switch the layout. Or just improve the wording in the documentation to say in order to do this it would need to be a fully custom implementation.
- [BD-3499](https://jira.braze.com/browse/BD-3499)
- N/A
- If I …
> [BD-3499] Content cleanup + clarifying requirements

- _docs/_hidden/other/feedback.md
- assets/css/_feedback.scss
Add a dedicated feedback page
`/docs/feedback/`
> add dedicated feedback page

- _layouts/broken_page.html
- _plugins/sdktabs.rb
- assets/css/_tabs.scss
- assets/js/documents.js
- assets/js/hash_redirect.js
- assets/js/toc.js
```
{% sdktabs %}
{% sdktab tab1 %}
Tab1 Content
{% endsdktab %}
{% sdktab Tab2 %}
Tab2 Content
{% endsdktab %}
{% endsdktabs %}
```
> Basic wireframe for a new tab type

- _layouts/partner_page.html
Partner page seems to generate an error when a partner is missing with the new schema.
> fix missing partner

- _docs/_api/endpoints/user_data/post_user_identify.md
[CO-3336](https://jira.braze.com/browse/CO-3336)
Add a note about what happens if two users in an identify scenario both have an alias with the same label.
> CO-3336 add note about aliases with the same label

- _docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
[CO-3340](https://jira.braze.com/browse/CO-3340)
- This table isn't super useful now that we charge based on storage.
- Removed the table in favor of a short description of the difference
> CO-3340: remove catalog tier table and add short description instead

- _docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md
[CO-3355](https://jira.braze.com/browse/CO-3355)
- add a line to clarify that braze_id is set by braze (cannot be assigned)
- include email and phone as identifiers
> CO-3355: update user profile lifecycle page to clarify a static braze_id + add email and phone identifiers

- _docs/_user_guide/data/custom_data/custom_events/nested_objects.md
[CO-3345](https://jira.braze.com/browse/CO-3345)
Adds a note about regenerating schemas and that it can only be done every 24 hours. Also a separate note about the permissions needed to do segmentation for nested objects.
> CO-3345 add note about cooldown and permissions

- _docs/_hidden/other/user_archival.md
[CO-3354](https://jira.braze.com/browse/CO-3354)
Two changes here:
1. We also include users reachable by LINE as active users
2. I think the sentence about treatment samples wasn't correct. The treatment sample is in the Global Control Group Report, and being in that excludes the user from being archived.
> CO-3354 add LINE to inactive users explanation and clarify treatment sample group

- _docs/_user_guide/analytics/reporting/viewing_and_understanding_segment_data.md
- _docs/_user_guide/engagement_tools/segments.md
- _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
- _docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
- _docs/_user_guide/engagement_tools/segments/troubleshooting.md
Add information to historical segment membership docs, including reasons for significant changes. The information comes from a SF KB article listed in the Jira ticket below.
[BD-4004](https://jira.braze.com/browse/BD-4004)
- N/A …
> BD-4004 New segment calculation page & additional segmentation edits

- _includes/data_centers.md
The format for the url for US-10 differs from other US regions: https://confluence.braze.com/spaces/DT/pages/463019025/2025+02+14+US-10+Cluster+Launch
> [NOTIX] update docs to have correct rest & sdk endpoints for US-10

- scripts/clean_orphaned_translations.py
Cleans up any language file that's not an english docs file due to being deleted or moved.
```
This script finds and deletes all files that exist in one or more '_lang' subdirectories
that don't exist in the primary '_docs' directory. It can be run against a single language or all languages.
USAGE:
./scripts/clean_orphaned_translations.py [LANGUAGE]
OPTIONS:
[LANGUAGE]         Process the given language. If none, process all. Available languages:
ja, de, es, fr, ko, pt-br
-h, --help         Show this help message
```
```
===== SUMMARY OF CLEANED FILES =====
ES - Total: 2 files cleaned
Files cleaned by section:
- _developer_guide: 2
FR - Total: 0 files cleaned
No files cleaned
```
> add language cleanup script

- _docs/_user_guide/data/custom_data/custom_attributes.md
- _docs/_user_guide/data/custom_data/custom_events.md
Reverts braze-inc/braze-docs#9386 because [BD-4777](https://jira.braze.com/browse/BD-4777?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D) asks for it to go out on June 3 or June 4 instead
> Revert "CO-3374: Add documentation for custom attributes/events entitlements [MERGE 5/19]"

- _docs/_hidden/other/feedback.md
- assets/js/feedback.js
Adds the externalid to the feedback submission process.
to test, might need to use `window.braze.getUser().getUserId()` to get your user and `window.braze.changeUser('[User]')` to set your user.
> add externalid to feedback

- _docs/_api/objects_filters/messaging/apple_object.md
Update the Braze doc api documentation after we have added apns-priority field
[PUSH-313](https://jira.braze.com/browse/PUSH-313)
- N/A …
> [PUSH-396] Add description about the apns_priority field in Apple Push object in Braze doc

- _docs/_user_guide/data/custom_data/custom_attributes.md
- _docs/_user_guide/data/custom_data/managing_custom_data.md
Adds note that the blocklisting limit of 300 includes custom attributes in the "Trashed" status
> [CO-3528] update custom attributes blocklisting docs

- .github/workflows/link-issue-to-pr.yml
Removed the comment creation for linking issues to PRs as this looks to be blocking linkage of PR to issue.
Removed the comment creation for linking issues to PRs as this looks to be blocking linkage of PR to issue.
- N/A
- N/A
- [ X ] I confirm that my PR meets the following: …
> Remove issue comment creation from PR workflow
