_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md, _docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md, _docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2059: Adding reporting/export behavior to cloud data storage partners

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/delete_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/delete_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/get_catalog_items_details_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md, _docs/_api/endpoints/preference_center.md, _docs/_api/endpoints/preference_center/get_create_url_preference_center.md, _docs/_api/endpoints/preference_center/get_list_preference_center.md, _docs/_api/endpoints/preference_center/get_view_details_preference_center.md, _docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_api/endpoints/preference_center/put_update_preference_center.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md
=> Edits from Postman audit

_docs/_partners/message_orchestration/additional_channels/messaging/sendbird.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove dev formatting from partner docs

_docs/_user_guide/administrative/manage_your_braze_users/user_permissions.md
This will support readers who are searching in the page for words like "keyword" to help them identify which permission is required for editing SMS keyword categories.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add more detail about subscription groups permission

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2151: Add md5 hashing example to s3 bucket export

_docs/_user_guide/message_building_by_channel/email/templates/email_template.md
=> BD-2155: Update mention of Inbox Vision

_docs/_user_guide/data_and_analytics/query_builder.md
=> BD-2154: Update QB max rows and look back

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2118: Update BigQuery Table Example

_docs/_api/endpoints/email.md, _docs/_api/endpoints/email/delete_remove_subscription_state.md, _docs/_api/endpoints/email/get_list_hard_bounces.md, _docs/_api/endpoints/email/get_query_by_email.md, _docs/_api/endpoints/email/get_query_by_email_or_phone.md, _docs/_api/endpoints/email/get_query_unsubscribed_email_addresses.md, _docs/_api/endpoints/email/post_blocklist.md, _docs/_api/endpoints/email/post_email_subscription_status.md, _docs/_api/endpoints/email/post_remove_hard_bounces.md, _docs/_api/endpoints/email/post_remove_spam.md, _docs/_api/home.md
=> BD-2125: New /users/subscription endpoint

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2161: Clarify link tracking behavior

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2159: Document schema generation caveat

_docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/5_30_23.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Release Notes 5/30/23

_docs/_hidden/other/credit_ratios.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2135: Update Credit Ratios Doc (MERGE 6/1)

_docs/_user_guide/message_building_by_channel/email/templates/email_template.md
=> BD-2156: Edit email footer details

_docs/_partners/canvas_steps/facebook_audience_sync.md, _docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2166: Facebook audience sync updates

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/post_create_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/post_create_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2169: Update catalogs endpoint troubleshooting description

_docs/_api/endpoints/catalogs/catalog_management/synchronous/post_create_catalog.md
> Addresses https://github.com/braze-inc/braze-docs/pull/5531
---
=> Update field limit from 30 to 500 for Create catalog endpoint

_docs/_user_guide/message_building_by_channel/email/drag_and_drop.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
=> BD-2157: New row as Content Block for drag-and-drop editor

_docs/_partners/data_and_infrastructure_agility/analytics/saleswings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Minor tweaks to SalesWings docs

_docs/_api/endpoints/export.md, _docs/_api/endpoints/export/purchases/get_number_of_purchases.md, _docs/_api/endpoints/export/purchases/get_revenue_series.md, _docs/_api/home.md
=> BD-2163: /purchases/revenue_series and /purchases/quantity_series endpoint docs

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove Content Block reference in Email overview

_docs/_api/endpoints/export/purchases/get_revenue_series.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Postman link pt. 2

_docs/_api/endpoints/export/purchases/get_number_of_purchases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Postman link pt. 1

_docs/_user_guide/message_building_by_channel/email/preference_center.md, _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md, _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2165: DND Preference Center GA - MERGE 6/5

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Update react_sdk_setup.md to state 0.68+ min version
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update react_sdk_setup.md to state 0.68+ min version

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
Removed EA Banner
@KellieHawks 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Remove EA Banner from link shortening docs

_includes/campaign_analytics.md
=> BD-2174: Update IAM reporting note on body clicks to include custom code

_docs/_user_guide/message_building_by_channel/whatsapp/faqs.md, _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
=> BD-2177: Fix links

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
Closes #**BD-2178**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2178: Add max time for re-eligibility

_docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
=> BD-2167: Add FAQs for Gmail promo tab

_docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
> Updating the delegate references and links from the Objective-C SDK to the Swift SDK for deep linking integrations.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Swift SDK links for Branch deeplinking example

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2173: Shopify updates

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update S3 snippet

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
=> BD-2183: Swap incorrect screenshots

_docs/_api/endpoints/sms/get_query_invalid_numbers.md
=> BD-2187: Fix link

_docs/_user_guide/data_and_analytics/query_builder.md, _docs/_user_guide/engagement_tools/segments/sql_segments.md
=> BD-2186: Clarify credit usage for SQL Segments

_docs/_partners/message_orchestration/attribution/airbridge.md
Hi, this is [Airbridge](https://airbridge.io) team.
I'm changing `airbridge.md` because our Help Center has been revamped recently.
We support redirection for the old addresses, but would be better to use a new one.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ ATTN: For …
=> docs: Update Airbridge document link

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/zoom.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Zoom registration

_docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2114: Update GTM docs w/ optional push setup

_docs/_docs_pages/index.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update "Canvas: The Basics" to "Canvas Basics"

_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2170: Update user update Liquid example

_docs/_hidden/private_betas/recommendations.md
=> BD-2175: Update Item Recommendations

assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add redirects for CDI

_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing/optimizations.md, assets/js/broken_redirect_list.js
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Pulling out PV and WV for search optimization

_docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md, _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md, _docs/_user_guide/message_building_by_channel/email/preference_center/overview.md, _docs/_user_guide/message_building_by_channel/in-app_messages.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
> Aligning docs with updated UI (Drag & Drop Editor > Drag-And-Drop Editor; drag & drop > drag-and-drop / drag and drop)
---
=> Update mentions of "drag & drop editor" to "drag-and-drop editor"

_docs/_hidden/private_betas/idle_campaigns.md
=> BD-2193: Add stopping Content Cards info

_docs/_hidden/private_betas/canvas_drafts.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
=> BD-2132: Add IAM prioritization for active Canvas drafts

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/in-app_messages_in_canvas.md
=> BD-2190: IAM priority for Canvas

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
[CO-1626](https://jira.braze.com/browse/CO-1626)
This updates the docs to indicate that the free tier's 100 MB of storage is included with each plan.
=> [CO-1626] Indicate that the free tier of storage is included with each plan

_docs/_hidden/private_betas/canvas_comments.md
=> BD-2191: Add keyboard shortcuts for Canvas comments

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
> I'm adding words to the Redshift information to make sure customers know there endpoint needs to be publicly accessable. 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Reminder to make Redshift Clusters publically accessable

_docs/_hidden/private_betas/phone_number_capture.md, _docs/_hidden/private_betas/recommendations.md, _docs/_hidden/private_betas/shopify_catalogs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Shopify catalogs (Hidden)

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-2198: Add minimum SDK version

_docs/_api/endpoints/user_data/post_users_merge.md
=> BD-2197: Clarify merge behavior details

_docs/_hidden/other/documentation_request.md
Add verify checkbox to request form
[GE-2122](https://jira.braze.com/browse/GE-2122)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Add verify to request

_docs/_user_guide/engagement_tools/segments/user_profiles.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove EA alert

_docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
=> BD-2120: Add merge user profiles to Collection best practices

_docs/_user_guide/administrative/app_settings/email_settings.md, _docs/_user_guide/message_building_by_channel/email/faq.md
=> BD-2210: Clarify changes to email settings

_docs/_api/endpoints/export/user_data/post_users_segment.md
Closes #**BD-2204**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2204: New parameter to export specific custom attributes for /users/export/segment

_docs/_docs_pages/index.md, _docs/_help/home.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update popular topics in docs based on Google Analytics

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
Removing the bcc address from 'Advanced' functionality, as we have it in the main Sending Info section.
- [x ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update overview.md - remove bcc from 'Advanced' functionality

_docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md
=> Fix incorrect image reference

_docs/_developer_guide/customization_guides/content_cards/logging_analytics.md, _docs/_user_guide/message_building_by_channel/content_cards/about.md
This PR is designed to capture feedback from stakeholders specifically about:
* logging_analytics.md
There are a few HTML comments that ask specific questions, but seeking feedback at any level - technical correctness, thoroughness, word choice, etc.
Will be merged back into the feature branch after feedback is gathered.
=> Content Cards Logging Analytics

_docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md, _docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
I'm adding a note / alert regarding GIF Support in the Swift SDK on the ContentCards integration page.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> ContentCards GIF Support note

_docs/_partners/canvas_steps/facebook_audience_sync.md
> I'm adding a sub-section to the [Audience Sync to Facebook](https://www.braze.com/docs/partners/canvas_steps/facebook_audience_sync#audience-sync-to-facebook) article.
Closes #BD-2213
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
=> BD-2213 Audience Sync to Facebook

_docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md, _docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md, _docs/_user_guide/data_and_analytics/analytics/understanding_your_app_usage_data.md, _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md, _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md, _docs/_user_guide/data_and_analytics/data_points.md
> I made spelling and style change suggestions for a few articles.
=> Docs Style Suggestions

_docs/_user_guide/engagement_tools/segments/user_profiles.md
=> BD-2215: Add EA alert

_docs/_partners/message_personalization/dynamic_content/wyng.md, _lang/fr/_partners/message_personalization/dynamic_content/wyng.md
> Updating the wording of our (Wyng) partner's page intro.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [Partners] Updated WYNG intro wording

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> BD-2217: Fix custom footer image

_docs/_partners/canvas_steps/google_audience_sync.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2214: Updates to google audience sync

_docs/_api/endpoints/catalogs/catalog_items/asynchronous/patch_catalog_items_bulk.md, _docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/patch_catalog_item.md, _docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
=> BD-2219: Clarify PUT and PATCH methods for catalog endpoints

_docs/_home/templates.md
> Update templates landing page to only include newer templates
=> Update templates landing page

_docs/_partners/isv_partners/api_partner.md, _docs/_partners/isv_partners/best_practices.md, _docs/_partners/isv_partners/cohort_import.md, _docs/_partners/isv_partners/currents_integration.md, _docs/_partners/isv_partners/data_transformation.md, _docs/_partners/isv_partners/snowflake_datasharing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Page formatting updates for ISV

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
=> BD-2220: Add AI copywriter to DND IAM docs

_docs/_developer_guide/platform_integration_guides/web/push_notifications/safari_mobile_push.md, _docs/_user_guide/administrative/privacy/managing_consent.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/message_building_by_channel/email/amphtml.md
> I removed several instances of "please" in the docs.
=> Remove "please"

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Liquid platform capitalization

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
> Minor modifications/updates to the React Native push setup documentation
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update React Native push docs

_layouts/dev_guide.html
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix dev guide layout

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> add DeleteObject back to data export tab for S3

_docs/_user_guide/intelligence/ai_copywriting.md
=> Update AI copywriting with DND IAM change

_docs/_hidden/private_betas/phone_number_capture.md
=> Update phone capture to make SDK requirements more explicit

_docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md, _docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md, _docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_archival.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
> I made edit suggestions for User Data Collection articles.
=> User Data Collection edits

_docs/_user_guide/data_and_analytics/custom_data.md, _docs/_user_guide/data_and_analytics/custom_data/blocklist_delete_custom_data.md, _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md, _docs/_user_guide/data_and_analytics/custom_data/pre-populating_custom_data.md
> I made suggestions for Custom Data articles.
=> Custom Data edit suggestions

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
=> BD-2133: Clarify custom event property segmentation

_docs/_api/endpoints/email.md, _docs/_api/endpoints/email/delete_remove_subscription_state.md, _docs/_api/endpoints/email/get_query_by_email_or_phone.md, _docs/_api/home.md
=> Hide /users/subscription docs

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
=> Add CORS requirement for custom fonts

_docs/_hidden/private_betas/sql_segments_tables.md
=> BD-2184: Add missing SQL tables to reference page

_docs/_user_guide/privacy_portal.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2231: Update privacy portal headers

_docs/_api/endpoints/user_data/post_users_merge.md
=> BD-2225: Clarify merge behavior 

_docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/6_27_23.md
=> June 2023 release notes

_docs/_api/api_limits.md
=> Style edits for API rate limits doc

_docs/_help/release_notes.md, _docs/_help/release_notes/2023/6_27_23.md
=> Add saving drafts for Canvas to release notes

_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
=> Minor edits for archiving segments

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
> I'm updating the `state_change_source` table because the source values have changed (added and deprecated). Updates were provided and reviewed by Weiqui Ma.
Closes [#BD-2236](https://jira.braze.com/browse/BD-2236?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)
=> BD-2236 Update state_change_source in Message Engagements Events

_docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
=> BD-2238: Cloning Canvases with branching now supported

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md, _docs/_developer_guide/platform_integration_guides/unity/sdk_integration/ios.md
> Adding instructions on how to enable verbose logging in the Unity editor.
Closes [#BD-2107](https://jira.braze.com/browse/BD-2107)
=> BD-2107 Enable Verbose Logging in Unity editor

_plugins/tabs.rb, assets/js/documents.js
- Add tab query, when you click on a tab, it'll update the url for easier linking
- For specific tabs, it'll save it so that when you refresh the page, it'll remember the last setting you pick.
---
<details>
<br>
</details>
<details>
<br> …
=> Add tab query and cookie

_docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
> I added a question to [Live Activities FAQ](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/live_activities/faq/#what-platforms-support-live-activities).
Closes [#BD-2240](https://jira.braze.com/browse/BD-2240?jql=project%20%3D%20BD%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(currentUser())%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)
=> BD-2240 Update Live Activities FAQ

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
=> Relocate EA alert for BigQuery

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> BD-2030: 90-day follow up to remove mention of Manage Approval Settings

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md
=> BD-2242: Clarify email templates for Inbox Vision support

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> BD-2243: Fix time_zone mentions in Liquid use case library

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
=> BD-2226: Add details for rate limiting for Canvas components

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
=> BD-2254: Replace brz.ai link with code text

_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
> I'm updating the sample code because it contains potentially sensitive information.
Closes [#BD-2255](https://jira.braze.com/browse/BD-2255)
=> BD-2255 Update Punchh sample code

_docs/_user_guide/data_and_analytics/custom_data.md, _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md, _docs/_user_guide/data_and_analytics/custom_data/events.md
=> Add clarifying documentation for events

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_in_braze.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2257: Update Shopify data processing fields

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md
=> Minor edits for Canvas components

_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
> Adding details about the expected accuracy of the calculate exact statistics feature in segments
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Segment calculate exact statistics accuracy

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2258: Updates to RudderStack

_docs/_api/endpoints/user_data/post_user_identify.md
=> BD-2260: Add banner for Identify users endpoint

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md, _docs/_user_guide/intelligence/ai_copywriting.md
Clarifying data usage policy of OpenAI ind ocs
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> OpenAI policy update

assets/js/broken_redirect_list.js
=> BD-2261: Fix link

_docs/_user_guide/message_building_by_channel/email/faq.md
> I'm updating mentions of "deliverability" to "delivery" for term clarification.
Closes #**BD-2264**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2264: Update "deliverability" to "delivery" for email FAQ

_docs/_user_guide/message_building_by_channel/push/best_practices/detailed_push_preferences.md, _docs/_user_guide/message_building_by_channel/push/best_practices/sunset_policies.md
> I edited the Push Best Practices docs to have headers and shorter paragraphs.
=> Modifying Push Best Practices

_docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md
edited for clarity following questions from CS
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Minor tweaks to reflect current state

_docs/_developer_guide/platform_integration_guides/web/content_cards/customization/custom_ui.md, _docs/_developer_guide/platform_integration_guides/web/content_cards/integration.md
=> content card example

_docs/_user_guide/data_and_analytics/query_builder.md
=> BD-2276: Update Query Builder credits to Snowflake credits

_docs/_user_guide/data_and_analytics/custom_data/blocklist_delete_custom_data.md
=> BD-2268: Clarify deleting custom data requires assistance

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
=> BD-2275: Add Currents note to link shortening FAQ

_docs/_hidden/other/documentation_request.md
=> Refine verification checkbox label for docs request

_docs/_user_guide/message_building_by_channel/sms/mms/faqs.md, _docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
> I updated two MMS articles to point out the potential wait for a short code re-approval process.
Closes [#BD-2273](https://jira.braze.com/browse/BD-2273)
=> BD-2273 Clarity to MMS setup

_docs/_developer_guide/platform_integration_guides/android/content_cards/integration.md, _docs/_developer_guide/platform_integration_guides/android/content_cards/refreshing_the_feed.md
https://jira.braze.com/browse/SDK-3957
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze …
=> SDK-3957/ update android cc refresh docs

_docs/_api/endpoints/user_data/post_users_merge.md
=> BD-2265: Clarify merge behavior

_docs/_user_guide/data_and_analytics/data_points.md
=> BD-2267: Add info about blocked data for data points consumption

_docs/_hidden/private_betas/shopify_catalogs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2277: Add troubleshooting to Shopify catalogs beta

_docs/_help/release_notes.md, _docs/_help/release_notes/2017/october.md, _docs/_help/release_notes/2023/12_13_22.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md, _docs/_user_guide/data_and_analytics/braze_currents/available_partners.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2280: Update segment.io to segment

_docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> CDI catalogs updates

_docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
=> BD-2285: Update email validation rule for all other domains

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md
=> Clarifications to post-launch edits for Content Cards

_docs/_user_guide/message_building_by_channel/content_cards/create.md
=> BD-2284: Update Content Card creation steps for Canvas

_docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
=> BD-2235: New whitespace after email preheader GA - MERGE 7/18

_docs/_hidden/other/dp-technical-assistance.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add permalink to dp technical assistance doc

_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
Making external_id generic in the examples, by request of Punchh
> Making external_id generic in the examples, by request of Punchh
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update punchh.md to make external_id generic

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_backfill.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_data_processing.md
> I updated the Shopify docs.
Closes #[BD-2287](https://jira.braze.com/browse/BD-2287)
=> BD-2287 Shopify Docs Update

_docs/_api/endpoints/user_data/post_user_track.md
https://jira.braze.com/browse/CO-1671
* Adds doc updates for update by phone
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> CO-1671 add docs for update by phone

_docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
Fixed a Talon.One Docs link and added a use case for Braze-Talon.One integration.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> fix: Talon.One URLs

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
=> BD-2291: Update catalog limitations for free version

_docs/_hidden/other/support_contact.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Support Workflow v2

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/phone_number_capture.md, _docs/_user_guide/message_building_by_channel/in-app_messages/traditional.md
=> Unhide phone number capture

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
=> Row component as drag-and-drop Content Block - MERGE 7/20

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
> I added two WhatsApp liquid properties to a table.
Closes [#BD-2293](https://jira.braze.com/browse/BD-2293)
=> BD-2293 Add WhatsApp liquid properties

_docs/_user_guide/administrative/app_settings/tags.md
=> BD-2295: Document tag limitation

_docs/_user_guide/engagement_tools/segments/user_profiles.md
=> BD-2294: Clarify blank destinations for messaging history

_docs/_developer_guide/platform_integration_guides/flutter/content_cards.md, _docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md, _docs/_developer_guide/platform_wide/feature_flags/create.md
https://jira.braze.com/browse/SDK-3976
- Adds relevant native steps for IAM and CC stream subscriptions in Flutter
- Removes the legacy docs around data callbacks, since we removed those deprecated methods recently
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-3976] Flutter docs - Update IAM and CC stream subscription steps

_docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md
=> BD-2303: Update schedule_id to required

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md
=> BD-2266: Replace HTML_FULL with HTML in-app message

_docs/_user_guide/message_building_by_channel/email/faq.md, _docs/_user_guide/message_building_by_channel/email/templates/faq.md
=> BD-2296: Clarify details about custom unsubscribe links

_docs/_api/endpoints/messaging/duplicate_campaigns.md
I've added a new endpoint, `/campaigns/duplicate` that is in early access that will go out this week. I don't know if I did it correctly to place this as a new link on the API endpoints under Messages.
---
<details>
<br>
</details>
<details>
<br> …
=> Add documentation page for duplicating Campaigns via API.

_docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2289: Update email validation rules

_docs/_hidden/other/support_contact.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update support flow fields

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
> I added a new doc and restructured the Treasure Data articles.
Closes [#BD-2292](https://jira.braze.com/browse/BD-2292)
=> BD-2292 Treasure Data for Currents

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, _docs/_hidden/other/ephemeral_custom_events.md, _docs/_hidden/wip_partnerships/WIP_guidelines.md, _lang/fr/_hidden/other/ephemeral_custom_events.md, _lang/fr/_hidden/wip_partnerships/WIP_guidelines.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Removal of Kellie

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2301: Minor tweaks to API endpoint parameters

_docs/_user_guide/sage_ai/predictive_suite/predictive_events.md, _docs/_user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction.md, assets/js/broken_redirect_list.js
=> Fix incorrect links on Predictive Events landing page

_docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
> Removed a bullet
Closes [#BD-2311](https://jira.braze.com/browse/BD-2311)
=> BD-2311 Remove bullet in WhatsApps article

_docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md, _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/user_retargeting.md
> I added legal verbiage to two articles.
Closes [#BD-2310](https://jira.braze.com/browse/BD-2310)
=> BD-2310 Add legal verbiage note

_docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md, _docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations.md, _docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
> Updated verbose logging sections.
Closes [#BD-2309](https://jira.braze.com/browse/BD-2309)
=> BD-2309 Edit Verbose Logging

_docs/_hidden/private_betas/sms_double_opt_in.md
> A few additions
Closes [#BD-2316](https://jira.braze.com/browse/BD-2316)
=> BD-2316 Update SMS Double Opt-In

_docs/_developer_guide/platform_integration_guides/android/content_cards/customization/swipe_to_dismiss.md, _docs/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md, _docs/_developer_guide/platform_integration_guides/android/news_feed/integration.md, _lang/fr/_developer_guide/platform_integration_guides/android/content_cards/customization/swipe_to_dismiss.md, _lang/fr/_includes/archive/android/universal_deep_link_delegate.md
Closes #SDK-3532
- [ X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix Android links

_docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
=> Fix small typo

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2317: Update Currents fields, and add alert

_docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md
=> BD-2315: Clarify differences between location tracking and geofences

_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
> New link added
Closes #BD-2325
=> BD-2325 Add Treasure Data to Currents partners

_docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
=> Fix search link for WhatsApp article

_docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md
> Update URL and broken link
Closes #BD-2326
=> BD-2326 Updates to SAML SSO Setup page

_docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
> Update URL and link
Closes #BD-2327
=> BD-2327 Updates to Azure Active Directory SAML SSO

_docs/_user_guide/data_and_analytics/report_metrics.md
=> BD-2324: Minor clarification on Body Clicks definition

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/use_cases.md, _docs/_user_guide/message_building_by_channel/push/android/notification_channels.md
=> BD-2335: Shopify catalogs GA

_docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md
=> BD-2336: Update Live Activities FAQ

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
we don't have a "group" concept
=> remove segment group call

_docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
Updating the React Native in-app message documentation to be more explicit and detailed in custom use cases. This will coincide with an upcoming release that cleans up and fixes the existing in-app message APIs in the Braze React Native SDK.
[Direct link to page](https://braze-docs-mejrxz0nt-braze.vercel.app/docs/developer_guide/platform_integration_guides/react_native/inapp_messages/)
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf …
=> Update in-app message documentation for React Native

_docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md
> Small addition
Closes #BD-2337
=> BD-2337 Update Abort Logic Documentation

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
> I'm updating the setup documentation for the React Native SDK to prepare for the release of the New Architecture Turbo Module.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …
=> Update React Native setup docs for Turbo Modules

_docs/_user_guide/personalization_and_dynamic_content/liquid.md
=> BD-2340: Remove reference of theme tags

_docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md
=> BD-2347 Appsflyer Integration Documentation Clarification Request

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
=> BD-2348 Fullscreen IAMs on Web SDK

_docs/_api/endpoints/export/campaigns/get_send_analytics.md
=> BD-2346: Update response

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
> Adding domain reputation with spam rate for email deliverability as phase 1.
Closes #**BD-2342**
---
=> BD-2342: Add domain reputation for email deliverability

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
=> BD-2348 Fullscreen IAM orientation

_docs/_partners/canvas_steps/facebook_audience_sync.md
=> BD-2352 Update Facebook ad account requirements

_docs/_api/endpoints/user_data/post_users_merge.md
[CO-1635](https://jira.braze.com/browse/CO-1635)
> Adds documentation for email support in /users/merge
Closes #**CO-1635**
=> Add documentation for users_merge_with_email

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_best_practices.md
=> Fix spacing

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update Android docs for FCM fallback service

_docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/rudderstack/rudderstack_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_for_currents.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md
=> BD-2353 Add examples to Currents doc

_docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
=> BD-2356: Remove EA note from Content QA

_docs/_docs_pages/robots.txt, vercel.json
Remove bot filter for blank pages to potentially fix some cdn issues.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Remove bot filter to blank pages

_docs/_hidden/private_betas/copying_to_workspace.md
=> Limitations for copying across workspaces

_docs/_developer_guide/platform_wide/sending_test_messages.md
=> Update incorrect link reference

_docs/_help/release_notes/2017/august.md, _lang/fr/_help/release_notes/2017/august.md, assets/js/broken_redirect_list.js
=> 404 audit part 1

_docs/_api/endpoints/user_data/post_users_merge.md
> Adding additional examples on prioritization
Closes #**CO-1635**
=> Document prioritziation for merging users by email

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
=> BD-2360 Add link to React Native doc

_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
=> BD-2358 Update Currents partners page

_docs/_api/identifier_types.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md, _docs/_developer_guide/platform_integration_guides/web/amp_support.md, _docs/_developer_guide/platform_wide/sending_test_messages.md, _docs/_help/release_notes/2019/july.md, _docs/_help/release_notes/2020/may.md, _docs/_partners/message_personalization/dynamic_content/certona.md, _docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md
> Changing placeholder from < > to { }
---
=> Updates for curly brackets - Pt. 1

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md
> Added note about matching user IDs with help from James Tilby-Jones
Closes #BD-2281
=> BD-2281 Update Current Docs about user IDs

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
=> BD-2359: Add detail for target entry audience

_docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md, _docs/_developer_guide/platform_wide/sending_test_messages.md, _docs/_help/help_articles/account/locked_out.md, _docs/_help/help_articles/segments/segmentation_logic_with_and_or.md, _docs/_help/release_notes/2019/november.md, _docs/_help/release_notes/2020/july.md, _docs/_help/release_notes/2020/october.md, _docs/_help/release_notes/2020/september.md, _docs/_help/release_notes/2021/october.md, _docs/_help/release_notes/2023/12_13_22.md, _docs/_partners/message_orchestration/additional_channels/messaging/line.md, _docs/_partners/message_orchestration/additional_channels/messaging/messenger.md, _docs/_user_guide/data_and_analytics/creating_a_formula.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md, _docs/_user_guide/data_and_analytics/tracking/email_tracking.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/conversion_events.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/scheduled_delivery.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md, _docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md, _docs/_user_guide/engagement_tools/segments/segment_insights.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md, _docs/_user_guide/message_building_by_channel/email/apple_mail/mpp.md, _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md, _docs/_user_guide/message_building_by_channel/email/faq.md, _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md, assets/js/broken_redirect_list.js
=> Deploy pt. 2 - August 15, 2023

_config.yml, _data/i18n.yml, _docs/_docs_pages/cla.md, _docs/_hidden/other/documentation_request.md, _docs/_hidden/other/support_contact.md, _includes/feedback.html, _lang/fr/_hidden/other/documentation_request.md, assets/css/_feedback.scss, assets/js/feedback.js
- Update endpoints
- Update feedback to 5 point rating
- 
Closes #GE-2280
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Feedback update 202308

_docs/_hidden/private_betas/copying_to_workspace.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Clarify omitted media item for copying across workspaces

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
> Adding two table for authentication and encryption information for email deliverability. Related to edits in https://github.com/braze-inc/braze-docs/pull/5936 and https://jira.braze.com/browse/BD-2342
Closes #**BD-2342**
---
=> BD-2342: Authentication and encryption tables for email deliverability GA

_docs/_hidden/private_betas/copying_to_workspace.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Minor edits

_docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md, _docs/_user_guide/administrative/access_braze/single_sign_on/okta.md, _docs/_user_guide/administrative/access_braze/single_sign_on/onelogin.md
> Minor edits to mentions of identity providers
---
=> Minor SSO edits

_docs/_hidden/other/support_contact.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix extra support question

_docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
=> Task-based edit Amazon S3 to Snowflake

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-2374 Update  key

_docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md
=> Task-based edit export Canvas data

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize.md
=> BD-2375 Custom Modal with CSS broken link

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md, _docs/_user_guide/sage_ai/intelligence/intelligent_channel.md
=> BD-2354 Add click tracking

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
=> Task-based edits Sending Test Messages

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md
=> BD-2370 Segment partner article update

assets/js/broken_redirect_list.js
=> Another redirect for intelligence

_docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/completing_integration.md
=> BD-2372: Replace reference to API docs with API identifier docs

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters/message_extras.md
=> BD-2377: Clarify message_extras is not available for IAMs

_docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md
=> BD-2373 Image nuance

_includes/campaign_analytics.md
=> BD-2380: Estimated real open rate EA

_docs/_help/release_notes.md, _docs/_help/release_notes/2023/8_22_23.md
=> Fix wording

_docs/_user_guide/engagement_tools/segments/user_profiles.md
Closes #[BD-2381](https://jira.braze.com/browse/BD-2381)
=> BD-2381 Search by user alias

_docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md
Closes #[BD-2382](https://jira.braze.com/browse/BD-2382)
=> BD-2382 Add uBlock callout

_layouts/broken_page.html
this should solve it once and for all 😬
=> fix 404 tracking

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> Remove duplciate filter and fix missing punctuation

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> BD-2384 Export CSV

_docs/_user_guide/message_building_by_channel/whatsapp.md, _docs/_user_guide/message_building_by_channel/whatsapp/message_processing/experiments.md
=> BD-2386: Add Meta experiment information from Legal

_docs/_api/endpoints/user_data/post_user_identify.md, _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md, _docs/_help/help_articles/data/blocklisting_deletion.md, _docs/_help/release_notes/2021/december.md, _docs/_home/templates/get_endpoint.md, _docs/_home/templates/post_endpoint.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md, _docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md, _docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md, _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md, _docs/_user_guide/message_building_by_channel/email/inbox_vision.md, _docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md, _docs/_user_guide/sage_ai/predictive_suite/predictive_churn/creating_a_churn_prediction.md, _docs/_user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction.md
> A small touch up of instances using "info" instead of "information"
=> Clean up: Changing "info" into "information"

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
This removes the early access notice for BigQuery CDI.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> remove early access notice for bigquery

_docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md
> I added a missing curly bracket to a Liquid example. I verified it by testing on the composer.
Closes #BD-2393
=> BD-2393 Liquid use case missing }

_docs/_help/help_articles/data/dispatch_id.md
Update dispatch_id to be more accurate. Do not merge without @diana-smirnova or @Bernie approval.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update dispatch_id wording.

_docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
=> BD-2395: Update Braze Learning links

_docs/_api/objects_filters/purchase_object.md
> Edited to make it clear that purchase event property segmentation exists
Closes #BD-2394
=> BD-2394 Update Purchase Event article

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
=> Fixing an errant large image

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
> Adds information on text links, request push primer, 
=> DND IAM doc updates [MERGE 8/29]

_docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
=> Task-based edits Audience Paths

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
=> Push notifications patch

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
=> Task edit: DND content blocks

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
=> new liquid tag just dropped (`${app.{api_id}}`)

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> Minor edits to User permissions

_docs/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md, _lang/fr/_developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners.md, _lang/fr/_developer_guide/platform_integration_guides/android/storage.md, _lang/fr/_developer_guide/platform_integration_guides/cordova/cordova_integration.md, _lang/fr/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/android.md, _lang/fr/_developer_guide/platform_integration_guides/cordova/initial_sdk_setup/ios.md, _lang/fr/_developer_guide/platform_integration_guides/unity/advanced_use_cases.md, _lang/fr/_developer_guide/platform_integration_guides/unity/push_notifications/adm_push_notifications.md, _lang/fr/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md, _lang/fr/_includes/archive/android/gifs.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-4063] Unity Appboy to Braze

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
Describes new fields for message archiving from the September 6, 2023 release.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add new fields for message archiving

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md, _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
=> BD-2357: Updates for team-level campaign and Canvas approval permissions - MERGE 8/31

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
> Added a few admin permissions
Closes #BD-2404
=> BD-2404 Update Shopify requirements

_docs/_user_guide/privacy_portal.md
=> BD-2403: Add Data Privacy Protection Framework link to Privacy Portal

_docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md
> I added a couple of details about updating user subscription statuses
Closes #BD-2401
=> BD-2401 WhatsApp updates

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
> Added limitations for what can be selected as a product identifier.
Closes #BD-2405
=> BD-2405 Add limitations to Shopify catalog article

vercel.json
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Redirect en path to root

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
> Task-based article edit
Closes #NONE
=> Task-based edit: Security Settings

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md
> Task-based edits for Inbox Vision.
=> Task-based edit: Inbox Vision

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_catalogs.md
> Added info that came in from engineering after the ticket was created
Closes #BD-2405
=> BD-2405 Quick fix with new info for ticket

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> Task-based edit to the User Permissions article.
=> Task-based edit: User Permissions

_docs/_developer_guide/platform_wide/feature_flags/faq.md
=> Minor edits to feature flags FAQ

_docs/_user_guide/message_building_by_channel/push/android/push_max.md
=> BD-2385: Push Max and promotion codes caveat 

_docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md, _docs/_user_guide/data_and_analytics/data_transformation/overview.md
=> Email as identifier updates to Data Transformation docs

_docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md, _docs/_user_guide/data_and_analytics/data_transformation/overview.md, _docs/_user_guide/message_building_by_channel/push/android/push_max.md
#6086 - Email as identifier updates to Data Transformation docs
=> Deploy pt. 2 - September 5, 2023

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md
> Add SMS legal disclaimer
Closes #BD-2407
=> BD-2407 add SMS legal disclaimer

_docs/_user_guide/data_and_analytics/data_transformation/overview.md
=> Edits to Data Transformation overview

_docs/_user_guide/engagement_tools/canvas/managing_canvases/cloning_canvases.md
=> Task-based edit: Cloning Canvases

_docs/_hidden/other/support_contact.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix support contact other and system not showing form.

_docs/_partners/data_and_infrastructure_agility/cohort_import/mparticle.md, assets/js/broken_redirect_list.js
=> Remove mparticle from cohort import

_docs/_user_guide/message_building_by_channel/sms/mms/mms_short_long_codes.md
> William Long gave feedback on the changes.
Closes #BD-2414
=> BD-2414 Remove MMS Canadian references

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
=> Q3 feedback - Deliverability Center typos

_docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
=> BD-2415: Add email to key-value pairs intro

_docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
=> BD-2406: Clarify supported languages for AI content QA

_docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
=> Task-based edit: Push Action Buttons

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
=> Q3 Docs feedback: Seed Groups

_docs/_user_guide/sage_ai/intelligence/intelligent_selection.md
=> Edits for Intelligent Selection

_docs/_user_guide/administrative/app_settings/internal_groups_tab.md
=> Edits to Internal Groups doc

_docs/_partners/message_personalization/location/accuweather.md
> Addresses https://github.com/braze-inc/braze-docs/issues/6108
---
=> Fix API request URL

_docs/_partners/message_personalization/location/accuweather.md
=> Fix API request URL pt. 2

_includes/archive/android/gifs.md
=> BD-2057 pt2: Clarify only HTML IAMs don't need special libraries

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
=> BD-2420: Add rate limit callout for Cloud Data Ingestion

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> I updated Liquid use cases that weren't working, added messages to demonstrate use cases worked, and updated some dates.
=> Fix Liquid Use Cases pt.1

_includes/archive/short_and_long_codes.md
=> BD-2418 updated short and long code throughput

_docs/_user_guide/message_building_by_channel/content_cards/testing.md
=> BD-2419: Clarification for Content Card testing requirements

_docs/_developer_guide/platform_integration_guides/android/in-app_messaging/integration.md, _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/customization/behavior_on_click.md, _docs/_developer_guide/platform_integration_guides/roku/in-app_messaging/integration.md, _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md, _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md
=> BD-2416: Clarify click action behavior in edge case

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> Liquid use case edits pt.2

_docs/_user_guide/message_building_by_channel/email/drag_and_drop.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md, _docs/_user_guide/message_building_by_channel/email/html_editor.md, _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
=> Edits for drag-and-drop email editor articles

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
=> BD-2421: Add note for exit criteria

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> Task-based edit: User Subscriptions

_docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
=> BD-2423 Fix steps numbering - Zapier

_docs/_api/objects_filters/messaging/email_object.md, _docs/_developer_guide/platform_integration_guides/android/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md, _docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md, _docs/_developer_guide/platform_wide/analytics_overview.md, _docs/_help/help_articles/campaigns_and_canvas/using_custom_event_properties.md, _docs/_home/static_video.md, _docs/_home/templates_old/partner_page_template_video.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md, _docs/_partners/message_orchestration/additional_channels/calendar/rokt_calendar.md, _docs/_user_guide/data_and_analytics/custom_data/custom_events.md, _docs/_user_guide/data_and_analytics/custom_data/purchase_events.md, _docs/_user_guide/message_building_by_channel/sms/faqs.md
=> Missing nav updates pt.2

_docs/_user_guide/message_building_by_channel/push/web.md
=> Q3 feedback: Updating web push article with use cases and more structure

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> BD-2429 Fix error in user permissions

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> Adding "View Transformations" and "Manage Transformations" user permissions
Closes #**BD-2430**
---
=> BD-2430: Add missing Data Transformation user permissions

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> Adding "Manage Feature Flags" and "Launch Preference Centers" user permissions
---
=> Add user permissions for feature flags and preference centers

_docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
=> Typo fix and minor edits

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> Liquid Use Case edit pt.3

_docs/_partners/isv_partners/best_practices.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
=> BD-2432: Connected Content limits cannot be increased

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
=> Deliverability Center GA

_docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
=> Add missing page title

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
=> BD-2151 Clarify Message Archiving note

_docs/_user_guide/onboarding_with_braze/terms_to_know.md
=> Add app instances to glossary

vercel.json
Redirect Korean to main site til we get the korean translations up.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> Redirect ko to en

_includes/header.html, assets/css/_header.scss
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Move language select

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
=> BD-2436 Fix list styling typo

assets/js/broken_redirect_list.js
> Updating redirects for the list-unsubscribe header as a workaround for an outdated link from the dashboard (email devs will also be updating the dashboard link)
---
=> Fix redirects for list-unsubscribe header

_docs/_help/help_articles/docs/contribution.md
=> Minor edits to Contributing to Braze docs help article

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> Liquid use case pt.4

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
=> Liquid use case edit pt.5

_docs/_help/release_notes/2023.md
=> Fix release notes year

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
=> BD-2443 WhatsApp added to subscription groups

_docs/_developer_guide/platform_integration_guides/swift/ios_17.md
=> Style edits to iOS 17 upgrade guide

_docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
> Update redirect link for Mixpanel
Closes #BD-2444
=> BD-2444 update Mixpanel redirect

_docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
> Removing "unknown" from language codes as flagged by Core Objects engineering
---
=> Remove "unknown" from language codes

_docs/_api/endpoints/export/campaigns/get_campaign_analytics.md
=> BD-2440 API Updates to include WhatsApp

_docs/_partners/message_orchestration/additional_channels/retargeting/facebook.md
> Now uses a step-based format. The screenshots are outdated, but I can't find a relevant workspace. I could look into it later.
=> Task-based edit: Facebook Audience Export

_docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md, _docs/_user_guide/message_building_by_channel/sms/keywords.md, _docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md, _docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md, _docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md, _docs/_user_guide/message_building_by_channel/sms/keywords/unknown_phone_numbers.md, assets/js/broken_redirect_list.js
> We launched the IAM phone number capture form and native SMS double opt-in feature, so this page is updated to reflect our current best practices.
Closes #BD-2446
=> BD-2446 update double opt-in best practices

_docs/_user_guide/message_building_by_channel/sms/best_practices/opt-ins.md
=> Fix numbering for opt-ins

_docs/_user_guide/message_building_by_channel/sms/keywords.md
=> Style edits for Keyword Processing landing

_docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md
> Reformatted the task-based steps
=> Task-based edit: Azure Active Directory

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
> Clarify Google Postmaster vs Microsoft SNDS metrics
---
=> Add Microsoft SNDS metrics

_lang/fr/_developer_guide/platform_integration_guides/react_native/inapp_messages.md
https://jira.braze.com/browse/SDK-2983
> I'm removing all the instances of a deprecated method `sendDeviceEventWithName`, in favor of the new method `sendEventWithName`. This change has already been done to EN and JP docs, so only the FR doc needs to be changed.
> In addition, I'm updating the code block in which the method is contained because it should be consistent with the ones on the EN and JP docs.
Closes #SDK-2983
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLp …
=> [SDK-2983] Update React Native In-App Message Docs

_docs/_api/endpoints/preference_center/get_create_url_preference_center.md
=> Q3 feedback preference center

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/time_based_canvas.md
=> BD-2439: Clarify Summary page for Canvas workflow

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/push_story.md, _docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
Trivial change to make App Groups more apparent in the push stories integration docs. Let me know if this makes sense. We have the information in the docs, but adding a header might make it more prominent.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Make App Groups clearer on iOS push stories

_docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md, _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md, _docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md, _docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md, _docs/_user_guide/data_and_analytics/data_transformation/use_cases.md, _docs/_user_guide/data_and_analytics/export_braze_data/export_custom_event_data.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md, _docs/_user_guide/engagement_tools/locations_and_geofences/mobile_integrations.md, _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md, _docs/_user_guide/engagement_tools/testing/race_conditions.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md
> Ran the spellcheck extension through User Guide up to `/content_cards`
=> Spelling fixes

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
=> Touch ups Creating a Catalog

_docs/_user_guide/data_and_analytics/reporting/reports_overview.md
=> BD-2455: Incorrect link on Reports Overview page

_docs/_user_guide/message_building_by_channel/email/email_setup/ip_warming.md
> Added peak-sending nuance, added Message Activity Log link, corrected typo
Closes #BD-2451
=> BD-2451 Add IP Warming nuance

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment.md, _docs/_user_guide/administrative/app_settings.md, _docs/_user_guide/sage_ai/intelligence/intelligent_selection.md
> Troubleshooting minor search inaccuracies 
=> Minor search fixes

_docs/_api/identifier_types.md, _docs/_api/objects_filters/messaging/email_object.md, _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
- Added email capture info for user data collection
- Updated file size limit for `email` object
- Added self-approval clarification for campaign approval
- Clarified where to find generated API keys 
---
=> Docs Q3 feedback

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
=> Fixes for Microsoft SNDS with Deliverability Center

_docs/_user_guide/data_and_analytics/data_transformation/overview.md
> Update "per minute" to "per month"
Closes #BD-2462
=> BD-2462 Update Data Transformation

_docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
> Resolving BD-2461 and scrubbing this article for readability and standards
Closes #**BD-2461**
=> BD-2461: Engagement Report links expire after 1 hour

_docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/troubleshooting.md
=> BD-2460: iOS simulator can test push notifications as of Xcode 14

_docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> Updated the universal links section with what we currently do, as recommended by Product.
Closes #**BD-2438**
---
=> BD-2438: Clarify info for universal links

_docs/_user_guide/engagement_tools/canvas/canvas_components/feature_flags.md
=> Conversions not conversations

_docs/_hidden/private_betas/campaign_data_retention.md
> Removing generalizing of "message interaction data" to just "campaign interaction data" because this only applies to campaigns right now 
---
=> Clarify campaign interaction data

_docs/_partners/message_personalization/location/radar.md
=> BD-2458: Add info about user aliases to Radar

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> BD-2465: Clarify control group details for editing Canvas after launch

_docs/_developer_guide/platform_integration_guides/unity/in-app_messaging.md
https://braze-docs-11ztaeg7o-braze.vercel.app/docs/developer_guide/platform_integration_guides/unity/in-app_messaging/#custom-action-listeners
Closes SDK-4096
- [X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> [SDK-4096] Update In-App Messaging for Unity

_docs/_developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv.md, _docs/_developer_guide/platform_integration_guides/swift/analytics/swift_idfv.md
Adding a note about `useUUIDAsDeviceId` being set to enabled by default in Swift SDK 7.0.0. **This version is pending release, so we'll hold off on merging until 7.0.0 has been released.**
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add note about IDFV being disabled by default in Swift SDK 7.0.0

_docs/_user_guide/message_building_by_channel/whatsapp/faqs.md, _docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md, _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md, _includes/campaign_analytics.md
> Making a handful of updates to WhatsApp articles.
Closes #BD-2471
=> BD-2471 WhatsApp Updates

_docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
=> BD-2464 Add details about updated phone numbers and subscription groups

_docs/_developer_guide/platform_integration_guides/swift/push_notifications/push_story.md
=> BD-2466 Adding pod target explanation for push stories

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
I'm updating the limitations section of Cloud Data Ingestion to indicate payload size limitations. The additional changes are a result of autoformatting.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add  payload size limitation for CDI

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md, _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
> Copying campaigns across workspaces GA
Closes #**BD-2474**
---
=> BD-2474: Copying campaigns across workspaces GA - MERGE 10/5

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns.md
=> BD-2488 Incorrect link for API triggered campaigns

_docs/_user_guide/message_building_by_channel/push/android/push_max.md
=> BD-2489: Clarify limitations with event properties

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix product limits on number of attributes

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
I'm removing a notice of early access for BigQuery and Databricks support for CDI. This has been in GA for a bit now, but we forgot to remove this notice.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> remove one more early access notice for bigquery and databricks CDI

assets/css/_details.scss, assets/css/application.scss, assets/css/main.scss
=> CSS tweaks

_docs/_api/endpoints/cdi.md, _docs/_api/endpoints/cdi/get_job_sync_status.md
=> BD-2495: Fix incorrect permalink and parent page links

_docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
=> BD-2499: Currents Field Transformations can apply only to string type

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add note about databricks instance types  and warmup time

.github/PULL_REQUEST_TEMPLATE.md
> Part of my Liquid OKR is to keep the Docs team updated on additions to the Liquid use case library. I added a small note to Lydia's "Product Vertical" row in the reviewer column. 
Closes #NONE
=> Liquid OKR: add Liquid use cases to the PR template

_docs/_hidden/other/documentation_request.md
Updates docs ticket submission confirmation page from:
To something more accurate:
=> Update docs ticket confirmation message

_docs/_user_guide/data_and_analytics/report_metrics.md
=> BD-2479 Metrics for deliveries and sends

_docs/_user_guide/sage_ai/intelligence/intelligent_timing.md
=> BD-2502: Remove mention of IAM in intelligent timing

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> Clarify that only administrators can delete users
Closes #BD-2493
=> BD-2493 Clarify user permissions

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md, _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> Edits include: 
> - Update steps to task-based
> - Move up managing link aliasing info
> - Update to new nav details for link templates
Closes #**BD-2470**
---
=> BD-2470: Clean up link aliasing and link template articles

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-2496: User import allows strings with commas with use of double quotes

_docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
=> BD-2503 Fix error in the example request for SCIM GET endpoint

.github/CODEOWNERS
> Adding Josh and me as code owners for the Liquid use case library.
Closes #None
=> Make Josh and Rachel code owners for Liquid use cases

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> BD-2504: Add caveat for being globally unsubscribed

_docs/_user_guide/engagement_tools/segments/user_profiles.md
> Merging user profiles GA
---
=> BD-2508: Merging user profiles GA

_docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
https://jira.braze.com/browse/CO-2007
=> [CO-2007] Update profile merge behavior documentation

_docs/_user_guide/engagement_tools/segments/sql_segments.md
=> BD-2509 Add tip to AI SQL Generator

_docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md
> Combo of Q3 feedback and Liquid use case editing
Closes #NONE
=> Q3 feedback and Liquid audit

_docs/_api/endpoints/cdi/get_job_sync_status.md
=> Add a period

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
=> Fix Liquid syntax error with raw tags

_config.yml
=> Fix incorrect searchableAttributes for Algolia

_docs/_user_guide/administrative/app_settings/message_activity_log_tab.md
After receiving user feedback, this PR makes a number of minor clarifications to make it more obvious that the messages listed within the log are only examples, and don't match 1-1 what can appear in the log. Attached is an image of the core changes: 
Closes #**BD-2498**
=> BD-2498: Update block sample message in Message Activity Log

_docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md, _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
=> BD-2510: Clarify Content Block updating behavior for drag-and-drop email editor

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
=> BD-2475 Rename appboyBridge to brazeBridge

_docs/_user_guide/administrative/access_braze/navigation.md
> Explicitly call out renamed pages
Closes #**BD-2491**
=> BD-2491: Add new column to navigation table

_docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md
=> BD-2514 Add detail to WhatsApp opt-in

_docs/_user_guide/administrative/access_braze/navigation.md
=> BD-2529: Fix incorrect term

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
> Add "Launch and Manage Content Blocks" user permission
---
=> Add "Launch and Manage Content Blocks" user permission

_docs/_help/release_notes/deprecations.md
=> BD-2521 Update Deprecations article with appboyBridge

_docs/_api/endpoints/email/get_list_hard_bounces.md
=> BD-2525: Add tips for encoding emails in URL and using `email` parameter

_docs/_api/endpoints/export/user_data/post_users_segment.md
> Fixes typo, adds `push_tokens` as a field to export, along with additional minor edits
---
=> Add `push_tokens` for Export user profile by segment

_docs/_user_guide/data_and_analytics/data_transformation/overview.md
=> BD-2535: Fix Data Transformation link

_docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
=> BD-2528: Clarify email self-service setup is only for onboarding customers

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
> Fix character code for |
Closes #BD-2533
=> BD-2533 Fix character code

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
=> BD-2536 Update custom domain requirements

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/content-cards_in_canvas.md
Closes #**[BD-2506](https://jira.braze.com/browse/BD-2506)**
=> BD-2506: Content Card expiration in Canvas

_docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/overview.md
Adds a note that the Swift SDK doesn't support Carthage as a package manager.
- [X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-4149] Add note on Carthage for Swift SDK

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
=> Remove mentions of specific channels

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md
=> BD-2541: Remove "JSON" from "What's copied across workspaces"

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md, _docs/_api/objects_filters/schedule_object.md, _docs/_developer_guide/platform_integration_guides/ios/advanced_use_cases/linking.md, _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md, _docs/_help/release_notes/2016/october.md, _docs/_hidden/other/support_contact.md, _docs/_user_guide/administrative/app_settings/company_settings/security_settings.md, _docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md, _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/sms/faqs.md, _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md, _lang/fr/_api/basics.md
=> BD-2518 Change whitelisting to allowlisting

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-2539: Fix typo in code snippet for updating custom nested attributes

_docs/_hidden/private_betas/campaign_data_retention.md
> Update campaign interaction data availability article to include details about retargeting by tags
---
=> Include info about retargeting by tag

_docs/_user_guide/message_building_by_channel/in-app_messages/about.md
=> BD-2537: Remove promotion code link from IAM

_docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
=> BD-2500: Include user permissions for email self-service

_docs/_help/support.md
> Capitalize "Braze Support team" and add tips for submitting a support case
Closes #**BD-2530**
---
=> BD-2530: Add best practices for submitting a support case

_docs/_api/endpoints/email/post_blacklist.md
=> BD-2545 Small edit for blacklist alert

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md
=> BD-2522 Media Library benefits

_docs/_user_guide/message_building_by_channel/email/amphtml.md
> AMP open counts are separate from HTML and plaintext count (separate numbers not cumulative)
Closes #**BD-2547**
---
=> BD-2547: Fix AMP email opens metric definition

_docs/_api/endpoints/user_data/post_user_track.md
> Removing old EA banners as part of BD-2448 that were missed
---
=> Remove old EA banners

_docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md, _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
Reverts braze-inc/braze-docs#6329
=> [SDK-4256] IAM Display Option .later deprecated for .reenqueue

_docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
> Adds details about accessing IAM button information from the IAM UI delegate for the Swift SDK
- [X ] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-4150] Add docs with further details about IAM buttons

_docs/_hidden/private_betas/quick_push.md
=> BD-2549: Clarify quick push entry point

_docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md
Small change to references to ChatGPT
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove "chat" from ChatGPT

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
=> Spellcheck edits: "Project" to "project"

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
=> Spellcheck edits: Creating a catalog

_docs/_api/basics.md, _docs/_home/styling_test_page.md, _docs/_partners/isv_partners/cohort_import.md, _docs/_user_guide/administrative/access_braze/sdk_endpoints.md, _docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md, _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md, _docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md, _lang/fr/_api/basics.md, _lang/fr/_partners/isv_partners/cohort_import.md, _lang/fr/_user_guide/administrative/access_braze/braze_instances.md, _lang/fr/_user_guide/administrative/access_braze/sdk_endpoints.md, _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/redshift.md, _lang/fr/_user_guide/data_and_analytics/user_data_collection/cloud_ingestion/snowflake.md, _lang/fr/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md, _lang/fr/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
Includes information about US 07, which is a new Braze cluster we are launching.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add US-07.

_docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
The json was invalid - it included `...` and was missing a close brace. This fixes the json
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix sample GeoJSON file

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
=> Spellcheck edits: Sheetdb to SheetDB

_docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md
=> Spellcheck edits: Update to "Creation"

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
=> Spellcheck edits: IDFA and ad ID

_docs/_user_guide/engagement_tools/segments/sql_segments.md
=> Spellcheck edits: Remove "CSM"

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
=> Spellcheck edits: Remove sentence

_docs/_user_guide/message_building_by_channel/sms/mms/contact_card.md
=> Spellcheck edits: Add hyphen

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/10dlc.md
=> Spellcheck edits: Remove COM/CSM

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
> Added details about what contact emails receive.
Closes #BD-2552
=> BD-2552 update contact emails information in cloud ingestion

_docs/_user_guide/data_and_analytics/report_metrics.md
=> Add definition for conversion window

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md
> Updated UX copy
Closes #NONE
=> Fix UI for Huawei push integration

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data.md
Fixing small typo in the [Treasure Data doc](https://www.braze.com/docs/partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data#step-2-define-your-query).
- Jira Ticket: [BD-2551](https://jira.braze.com/browse/BD-2551)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> BD-2551: Fixing small typo in Treasure Data

_docs/_user_guide/message_building_by_channel/email/email_setup/setting_up_ips_and_domains.md
> Creating a prerequisite section to address how to access and use self-service email setup 
---
=> Clarify prerequisites for self-service email setup

_docs/_user_guide/data_and_analytics/report_metrics.md
=> Fix duplicate metric filter

_docs/_partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee.md
=> Spellcheck edits: ".txt" to text

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/lytics.md
=> Spellcheck edits: Lytics

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
=> Spellcheck edits: "CSM" to "customer success manager"

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data.md
=> Spellcheck edits: "quieries" to "queries"

_docs/_partners/message_personalization/dynamic_content/personalize.md
=> Spellcheck edits: Removing hyphens

_docs/_user_guide/message_building_by_channel/sms/keywords/fuzzy_opt_out.md
=> Spellcheck edits: Article title and minor edits

_docs/_partners/data_and_infrastructure_agility/analytics/datadog.md
> Missed this "DataDog" to "Datadog" during Aspell 
---
=> Spellcheck edits: "DataDog" to "Datadog"

_docs/_partners/data_and_infrastructure_agility/analytics/thoughtspot.md
=> Spellcheck edits: "prebuilt"

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium.md
=> Spellcheck edits: "CSM" to "customer success manager" pt. 2

_docs/_user_guide/data_and_analytics/export_braze_data/segment_data_to_csv.md
=> BD-2558: Update list of data included in segment CSV export 

_layouts/api_page.html
=> Fix TOC for endpoints layout

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md, _lang/fr/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md
> I'm updating iOS and Android links on the Segment SDK documentation because the new Segment Swift SDK and Segment Kotlin SDK are preferred over the legacy Segment iOS SDK and Segment Android SDK (on the appboy repository). I also went through the docs to make sure they are consistent between the Android and iOS integration tabs in English and French.
Closes [SDK-3256](https://jira.braze.com/browse/SDK-3256)
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXR …
=> [SDK-3256] Update Segment Docs to include Segment Swift and Segment Kotlin SDK

_docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md
=> BD-2564 clarify automated user provisioning article

_docs/_developer_guide/platform_integration_guides/ios/push_notifications/silent_push_notifications.md, _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
Clarifying some additional information around silent notifications on iOS.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add alert on silent notifications with title and body

assets/download_file/data-sharing-raw-table-schemas.txt
[DLK-1418](https://jira.braze.com/browse/DLK-1418)
regenerating docs after upgrading CUE version to 0.1.1929+8f844ba
=> update CUE version to 0.1.1929+8f844ba

_docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
=> BD-2572 Add eligibility window to SMS double opt-in

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> Clarify "Launch and Manage Content Blocks" permission

_docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
=> Style edits

_docs/_user_guide/message_building_by_channel/push/android/push_max.md
=> BD-2574 Updated minimum SDK version for Push Max

_docs/_user_guide/getting_started/web_sdk.md
=> Style edits pt. 2

_docs/_user_guide/getting_started/integration.md
=> Style edits pt. 3

_docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md
=> "Block" to "block"

_docs/_user_guide/data_and_analytics/reporting/campaign_analytics.md, _docs/_user_guide/engagement_tools/campaigns.md
=> Fix weird capitalization inconsistency

_docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md
=> Fix capitalization inconsistencies

_docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
=> Remove line break

_docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md
=> Fix regular expression bit

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/templates/simple_survey.md
=> Remove "new" from simple survey

_docs/_api/endpoints/export/user_data/post_users_identifier.md
=> BD-2577 fix phone number formatting JSON responses

_docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md
> Single JSON object not an array of objects
Closes #**BD-2562**
---
=> BD-2562: Remove square brackets from example request

_includes/campaign_analytics.md
=> Clarify EROR is not retroactive

_docs/_developer_guide/platform_wide/getting_started.md
=> "Articles" to "articles"

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md
=> Small edits

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
=> Fix incorrect heading levels and table break syntax

_docs/_user_guide/getting_started/web_sdk.md
=> BD-2590: Fix URL missing a slash

_docs/_user_guide/data_and_analytics/query_builder.md, _docs/_user_guide/engagement_tools/segments/sql_segments.md
=> BD-2583: Clarify Snowflake credit usage is feature-independent

_docs/_developer_guide/platform_integration_guides/flutter/flutter_sdk_integration.md
[Complementary changes in our private Flutter repo](https://github.com/braze-inc/flutter-sdk/pull/191)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> [Untracked] Add Flutter version requirements to public docs

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> BD-2563: Clarify behavior for deleting variants after Canvas launch

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md, _docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
=> BD-2559: Update list of trigger types for action-based campaign delivery

_docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
=> BD-2600 remove EA alert for SMS double opt-in

_docs/_user_guide/administrative/access_braze/global_search.md
=> Global search GA

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
> Addresses https://github.com/braze-inc/braze-docs/pull/6512/ and some minor edits
---
=> Add legal edit for custom fonts in drag-and-drop email style settings

_docs/_docs_pages/index.md, _docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/11_14_23.md, _includes/release_type.md
> Using November 2023 release notes as a trial for revamping the release notes structure
---
=> November 2023 release notes

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
Adding documentation around listening for push notification events on React Native.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add documentation on React Native push notification events

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/huawei_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/customization/advanced_settings.md, _docs/_developer_guide/platform_integration_guides/ios/push_notifications/customization/custom_sounds.md, _docs/_developer_guide/platform_wide/sending_test_messages.md, _docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md, _docs/_hidden/private_betas/multiple_stores.md, _docs/_hidden/private_betas/whatsapp_response_messaging.md, _docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/scripttag_web_sdk_integration.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/setting_up_shopify.md, _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_backfill.md, _docs/_partners/message_orchestration/channel_extensions/surveys/survicate.md, _docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/capturing_lapsing_users.md, _docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md, _docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md, _docs/_user_guide/message_building_by_channel/content_cards/create.md, _docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md, _docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md, _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md, _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md, _docs/_user_guide/message_building_by_channel/sms/campaign/create.md, _docs/_user_guide/message_building_by_channel/sms/campaign/segments.md, _docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md, _docs/_user_guide/message_building_by_channel/whatsapp/overview.md, _docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md, _lang/fr/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md, _lang/fr/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
> Removed or replaced mentions of "wizard", per the Glossary
Closes #NONE
=> Remove mentions of wizard

_docs/_api/endpoints/user_data/post_user_delete.md, _docs/_api/endpoints/user_data/post_user_track.md, _docs/_docs_pages/index.md
=> Update popular topics and fix plural inconsistency

_docs/_hidden/archive_docs/previous_in-app_message_generations.md, _docs/_user_guide/engagement_tools/news_feed/creating_a_news_feed_item.md, _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/modal.md, _docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/slideup.md, _docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md, _docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md, _docs/_user_guide/message_building_by_channel/sms/mms/create.md
=> Standards edit: JPG to JPEG

_docs/_api/endpoints/user_data/post_user_identify.md, _docs/_api/endpoints/user_data/post_users_merge.md
* This documentation is a little confusing since the line below says we move over some event properties and purchase properties
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ ATTN: For …
=> Raghavnarain3 patch users merge users identify

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
=> BD-2524: Clarify partner limitation for array of objects and nested custom attributes

_docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md
=> Fix capitalization of third-party provider

_docs/_user_guide/engagement_tools/segments/sql_segments.md
=> BD-2611 update SQL Segment Extensions automatic membership regeneration

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
=> BD-2569: Add integration method note

_docs/_user_guide/message_building_by_channel/email.md, _docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
=> Fix email footer links

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md
=> BD-2603: Add quotes to Liquid example

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
=> BD-2608: Rate limiting and Canvas components

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md
=> BD-2604: User email addresses must be unique for a workspace

assets/js/broken_redirect_list.js
=> Fix IAM traditional editor redirects

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
=> BD-2623: Email capture form EA

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
> Updated link shortening FAQ regarding Advanced Tracking and SMS click events
Closes #BD-2620
=> BD-2620 Update link shortening FAQ

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
=> BD-2627: Add note about dashboard time zone for catalog time field

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
=> BD-2634: Remove EA for already GA'd feature

_docs/_api/endpoints/cdi.md, _docs/_api/endpoints/cdi/get_integration_list.md, _docs/_api/endpoints/cdi/get_job_sync_status.md, _docs/_api/endpoints/cdi/post_job_sync.md, _docs/_api/home.md
=> BD-2645: Unhide Cloud Data Ingestion endpoint docs

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> Made the "or" operator all lower case for the web browser use case
Closes #BD-2650
=> BD-2650 Fix Liquid use case operator

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
=> BD-2638 Update WhatsApp message engagement events

_docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md
=> BD-2648: Add detail for annotated emails in Gmail Promotions tab

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md, _docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md
Additional documentation around React Native and Expo push notification support (pending release of https://github.com/braze-inc/expo-plugin/pull/31)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add additional notes for Expo Notifications

_includes/archive/setting_user_ids/aliasing.md, _includes/archive/setting_user_ids/best_practices.md
=> BD-2565: Add reference links for user IDs and user aliasing in SDK docs

_docs/_user_guide/data_and_analytics/report_metrics.md, _docs/_user_guide/message_building_by_channel/content_cards/migrating_from_news_feed.md, _includes/campaign_analytics.md
=> BD-2630: Clarifications for "Messages Sent" metric for Content Cards 

_docs/_api/endpoints/email/post_blacklist.md
=> Postman audit: Update permission phrasing pt. 5

_docs/_api/endpoints/email/post_email_subscription_status.md
=> Postman audit: Update permission phrasing pt. 1

_docs/_api/endpoints/email/post_remove_hard_bounces.md
=> Postman audit: Update permission phrasing pt. 3

_docs/_api/endpoints/email/post_blocklist.md
=> Postman audit: Update permission phrasing pt. 4

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Update to previous change about rate limiting (from this [docs request](https://jira.braze.com/browse/BD-2608))
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> fix reference to campaigns in canvas section

_docs/_api/endpoints/export/user_data/post_users_segment.md
=> Postman audit fixes pt.1

_docs/_api/endpoints/export/user_data/post_users_global_control_group.md
=> Postman audit fixes pt.2

_docs/_developer_guide/platform_wide/feature_flags/about.md
=> BD-2632: Clarify active feature flags definition

_docs/_api/endpoints/scim/get_search_existing_dashboard_user.md
=> Postman audit pt1 - SCIM GET

_docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
=> BD-2660: Update FAQ for Facebook Leads article

_docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md, _docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
=> BD-2658: Move spam blocking alert to different article

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> BD-2662 Add missing definitions

_docs/_api/endpoints/templates/content_blocks_templates/get_list_email_content_blocks.md, _docs/_api/endpoints/templates/content_blocks_templates/get_see_email_content_blocks_information.md, _docs/_api/endpoints/templates/content_blocks_templates/post_create_email_content_block.md, _docs/_api/endpoints/templates/content_blocks_templates/post_update_content_block.md, _docs/_api/endpoints/templates/email_templates/get_list_email_templates.md, _docs/_api/endpoints/templates/email_templates/get_see_email_template_information.md, _docs/_api/endpoints/templates/email_templates/post_create_email_template.md, _docs/_api/endpoints/templates/email_templates/post_update_email_template.md, _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md, _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_rename.md, _docs/_api/endpoints/user_data/post_user_alias.md, _docs/_api/endpoints/user_data/post_user_delete.md, _docs/_api/endpoints/user_data/post_user_identify.md, _docs/_api/endpoints/user_data/post_user_track.md, _docs/_api/endpoints/user_data/post_users_alias_update.md, _docs/_api/endpoints/user_data/post_users_merge.md, _docs/_developer_guide/platform_integration_guides/web/push_notifications/integration.md
Applied some style edits to my section of endpoints.
The only ones I believe need close editing are Users Track and Merge Users, both of which are important endpoints and needed a little TLC. Please review my work on these carefully to make sure all of my improvements are actually improvements.
=> Postman Audit

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md
Updates step 5 with context that if a specified folder name doesn't exist, Braze will automatically create it for the user.
Closes #**BD-2654**
=> BD-2654: Update step 5 of Amazon S3 partner doc

_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
=> BD-2670: Clarify data point consumption for User Update step

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> BD-2629: Clarify post-launch editing

_docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md, _includes/campaign_analytics.md
=> BD-2668: Add dispatch_id for Unique Clicks metric

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md
> Also cleaned up the article for content and style.
Closes #**BD-2612**
=> BD-2612: Add external_id to Message Archiving file references

_docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
=> BD-2657: Add example for deduplication behavior

_docs/_api/endpoints/preference_center/get_create_url_preference_center.md, _docs/_api/endpoints/preference_center/get_list_preference_center.md, _docs/_api/endpoints/preference_center/get_view_details_preference_center.md, _docs/_api/endpoints/preference_center/post_create_preference_center.md, _docs/_api/endpoints/preference_center/put_update_preference_center.md, _docs/_api/endpoints/scim/delete_existing_dashboard_user.md, _docs/_api/endpoints/scim/get_search_existing_dashboard_user.md, _docs/_api/endpoints/scim/get_see_user_account_information.md, _docs/_api/endpoints/scim/post_create_user_account.md, _docs/_api/endpoints/scim/put_update_existing_user_account.md
=> Postman audit pt2

_docs/_developer_guide/home.md, assets/js/broken_redirect_list.js
The buttons for MacOS and tvOS under "Legacy integrations" result in a 404. You can navigate to the pages using the sidebar on the left however.
- **Affected doc:** [Braze Developer Guide](https://www.braze.com/docs/developer_guide/home)
- **Jira Ticket:** [BD-2674](https://jira.braze.com/browse/BD-2674)
---
<details>
<br>
</details>
<details>
<br> …
=> BD-2674 Hotfix: fixing 404s from developer guide homepage

_docs/_hidden/other/support_contact.md
Add company id to support contact page.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add company id to support contact

_docs/_partners/message_personalization/dynamic_content/playable.md, _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
=> BD-2625: Updating "Twitter" to "X" when applicable

_docs/_help/release_notes.md, _docs/_help/release_notes/2023.md, _docs/_help/release_notes/2023/12_12_23.md
=> December 2023 release notes

_docs/_api/objects_filters/user_attributes_object.md, _docs/_home/templates_old/api_glossary.md, _docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/event_forwarding_extension.md, _docs/_partners/message_orchestration/attribution/adjust.md, _docs/_partners/message_orchestration/attribution/appsflyer/appsflyer.md, _docs/_partners/message_orchestration/attribution/branch/branch_for_attribution.md, _docs/_partners/message_orchestration/attribution/kochava.md, _docs/_partners/message_orchestration/attribution/singular.md, _docs/_user_guide/engagement_tools/segments/segment_funnels.md, _docs/_user_guide/engagement_tools/segments/segmentation_filters.md, _docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
=> Minor fixes for X (formerly Twitter)

Rakefile
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> copy 404 file to root path

Rakefile
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fix 404 typo

_docs/_partners/message_orchestration/attribution/branch/branch_for_deeplinking.md
=> BD-2628: Add detail for telephone redirects in Gmail

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_for_currents.md, _docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md, _includes/updating_currents.md
Adds steps to Segment for Currents and Setting up Currents docs on how to update existing Currents without relaunching them. This uses an includes so that the information can later be added to other partner docs if needed. 
Closes #**BD-2671**
=> BD-2671: Instructions for updating existing Currents

_layouts/broken_page.html
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Auto redirect to 404 language to default page

assets/js/broken_redirect_list.js
=> Add list-unsubscribe redirect

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
> I'm removing documentation on PII/NON_PII tables, which we removed sometime in 2020/2021. This documentation was meant for the transition period, which we are well past of. 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details> …
=> Remove very old documentation on PII and NON_PII tables in Datalake

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> BD-2678 Change description for Manage media library permission

_docs/_user_guide/administrative/app_settings/email_settings.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add note about dynamic sending domains + IP pools

_docs/_hidden/misc_reference/scim_api_appendix.md, _docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md, _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
=> Update Manage Media Library Assets

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
Developer Console no longer exists in the new navigation, so updating this permission to be more specific. Change approved by Ingestion PM in this [Slack thread](https://brazetechnology.slack.com/archives/C01DB7JAL1Y/p1702490068619609)
---
=> Update description for Access Dev Console permission

_docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
=> BD-2685: 404 fix

_docs/_hidden/private_betas/campaign_data_retention.md
=> BD-2683: Update campaign interaction data EA note

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md, _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md, _includes/early_access_banner.md, _includes/firebase_cloud_messaging/early_access_banner.md
Adding 'Early Access' banner to FCM docs by creating and linking to a new include.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Hotfix - Adding 'Early Access' banner to FCM docs

_docs/_user_guide/message_building_by_channel/content_cards/create.md
=> BD-2679 Remove content card limit

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
Added a clarification around the behavior of rate limiting for multi-channel canvas steps that include push. 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add push clarification to canvas rate limiting docs

_docs/_api/endpoints/messaging/live_activity/update.md, _docs/_api/endpoints/messaging/send_messages/post_create_send_ids.md, _docs/_api/endpoints/messaging/send_messages/post_send_messages.md, _docs/_api/endpoints/messaging/send_messages/post_send_transactional_message.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md, _docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
API fixes found during endpoint audit. Mainly converting the `{% alert note %}` tags to an H2 heading called **Prerequisites** per our new standards.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> API fixes found during endpoint audit

_docs/_api/endpoints/export/custom_events/get_custom_events.md, _docs/_api/endpoints/export/custom_events/get_custom_events_analytics.md, _docs/_api/endpoints/export/kpi/get_kpi_daily_new_users_date.md, _docs/_api/endpoints/export/kpi/get_kpi_dau_date.md, _docs/_api/endpoints/export/kpi/get_kpi_mau_30_days.md, _docs/_api/endpoints/export/kpi/get_kpi_uninstalls_date.md, _docs/_api/endpoints/export/news_feed/get_news_feed_card_analytics.md, _docs/_api/endpoints/export/news_feed/get_news_feed_card_details.md, _docs/_api/endpoints/export/news_feed/get_news_feed_cards.md, _docs/_api/endpoints/export/purchases/get_list_product_id.md, _docs/_api/endpoints/export/purchases/get_number_of_purchases.md, _docs/_api/endpoints/export/purchases/get_revenue_series.md, _docs/_api/endpoints/export/segments/get_segment.md, _docs/_api/endpoints/export/segments/get_segment_analytics.md, _docs/_api/endpoints/export/segments/get_segment_details.md, _docs/_api/endpoints/export/sessions/get_sessions_analytics.md, _docs/_api/endpoints/export/user_data/post_users_global_control_group.md, _docs/_api/endpoints/export/user_data/post_users_identifier.md, _docs/_api/endpoints/export/user_data/post_users_segment.md, _docs/_api/endpoints/sms/get_query_invalid_numbers.md, _docs/_api/endpoints/sms/post_remove_invalid_numbers.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_group_status.md, _docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md, _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md, _docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md
=> Postman prerequisites fixes

_docs/_hidden/other/user_archival.md
=> Fix Liquid snippet

_docs/_docs_pages/404.md, _lang/fr/_docs_pages/404.md, _layouts/broken_page.html
Add additional language subtext to 404 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add additional subtext to 404

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md, _docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> BD-2677 Add information on segmentation filtering

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md
=> BD-2690 email capture updates

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
=> BD-2686 Add note to link shortening testing

_docs/_developer_guide/platform_wide/feature_flags/create.md
=> Remove non-inclusive language

_docs/_api/objects_filters/user_attributes_object.md
=> BD-2682 Update user attributes with warnings

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md
=> BD-2692 Add an additional line for the AndroidManifest.xml file

_docs/_api/endpoints/user_data/post_users_merge.md
JIRA: [BD-2700](https://jira.braze.com/browse/BD-2700)
> I'm changing the examples on the Merge Users page because most of the current ones are invalid and will return an error. `merge_updates` needs to be an array of objects, and won't work if it's just a single object without an array wrapper. In addition, there are some trailing commas which are not allowed in JSON. Please feel to reach out to me on Slack if you have any questions!
Note: [The French version of this page](https://github.com/braze-inc/braze-docs/blob/develop/_lang/fr/_api/endpoints/user_data/post_users_merge.md) does not appear to contain these examples. Does the French translation need to be updated?
---
<details>
<br>
</details>
<details> …
=> Fix merge_updates JSON formatting.

assets/js/broken_redirect_list.js
Fixing the broken link on the [iOS In-App Message Customization](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/in-app_messaging/customization) page, on the tile labeled **Overriding In-App Message Logic**. It appears there was a URL redirect conflict where a page was point to a page that was pointing to another page. This has been fixed.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkic …
=> Fixing broken link in iOS in-app messaging

assets/js/broken_redirect_list.js
=> Fix redirect due to capitalization

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
=> BD-2675: Clarify HTML attributes for email editors

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
=> BD-2681: Add "2XX response" detail for returning valid JSON

_docs/_help/help_articles/data/change_custom_data_type.md
https://jira.braze.com/browse/CO-2237
=> [CO-2237] Updated doc for custom attribute automatic type detection

_docs/_user_guide/message_building_by_channel/sms/campaign/retargeting.md
=> BD-2706: Typo fix

_docs/_hidden/private_betas/campaign_data_retention.md
=> Clarify message interaction data expiration behavior for campaigns with tags

_docs/_user_guide/data_and_analytics/analytics/home_dashboard.md
=> BD-2702: Fix app-centric language

_docs/_hidden/private_betas/updated_segment_experience.md
=> BD-2709 Create hidden page for updated "Creating a segment" article

_docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
=> BD-2703: Remove mention of using API to update catalog fields for Sync catalogs data

_docs/_partners/canvas_steps.md, _docs/_partners/canvas_steps/google_audience_sync.md, _docs/_partners/canvas_steps/pinterest_audience_sync.md, _docs/_partners/canvas_steps/snapchat_audience_sync.md, _docs/_partners/canvas_steps/tiktok_audience_sync.md
=> BD-2701: Clarify which integrations are Audience Sync Pro

_docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md, _docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md
=> BD-2711: Add note about Custom Code block behavior

_docs/_user_guide/administrative/access_braze/global_search.md
=> BD-2721: Clarify only Canvas names are searchable, not steps

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
=> BD-2629: Follow up clarification for enqueued

_docs/_user_guide/administrative/app_settings/custom_event_and_attribute_management.md
=> BD-2725: Blocklist up to 300 custom attributes and 300 events

_docs/_help/release_notes.md, _docs/_help/release_notes/2024.md, _docs/_help/release_notes/2024/1_9_24.md
=> January 2024 release notes

_docs/_user_guide/data_and_analytics/query_builder.md
=> BD-2727 Update Query Builder variable

_docs/_hidden/private_betas/updated_segment_experience.md, _docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
=> BD-2728 Update Segment docs

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md, _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/cocoapods.md, _docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/swift_package_manager.md
* Adds new notes about prebuilt dynamic and static XCFrameworks as Swift SDK options
* Re-formats structure for notification extension targets in Swift SDK to be clearer
* Adds Objective-C++ notes for dynamic XCFrameworks to React Native SDK installation guide
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Add and re-format installation instructions for Braze Swift SDK

_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
=> BD-2720 Update Content Card Refresh Details

_docs/_user_guide/engagement_tools/segments.md
=> BD-2726 Add Custom Attributes tile to Segments page

_docs/_partners/message_personalization/location/loplat.md, _lang/fr/_partners/message_personalization/location/loplat.md
> Updated hosting for the Integration Guide website, replaced two links in the markdown accordingly.
- [✔️] No
@josh-mccrowell-braze
@bre-fitzgerald
---
<details>
<br>
- [ ✔️ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ✔️ ] Check that all links work.
- [ ✔️ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ✔️ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
</details>
<details> …
=> Partner Docs: loplat

_config.yml, _includes/html_include.html, _includes/search_page.html, assets/js/algolia_header_search.js, assets/js/algolia_main_search.js
Update Learning index reference.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Update Lab index

_docs/_user_guide/sage_ai/recommendations.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add note about flattening arrays

_includes/campaign_analytics.md
Adding more details about EROR
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update EROR about minimum data

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
=> BD-2723: Remove outdated Braze Learning link and video

_docs/_user_guide/message_building_by_channel/in-app_messages/creative_details/fullscreen.md
=> BD-2729 Link to GIF-specs article

_config.yml, _docs/_hidden/other/support_contact.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Update support with developerid

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md
> Custom Code block documentation is a [WIP](https://docs.google.com/document/d/13iQwxGSlxZdX98JOSjBU7xytREuusY1wVCSZkgCV5F4/edit#heading=h.d2ha0mauydhw).
Closes #BD-2744
=> BD-2744 Update Custom Code Block FAQ

_docs/_user_guide/message_building_by_channel/sms/keywords/sms_double_opt_in.md
=> BD-2742 Update SMS double opt-in images

_docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
Hello. We recently deployed a manual integration guide for the Swift SDK. We pretty quickly got [a support issue](https://brazetechnology.slack.com/archives/CBU9BRKHA/p1705338248126749) related to a client not realizing they needed to include `BrazeKit.xcframework` as part of their project. So, I thought I may as well push a quick edit to try and make that warning a little louder.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SX …
=> [Untracked] Make the Swift SDK manual integration more explicit on `BrazeKit` being required

_docs/_api/endpoints/export/campaigns/get_send_analytics.md
=> BD-2740: Clarify API campaigns only for Export send analytics endpoint

_docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
=> BD-2745 Update WhatsApp external link

_docs/_partners/message_personalization/location/loplat.md, _lang/fr/_partners/message_personalization/location/loplat.md
> I have modified the link in the integration guide document (loplat.md). The update reflects the most recent information.
- [ ✔️ ] No
@josh-mccrowell-braze
@bre-fitzgerald
---
<details>
<br>
- [ ✔️ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [✔️  ] Check that all links work.
- [ ✔️ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ✔️ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer. …
=> Update link in loplat.md

_docs/_api/api_limits.md, _docs/_api/endpoints/export/campaigns/get_campaign_analytics.md, _includes/rate_limits.md
=> BD-2746: Fix rate limit for `/campaigns/data_series`

_docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Add the following iOS requirements for the Braze Flutter SDK's in-app messaging feature: [Swift: Enabling in-app messages](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery#enabling-in-app-messages).
- **Ticket:** [BD-2694](https://jira.braze.com/browse/BD-2694)
---
<details>
<br>
</details>
<details>
<br> …
=>  BD-2694: Add iOS reqs for Flutter's in-app messaging

_docs/_api/api_limits.md
Making default API rate limits more clear, by stating requests not listed in the table _share_ a default rate limit of 250,000 requests per hour.  
- **Ticket:** [BD-2697](https://jira.braze.com/browse/BD-2697).
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> BD-2697: Making default API rate limits clearer

_docs/_hidden/other/user_archival.md
> I'm changing https://www.braze.com/docs/user_archival/ because we recently had an IRT that proved that recording a data point does not prevent user archival. 
After:
Closes #CO-2282
- No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> CO-2282 remove data points references from user archival docs

_docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md
=> BD-2748 Update catalog segments definition

_docs/_help/help_articles/push/reducing_payload_size.md
=> BD-2741: New help article for reducing push notification payload size

_docs/_developer_guide/platform_integration_guides/swift/initial_sdk_setup/installation_methods/manual_integration.md
Fixing incorrect cross-reference syntax throughout the repository.
**Wrong syntax:**
```
{{sitebase.url}}/PATH
```
**Correct syntax:**
```
{{site.baseurl}}/PATH
```
_*Note the incorrect location of the period._
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Fixing incorrect cross-reference syntax

_docs/_developer_guide/platform_wide/sending_test_messages.md
=> Fix small typo in Sending test messages

_docs/_user_guide/engagement_tools/locations_and_geofences.md, _docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
=> BD-2649: Boost search rank for geofences

_docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md
This PR adds documentation for deleting catalog items through CDI. This is a new feature.
Additionally, I've also made some small updates to the catalog documentation for CDI to reflect that a) it also supports Databricks, and b) the integration name does not need to match the catalog name anymore
---
<details>
<br>
</details>
<details>
<br> …
=> Add documentation for deleting catalog items

_docs/_hidden/private_betas/preview_user_paths.md
=> BD-2755: Fix typo

assets/js/broken_redirect_list.js
=> BD-2754: Remove duplicate redirect that broke existing one

_docs/_developer_guide/platform_integration_guides/flutter/inapp_messages.md
Edits the Flutter iOS IAM docs to make it more explicit that you need to enable IAM UI in order for IAMs to display. I also updated how you sent IAM data from iOS → Flutter layer since we now have 2 options
Closes https://jira.braze.com/browse/SDK-4621
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> [SDK-4621] Improve Flutter iOS IAM docs

_docs/_user_guide/engagement_tools/segments/sql_segments/use_cases.md, _layouts/sql_segment_extensions_glossary.html
=> BD-2753 Create SQL Segment Extensions use case library

_docs/_partners/canvas_steps/google_audience_sync.md
> Added the following:
> * New prerequisite
> * Chart for custom attribute fields
> * Tips for a successful import
Closes #**BD-2756**
---
=> BD-2756: Updates for Audience Sync to Google - MERGE 1/23

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
=> BD-2691: Clarify how to send only deltas for CDI

_docs/_user_guide/administrative/app_settings/workspaces.md, assets/js/broken_redirect_list.js
=> BD-2757 fix broken link for targeting a singular app

_docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md
> Clarified a sentence and removed "ensure" reference
Closes #BD-2770
=> BD-2770 Clarify sentence in User Profile Lifecycle

_docs/_partners/canvas_steps/google_audience_sync.md
=> Legal update for Google Audience Sync

_docs/_user_guide/data_and_analytics/reporting.md, _docs/_user_guide/data_and_analytics/reporting/campaign_analytics.md, _docs/_user_guide/data_and_analytics/reporting/canvas_analytics.md
=> BD-2768: Add Canvas analytics to Your Reports section

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
=> BD-2772: Clarify deduplication is only for original editor Canvases

_docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md
=> Link Segment Insights to Performance by Segment article

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
I'm updating the documentation for the `time` field for CDI events and purchases noting that it's not mandatory.
Also added the Databricks section for views while working on this page.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<summary>❗ …
=> update documentation for time field in events and purchases for CDI

_docs/_api/endpoints/user_data/post_users_merge.md, _docs/_user_guide/engagement_tools/segments/user_profiles.md
=> BD-2774 Update merge behavior documentation

_docs/_hidden/private_betas/updated_segment_experience.md
=> Fix custom attribute link

_docs/_api/endpoints/cdi.md, _docs/_api/endpoints/cdi/get_integration_list.md, _docs/_api/endpoints/cdi/get_job_sync_status.md, _docs/_api/endpoints/cdi/post_job_sync.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Remove EA flag from cdi endpoints page

_docs/_user_guide/sage_ai/recommendations.md
Clarify recommendation definition
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …
=> Clarification for recommendations

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
=> BD-2783: Clarify required permissions to view Deliverability Center

_docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
https://jira.braze.com/browse/SDK-4178
- After [this PR](https://github.com/braze-inc/xamarin-sdk/pull/180) has been released
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> [SDK-4178] Xamarin docs - Swift SDK and AppboyKit version note

_docs/_user_guide/data_and_analytics/export_braze_data.md, _layouts/dev_guide.html
=> BD-2765: Add Currents tiles to Data Export, and add description option to `dev_guide` layout

_docs/_api/endpoints/export/campaigns/get_campaign_details.md, _docs/_api/endpoints/export/canvas/get_canvas_details.md, _docs/_api/endpoints/export/segments/get_segment_details.md
> The February 6, 2024 release includes a "teams" key in the output from /campaigns/details, /canvases/details and /segments/details.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …
=> Add Team names to /details endpoints for Campaigns, Canvases and Segments. - Merge 2/6

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md
=> BD-2802 WhatsApp product update Feb 2024

_docs/_user_guide/administrative/app_settings/email_settings.md, _docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
=> BD-2801: Email edits

_docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md
=> BD-2800: Clarify user email subscription

_docs/_user_guide/sage_ai/recommendations.md
Adds example mappings to Step 4 of AI item recommendations.  
Closes #**BD-2788**
=> BD-2788: Add example for selecting property name to AI item recs

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md, _docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md, _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
=> BD-2785 Updating Custom Attributes - MERGE 2/8

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
=> KB audit: Segment membership filter

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md
> Aligning with how we have "Editing Canvas after launch"
---
=> KB audit: "Changing" to "Editing"

_docs/_hidden/private_betas/campaign_data_retention.md
=> Clarifications for campaign interaction data
