_docs/_help/help_articles/data/change_custom_data_type.md

KB audit: Changing custom attribute data types

---

_docs/_user_guide/sage_ai/recommendations.md

Changes to avoid customers  customers interpreting AI recs as being related to generative AI or LLMs.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

AI Recs / LLM clarification

---

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md

BD-2736 Update Segmentation filters

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md

BD-2804: Provide more details on how to regenerate schema

---

assets/js/algolia_header_search.js
assets/js/algolia_main_search.js

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

fix learning search results

---

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md

BD-2787 Add detail to re-evaluate campaign eligibility

---

_docs/_help/help_articles/push.md
_docs/_help/help_articles/push/resetting_push_permissions.md

BD-2615: New help article for resetting push permissions

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md

BD-2778 Add email capture form to back-in-stock notifs

---

.github/PULL_REQUEST_TEMPLATE.md

Replace Bre with Isaiah in PR template.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Replace Bre with Isaiah in PR template

---

_docs/_user_guide/message_building_by_channel/push/users_and_subscriptions.md

BD-2821: Clarify push subscription state with multiple devices

---

_docs/_user_guide/message_building_by_channel/email/best_practices/managing_email_subscriptions.md

BD-2798: Clarify users who are ubsubscribed

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md

BD-2784: Add limitation for image blocks and button links

---

_docs/_api/endpoints/user_data/post_user_track.md
_docs/_api/objects_filters/event_object.md

BD-2761: Add email as an identifier for event object 

---

README.md
_docs/_contributing/generating_a_preview.md
_docs/_contributing/home.md

Updating docs for Ruby 3.2.2 upgrade that took place in #6853. cc @zzhaobraze 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Updating docs for Ruby 3.2.2 upgrade

---

_docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md

BD-2828 Update MMS messages size

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md

BD-2829: Add quotes around `CAMPAIGN_ID`

---

_docs/_user_guide/administrative/access_braze/single_sign_on/azure_ad.md

BD-2826: Remove image from Azure AD

---

_docs/_hidden/private_betas/quick_push.md
_docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md

BD-2823: Clarify push action buttons not support with quick push campaigns

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/campaign_calendar.md

BD-2822: Add note that IAMs are not included in Send calendar

---

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md

BD-2687: Add experiment path caveat

---

_docs/_user_guide/message_building_by_channel/sms/faqs.md

Users do need to be in the subscription group to receive test sends
@josh-mccrowell-braze  
@internetisaiah 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Update SMS FAQs - test sends

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Shopify_Features/shopify_catalogs/back_in_stock.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md

BD-2835 Update back-in-stock notifications item_id

---

_docs/_user_guide/administrative/app_settings/company_settings/automated_user_provisioning.md

BD-2847: Update to SCIM Provisioning

---

assets/js/broken_redirect_list.js

BD-2838: Fix broken link

---

_docs/_user_guide/message_building_by_channel/email/amphtml.md

BD-2844: Clarify details for AMP email editor

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md

BD-2864 Unhide email capture form

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

BD-2858 Link Custom Attributes inside Segmentation Filters

---

_docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md

BD-2807 Inherited phone numbers also inherit subscription states

---

_docs/_help/help_articles/push/push_token_migration.md

Fixes #6928 , which is related to incorrect closing tags for example curl commands in [Migrating Push Tokens](https://www.braze.com/docs/help/help_articles/push/push_token_migration#manual-migration-via-api).
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fixing issue #6928 | Curl Commands

---

_docs/_contributing/content_management/cross_referencing.md

BD-2859 Update Cross Referencing with HTML link

---

_docs/_api/objects_filters/user_attributes_object.md

BD-2855: Include email for user attributes object

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md
assets/js/broken_redirect_list.js

BD-2862 Fix broken link for viewing PII

---

_docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md

Adds documentation regarding Tone control for the copywriting assistant.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Add tone control

---

_docs/_contributing/content_management/redirecting_urls.md
_docs/_contributing/troubleshooting.md
_includes/contributing/alerts/warning_urls_must_be_lowercase.md

Updating redirect + troubleshooting docs based on the issue discussed in [this PR](https://github.com/braze-inc/braze-docs/pull/6921#issuecomment-1959638074). (Summary: you can't have uppercase characters in URL strings for redirects).
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Updating redirect + troubleshooting docs

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md

We've decided to add a page limit out of precaution to 10
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Update create.md to reflect new page limit

---

_docs/_partners/canvas_steps/google_audience_sync.md

BD-2860: Update to Google Audience Sync details

---

_docs/_api/endpoints/export/user_data/post_users_global_control_group.md

BD-2867: Clarify Global Control Group for exporting user data

---

_docs/_api/endpoints/messaging/send_messages/post_send_messages.md
_docs/_hidden/private_betas/link_shortening.md

BD-2837 Add hidden Link Shortening page and updated post/send

---

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md

Describes support for Message Archiving for Azure & GCS.
Adds information that Message Archiving is no longer limited to AWS S3.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Message Archiving support for Azure and GCS. - to be merged February 28

---

_docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
assets/js/broken_redirect_list.js

Make SQL Table Reference public

---

_docs/_user_guide/message_building_by_channel/sms/keywords/keyword_handling.md

This doesn't go to any different documentation it just confusingly redirects back to the list of SMS topics currently.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Remove reference to non-native SMS

---

_docs/_hidden/pricing/message_credits_delta_a3sy.md
_docs/_hidden/pricing/message_credits_gamma_0dhr.md
_docs/_hidden/pricing/message_credits_sigma_pow2.md
_docs/_hidden/pricing/message_credits_theta_d9kw.md
assets/css/_content.scss

Formalizing the request post conversation with Isaiah and Joshua on FY25 pricing links and approvals (request vetting) process that we need.
- **Ticket:** [BD-2731](https://jira.braze.com/browse/BD-2731)
1. Due to Legal's feedback, some content (like capitalization, wording, etc.) intentionally does not follow the style guide.
2. Changes to the CSS files were approved (via Slack) by @zzhaobraze.

BD-2731: FY25 Pricing Hidden Links

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md

BD-2874: Add details for maximum duration in Canvas

---

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md
_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/troubleshooting.md

> Add FAQ to debug why push might not be sending
Closes #**BD-2872**

BD-2872 Troubleshooting push not sending - Android

---

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md

Add a note that uploading new tokens will not remove legacy keys and will only use those as a backup in case they delete their new keys. We use new keys if they exist, otherwise we use old keys.
- **Ticket:** [BD-2769](https://jira.braze.com/browse/BD-2769)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

BD-2769: Add note to FCM migration doc

---

_docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md

> Remove EA banner for Content Card creation
Closes #**BD-2883**

BD-2883 Content Card creation GA

---

_docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md

BD-2882: Add recommendation to use GIF instead of JavaScript

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Remove repeated requirements for custom list-unsubscribe header

---

_docs/_user_guide/message_building_by_channel/email/html_editor/gmail_promotions_tab.md

BD-2884: Update details for link tracking

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md

Updating Experiment Paths docs to reflect a new feature
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Experiment step randomization mode - MERGE 3/5

---

_docs/_api/objects_filters/purchase_object.md
_docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md

BD-2868: Replace mention of Braze to Braze webhook with Segment Extensions

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing/ab_test_projection.md

BD-2886: Hide A/B test projection doc

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2024/3_5_24.md

Edit to March release notes

---

_docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
_docs/_developer_guide/customization_guides/content_cards/customizing_styles.md
_docs/_developer_guide/platform_integration_guides/android/content_cards/implementation_guide.md
_docs/_developer_guide/platform_integration_guides/android/content_cards/jetpackcompose.md
_includes/archive/android/gifs.md

I'm adding new sections to talk about how to use the Android SDK with Jetpack Compose.
Closes SDK-4656
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

[SDK-4656] Jetpack Compose Content Cards

---

_docs/_partners/canvas_steps/google_audience_sync.md

Update wording for Audience Sync to Google

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2024/3_5_24.md

Update phrasing for Audience Sync to Google

---

_docs/_partners/canvas_steps/facebook_audience_sync.md

BD-2870: Add troubleshooting detail for Facebook Audience Sync step

---

_docs/_api/data_retention.md

BD-2885 Update data retention

---

_docs/_user_guide/message_building_by_channel/email/templates/link_template.md

BD-2873: Add access to Link Management tab details for updated HTML editor

---

_docs/_developer_guide/platform_integration_guides/web/google_tag_manager.md
_docs/_partners/canvas_steps/google_audience_sync.md

BD-2869: Include updated EU User Consent Policy for Google Tag Manager

---

.github/PULL_REQUEST_TEMPLATE.md

Update legal team reference on PR template

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md

> Preview user paths GA
Closes #**BD-2864**
---

BD-2864: Preview user paths GA - MERGE 3/7

---

_docs/_hidden/private_betas/messaging_interaction_data.md

BD-2888: Clarify what's impacted and not for messaging interaction data

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2024/3_5_24.md

Add preview user paths to March release notes

---

_docs/_user_guide/message_building_by_channel.md
_docs/_user_guide/message_building_by_channel/webhooks.md
_docs/_user_guide/message_building_by_channel/whatsapp.md

BD-2892: Alphabetize messaging channel navigation

---

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md

Updates the minimum supported version of React Native to 0.71+, pending release of 9.0.0
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Update React Native minimum version support to 0.71

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Updated Extole integration guide to reflect changes on the Extole side

---

_docs/_developer_guide/platform_wide/feature_flags/create.md

Fix to match naming for [Swift SDK method](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/featureflags-swift.class/logfeatureflagimpression(id:))
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Fix sample Swift code for logFeatureFlagImpression

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Adding documentation for a new segmentation filter
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Add message Open likelihood filter description

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md

BD-2881: Canvas zoom in and zoom out - MERGE 3/11

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Reverts braze-inc/braze-docs#7008

Revert "Add message Open likelihood filter description"

---

_docs/_developer_guide/platform_integration_guides/swift/analytics/tracking_sessions.md

Adding documentation to a new Swift SDK method, see https://github.com/braze-inc/swift-sdk/pull/620 and https://jira.braze.com/browse/SDK-4737
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Add code snippets for Swift subscribeToSessionUpdates(_:)

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

BD-2896: Add back SMS sends to carrier events and add support detail

---

_docs/_user_guide/engagement_tools/campaigns/faq.md

Fix slightly misleading FAQ for safe zone

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md

Update keyboard shortcuts for Canvas zoom

---

_docs/_user_guide/engagement_tools/segments/regex.md

BD-2893 Add FAQ about regex filter

---

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md

Minor edits to Custom events

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

BD-2891 Update Push Enabled For App

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md

BD-2915 Edit wording for exception events

---

_docs/_user_guide/data_and_analytics/braze_currents.md

BD-2922: Fix wording

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

BD-2895 Add message_extras field

---

_docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md

BD-2920: Updates for archiving Content Blocks - Looker feedback

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

> Addition from Jeff Stutz, detailed out in this [doc](https://docs.google.com/document/d/1UUU2su4VUlpyxNN3DDmJqf51ZFK16mbqpBaMux-USG0/edit)
Closes #**None**

Add new IAM event fields

---

_docs/_help/help_articles.md
_docs/_help/help_articles/email.md
_docs/_help/help_articles/in-app_messages.md
_docs/_help/help_articles/segments.md
_docs/_user_guide/administrative/app_settings/company_settings.md
_docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
_docs/_user_guide/engagement_tools/campaigns/getting_started.md
_docs/_user_guide/engagement_tools/campaigns/managing_campaigns.md
_docs/_user_guide/engagement_tools/canvas/canvas_components.md
_docs/_user_guide/engagement_tools/canvas/get_started.md
_docs/_user_guide/engagement_tools/canvas/managing_canvases.md
_docs/_user_guide/engagement_tools/canvas/testing_canvases.md
_docs/_user_guide/message_building_by_channel/content_cards/best_practices.md
_docs/_user_guide/message_building_by_channel/email/apple_mail.md
_docs/_user_guide/message_building_by_channel/email/best_practices.md
_docs/_user_guide/message_building_by_channel/email/drag_and_drop.md
_docs/_user_guide/message_building_by_channel/email/email_setup.md
_docs/_user_guide/message_building_by_channel/email/html_editor.md
_docs/_user_guide/message_building_by_channel/email/preference_center.md
_docs/_user_guide/message_building_by_channel/email/templates.md
_docs/_user_guide/message_building_by_channel/in-app_messages/best_practices.md

Minor edits to section titles

---

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md

BD-2925: Clarify parent domains and subdomains for Deliverability Center and Google Postmaster

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md

BD-2907 Add nested custom attributes limitation

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md

BD-2906: Add fallback image requirement for dynamic images

---

_includes/image_specs.md

> Adding button details to IAM image specs
Closes #**BD-2912**

BD-2912 Update image specs for IAM

---

_docs/_hidden/other/documentation_request.md

Closes #GE-2949
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Add due date to request form

---

_docs/_user_guide/data_and_analytics/tracking/segment_analytics_tracking.md

BD-2917 Update Segment analytics tracking

---

_docs/_api/objects_filters/aliases_to_identify.md
_docs/_api/objects_filters/canvas_entry_properties_object.md
_docs/_api/objects_filters/connected_audience.md
_docs/_api/objects_filters/messaging/android_object.md
_docs/_api/objects_filters/messaging/apple_object.md
_docs/_api/objects_filters/messaging/web_objects.md
_docs/_api/objects_filters/messaging/webhook_object.md
_docs/_api/objects_filters/purchase_object.md
_docs/_api/objects_filters/recipient_object.md
_docs/_api/objects_filters/schedule_object.md
_docs/_api/objects_filters/user_alias_object.md
_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md
_includes/rate_limits.md

BD-2921: Edits for objects and filters section - Looker feedback

---

_docs/_user_guide/message_building_by_channel/webhooks/braze_to_braze_webhooks.md

Edits to Braze-to-Braze webhooks

---

_docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
_docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md

> I'm updating the information on the In-App Message and Content Card pages for the React Native SDK developer guide because we want to include descriptions for the model properties. I also updated the methods to be up-to-date.
Closes [#SDK-4669](https://jira.braze.com/browse/SDK-4669)
---
<details>
<br>
</details>
<details>
<br> …

[SDK-4669] Add more properties for IAM and CC to React Native doc

---

_docs/_api/endpoints/user_data/post_users_merge.md

BD-2943: Remove sentence from parameters table

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment_engage.md

BD-2944 GA Cohort Destinations

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md

BD-2924 Add trigger event option SMS shortened link

---

_docs/_api/endpoints/messaging/send_messages/post_send_messages.md
_docs/_api/endpoints/preference_center/post_create_preference_center.md
_docs/_developer_guide/platform_integration_guides/android/analytics/setting_user_ids.md
_docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/analytics/setting_user_ids.md
_docs/_developer_guide/platform_integration_guides/swift/analytics/setting_user_ids.md
_docs/_developer_guide/platform_integration_guides/unity/Analytics/setting_user_ids.md
_docs/_developer_guide/platform_integration_guides/web/analytics/setting_user_ids.md
_docs/_hidden/archive_docs/windows_universal/analytics/setting_user_ids.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md

BD-2940: Edits to endpoint articles - Looker feedback

---

_docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md

BD-2945: Clarify sentence for nested properties

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

> Part 1 of user permission updates related to creating or uploading promotion code lists. This callout will be removed after April 4, when https://github.com/braze-inc/braze-docs/pull/7070 will be merged.
Closes #**BD-2932**
---

BD-2932: Add note for permissions to create or upload promotion code

---

_docs/_developer_guide/platform_integration_guides/unity/push_notifications/ios.md
_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/advanced_use_cases.md
_docs/_hidden/archived_layouts/glossary.md
_docs/_hidden/private_betas/multi_language_settings.md
_docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md
_docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
_docs/_partners/message_orchestration/additional_channels/retargeting/quikly.md
_docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
_docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md

Minor style edits for mentions of "optional"

---

_docs/_partners/data_and_infrastructure_agility/cohort_import.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/census.md
_docs/_partners/data_and_infrastructure_agility/workflow_automation/census.md

BD-2808 Update cohort import page

---

_docs/_api/objects_filters/messaging/apple_object.md

Fix for https://jira.braze.com/browse/CH-5458?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Update docs for `sound` field in Live Activities payload

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md

Updating descriptions of personalizad paths to more closely match the language revised in the UI
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …

Pers paths GA 3/26

---

_docs/_hidden/other/generations.md

BD-2947: Move IAM generations out of archive

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

BD-2946 Update Catalog use cases with Liquid if statements

---

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md
_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md

Add Expo integration instructions for [iOS rich push notifications and push stories](https://github.com/braze-inc/braze-expo-plugin/releases/tag/2.1.0)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Add integration instructions for Expo rich push and push stories for iOS

---

_docs/_api/data_retention.md
_docs/_hidden/private_betas/messaging_interaction_data.md

> Updating the **Campaign and Canvas Interactions Data** section to reflect approved edits from Legal and Product
Closes #**BD-2926**
---

BD-2926: Replace Campaign and Canvas Interactions Data section in Braze Data Retention Policy

---

_docs/_api/data_retention.md
_docs/_hidden/private_betas/messaging_interaction_data.md

Reverts braze-inc/braze-docs#7058

Revert "BD-2926: Replace Campaign and Canvas Interactions Data section in Braze Data Retention Policy"

---

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md

BD-2959 Add WhatsApp product update for April 2024

---

_docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md

BD-2964 Update MMS throughput

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md
_docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md
_docs/_user_guide/engagement_tools/canvas/canvas_components/decision_split.md
_docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md

Edits to Canvas components section

---

_docs/_hidden/private_betas/updated_segment_experience.md

BD-2966 Update exclusion group definition

---

_docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_drafts.md

Minor edits to Canvas drafts

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fix DP info on overview.md

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

BD-2931: Update description for global state change event

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
_docs/_user_guide/sage_ai/intelligence/intelligent_channel.md

Documentation for channel open likelihood filter and related mention on Intelligent Channel
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Message Open Likelihood filter and related

---

_docs/_user_guide/message_building_by_channel/email/faq.md

BD-2965: Update Braze tracking unsubscribe links detail

---

_docs/_user_guide/sage_ai/generative_ai/ai_content_qa.md

Update AI Content QA description to include IAM with release 
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

 AI Content QA in IAM

---

_docs/_user_guide/data_and_analytics/export_braze_data/export_campaign_results_data.md
_docs/_user_guide/data_and_analytics/export_braze_data/export_canvas_data.md

Closes #**BD-2962** and **BD-2963**
---

BD-2962 and BD-2963: Add export entrants for Canvas detail

---

_docs/_api/data_retention.md

> Updates to Campaign and Canvas Interactions Data for Data Retention doc (Legal approved)
---

Updates to Campaign and Canvas Interactions Data for Data Retention doc

---

_docs/_hidden/private_betas/post_duplicate_canvas.md

BD-2967: Duplicate Canvases EA - MERGE 4/2

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/Using_Shopify/use_cases.md

You can't tell, but I made the folder names lowercase for the Shopify docs

Lowercase folder names

---

_docs/_api/endpoints/messaging/duplicate_campaigns.md

> Change alert to prerequisites section
---

Add Prerequisites section for Duplicate campaigns doc

---

_docs/_api/errors.md

BD-2974 Fix 404 error description

---

_docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md

BD-2976: Fix typo

---

_docs/_contributing/content_management/images.md

Fix syntax typo in images.md
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fix syntax typo in images.md

---

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging.md

Adding note related to Google's FCM rate limit.
- **Ticket:** [BD-2935](https://jira.braze.com/browse/BD-2935)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

BD-2935: Add note for FCM rate limit

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md

Fixing some exposed liquid that leaked into `develop` and `master`. Will do an ad hoc deploy once this is merged.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fixing some exposed liquid

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

BD-2960 Correct Segmentation Filters for Purchase Behavior

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify.md

BD-2980 Fix Shopify folder titlecase

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

BD-2986: Add alerts for empty fields for email open and email click events

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

BD-2987 Update SMS click events

---

_docs/_hidden/private_betas/idle_campaigns.md

Update "end date" to "send date" where needed

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs/back_in_stock.md

> Revert deletion of email capture form

Revert deletion of email capture form

---

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md

BD-2989 Braze retries webhook sends for up to 24 hrs

---

_docs/_partners/data_and_infrastructure_agility.md
_docs/_partners/data_and_infrastructure_agility/workflow_automation.md
_docs/_partners/home.md

Forgot to add the landing page links for MetaRouter in #7172.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

MetaRouter Docs: Adding to landing pages

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

BD-2990: Update CSV file section for catalogs

---

_docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md

BD-2997: Clarify list of scheduled campaigns and Canvases

---

_docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md

Accompanying documentation for https://github.com/braze-inc/swift-sdk/pull/654. Adding clarifications and new API usage details for background geofences on iOS.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Update background geofence documentation for iOS

---

_docs/_api/endpoints/preference_center/post_create_preference_center.md

> Small fix that was caught but not applied in a previous PR

Small edit for post create preference center

---

_docs/_hidden/pricing/braze_go.md

BD-3000: Braze Go article

---

_docs/_api/endpoints/user_data/post_user_track.md

Minor style edits

---

_docs/_developer_guide/platform_integration_guides/react_native/content_cards.md
_docs/_developer_guide/platform_integration_guides/react_native/inapp_messages.md

> I'm adding information for GIF support on React Native for in-app messages and content cards for iOS and Android.
Closes #[**SDK-4491**](https://jira.braze.com/browse/SDK-4491)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

[SDK-4491] GIF Support on React Native

---

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md

A [support ticket](https://brazetechnology.slack.com/archives/C03A4QR4U2G/p1713164944257399) came in that brought up that our documentation says you can create IAMs as an API campaign but the UI does not allow you to do this.
We verified in the code and the backend does not support creating IAMs, and the rest of the [documentation](https://www.braze.com/docs/api/endpoints/messaging/send_messages/post_send_messages/#request-body) agrees with this fact.
No ticket - I'm on-call and this is a minor fix.
---
<details>
<br>
</details>
<details>
<br>
- …

Remove reference to "API Campaign" from IAM creation

---

_docs/_api/endpoints/user_data/post_user_track.md

BD-3003 Update POST user track

---

_docs/_api/basics.md

Minor edits to API overview

---

_docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
_includes/create_transformation.md

Data Transformation docs need to be updated for revised Catalogs functionality.
- **Ticket:** [BD-3005](https://jira.braze.com/browse/BD-3005)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

BD-2988: Catalogs feature update

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md

BD-3017: Add note for `product_handle` and `product_url` access

---

_docs/_user_guide/message_building_by_channel/whatsapp/message_processing/handling_unknown_numbers.md

BD-3022: Edits to handling unknown phone numbers

---

_docs/_contributing/styling_examples.md

Insignificant edit to test GitHub file editing on a forked branch

Guest edit test

---

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md

BD-3024 Update Meta Resources with template pacing

---

_docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md

BD-3032 Remove EA note for performance data by segment

---

_docs/_developer_guide/platform_integration_guides/unity/sdk_integration/android.md

https://jira.braze.com/browse/SDK-4844
Updates the unity android docs to be a bit more thorough in terms of what's needed. Also points to the sample app as well.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

SDK-4844 / more thorough unity android gradle docs

---

_docs/_developer_guide/platform_wide/sdk_authentication.md

> Fixes typo in SDK Authentication doc (changes `seconday` --> `secondary`)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fix typo in SDK Authentication doc

---

_docs/_hidden/pricing/message_credits_delta_a3sy.md
_docs/_hidden/pricing/message_credits_gamma_0dhr.md
_docs/_hidden/pricing/message_credits_sigma_pow2.md
_docs/_hidden/pricing/message_credits_theta_d9kw.md

BD-3034 Update credit ratio tables - Italy SMS

---

_docs/_hidden/private_betas/price_drop_notifications.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md

https://jira.braze.com/browse/CO-2499

[CO-2499] Updated back-in-stock / price-drop documentation to include previous / new value

---

_docs/_user_guide/administrative/access_braze/single_sign_on/saml_jit.md

BD-3036 SAML Just-in-Time Provisioning

---

_docs/_user_guide/sage_ai/generative_ai/ai_copywriting.md

Resolving a slight ambiguity
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

on brand copy tweak

---

_docs/_user_guide/message_building_by_channel/whatsapp/overview.md

BD-3038 WhatsApp Cloud API Local Storage

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Update canvas rate limiting docs

---

_docs/_api/endpoints/messaging/schedule_messages/get_messages_scheduled.md

Fix colons

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md

Fix broken link in Extole article

---

_docs/_user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq.md

Minor edit

---

_docs/_hidden/other/user_archival.md

> Update user archival docs to mention WhatsApp and Global Control Groups
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

add WhatsApp and Global Control Group to user archival

---

_docs/_partners/data_and_infrastructure_agility/analytics/datadog.md

BD-3045 Remove support paragraph - Datadog

---

_plugins/urlnavmenu_generator.rb

Fix issue with redirect_to in left nav menu sending to english page.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

add multi_lang support for redirect in navigation

---

_docs/_developer_guide/platform_integration_guides/flutter/push_notifications.md

https://jira.braze.com/browse/SDK-4855
This portion of the docs were incorrectly copied from the React Native docs when expanding these Flutter docs
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

[SDK-4855] Cleanup mentions of `app.json` in Flutter docs

---

_docs/_api/objects_filters/messaging/android_object.md

Fix incorrect link to the android push notification priority doc.
- **Ticket:** [BD-3048](https://jira.braze.com/browse/BD-3048)
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work …

BD-3048: Fix incorrect link for android pn priority

---

_docs/_user_guide/engagement_tools/testing/race_conditions.md

BD-3014: Clarify details for race conditions and multiple endpoints

---

_docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md

BD-3057 Update link in CDI segments

---

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md

BD-3061: Update important alert

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
_docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md

> Fix EA notes
Closes #**NONE**

Fix EA notes

---

_docs/_user_guide/engagement_tools/locations_and_geofences/faqs.md

BD-3016: Add additional resource links for geofences

---

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md

BD-3039: Add troubleshooting info for IAM test sends

---

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md

BD-3062 Remove beta from Event Streaming in Amplitude Audiences

---

_docs/_user_guide/message_building_by_channel/sms/campaign/create.md

> Removed stray tag that renders unescapes and look weird
Closes #n/a
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

[NOTIX] Remove stray tags

---

_docs/_help/help_articles/data/change_custom_data_type.md
_docs/_partners/isv_partners/best_practices.md
_docs/_partners/message_orchestration/additional_channels/messaging/regal.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/getting_started_shopify.md
_docs/_user_guide/data_and_analytics/custom_data/purchase_events.md

Convert alert notes to alert importants for early access

---

_docs/_api/use_cases.md

Align headers

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

BD-3068 Update security settings for 2FA

---

_docs/_api/endpoints/user_data/post_user_identify.md

BD-3013: Minor edit for /users/identify

---

_docs/_api/endpoints/translations.md

Update translation endpoint icons

---

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/add_to_calendar_links.md

BD-3052: Add resources to add-to-calendar links article

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md

[DLK-1754](https://jira.braze.com/browse/DLK-1754)
- add query timeout recommendations

[DLK-1754] add doc for query timeouts 

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md

BD-3046 Details about editing experiment messages mid-send

---

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md

https://jira.braze.com/browse/SDK-4882
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze …

SDK-4882 / fixed firebase cloud messaging gradle dependency line back

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

BD-3080: Update promo codes detail for test sends

---

_docs/_user_guide/message_building_by_channel/email/best_practices.md

Add tile for sanitization article

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md

BD-3096: Update description for capitalize string filter

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

BD-3092 Clarify Canvas variation and control group filters

---

_docs/_user_guide/data_and_analytics/reporting/funnel_reports.md

BD-3099: Clarify detail for funnel reports

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing/ab_test_projection.md

BD-3100: A/B testing for multiple devices for quick push campaign

---

_docs/_api/endpoints/export/user_data/post_users_identifier.md

BD-3066 Add  identifier to overview

---

_docs/_hidden/private_betas/dashboard_builder.md

BD-3095 last-touch attribution template - dashboard builder

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

BD-3102: Clarify promotion code detail

---

_docs/_hidden/private_betas/dashboard_builder.md

Small update for bd-3095

---

_docs/_hidden/private_betas/idle_campaigns.md
_docs/_user_guide/engagement_tools/campaigns/getting_started/understanding_campaign_status.md
_docs/_user_guide/engagement_tools/canvas/get_started/canvas_outlines.md
_docs/_user_guide/engagement_tools/canvas/get_started/canvas_status.md
assets/js/broken_redirect_list.js

> Updates to Understanding campaign status article, new article for Understanding Canvas status, and updates to include information for idle Canvases
Closes #**BD-3082**
---

BD-3082: Update statuses for campaigns and Canvases

---

_docs/_user_guide/engagement_tools/canvas/get_started.md

Add Understanding Canvas status tile

---

_docs/_api/endpoints/translations.md

Fix tile links for Translation API

---

_docs/_user_guide/administrative/app_settings.md
_docs/_user_guide/administrative/app_settings/multi_language_settings.md
_docs/_user_guide/message_building_by_channel/email.md
_docs/_user_guide/message_building_by_channel/email/using_locales.md

BD-3097: Multi-Language Settings GA

---

_docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md

> Updated content type to application/json
Closes #**BD-3104**

BD-3104 Update application/json in Zapier docs

---

_docs/_user_guide/message_building_by_channel/email/templates/link_template.md

BD-3107 Add Link templates title

---

_docs/_hidden/pricing/braze_go.md

BD-3109: Fix Braze Go doc

---

_docs/_hidden/private_betas/idle_campaigns.md

Fix sentence

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/winning_path.md

BD-3110: Add detail about concluding Winning Paths

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

Update callout from "Beginning in early April 2024" to "As of April 2024"

Update outdated callout

---

_docs/_contributing/content_management.md
_docs/_contributing/content_management/cross_referencing.md
_docs/_contributing/content_management/images.md
_docs/_contributing/content_management/jekyll_collections.md
_docs/_contributing/content_management/pages.md
_docs/_contributing/content_management/redirecting_urls.md
_docs/_contributing/content_management/reusing_content.md
_docs/_contributing/content_management/sections.md
_docs/_contributing/yaml_front_matter/metadata.md
_docs/_contributing/yaml_front_matter/page_layouts.md
_docs/_contributing/your_first_contribution.md

After a presentation I realized one title wasn't diataxis-typed + some unclear headings. Also realized there was no overview for cross-references on the "Explanation" page, so I added one.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Diataxis tweak + new heading for content management

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md

BD-3114 Fix Liquid use case

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

BD-3116: Remove sentence

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md

BD-3112: Clarify note

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Add note for updated HTML editor

---

_docs/_partners/data_and_infrastructure_agility/cloud_storage/google_cloud_storage_for_currents.md

BD-3118: Add permission for Google Cloud Storage

---

_docs/_hidden/compliance/home.md
_docs/_hidden/compliance/webhook_channel.md
_docs/_hidden/compliance/whatsapp.md

> New compliance documentation for webhooks
Closes #**BD-3117**
---

BD-3117: Compliance documentation for webhooks

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

> Clarify "calendar days" for Delay step based on feedback from product question
---

PQ-2235: Clarify "calendar days"

---

Rakefile

Fix missing language build step
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Add language build

---

_docs/_developer_guide/platform_integration_guides/web/initial_sdk_setup.md

BD-3119: Fix links

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Add subheadings for FAQ

---

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md

BD-3122: Semicolon to colon

---

_docs/_user_guide/introduction.md

Update link for Manage your account tile

---

_docs/_api/api_limits.md

Adding batch request example to `api_limits.md`. Fixes #7397.
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Adding batch request example to api_limits.md

---

_docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md

BD-3134: Remove sentence

---

_docs/_partners/data_and_infrastructure_agility/cloud_storage/microsoft_azure_blob_storage_for_currents.md

BD-3133: Update Azure storage requirements

---

_docs/_help/release_notes/2024.md

Update April icons

---

_docs/_user_guide/message_building_by_channel/sms/best_practices.md
_docs/_user_guide/message_building_by_channel/sms/best_practices/best_practices.md
_docs/_user_guide/privacy_portal.md

BD-3125: SMS/MMS best practices

---

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md

BD-3139: Update "Meta Resources" with recent changes

---

assets/js/documents.js

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

fix scroll not registering

---

_docs/_api/basics.md
_docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md

BD-3113: Clarify detail on API keys and deleted user

---

_data/i18n.yml
_includes/html_include.html
_includes/wovn.html
assets/js/documents.js

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Remove wovn from docs

---

assets/js/documents.js

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fix default lang path

---

_docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md

BD-3131: Fix rate limit info

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md

BD-3128: SMS and WhatsApp Liquid properties for Canvas Flow GA

---

_docs/_api/endpoints/catalogs.md
_docs/_api/home.md
_includes/rate_limits.md

Fix catalog selection links

---

_docs/_docs_pages/index.md
_lang/ja/_api/home.md
_lang/ja/_docs_pages/index.md
_lang/ja/_user_guide/introduction.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Add japanese main pages

---

_plugins/alloy_partner.rb

Allow a different partner url for japanese
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Allow jp partners url

---

_lang/ja/_api/home.md

fix the description for the api page
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Fix api description

---

_docs/_user_guide/message_building_by_channel/whatsapp/overview.md

BD-3141: Update external WhatsApp links

---

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md

BD-3124: Clarify time zone as UTC

---

_docs/_user_guide/administrative/access_braze/single_sign_on/set_up.md

BD-3137: Add EU domain detail

---

_docs/_api/objects_filters/schedule_object.md

BD-3148: Clarify details for schedule object

---

_docs/_help/help_articles/campaigns_and_canvas/more_people_in_control_group.md
_docs/_hidden/misc_reference/x-in-y-behavior.md
_docs/_hidden/private_betas/ai_step.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/treasuredata.md
_docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/adobe.md
_docs/_partners/data_and_infrastructure_agility/support/pypestream.md
_docs/_partners/message_orchestration/channel_extensions/loyalty/friendbuy.md
_docs/_partners/message_orchestration/channel_extensions/loyalty/voucherify/voucherify_fetching_data_through_braze_connected_content.md
_docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
_docs/_partners/message_personalization/dynamic_content/amazon_personalize/amazon_personalize.md
_docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md
_docs/_user_guide/data_and_analytics/custom_data/events.md
_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md
_docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
_docs/_user_guide/getting_started/users_segments.md
_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md
_docs/_user_guide/message_building_by_channel/sms/sms_setup/user_data_migration.md
_docs/_user_guide/onboarding_faq.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
_docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md
_lang/ja/_user_guide/data_and_analytics/custom_data/events.md

> Transitioned "example" headers to include "use case" when appropriate
Closes #**BD-3070**

BD-3070 pt1 changing example to use case when appropriate

---

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md

BD-2759 Add canvas_entry_properties use cases

---

_docs/_help/help_articles/api/attribute_name_id_across_sources.md

> I'm updating the mappings here because they were wrong and we got product requests around them 
Closes #MOPS-3125
- [ X] No
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at …

[MOPS-3125] Update docs with correct fields

---

_docs/_partners/canvas_steps/facebook_audience_sync.md

BD-3129: Update FAQ

---

_lang/ja/_help/home.md
_lang/ja/_partners/home.md

Update help and partners pages for ja
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Update ja home pages for help and partners

---

_includes/header.html

Simple change to drop down from jp to ja
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Change jp to ja

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/content-cards_in_canvas.md
_docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md

BD-3149 Update Content Card expiration docs

---

_docs/_hidden/pricing/message_credits_delta_a3sy.md
_docs/_hidden/pricing/message_credits_gamma_0dhr.md
_docs/_hidden/pricing/message_credits_sigma_pow2.md
_docs/_hidden/pricing/message_credits_theta_d9kw.md

> Relates to #7301
Closes #**BD-3155**
---

BD-3155: Update Message Credit pages - MERGE 6/10

---

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/search_campaigns.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Small edit for translation clarity

---

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md

Update copying campaigns based on translation feedback

---

_docs/_hidden/pricing/message_credits_lambda_k5gh.md

Update table for Message Credits

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/blueconic.md

BD-3168 Update BlueConic docs with credentials info

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

BD-3163: Add list-unsubscribe source for subscription event

---

_docs/_user_guide/privacy_portal.md

BD-3169: Add tiles to Privacy Portal

---

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md

> I'm changing Connected Content `no_cache` docs to help customers understand that even if the `no_cache` option is used in Connected Content, we will still cache the response if the host is internal to Braze. This will help to avoid any possible confusion if customers wonder why Braze-to-Braze Connected Content GET requests are not being cached despite using the `no_cache` option.
Closes [MP-4766](https://jira.braze.com/browse/MP-4766)
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …

[MP-4766] Update `no_cache` docs

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
_docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md

Add Big Query and Data bricks SQL commands
Closes DLK-1665
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

[DLK-1665] Add Big Query and Data bricks SQL commands

---

_docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md

BD-3172 Update AI item recommendation event property requirements

---

_docs/_hidden/private_betas/pick_up_where_you_left_off.md

Add EA banner for PUWYLO

---

_docs/_hidden/private_betas/field_level_encryption.md

email_encrypted not encrypted_email

---

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md

Message Archiving to message archiving

---

_docs/_user_guide/sage_ai/recommendations/ai_item_recommendations.md

BD-3172 Fix AI item recommendations nested properties

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

BD-3130: Clarify two messages promotion codes

---

_docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md

BD-3176 WhatsApp supports more than one subscription group per workspace

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/faqs.md

Adding troubleshooting steps for support emails and test connection issues.
Closes DLK-1793
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

[DLK-1793] Updating troubleshooting tips for test connection

---

_docs/_api/use_cases.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Update header for consistency

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/attribute_triggers.md

BD-3150: Add alert for subscription status

---

_docs/_user_guide/data_and_analytics/reporting/engagement_reports.md

BD-3171: Add detail on deleting Canvas step and Engagement Reports

---

_docs/_hidden/other/support_contact.md
_layouts/api_glossary.html
_layouts/self_help.html
assets/css/_404.scss
assets/css/_bottom_nav.scss
assets/css/_content.scss
assets/css/_dev_guide.scss
assets/css/_doc_guide.scss
assets/css/_footer.scss
assets/css/_glossary_page.scss
assets/css/_partner_page.scss
assets/css/_self_help.scss
assets/css/_toc.scss
assets/css/_user_guide.scss
assets/css/swipercustom.scss
assets/js/documents.js

Brand refresh tweaks

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/user_update.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Remove extraneous line

---

_docs/_api/api_campaigns.md
_docs/_user_guide/administrative/app_settings/email_settings.md

BD-3183 Update email settings warning

---

_docs/_hidden/private_betas/post_user_track_synchronous.md

BD-3167: Track user sync beta - MERGE 6/18

---

_docs/_hidden/other/documentation_request.md

Request page changes

---

_docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md

For the changes made here: https://github.com/Appboy/platform/pull/79536
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Update docs for test connectors

---

_docs/_user_guide/administrative/app_settings/subscription_and_usage.md

> Added headers and navigation details to the workspace tables docs.
Closes #**BD-3120**

BD-3120 Add clarity to billing tables

---

_docs/_hidden/private_betas/field_level_encryption.md

Adding details and links for Field Level Encryption
---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details> …

Tiffanyjlin patch 2

---

_docs/_help/release_notes/deprecations.md
_docs/_help/release_notes/deprecations/shopify_checkout.md

BD-3184 Shopify checkout.liquid deprecation

---

_docs/_help/release_notes/deprecations/shopify_checkout.md

Fix indents on bullets and javascript

[PP][NOTIX] fix indents on page

---

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md

BD-3179: Add locales in messaging to strategies

---

_docs/_hidden/private_betas/idle_campaigns.md

Edits to idle campaigns and Canvases

---

_docs/_help/support.md

BD-3198 Add user sample size to support doc

---

_docs/_user_guide/data_and_analytics/custom_data/purchase_events.md
_docs/_user_guide/data_and_analytics/reporting/revenue_report.md

BD-3204 Update revenue metric definitions

---

_docs/_api/api_limits.md
_includes/rate_limits.md

BD-3203: Fix rate limit

---

_docs/_help/help_articles/campaigns_and_canvas.md
_docs/_help/help_articles/campaigns_and_canvas/canvas_not_sending.md
_docs/_help/help_articles/campaigns_and_canvas/know_before_send.md
_docs/_help/help_articles/campaigns_and_canvas/not_triggering.md
_docs/_user_guide/engagement_tools/campaigns/faq.md
_docs/_user_guide/engagement_tools/canvas/faqs.md

BD-3196: Add troubleshooting tip for diagnostic logs

---

_docs/_api/basics.md

BD-3205: Update creating API key steps

---

_docs/_developer_guide/platform_integration_guides/web/analytics/tracking_custom_events.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fix link not rendering properly

---

_docs/_developer_guide/platform_integration_guides/web/analytics/setting_custom_attributes.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Update best practices links

---

_docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md

BD-3201: Add sending info steps to HTML email article

---

_docs/_api/endpoints/user_data/post_users_merge.md

BD-3123: Add considerations section for merge behavior

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_user_identity.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br> …

Fix blank link reference

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

> Closes https://github.com/braze-inc/braze-docs/pull/7597
---

Add back callout for Liquid in catalog

---

_docs/_developer_guide/platform_integration_guides/tv_and_ott.md

* add feature flags to ott
* add vision pro to ott

add feature flags to ott

---

_docs/_developer_guide/platform_integration_guides/react_native/content_cards.md

This pull request updates the [React Native content card integration guide](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/content_cards/#customization). 
Specifically, it enhances the documentation for the `getContentCards()` and `requestContentCardsRefresh()` SDK methods. This as been an area of confusion for myself and my team, and I believe describing their behaviour in more detail will prevent confusion among _future_ Braze React Native SDK consumers.
There is no corresponding issue for this pull request.
---
<details>
<br>
</details>
<details>
<br>
- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH …

docs(react-native): clarify `getContentCards()` vs. `requestContentCardsRefresh()`

---

_docs/_developer_guide/platform_integration_guides/react_native/content_cards.md

This pull request updates the React Native SDK documentation to reference and explain 'control' cards. Specifically:
- It identifies 'control' cards as a distinct type.
- It describes the unique properties of 'control' cards.
- It links out to the Android and iOS 'control' card documentation.
Myself and my team have found 'control' cards to be tricky. My hope is that this pull request makes it easier for future SDK consumers to understand and accommodate 'control' cards in their work.
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …

docs(react-native): clarify 'control card' impression logging

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/targeting_users.md
_docs/_user_guide/engagement_tools/segments/creating_a_segment.md

BD-3197: Clarify audience stats and reachable users

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

> Fixes an inadvertent revert 
---

Add list-unsubscribe for property details

---

_docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md

> Add note on one-click list-unsubscribe for Transactional Email Campaigns
Closes #**BD-3126**
---

BD-3126: Add note on one-click list-unsubscribe

---

_docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md

Revised edit for transactional email and one-click list-unsub

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md

BD-3212: Add more details for action-based delivery FAQ

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md

BD-3191: Clarify how to add a background image

---

_docs/_developer_guide/platform_integration_guides/xamarin/analytics.md
_docs/_developer_guide/platform_integration_guides/xamarin/changelog.md
_docs/_developer_guide/platform_integration_guides/xamarin/content_cards.md
_docs/_developer_guide/platform_integration_guides/xamarin/inapp_messages.md
_docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md
_docs/_developer_guide/platform_integration_guides/xamarin/news_feed.md
_docs/_developer_guide/platform_integration_guides/xamarin/push_notifications.md

https://jira.braze.com/browse/SDK-4885
> I'm updating the Xamarin SDK iOS documentation because [since version 4.0.0](https://github.com/braze-inc/braze-xamarin-sdk/releases/tag/4.0.0), the SDK uses the Swift SDK binding. Updated the code snippets and links to reference the new convention and Sample Apps. Also added additional information to make the documentation more descriptive and updated Android information, where necessary.
Closes [**#SDK-4885**](https://jira.braze.com/browse/SDK-4885)
---
<details>
<br>
</details>
<details>
<br>
- [Image Style …

[SDK-4885] Update Xamarin documentation for Swift + MAUI

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes/migrating_from_data_feeds.md

BD-3208: Migrating from data feeds to promotion codes

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md

BD-3220: Update shopify_created_order payload and add Liquid example payload

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md

Revert general Shopify back-in-stock notif.
- N/A
- N/A …

Revert general Shopify back-in-stock notif

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

The JSON in this PR was missing some "s -> https://github.com/braze-inc/braze-docs/pull/7617

Fixing the JSON in Currents docs

---

_docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/troubleshooting.md

Adding some troubleshooting docs for a common error encountered by customers when integrating Braze Swift SDK with third-party network logging libraries.
Quick link to doc: https://braze-docs-fq0ls6g5u-braze.vercel.app/docs/developer_guide/platform_integration_guides/swift/in-app_messaging/troubleshooting/?tab=swift#troubleshooting-asset-loading
---
<details>
<br>
</details>
<details>
<br>
- [Styling …

Add troubleshooting docs for Swift SDK IAM networking

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md

Removing EA alert
Fixes **#BD-3231**
- N/A …

BD-3231 Multi-page IAMs GA

---

_docs/_hidden/private_betas/link_shortening.md

My PR...
Fixes **#BD-3228**
- N/A
- If my …

BD-3228 Delegating your custom domain

---

_docs/_hidden/private_betas/field_level_encryption.md

Must add `email_encrypted` when updating existing users who don't have emails yet
- Closes [BD-3233](https://jira.braze.com/browse/BD-3233)
- N/A …

BD-3233: Clarify email_encrypted detail

---

_docs/_hidden/misc_reference/scim_api_appendix.md

Adds Launch Content Block permission to workspace permission strings
- Closes [BD-3226](https://jira.braze.com/browse/BD-3226)
- N/A …

BD-3226: Add Launch Content Block permission

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md

Add other method to remove custom attributes
- Closes [BD-3223](https://jira.braze.com/browse/BD-3223) 
- N/A …

BD-3223: Add method for removing custom attribute

---

_includes/feedback.html
assets/js/feedback.js

Add article and nav title to feedback response

Add article and nav title to feedback

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Add more clarity for promotion codes doc
- Closes [BD-3219](https://jira.braze.com/browse/BD-3219) and [BD-3234](https://jira.braze.com/browse/BD-3234)
- N/A …

BD-3219 and BD-3234: Promotion codes edits

---

_docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md

---
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
</details>
<details>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, …

[SDK-5061] Add push received offering to subscribeToUpdates API and a new delegate method

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Clarify sentence to include single-channel sends
- N/A
- N/A …

Add single-channel sends

---

_docs/_api/endpoints/user_data/post_users_merge.md

We can now merge by using phone numbers.
- N/A
#BD-3243 …

BD-3243 Update POST users merge to now include phone numbers

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

Removing "USD" from the sample CSV file contents.
#BD-3244
- N/A …

BD-3244 Correct CSV file sample for catalog creation

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md

Add a section explaining the differences among teams, permission sets, and roles
Fixes #BD-3232
- N/A …

BD-3232 Update Teams with explanations

---

_docs/_user_guide/data_and_analytics/report_metrics.md
_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
_includes/campaign_analytics.md

Add Total Clicks definitions and calculations where missing
[#BD-3235](https://jira.braze.com/browse/BD-3235)
- N/A …

BD-3235 Add SMS Total Clicks info

---

_docs/_user_guide/sage_ai/generative_ai.md
_docs/_user_guide/sage_ai/generative_ai/ai_liquid.md
_docs/_user_guide/sage_ai/generative_ai/ai_liquid/ai_liquid_prompts.md

Closes #**BD-3164** & **BD-3165**

BD-3164, BD-3165 - AI Liquid Assistant overview and prompt guide

---

_plugins/urlnavmenu_generator.rb

Fix redirect_to layout with language issue

fix layout redirect url

---

assets/js/documents.js
assets/js/toc.js
vercel.json

Fix ja table of content nav

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/back_in_stock_notifications.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/price_drop_notifications.md

Updates price drop docs to look like back in stock. In particular, added a example custom event for subscriptions.
- N/A
- N/A …

update price drop docs to look like back in stock

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

Removes a note about coming soon Canvas Flow names
- Closes [BD-3255](https://jira.braze.com/browse/BD-3255)
- N/A …

BD-3255: Remove note about Canvas Flow names coming soon

---

_docs/_developer_guide/platform_wide/sdk_authentication.md

rename appboy to braze in sdk_authentication.md `Register a callback function for invalid tokens`
<!--
Thank you for contributing to Braze Docs! Read comments like this one for help filling out your Pull Request (PR). For more information about contributing to Braze Docs, see:
braze.com/docs/contributing/.
<!-- In one or two sentences, describe your changes. 
My PR...
<!--
For related GitHub issues and features, add "Fixes #ISSUE_NUMBER".
For Jira tickets, add the ticket number and a link to the ticket, like: [BD-NUMBER](LINK).
- N/A
<!-- If this PR is related to an upcoming Braze feature, add the date below, like: 15 May 2024. 
- N/A
<!-- After you've filled out the previous sections, select "Create Draft Pull Request", then review your PR before filling out the following checklist. 
- I …

rename appboy to braze in sdk_authentication.md `Register a callback function for invalid tokens`

---

_docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md

#7450 wasn't ready to be merged. This PR reverts this file to its original state pre-merge commit.
- N/A
- N/A …

Reverting SDK-5061 doc updates

---

_docs/_hidden/other/user_archival.md
_docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md

Add section about treatment sample group to the User Archival page
#BD-3250
- N/A …

BD-3250 Add treatment sample group to User Archival

---

_docs/_user_guide/message_building_by_channel/email/templates/faq.md

Add an FAQ to link aliasing about using Liquid conditional logic in HTML anchor tags
#BD-3252
- N/A …

BD-3252 Add FAQ to Link aliasing

---

_docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md

My PR adds the generate/refresh icon to the docs that explain how to generate a schema:
- [BD-3263](https://jira.braze.com/browse/BD-3263)
- N/A …

BD-3263 Add the icon for generating a nested event property schema.

---

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/data_retention.md
_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/faqs.md

Adds a new page for Snowflake data retention
#BD-3260
- N/A …

BD-3260 Snowflake Data Retention

---

_docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md

Updates the wording for size discrepancies between Global Control Groups and treatment sample groups. 
#BD-3052
- N/A …

BD-3050-2 Update wording for user group sizes

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/connected_sources.md
_docs/_user_guide/engagement_tools/segments/segment_extension/cdi_segments.md

Update CDI segments for GA

---

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md

My PR...
- Closes [BD-3249](https://jira.braze.com/browse/BD-3249)
- N/A …

BD-3249: Add tip about record availability for Deliverability Center

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

Add clarity for "View Usage Data" permission
- Closes [BD-3259](https://jira.braze.com/browse/BD-3259)
- N/A …

BD-3259: Add clarity for "View Usage Data" permission

---

_docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md

Removes USERS_CANVAS_ABORT_SHARED and USERS_CAMPAIGNS_ABORT_SHARED SQL tables
- Closes [BD-3267](https://jira.braze.com/browse/BD-3267)
- N/A …

BD-3267: Remove USERS_CANVAS_ABORT_SHARED and USERS_CAMPAIGNS_ABORT_SHARED

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md

Updates "Abandoned Card" to "Abandoned Cart"
- Closes [BD-3268](https://jira.braze.com/browse/BD-3268)
- N/A …

BD-3268: Update to "Abandoned Cart"

---

_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md

Adds clarification for TXT record
- Closes [BD-3225](https://jira.braze.com/browse/BD-3225)
- N/A …

BD-3225: Clarify TXT record

---

_docs/_api/endpoints/export/custom_attributes/get_custom_attributes.md
_docs/_api/endpoints/export/custom_events/get_custom_events_data.md

Removes EA banners
- Closes [BD-3262](https://jira.braze.com/browse/BD-3262)
- N/A …

BD-3262: Export custom events and Export custom attributes endpoints GA - MERGE 7/18

---

_docs/_hidden/other/user_archival.md

Adds an alert that states both inactive and dormant users get archived. Screenshot below:
I don't know if it is strange that this is before the definitions of these groups of users. I tried it below the dormant users section as well, but I think it'd be more likely to be missed sitting there.
- N/A
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redi …

add alert that both inactive and dormant users get archived

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

Add back list-unsubscribe property detail

---

_docs/_user_guide/engagement_tools/segments.md

Add an "About" section to the segments landing page
#BD-3251
- N/A …

BD-3251 About segments section

---

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md

Updates details for test IAMs
- Closes [BD-3272](https://jira.braze.com/browse/BD-3272)
- N/A …

BD-3272: Updates details for test IAMs

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Update example and minor edits
- N/A
- N/A …

Update example and minor edits

---

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md

Add a note to Link Aliasing about using ampersands when templating in links that have parameters.
#BD-3269
- N/A …

BD-3269 Add ampersand link to link aliasing

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

Add alert note that coupon code buttons currently aren't supported
#BD-3254
- N/A …

BD-3254 WhatsApp templates don't support coupon code buttons

---

_docs/_user_guide/personalization_and_dynamic_content.md
_docs/_user_guide/personalization_and_dynamic_content/canvas_persistent_entry_properties.md

My PR...
- Closes [BD-3277](https://jira.braze.com/browse/BD-3277)
- N/A …

BD-3277: Update links

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/message_step.md

My PR...
#BD-3276
- N/A
- If my PR is …

BD-3276 Update SMS Liquid functionality

---

_docs/_api/endpoints/user_data/post_user_delete.md
_docs/_api/endpoints/user_data/post_user_identify.md

https://jira.braze.com/browse/CO-2780

[CO-2780] Updated users/identify users/delete document to include email as identifier

---

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_for_currents.md

Flagged in #ask-docs, this PR fixes a typo in the word "appboy" in an example API call
- N/A
- N/A …

Remove extra P from Appboy

---

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md
_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md

Added documentation to the Snowflake Data Sharing docs about our data retention policies, and what happens when we archive event data.
- [DLK-191](https://jira.braze.com/browse/DLK-191)
- August 20th 2024 …

[DLK-200] Add documentation about data retention policies - Merge 7/23

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2024.md
_docs/_help/release_notes/2024/7_23_24.md

I'm still not very confident of what section each blurb should go under, but these are all the blurbs for the release 👍🏽  I will leave a comment with the list of deployment bodies below so you simply have to copy+paste.
- N/A
- N/A
- If I updated or replaced an image, I did …

July 23, 2024 release notes

---

_docs/_api/endpoints/export/user_data/post_users_segment.md

My PR...
- Closes [BD-3292](https://jira.braze.com/browse/BD-3292)
- N/A …

BD-3292: Remove mentions of "Beginning December" and "Beginning April"

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

Add use cases to catalogs and an explanation about how it relates/differs to Liquid
#BD-3286
- N/A …

BD-3286 Catalog use cases and explanation

---

_docs/_hidden/private_betas/canvas_templates.md

Add note for Canvas templates

---

_docs/_hidden/private_betas/canvas_templates.md

Reverts braze-inc/braze-docs#7754 (fixed this bug)

Revert "Add note for Canvas templates"

---

assets/js/documents.js

Fix ja -> en not working on some pages.

fix ja switcher

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md

My PR...
#BD-3278
- N/A
- If my PR is …

BD-3278 Add note about Liquid  filter

---

_docs/_user_guide/message_building_by_channel/sms/mms/create.md

My PR...
#BD-3287
- N/A
- If my PR is …

BD-3287 Update MMS image specs

---

_docs/_user_guide/sage_ai/generative_ai.md

My PR...
#BD-3279
- N/A
- If my PR is …

BD-3279 Add tiles to Generative AI

---

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md

Updates partner links at the end of article
- Closes [BD-3305](https://jira.braze.com/browse/BD-3305)
- N/A …

BD-3305: Update links

---

_docs/_user_guide/administrative/app_settings/workspaces.md

My PR...
- Closes #7712
- N/A
- If my PR …

Edits from voice team meeting

---

_docs/_user_guide/administrative/app_settings/workspaces.md

Adds a closing bracket to tip alert
- N/A
- N/A …

Add closing bracket to tip alert

---

_docs/_hidden/private_betas/canvas_templates.md

Adds an FAQ section
- Closes [BD-3301](https://jira.braze.com/browse/BD-3301)
- N/A …

BD-3301: FAQ for Canvas templates

---

_docs/_user_guide/administrative/access_braze/navigation.md

Update year for KO deprecation to 2025

---

_includes/archive/short_and_long_codes.md

Part 1 of update: Changed the information structure
#BD-3064
- N/A …

BD-3064 Update types of phone numbers - Part 1

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

Update permission name
#BD-3313
- N/A
- If …

BD-3313 Update Currents permissions

---

_docs/_help/help_articles/push/push_unsubscribes.md

Adds an important alert for data point consumption 
- Closes [BD-3296](https://jira.braze.com/browse/BD-3296)
- N/A …

BD-3296: Add note on consuming data points

---

_docs/_api/endpoints/scim/delete_existing_dashboard_user.md
_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

"Manage Users" has been updated to "Company Users" in the braze ui, so this PR fixes it in the docs where applicable.
- [BD-3320](https://jira.braze.com/browse/BD-3320)
- N/A …

Change "Manage Users" to "Company Users"

---

_docs/_user_guide/message_building_by_channel/email/best_practices.md

Fix email tile

---

_docs/_user_guide/engagement_tools/segments/sql_segments/catalog_segments.md

My PR...
#BD-3299
- N/A
- If my PR is …

BD-3299 Update catalog segments use cases

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

My PR...
#BD-3321
- N/A
- If my PR is …

BD-3321 Update security event download

---

assets/js/documents.js

Fix issue with punctuation error causing js error on the page.

Fix punctuation issue

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

My PR...
- Closes [BD-3327](https://jira.braze.com/browse/BD-3327)
- N/A …

BD-3327: Support for templates in a catalog name

---

_docs/_user_guide/message_building_by_channel/push/about.md

This page is missing a link.
- N/A
- N/A
- …

Quick fix: Missing link

---

_docs/_developer_guide/platform_integration_guides/xamarin/initial_sdk_setup.md

Fixing a missing link in the Xamarin set up doc.
- N/A
- N/A …

Quick Fix: Missing Link for Xamarin

---

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md

Some notes for touching up the User Import docs to align with our brand tone and voice guidelines.
- N/A
- N/A …

User Import notes for brand voice

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

Updates the permissions doc to clarify what only a company admin can do, as described by Emily Fong.
See [Slack thread](https://brazetechnology.slack.com/archives/C02BLSEKCP9/p1686155911924429) for details 
- N/A
- If I updated or replaced an image, I did not remove the …

BD-2176: Add what only admins can do

---

_docs/_api/endpoints/export/canvas/get_canvas_details.md

My PR...
- Closes [BD-3056](https://jira.braze.com/browse/BD-3056)
- N/A …

BD-3056: Add response example for messages by channel

---

_includes/archive/short_and_long_codes.md

My PR...
#BD-3335
- N/A
- If my PR is …

BD-3335 Update alphanumeric sender IDs

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md

My PR...
#BD-3322
- N/A
- If my PR is …

BD-3322 Update DnD dark mode FAQ

---

_docs/_contributing/yaml_front_matter/page_layouts.md

The Page layouts section of the contributing docs is missing some information on the `blank_config` tag. This only described half the behavior, filled it in with the remaining context on using `config_only`.
- N/A
- N/A
- If I updated or replaced an image, I did not remove …

Clarify behavior of config_only

---

_docs/_user_guide/engagement_tools/campaigns/faq.md

My PR...
- Closes [BD-3288](https://jira.braze.com/browse/BD-3288)
- N/A …

BD-3288: Add FAQ for scheduled campaign

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md

Example success request and notice explanation

---

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/video.md

My PR...
- Closes [BD-3274](https://jira.braze.com/browse/BD-3274)
- N/A …

BD-3274: Clarify iOS considerations for IAM

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md

My PR...
- Closes [BD-3144](https://jira.braze.com/browse/BD-3144)
- N/A …

BD-3144: Clarify SQL example and minor edits

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md

My PR...
- Closes [BD-3215](https://jira.braze.com/browse/BD-3215)
- N/A …

BD-3215: Edits to Creating a catalog article

---

_docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
_docs/_developer_guide/platform_integration_guides/swift/content_cards/integration.md

The disclaimer note at the bottom of [Android Content Cards: Logging impressions, clicks, and dismissals](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/content_cards/implementation_guide/#logging-impressions-clicks-and-dismissals) is not present on the Swift docs and we've had reports of users running into issues because of this. Additionally, it _used_ to be present on the [iOS legacy docs](https://www.braze.com/docs/developer_guide/platform_integration_guides/legacy_sdks/ios/content_cards/implementation_guide):
> For a control variant Content Card, a custom object should still be instantiated, and UI logic should set the object’s corresponding view as hidden. The object can then log an impression to inform our analytics of when a user would have seen the …

[BD-2809] Adding control variant alert to CC docs

---

_docs/_hidden/private_betas/field_level_encryption.md

My PR...
- Closes [BD-3330](https://jira.braze.com/browse/BD-3330)
- N/A …

BD-3330: Add FAQ for field-level encryption

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md

My PR...
- Closes [BD-3010](https://jira.braze.com/browse/BD-3010)
- N/A …

BD-3010: Clarify Redshift URL

---

_includes/campaign_analytics.md

My PR...
[#BD-3342](https://jira.braze.com/browse/BD-3342)
- N/A …

BD-3342 Update estimated real open rate

---

_docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md

Two parts:
- Re-applies this [previously-reverted PR](https://github.com/braze-inc/braze-docs/pull/7450) by Jackson ([see commit](https://github.com/braze-inc/braze-docs/commit/fd6599e227592e540ae2bc09b1592579e0ef910a))
- Makes slight tweaks on top of Jackson's original changes ([see all commits after first one](https://github.com/braze-inc/braze-docs/compare/fd6599e...sdk-4699-push-received-breakingUpdates))
- https://github.com/braze-inc/braze-docs/pull/7450
- https://github.com/braze-inc/swift-sdk/pull/733
- [BD-3348](https://jira.braze.com/browse/BD-3348)
- Yes, after the upcoming Swift SDK 10.0.0 release
- My style and voice follows the [Braze Style …

[SDK-4699] Subscribe to "Push received" event, with upcoming breaking updates

---

_docs/_user_guide/administrative/access_braze/global_search.md

Add Content Blocks to search list
#BD-3341
- N/A …

BD-3341 Add Content Blocks to search list

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

My PR...
#BD-3329
- N/A
- If my PR is …

BD-3329 Update FAQ about empty promotion codes

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/sync_catalogs_data.md

My PR...
- Closes [BD-3143](https://jira.braze.com/browse/BD-3143)
- N/A …

BD-3143: Add option for creating catalog for CDI

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md
_docs/_user_guide/engagement_tools/canvas/testing_canvases/sending_test_canvases.md

My PR...
- Closes [BD-3207](https://jira.braze.com/browse/BD-3207)
- N/A …

BD-3207: Update articles for search relevancy

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md

My PR...
#BD-3356
- N/A
- If my PR is …

BD-3356 Add a generic sample size calculator to A/B testing

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md

My PR...
- Closes [BD-3353](https://jira.braze.com/browse/BD-3353)
- N/A …

BD-3353: Clarify triggers for Action Paths step

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

My PR...
- Closes [BD-3361](https://jira.braze.com/browse/BD-3361)
- N/A …

BD-3361: Fix typo

---

_docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md

My PR...
#BD-3336
- N/A
- If my PR is …

BD-3336 Currents IP Allowlisting

---

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md

Minor edits to Creating a webhook

---

_docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md

My PR...
[#BD-3344
](https://jira.braze.com/browse/BD-3344)
- N/A …

BD-3344 Remove video from Amplitude cohort import

---

_docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md

My PR...
- Closes [BD-3363](https://jira.braze.com/browse/BD-3363)
- N/A …

BD-3363: Add 6-month detail for Email Insights dashboard

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md

Minor edits to In-app message in Canvas

---

_docs/_hidden/private_betas/campaign_autosave.md

BD-3366: Add warning to autosave campaigns

---

_docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md

BD-3365: Clarify Canvas entry properties and event properties support

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

My PR...
[#BD-3370](https://jira.braze.com/browse/BD-3370)
- N/A …

BD-3370 Replace missing user permission

---

_docs/_hidden/private_betas/campaign_autosave.md

Wording fix: "composer" to "editor"

---

_docs/_developer_guide/platform_integration_guides/roku/initial_sdk_setup.md

Adds an alert tip to the Roku integration doc that includes a link to our sample Roku app: TorchieTV.
- N/A
- N/A …

[BD-2696] Update Roku docs with sample app

---

_includes/campaign_analytics.md

My PR...
[#BD-3372](https://jira.braze.com/browse/BD-3372)
- N/A …

BD-3372 Add 'Rate' column for WhatsApp metrics

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md

My PR...
[#BD-3373](https://jira.braze.com/browse/BD-3373)
- N/A …

BD-3373 Add A/B section to rate limiting

---

_docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md

BD-3375: Fix typo

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md

My PR...
[#BD-3374](https://jira.braze.com/browse/BD-3374)
- N/A …

BD-3374 Add A/B section to multivariate campaign

---

_docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
_docs/_user_guide/message_building_by_channel/email/preference_center/overview.md
_includes/preference_center_warning.md

BD-3371: Add preference center browser alert

---

_docs/_help/release_notes/deprecations/shopify_checkout.md
_docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md

My PR...
- Closes [BD-3376](https://jira.braze.com/browse/BD-3376)
- August 20, 2024 …

BD-3376: Bulk merging GA

---

_docs/_user_guide/message_building_by_channel/content_cards/create.md

We've updated Content Cards to base re-eligibility strictly on "send time", and not based on impression time. This does not apply to the new "at first impression" cards.
- [BD-2880](https://jira.braze.com/browse/BD-2880)
- N/A …

[BD-2880] Content Cards now base re-eligibilty on send time

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/preview_user_paths.md

My PR...
- Closes [BD-3360](https://jira.braze.com/browse/BD-3360)
- N/A …

BD-3360: Add Liquid note for Previewing user paths

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md

Removes EA banner for data export
- Closes [BD-3381](https://jira.braze.com/browse/BD-3381)
- N/A …

BD-3381: Data export GA

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/mParticle/mparticle_for_currents.md

mParticle is unique in that it has workspace-level credentials and app-level credentials. This PR explains the difference.
mParticle is unique in that it has workspace-level credentials and app-level credentials. I'd like to clarify how they're used:
App-specific events belong to exactly one app, and are sent if and only if credentials are provided for that app. Non-app-specific event types are sent if and only if credentials are provided for the app group.
So if I have one app for iOS and another for Android and another for Web, the events will be disjoint, which means that if I provide the same mP creds for all 3 then the one mP bucket will receive data for all of my apps, with no duplication.
mP has them separated due to their setup where basically they ingest a "feed" based on an app …

[BD-2985] Clarify the different mParticle credentials

---

_docs/_user_guide/personalization_and_dynamic_content/liquid.md
_docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md
_docs/_user_guide/personalization_and_dynamic_content/liquid/tutorials.md
assets/css/_content.scss

Introduce Liquid tutorials
#BD-3071
- N/A …

BD-3071 Liquid tutorials

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

Removed REST API serialization from Currents event glossaries
REST API  is for partners, was causing confusion for customers
- N/A
- [X ] I confirm that my PR meets the following: …

Removed REST API serialization from Currents event glossaries

---

_docs/_user_guide/data_and_analytics/export_braze_data.md
_docs/_user_guide/data_and_analytics/export_braze_data/export_news_feed_data.md

My PR...
[#BD-3386](https://jira.braze.com/browse/BD-3386)
- N/A …

BD-3386 Hide News Feed Data Export article

---

_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/android_tv_push.md

Remove Fire TV push screenshot
#BD-3315
- N/A …

BD-3315 Remove Fire TV push screenshot

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

This reverts commit 6fdac9aadd5183521b197fd8d988c7d20b075822.
- [BD-3389](https://jira.braze.com/browse/BD-3389)
- N/A …

[BD-3389] Revert "Update event documentation"

---

_docs/_user_guide/message_building_by_channel/line/line_setup.md

Adding a user ID reconciliation method to the docs
#BD-3392
- N/A …

BD-3392 Add LINE Login to User ID Reconciliation

---

_docs/_user_guide/administrative/privacy.md

Fix Administrative > Privacy landing page icon

---

_docs/_user_guide/message_building_by_channel/line/line_users.md

Make LINE Users doc hidden

---

_docs/_developer_guide/platform_integration_guides/web/cookies_and_storage.md

Updates the web SDK cookie expiration date to reflect the current value
[FF-589](https://jira.braze.com/browse/FF-589)

[FF-589] - Update cookies_and_storage.md

---

_docs/_user_guide/message_building_by_channel/line.md

Fix LINE tile

---

_docs/_hidden/private_betas/multiple_stores.md

My PR...
[#BD-3393](https://jira.braze.com/browse/BD-3393)
- N/A …

BD-3393 Add note about multiple brands to Shopify multiple stores

---

_docs/_developer_guide/platform_integration_guides/react_native/push_notifications.md

My PR updates the React Native SDK documentation with updated information about how push received events are processed on iOS. This follows the React Native SDK 12.0.0 release, which introduces the new event type from the recent Swift SDK 10.0.0 version. …

Update React Native docs with iOS push received events

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/setting_default_values.md

My PR...
#BD-3206
- N/A
- If my PR is …

BD-3206 Add data type use cases to default values

---

_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md

My PR...
- Closes [BD-3396](https://jira.braze.com/browse/BD-3396)
- N/A …

BD-3396: Clarify Connected Content caching

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md

Hide partner doc

---

_docs/_user_guide/data_and_analytics/analytics/conversions_dashboard.md
_docs/_user_guide/data_and_analytics/analytics/deliverability_center.md
_docs/_user_guide/data_and_analytics/analytics/email_performance_dashboard.md
_docs/_user_guide/data_and_analytics/analytics/home_dashboard.md

My PR...
[#BD-3398](https://jira.braze.com/browse/BD-3398)
- N/A …

BD-3398 Apply template standards to Your Analytics Dashboards

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md

My PR...
- Closes [BD-3402](https://jira.braze.com/browse/BD-3402)
- N/A …

BD-3402: Add remove attribute detail

---

_docs/_hidden/private_betas/canvas_triggered_iams.md

Add EA banner

---

_docs/_api/endpoints/export/user_data/post_users_identifier.md
_docs/_api/endpoints/export/user_data/post_users_segment.md

My PR...
- Closes [BD-3404](https://jira.braze.com/browse/BD-3404)
- N/A …

BD-3404: Add missing fields for `push_tokens`

---

_includes/rate_limits.md

My PR...
- Closes [BD-3408](https://jira.braze.com/browse/BD-3408)
- N/A …

BD-3408: Clarify rate limit

---

_docs/_partners/message_orchestration/attribution/adjust.md

My PR...
- Closes [BD-3409
](https://jira.braze.com/browse/BD-3409)
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managemen …

BD-3409: Update link

---

_docs/_user_guide/message_building_by_channel/email/templates/link_template.md

My PR...
- Closes [BD-3391](https://jira.braze.com/browse/BD-3391)
- N/A …

BD-3391: Add note about link templates

---

_plugins/sdk_min_versions_tag.rb

Updating `sdk_min_versions_tag.rb` with the following:
- Point `swift` platform variables to to [Swift SDK Change logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/changelog/) instead of [iOS SDK Change logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/legacy_sdks/ios/changelog/swift_changelog?redirected=true#1020).
- Changed the various iOS variable names to `legacy_ios`, `legacy_objc`, and `swift` respectively.
- Removed the `original` string from the various variables like `@original_web` to `@web`.
- Slightly re-ordered some of the lines for better readability (i.e. grouping legacy sdk lines together).
- N/A
- N/A
- My style and voice …

Updating 'sdk_min_versions_tag.rb'

---

_docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md

My PR...
- Closes [BD-3412](https://jira.braze.com/browse/BD-3412)
- N/A …

BD-3412: Update step

---

_docs/_api/objects_filters/messaging/web_objects.md

This updates the description of the `require_interaction` field of the web push object to reflect the current support landscape. It is based on the MDN documentation [here](https://developer.mozilla.org/en-US/docs/Web/API/Notification/requireInteraction#browser_compatibility).
https://jira.braze.com/browse/FF-588

[FF-588] - Update web_objects.md

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md

My PR...
[#BD-3403](https://jira.braze.com/browse/BD-3403)
- N/A …

BD-3403 Add Cart ID to Abandoned Cart for Shopify

---

_docs/_api/endpoints/export/campaigns/get_campaign_details.md

Add proper doc for the newly introduced fields in /campaigns/details and /canvas/details APIs
see https://github.com/Appboy/platform/pull/83622 …

Add proper doc for the newly introduced fields in /campaigns/details and /canvas/details APIs

---

_docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md

BD-3364: Clarify email validation for Gmail addresses

---

_docs/_user_guide/message_building_by_channel/email/email_setup/email_validation.md

Fix typo for email validation.
- N/A
- N/A …

Fix typo for email validation

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/adobe/adobe.md

Add note and apply Diataxis template
[BD-3415](https://jira.braze.com/browse/BD-3415)
- N/A …

BD-3415 Add note to Adobe about removing user values

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md

My PR...
- Closes [BD-3300](https://jira.braze.com/browse/BD-3300)
- N/A …

BD-3300: Clarify example request for /canvas/trigger/send

---

_docs/_developer_guide/platform_integration_guides/unity/analytics/logging_custom_events.md
_docs/_developer_guide/platform_integration_guides/unity/analytics/logging_purchases.md
_docs/_developer_guide/platform_integration_guides/unity/analytics/setting_custom_attributes.md
_docs/_developer_guide/platform_integration_guides/unity/analytics/setting_user_ids.md

When you navigate to any page under the **Analytics** section of the [Unity dev docs](https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/news_feed), the TOC will break because the directory name is currently uppercase. This PR changes the directory name to lowercase to fix the issue.
- N/A
- N/A …

Unity docs: directory name 'Analytics' > 'analytics'

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md

- Added missing exception events for exit criteria 
- Restructured the article
- Cleaned up some language
- Closes [BD-3380](https://jira.braze.com/browse/BD-3380)
- N/A …

BD-3380: Add exception events for exit criteria

---

_docs/_user_guide/data_and_analytics/custom_data/custom_events.md

Applies Diataxis template and new branding voice to Custom Events
Part of [#BD-3318](https://jira.braze.com/browse/BD-3318)
- N/A …

BD-3318-1 Custom Events Diataxis application

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/overview.md

My PR...
- Closes [BD-3004](https://jira.braze.com/browse/BD-3004)
- N/A …

BD-3004: Add recommendation for incremental updates

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/file_storage_integrations.md

remove EA from CDI S3 docs

---

_docs/_user_guide/data_and_analytics/data_points.md

My PR...
- Closes [BD-3248](https://jira.braze.com/browse/BD-3248)
- N/A …

BD-3248: Add to notes section for custom attributes

---

_lang/ja/_developer_guide/platform_wide/sending_test_messages.md

JA - fix reference

---

_docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
_docs/_user_guide/engagement_tools/segments/managing_segments.md
_includes/campaign_analytics.md

My PR added information about the self-service "Changelog" of "Changes Since Last Viewed"
https://jira.braze.com/browse/BD-3420 
- N/A …

Added information about the self-service "Changelog" of "Changes Since Last Viewed"

---

_docs/_developer_guide/customization_guides/content_cards/logging_analytics.md
_plugins/tabs.rb

Allow utf8 chars in tabids

---

.vercel/build.js
Rakefile
_data/i18n.yml
_lang/_config_ko.yml
public/index_ja.html
public/index_ko.html

Add ko setting

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

My PR...
[BD-3425](https://jira.braze.com/browse/BD-3425)
- N/A …

BD-3425 Roles GA

---

_docs/_partners/data_and_infrastructure_agility/workflow_automation/airbyte.md

Update airbyte.md prerequisites 

---

_docs/_api/endpoints/messaging/send_messages/post_send_messages.md
_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md

Alphabetize the messaging channels in example request for `/messages/send`
- Closes [BD-3429](https://jira.braze.com/browse/BD-3429)
- N/A …

BD-3429: Alphabetize channels in example request

---

_docs/_user_guide/message_building_by_channel/content_cards/about.md

My PR applies the Diataxis standards and rebrand guidelines to About Content Cards. Part of my OKR.
[BD-3318](https://jira.braze.com/browse/BD-3318)
- N/A …

BD-3318-2 Apply Diataxis standards to About Content Cards

---

_docs/_user_guide/data_and_analytics/user_data_collection.md
_docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
_docs/_user_guide/data_and_analytics/user_data_collection/collection_use_case.md
_docs/_user_guide/data_and_analytics/user_data_collection/language_codes.md
_docs/_user_guide/data_and_analytics/user_data_collection/sdk_data_collection.md
_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
_docs/_user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle.md

My PR...
[#BD-3418](https://jira.braze.com/browse/BD-3418)
- N/A …

BD-3418 Apply Diataxis standards to Update User Data Collection

---

_docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md

My PR updates the metric name for Primacy Conversions.
[#BD-3439](https://jira.braze.com/browse/BD-3439)
- N/A …

BD-3439 Update Primary Conversions email metric name

---

_lang/ja/_user_guide/administrative/app_settings/company_settings/security_settings.md

File sending_test_messages.md committed.

---

_docs/_hidden/private_betas/canvas_triggered_iams.md

Update EA note with before and after triggered IAM behavior

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md

Clarified that you can add up to 4 filters per catalog selection
- Closes [BD-3426](https://jira.braze.com/browse/BD-3426)
- N/A …

BD-3426: Add limit for 4 filters per catalog selection

---

_docs/_api/endpoints/export/canvas/get_canvas_analytics_summary.md

My PR provides the correct UTC offset for the example request so that it works as expected with the API. …

fix: convert UTC offset to 2 digits for the hour instead of 1 digit.

---

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md

Close note alert

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

My PR adds a list of reported security events to the Security Settings article.
[BD-3445](https://jira.braze.com/browse/BD-3445)
- N/A …

BD-3445 Add list of security events that are reported

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

My PR adds a sentence to the security event report download about internal audits
BD-3445
- N/A …

BD-3445-2 Add sentence to security event report download

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/sessionm.md

Unhides SessionM partner doc
- N/A
- N/A
- …

SessionM Partnership Doc

---

_docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md

Removes the word "have" and additional edits
- Closes [BD-3447](https://jira.braze.com/browse/BD-3447)
- N/A …

BD-3447: Fix typo and minor edits

---

_docs/_partners/canvas_steps/google_audience_sync.md

My PR recommends that users only target EEA & UK users who have true Google consent attributes.
[BD-3454](https://jira.braze.com/browse/BD-3454)
- N/A …

BD-3454 Suggestion to target users with true Google consent attributes

---

_docs/_user_guide/sage_ai/recommendations/about_item_recommendations.md

My PR adds "Trending" item recommendations to the AI item recommendations page.
[BD-3424](https://jira.braze.com/browse/BD-3424)
19 September 2024 …

BD-3440 Add Trending item recommendations 

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

My PR removes the EA note for response messages.
[BD-3460](https://jira.braze.com/browse/BD-3460)
- N/A …

BD-3460 Response messages GA

---

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md

For [EINFRA-2073](https://jira.braze.com/browse/EINFRA-2073), there was a request to increase the max subscription group limit from 100 to 350. 
Updating the docs in accordance to change in this [PR](url) …

[einfra-2073] Increase max sg limit per ws from 100 to 350

---

_docs/_user_guide/engagement_tools/landing_pages.md
_docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md

My PR unhides the landing pages beta pages.
[BD-3458](https://jira.braze.com/browse/BD-3458)
- N/A …

BD-3458 Unhide landing pages beta

---

_docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md

Removes an outdated Google Analytics link
- Closes [BD-3464](https://jira.braze.com/browse/BD-3464)
- N/A …

BD-3464: Remove broken 3rd party link

---

_docs/_user_guide/data_and_analytics/reporting/engagement_reports.md

My PR updates Engagement reports to say that time is based on the company time zone.
[BD-3446](https://jira.braze.com/browse/BD-3446)
- N/A …

BD-3446 Specify that engagment reports use company time zone

---

_docs/_partners/data_and_infrastructure_agility.md
_docs/_partners/data_and_infrastructure_agility/analytics.md
_docs/_partners/data_and_infrastructure_agility/analytics/inbox_monster.md
_docs/_partners/home.md

My PR adds the inbox monster partner page and links
- N/A
- N/A …

add inbox monster partner doc and link to added page

---

_docs/_contributing/yaml_front_matter/metadata.md
_docs/_contributing/yaml_front_matter/page_layouts.md

Updating the metadata and layout pages to be a little more clear in their descriptions and how they interact with each other.
- N/A
- N/A …

Update metadata.md & page_layouts.md

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
_docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md

Adds information for custom data deletion EA
- Closes [BD-3410](https://jira.braze.com/browse/BD-3410)
- N/A …

BD-3410: Custom data deletion EA

---

_docs/_user_guide/sage_ai/generative_ai/ai_liquid.md
_docs/_user_guide/sage_ai/generative_ai/ai_liquid/ai_liquid_prompts.md

My PR adds the email channel to the BrazeAI Liquid Assistant
[BD-3471](https://jira.braze.com/browse/BD-3471)
- N/A …

BD-3471 Add Email to the BrazeAI Liquid Assistant

---

_docs/_user_guide/engagement_tools/segments/regex.md

Moving the alert outside of the tab to allow for Markdown rendering and sidestep an issue with the translation tool
- N/A
- N/A
- [X ] I confirm that my PR meets the following: …

Moving the alert outside of the tab to allow for Markdown

---

_docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md

Removing time-bound content from article
- N/A
- N/A
- [x ] I confirm that my PR meets the following: …

Removing time-bound content from article

---

_docs/_api/endpoints/user_data/post_user_track.md
_docs/_api/objects_filters/event_object.md
_docs/_api/objects_filters/purchase_object.md
_docs/_api/objects_filters/user_attributes_object.md

Add `phone` for these articles:
* Event object
* Purchase object
* User attributes object
- Closes [BD-3453](https://jira.braze.com/browse/BD-3453)
- N/A …

BD-3453: Add `phone` for objects articles

---

_docs/_api/endpoints/user_data/post_users_merge.md

Updates `phone_number` to `phone` as the correct phone number identifier
- Closes [BD-3474](https://jira.braze.com/browse/BD-3474)
- N/A …

BD-3474: Update to `phone` for phone number identifier

---

_docs/_help/release_notes.md

My PR adds the September release notes to the main release notes page
- N/A
- N/A …

Add current release notes to main page

---

bdocs
scripts/list_redirect_urls.sh

Was a bit annoying to always be asked because you can't effectively use `pbcopy`. Now it only asks if no argument is given through bdocs.
Checkout this branch, then add some random lines to the broken redirect list:
```
validurls['/docs/partners/data_and_infrastructure_agility/ab_testing/phrasee'] = '/docs/partners/data_and_infrastructure_agility/ab_testing/jacquard/';
validurls['/docs/partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee'] = '/docs/partners/data_and_infrastructure_agility/ab_testing/jacquard/';
validurls['/docs/partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee_react'] = '/docs/partners/data_and_infrastructure_agility/ab_testing/jacquard/';
validurls['/docs/partners/data_and_infrastructure_agility/ab_testing/phrasee/phrasee#phrasee'] = …
```

Quick fix: allow arguments for 'redirects' command

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

My PR clean the documentation, there is a column name canvas_name that gets duplicated in the braze message event content card impression
- N/A
- N/A …

Update message_engagement_events.md remove duplication of canvas_name

---

_docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md

Adding timebound content back to Landing Pages for the time being
Who is the time being? Is it here in the room with us?
- N/A
- N/A …

Adding the Roadmap back to Landing Pages

---

_docs/_partners/data_and_infrastructure_agility/data_warehouses.md
_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
_docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md

Updates mentions of "Data Warehouse" to "Data Warehouse Storage"
- Closes [BD-3484](https://jira.braze.com/browse/BD-3484)
- N/A …

BD-3484: Update mentions of "Data Warehouse" to "Data Warehouse Storage"

---

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md

Add example for adding UTM parameter to URL in SMS
- Closes [BD-3469](https://jira.braze.com/browse/BD-3469)
- N/A …

BD-3469: Add example for adding UTM parameter to URL in SMS

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

My PR updates the reported security events list
[BD-3483](https://jira.braze.com/browse/BD-3483)
- N/A …

BD-3483 Update reported security event

---

_docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md

My PR adds the Trending model to the AI item recommendations article
[BD-3424](https://jira.braze.com/browse/BD-3424)
19 September 2024 …

BD-3424 Add trending model to AI item recommendations

---

_docs/_user_guide/brazeai/generative_ai/ai_copywriting.md

My PR updates DALL-E 2 to DALL-E 3 on the AI copywriter page
[BD-3486](https://jira.braze.com/browse/BD-3486)
- N/A …

BD-3486 Update Dall-e 2 to Dall-e 3

---

_docs/_developer_guide/platform_integration_guides/react_native/react_sdk_setup.md

[SDK-5158] Add docs about React location library fro Android

---

_docs/_api/objects_filters/event_object.md
_docs/_api/objects_filters/purchase_object.md
_docs/_api/objects_filters/user_attributes_object.md

Updates mentions of `phone` to "phone" in object bodies for consistency
- N/A
- N/A …

Updates mentions of `phone` to "phone" in object bodies for consistency

---

_docs/_api/basics.md

Reorganize API key content for API overview and rename headers to flow better
- Closes [BD-3490](https://jira.braze.com/browse/BD-3490)
- N/A …

[Docs feedback] BD-3490: Reorganize API key content for API overview

---

assets/js/broken_redirect_list.js

Fixed redirect for Content QA with AI
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-im …

Fix redirect

---

_docs/_developer_guide/platform_integration_guides/swift/live_activities/faq.md

Updates some of the Live Activities FAQs with some of the more recent questions we've received.
- [BD-3494](https://jira.braze.com/browse/BD-3494)
- N/A …

[BD-3494] Update Live Activities FAQ

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/operators.md

Add that parentheses are invalid Liquid characters for Liquid operators article
- Closes [BD-3500](https://jira.braze.com/browse/BD-3500)
- N/A …

BD-3500: Add parentheses are invalid Liquid characters

---

_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md

Clarify sentence in things to consider after launch
- Closes [BD-3503](https://jira.braze.com/browse/BD-3503)
- N/A …

BD-3503: Clarify sentence in things to consider after launch

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md

Call out the maximum delay for in-app message campaigns
- Closes [BD-3501](https://jira.braze.com/browse/BD-3501)
- N/A …

BD-3501: Add maximum delay for in-app message campaigns

---

_docs/_user_guide/message_building_by_channel/email/amphtml.md

Fix typo "fun" to "run"
- Closes [BD-3512](https://jira.braze.com/browse/BD-3512)
- N/A …

BD-3512: Fix typo

---

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md

Clarifies that after a Canvas launches, you can't make changes to audience paths, action paths, and experiment paths, and you can't adjust the ranking order
- Closes [BD-3507](https://jira.braze.com/browse/BD-3507)
- N/A
- If I updated or replaced an image, I did not remove …

BD-3507: Clarify post-launch details

---

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md

- Reformat link aliasing examples section 
- Add a new example for anchor and capture tag
- Closes [BD-3497](https://jira.braze.com/browse/BD-3497)
- N/A …

BD-3497: Add link aliasing example for anchor and capture tag

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/treasure_data/treasure_data_for_currents.md

Add note for Treasure Data that data is sent in batches and fix spacing
- Closes [BD-3511](https://jira.braze.com/browse/BD-3511)
- N/A …

BD-3511: Add note for Treasure Data that data is sent in batches

---

_docs/_user_guide/brazeai/generative_ai/ai_liquid.md
_docs/_user_guide/brazeai/generative_ai/ai_liquid/ai_liquid_prompts.md
assets/js/broken_redirect_list.js

My PR applies changes to make the BrazeAI Liquid Assistant ready for GA
[BD-3492](https://jira.braze.com/browse/BD-3492)
24 September 2024 …

BD-3492 BrazeAI Liquid Assistant GA MERGE 9/24

---

_docs/_user_guide/message_building_by_channel/content_cards/about.md

Fixed Braze learning link in About Content Cards article
[BD-3518](https://jira.braze.com/browse/BD-3518)
- N/A …

BD-3518 Fix broken Content Cards learning link

---

_docs/_user_guide/engagement_tools/testing/global_control_group.md

Correct what kind of behaviors you can report on from global control groups
[BD-3513](https://jira.braze.com/browse/BD-3513)
- N/A …

BD-3513 Update global control group

---

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md

Update mention of DALL E 2 to DALL E 3
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-i …

Update mention of DALL E 2 to DALL E 3

---

_docs/_help/help_articles/api/delete_user.md

Update anonymized to deleted (nulled) for removing users via API (Legal approved)
- Closes [BD-3271](https://jira.braze.com/browse/BD-3271)
- N/A …

BD-3271: Update anonymized to deleted (nulled)

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md

- Update language on limitations for adding multiple catalog items
- Fix image links
- Closes [BD-3519](https://jira.braze.com/browse/BD-3519)
- N/A …

BD-3519: Update language on limitations for adding multiple catalog items

---

_docs/_developer_guide/platform_integration_guides/legacy_sdks/ios/initial_sdk_setup.md
assets/js/broken_redirect_list.js

Fixing some misc redirects for legacy iOS docs. The primary request is to make the `/initial_sdk_setup/` config only page redirect to the `/initial_sdk_setup/overview.md` page since this link has been directly embedded in the product for some time.
- [BD-3522](https://jira.braze.com/browse/BD-3522)
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redi …

[BD-3522 ] Fixing redirect for legacy iOS

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md

Fix broken Liquid brackets
[BD-3532](https://jira.braze.com/browse/BD-3532)
- N/A …

BD-3532 Docs Feedback - Fix Liquid brackets

---

_docs/_user_guide/administrative/app_settings/subscription_and_usage.md

Update description for App Level Total Data Point Usage table
[BD-3515](https://jira.braze.com/browse/BD-3515)
- N/A …

BD-3515 Update App Level Total Data Point Usage table description

---

_docs/_user_guide/data_and_analytics/query_builder.md

Removed an old AI query builder beta alert
None
- N/A …

Remove old AI query builder beta alert

---

_docs/_user_guide/administrative/access_braze/portal.md

Some tables on this page don't have headers, which aren't accessible. 
- N/A
- N/A …

Fix tables missing headers

---

_docs/_user_guide/message_building_by_channel/whatsapp/overview.md

Remove the note that says Multi-WABA isn't supported
[BD-3536](https://jira.braze.com/browse/BD-3536)
- N/A …

BD-3536 Multi-WABA is supported

---

assets/js/broken_redirect_list.js

Fixed broken redirect
- N/A
- N/A
- [x ] I confirm that my PR meets the following: …

Fixed broken redirect

---

assets/js/broken_redirect_list.js

Added a redirect for IDFA collection
- N/A
- N/A
- [x ] I confirm that my PR meets the following: …

Added a redirect for IDFA collection

---

_lang/ko/_api/endpoints/export/purchases/get_revenue_series.md

One of the ruby `{% endapiref %}` tags got accidently translated to korean, [breaking vercel](https://vercel.com/braze/braze-docs-ko/9dTqHPiybseYE6EHYM9cbiKZXGD3?utm_medium=email&utm_source=notifications&filter=errors). I've reverted the tag back to english.
- N/A
- N/A
- If …

Fix ruby syntax for 'ko' docs

---

_docs/_hidden/other/credit_ratios.md
_docs/_hidden/pricing/message_credits_delta_a3sy.md
_docs/_hidden/pricing/message_credits_gamma_0dhr.md
_docs/_hidden/pricing/message_credits_lambda_k5gh.md
_docs/_hidden/pricing/message_credits_sigma_pow2.md
_docs/_hidden/pricing/message_credits_theta_d9kw.md

Update UK Marketing credit ratios
[BD-3525](https://jira.braze.com/browse/BD-3525)
- N/A …

BD-3525 Update UK Marketing ratios

---

.github/CODEOWNERS
_docs/_api/endpoints/user_data/post_user_track.md

Ingestion owns data transformation templates for a variety of braze endpoints. We are setting up the codeowners here to be notified when these endpoint interfaces change so we can update our templates accordingly.
- N/A
- N/A …

[INN-1790] Add ingestion as codeowners

---

_docs/_user_guide/data_and_analytics/report_metrics.md
_docs/_user_guide/data_and_analytics/reporting/report_builder.md

Add detail about Unique Recipients metric
[BD-3479](https://jira.braze.com/browse/BD-3479)
- N/A …

BD-3479 Add detail to Unique Recipients metric

---

_docs/_user_guide/data_and_analytics/query_builder.md

Clarify that Query Builder data is from the past 60 days
[BD-3531](https://jira.braze.com/browse/BD-3531)
- N/A …

BD-3531 Docs feedback- Clarify Query Builder data timeline

---

_docs/_api/objects_filters/user_alias_object.md

Adds an example for a user alias object
- Closes [BD-3488](https://jira.braze.com/browse/BD-3488)
- N/A …

[Docs feedback] BD-3488 - Add user alias object example

---

_docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md

Updated header and link name in Subscription Group article
[BD-3529](https://jira.braze.com/browse/BD-3529)
- N/A …

BD-3529 Update subscription groups header and link name

---

_docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md

Update deleting custom data details based on feedback from PM and Legal teams
- Closes [BD-3542](https://jira.braze.com/browse/BD-3542)
- N/A …

BD-3542: Update deleting custom data details

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
_docs/_api/errors.md

Add reference link to Errors and responses article for error codes and details if a user receives a fatal error in the request.
- Closes [BD-3489](https://jira.braze.com/browse/BD-3489)
- N/A
- If I updated or replaced an image, I did not remove the original image file from …

[Docs feedback] BD-3489: Add reference link to API errors and responses

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md

Removed an extra bracket in a Liquid snippet
[BD-3546](https://jira.braze.com/browse/BD-3546)
- N/A …

BD-3546 Fix Liquid use case that has extra bracket

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/templates/email_capture.md

Clarify that the message step has to be an email step
[BD-3544](https://jira.braze.com/browse/BD-3547)
- N/A …

BD-3544 Update Email Capture form docs

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Wording fix for the loudly notify runbook …

Wording fix for the loudly notify runbook

---

scripts/create_release_text.sh

A few weeks ago I updated the name of the file for the `deploy` command, but I forgot to update the reference in the file for the `release` command. This PR fixes that issue so no errors are thrown for "missing/unkown" file.
- N/A
- N/A
- If I updated or replaced an image, I …

Fixing bug with bdocs release

---

_docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md

Update that you can use `/users/track` instead of previous endpoint
- Closes [BD-3493](https://jira.braze.com/browse/BD-3493)
- N/A …

BD-3493: Update how to capture user data with web form

---

_docs/_developer_guide/platform_integration_guides/unity/push_notifications/android.md

Added Unity docs for how to add Android Push notification icons
[BD-3018](https://jira.braze.com/browse/BD-3018)
- N/A …

BD-3018 Add section for how to add Unity Push icons

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users.md
_docs/_user_guide/administrative/app_settings/manage_your_braze_users/teams.md
_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md

Moved comparison table to landing page and added links to respective sub-pages.
[BD-3533](https://jira.braze.com/browse/BD-3533)
- N/A …

BD-3533 Add comparison table to Company Users page

---

_docs/_user_guide/message_building_by_channel/line/line_setup.md

Update User ID Reconciliation intro to mention two methods.
[BD-3552](https://jira.braze.com/browse/BD-3552)
- N/A …

BD-3552 Update LINE user ID intro

---

_docs/_user_guide/message_building_by_channel/email/preference_center/overview.md

Clarifies why a user would see "PreferenceCenterBrazeDefault" if they haven't created a preference center
- Closes [BD-3480](https://jira.braze.com/browse/BD-3480)
- N/A …

BD-3480: Clarify reason for seeing PreferenceCenterBrazeDefault on dashboard

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md

Fixing alerts that had a plus sign carry over from GitHub suggestions
- N/A
- N/A …

Fix alerts

---

_docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md

Updating in-app message customization docs with Objective-C snippets of previously unavailable method. …

Swift SDK: Update with Objective-C samples for prepareWith method

---

_docs/_api/objects_filters/user_attributes_object.md
_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md

* Add mentions of nested attributes and array of objects to [User attributes object article](https://braze.com/docs/api/objects_filters/user_attributes_object#array-of-objects-example)
* Add link to User attributes object article to [Array of objects article](https://www.braze.com/docs/user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects/)
- Closes [BD-3498](https://jira.braze.com/browse/BD-3498)
- N/A
- If I …

BD-3498: Add mentions of nested attributes and array of objects

---

_docs/_contributing/content_management/jekyll_collections.md

Align article title YAML so that it matches the other search results
- N/A
- N/A …

Edit for article title in YAML

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md

- Updates `$time` portion of attributes Liquid templating example
- Closes [BD-3541](https://jira.braze.com/browse/BD-3541)
- N/A …

BD-3541: Clarify ISO8601 timestamp format example

---

_docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md
_lang/ja/_developer_guide/platform_integration_guides/android/initial_sdk_setup/accessibility.md

Remove the period in tab name so that the content will display
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_manageme …

Fix tab name formatting

---

_docs/_user_guide/data_and_analytics/query_builder.md

Add details about column names that appear
[BD-3565](https://jira.braze.com/browse/BD-3565)
- N/A …

BD-3565 Update Query Builder with column name

---

_docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md

Clarify confusing beta note on landing pages article
[BD-3550](https://jira.braze.com/browse/BD-3550)
- N/A …

BD-3550 Clarify landing pages beta note

---

_docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md

Update AI item recommendation table superscript and table content
[BD-3551](https://jira.braze.com/browse/BD-3551)
- N/A …

BD-3551 Update AI item recommendation table

---

_docs/_developer_guide/platform_wide/sdk_authentication.md

We don't use these 2 fields and a client was asking about them
https://jira.braze.com/browse/FF-716
- N/A …

FF-716 / remove aud and iss from JWT specs

---

_docs/_user_guide/message_building_by_channel/sms/sms_laws_and_regulations.md

Update CTIA messaging principles and best practices PDF
[BD-3563](https://jira.braze.com/browse/BD-3563)
- N/A …

BD-3563 Update CTIA PDF link

---

_docs/_partners/canvas_steps/facebook_audience_sync.md

Updated TOS links and minor edits
[BD-3569](https://jira.braze.com/browse/BD-3569)
- N/A …

BD-3569 Update Audience Sync to Facebook TOS links

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md

Remove comma from tab header
- Closes [BD-3571](https://jira.braze.com/browse/BD-3571?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)
- N/A …

BD-3571: Fix tab header

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/aborting_messages.md

Add that users can use Query Builder or query their own data warehouse for abort messages
[BD-3566](https://jira.braze.com/browse/BD-3566)
- N/A …

BD-3566 Add to Aborting Liquid Messages

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Clarify requirements in the CSV file (columns) used for promotion codes
- Closes [BD-3487](https://jira.braze.com/browse/BD-3487)
- N/A …

[Docs feedback] BD-3487: Clarify columns in CSV file for promotion codes

---

_includes/campaign_analytics.md

Removed old table from email reporting article
- N/A
- N/A …

Remove email metrics duplicate table

---

_config.yml

Update config setting to match algolia

update config settings

---

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md

I moved the SMS note to a new section (Considerations) on the User Import page. A PM requested that the note be added to that page among others, so I don't want to remove it.
[BD-3572](https://jira.braze.com/browse/BD-3572)
- N/A …

BD-3572 Move SMS note to a Consideratinos section in User Import

---

.github/CODEOWNERS

Currents team would like to be notified for any changes to `message_engagement_events.md` and `customer_behavior_events.md`, since we keep templates on our end in order to auto-generate the event payload documentation that appears on these pages. Any changes to these docs pages outside of the auto-generated payloads need to be reverse-synchronized with our templates to ensure consistency.
- https://jira.braze.com/browse/DI-6567
- N/A …

[DI-6567] Make Currents the codeowners for Currents event docs

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md

Reverts braze-inc/braze-docs#8498

Revert "BD-3576: Clarify re-eligibility for triggered campaigns and Canvases"

---

_docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md

Add a tip that users should use a campaign if they want anonymous users to view a Content Card after their very first session.
[BD-3597](https://jira.braze.com/browse/BD-3697)
- N/A …

BD-3597 Add tip to Content Card creation

---

_docs/_partners/isv_partners/currents_integration.md

The CustomHTTP docs were somehow full of stuff that is not relevant for external customer-facing documentation. This PR rewrites it so that it is more relevant to external customers as opposed to internal stakeholders.
- N/A
- N/A
- If I updated or replaced an image, I did …

Remove a bunch of Currents CustomHTTP information that is not customer-facing

---

_docs/_user_guide/engagement_tools/locations_and_geofences/location_tracking.md

Add behavior for SDK user location by IP address
- BD-3701
- November 26, 2024 …

BD-3701: Add info for SDK user location by IP address - MERGE 11/26

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_catalogs.md

Minor edits to Shopify product sync
- N/A
- N/A …

Minor edits to Shopify product sync

---

_docs/_developer_guide/platform_integration_guides/swift/live_activities/live_activities.md

Added details to the 2nd Live Activities step
[BD-3699](https://jira.braze.com/browse/BD-3699)
- N/A …

BD-3699 Update Live Activities step

---

_docs/_user_guide/engagement_tools/canvas/faqs.md

Clarify IAM behavior for Canvases after being stopped
- BD-3626
- N/A …

BD-3626: Clarify IAM behavior for Canvases after being stopped

---

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md

Added a missing word to the link shortening FAQs
- N/A
- N/A …

Fix typo in link shortening FAQ

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Remove 24-hour period for a segmentation filter that _isn't_ limited to a 24-hour period
[BD-3713](https://jira.braze.com/browse/BD-3713)
- N/A …

BD-3713 Remove 24-hour period for filter

---

_docs/_hidden/compliance/home.md
_docs/_hidden/compliance/sms_channel.md
_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Update Mobile Messages Services documentation
[BD-3717](https://jira.braze.com/browse/BD-3717)
- N/A …

BD-3717 Update Mobile Messages Services doc

---

_docs/_partners/data_and_infrastructure_agility.md
_docs/_partners/data_and_infrastructure_agility/leads_capture.md
_docs/_partners/data_and_infrastructure_agility/leads_capture/outgrow.md
_docs/_partners/home.md

Add Outgrow docs
[BD-3664](https://jira.braze.com/browse/BD-3664)
- N/A …

BD-3664 Outgrow partner docs

---

_docs/_partners/message_personalization/dynamic_content/seen.md

Add missing commas
Reword content to align with existing partner docs
- N/A
- N/A …

Minor edits to SEEN partner doc

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2024/9_17_24.md
_lang/es/_help/release_notes.md
_lang/es/_help/release_notes/2024/9_17_24.md
_lang/fr_fr/_help/release_notes/2024/9_17_24.md
_lang/ja/_help/release_notes.md
_lang/ja/_help/release_notes/2024/9_17_24.md
_lang/ko/_help/release_notes.md
_lang/ko/_help/release_notes/2024/9_17_24.md

There was a misreporting on the rate limit for the /users/export/ids endpoint. I removed all related entries because there actually wasn't a rate increase.
Rather, depending on when the user joined Braze, either 2,500 or 250 could apply to them:
- Onboarded before August 22, 2024: rate limit = 2,500
- Onboarded on or after August 22, 2024: rate limit = 250
- N/A
- N/A …

Correct release notes regarding rate limit

---

_docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md

Add note about the **Does not equal** filter only matching if all properties don't include the stated values
[BD-3678](https://jira.braze.com/browse/BD-3678)
- N/A …

BD-3678 Update nested object filter

---

_docs/_api/basics.md
_docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration.md
_docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration.md
_docs/_developer_guide/platform_integration_guides/swift/push_notifications/integration.md
_docs/_user_guide/brazeai/predictive_suite/predictive_events.md
_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md
_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
_docs/_user_guide/message_building_by_channel/content_cards/about.md
_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
_docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md

[These are the top pages visited on Braze Docs](https://docs.google.com/spreadsheets/d/1vmQIXACCU4exnHCMHT9HkJQauJg5ykcAELglzz7nUO0/edit?gid=0#gid=0), so we have decided to ensure that all their images have alt text and any existing alt text does not use directional language.
_*Original PR had an issue with the commits._
- [BD-3620](https://jira.braze.com/browse/BD-3620)
- Fixes #8503
- N/A
- If I renamed or moved a file or directory, …

ADA Compliance Dec 2024

---

_docs/_user_guide/getting_started/users_segments.md

The Braze SDK does not automatically track standard attributes after the SDK is integrated into an app.
- [BD-3687](https://jira.braze.com/browse/BD-3687)
- N/A …

[BD-3687] Remove mention of 'automatic tracking'

---

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/retargeting_campaigns.md
_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Clarify "Last received X" filters so that it's clear only specific campaigns or Canvases are considered
[BD-3725](https://jira.braze.com/browse/BD-3725)
- N/A …

BD-3725 Clarify last received filters

---

_includes/campaign_analytics.md

Resolves BD-3675 as part of the [initiative](https://confluence.braze.com/display/PDT/KB+article+tracker) to source docs feedback from KB articles. Also cleans up some surrounding content in the "Push metrics" section to structure content for readability.
- N/A
- N/A
- If I …

BD-3675: Add context to push reporting about sends and unique recipients 

---

_docs/_partners/message_personalization/localization/smartling.md

Pulls in edits from https://github.com/braze-inc/braze-docs/pull/8549/ because I didn't have editing permissions on that branch/PR
- #8549 
- N/A …

Add info about Canvas and campaign for Smartling partner doc

---

_includes/header.html

Add ko to dropdown

---

_docs/_user_guide/data_and_analytics/braze_currents.md
_docs/_user_guide/data_and_analytics/braze_currents/available_partners.md
_docs/_user_guide/data_and_analytics/braze_currents/event_delivery_semantics.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/customer_behavior_events.md
_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_docs/_user_guide/data_and_analytics/braze_currents/how_braze_uses_currents.md
_docs/_user_guide/data_and_analytics/braze_currents/s3_to_snowflake.md
_docs/_user_guide/data_and_analytics/braze_currents/setting_up_currents.md
_docs/_user_guide/data_and_analytics/braze_currents/transferring_data_to_redshift.md
_includes/updating_currents.md

Updated the Currents documentation to follow the Diataxis standards. Also applied a variety of edits, from formatting to wording.
[BD-3740](https://jira.braze.com/browse/BD-3740)
- N/A …

BD-3740 Apply Diataxis template to Currents

---

_docs/_partners/data_and_infrastructure_agility/analytics/amplitude/amplitude_audiences.md

Define what "user ID" means in Amplitude, because Braze uses "user ID" and "external ID" interchangeably.
[BD-3718](https://jira.braze.com/browse/BD-3718)
- N/A …

BD-3718 Update Amplitude Audiences to define 'user ids'

---

_docs/_user_guide/message_building_by_channel/webhooks/lead_scoring.md

Fix broken nav header that links to the B2B lead scoring use case
- N/A
- N/A …

Fix broken nav header that links to a use case

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze.md

The ability to trigger off of nested event properties across shopify events should be listed as line_items[0].product_id.
[BD-3742](https://jira.braze.com/browse/BD-3742)
- N/A …

BD-3742 Update Shopify event property

---

_docs/_developer_guide/getting_started.md

Updated links on the Develop Getting Started landing page. Initially, two weren't included, and the others had outdated links that were being redirected.
[BD-3724](https://jira.braze.com/browse/BD-3724)
- N/A …

BD-3724 Update links on Developer Getting Started page

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md

Remove inaccurate sentence about price drop and BIS notifications for catalog triggers
- BD-3737
- N/A …

BD-3737: Remove inaccurate sentence about price drop and BIS

---

_docs/_user_guide/getting_started/b2b_use_cases/account_based_segmentation.md

Remove space in site.baseurl
- N/A
- N/A
- …

Remove space in site.baseurl

---

_docs/_user_guide/engagement_tools/landing_pages/data_tracking.md
_docs/_user_guide/engagement_tools/landing_pages/drag_and_drop.md

Add Legal edits to the landing page docs
[BD-3719](https://jira.braze.com/browse/BD-3719)
- N/A …

BD-3719 Landing page edits

---

_docs/_api/objects_filters/messaging/android_object.md
_docs/_api/objects_filters/messaging/apple_object.md

Add use_webview attribute for Android and Apple push objects
- [#8521](https://github.com/braze-inc/braze-docs/issues/8521)
- N/A …

Add use_webview attribute for Android and Apple push objects

---

_docs/_hidden/compliance/sms_channel.md

Updating documentation with details for usage of the Mobile Messages channels.
[BD-3743](https://jira.braze.com/browse/BD-3743)
- N/A …

BD-3743 Update mobile messages documentation

---

_docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md

Update redirect and add alt text for preference center
- BD-3761
- N/A …

BD-3761: Update redirect and add alt text

---

_docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md

Add information to custom data deletion about supported data types
- BD-3763
- N/A …

BD-3763: Add supported data types for custom data deletion

---

_docs/_user_guide/data_and_analytics/report_metrics.md

Calculation for Bounce rate was incorrectly duplicating the calculation for Delivery rate.
- N/A
- N/A …

Fix bounce rate calculation

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md

_In response to an escalation, this PR clarifies request/response behavior for the unhealthy host detection used by webhooks and Connected Content._
- [MOPS-3235](https://jira.braze.com/browse/MOPS-3235)
- ASAP
- If I updated or replaced an image, I did not remove the …

[MOPS-3235] Add documentation around unhealthy host detection

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md

Adding details/clarification about what is kept when a Braze dashboard user is deleted.
[BD-3714](https://jira.braze.com/browse/BD-3714)
- N/A …

BD-3714 Add details to Deleting Braze users

---

_docs/_partners/canvas_steps/google_audience_sync.md

Removing incorrect info from Google Audience Sync steps (from PM)
- N/A
- N/A …

Remove incorrect sentence for Google Audience Sync

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md

Fix incorrect senetence for back-in-stock notifications
- BD-3738
- N/A …

BD-3738: Fix incorrect senetence for back-in-stock notifications

---

_docs/_user_guide/data_and_analytics/export_braze_data/message_archiving.md

Add GCS and Azure credential errors included in AWS credential notification setting
- BD-3691
- N/A …

BD-3691: Add GCS and Azure credential errors included in AWS setting

---

_docs/_user_guide/administrative/app_settings/company_settings/notification_preferences.md

Add that GCS and Azure credential errors are included in AWS notification setting
- BD-3691
- N/A …

BD-3691: Add GCS and Azure credential errors included in AWS setting pt. 2

---

_docs/_developer_guide/content_cards.md
_docs/_developer_guide/content_cards/creating_custom_content_cards.md
_docs/_developer_guide/content_cards/customizing_behavior.md
_docs/_developer_guide/content_cards/customizing_feed.md
_docs/_developer_guide/content_cards/customizing_styles.md
_docs/_developer_guide/feature_flags/create.md
_docs/_developer_guide/getting_started/integration_overview.md
_docs/_developer_guide/getting_started/platform_overview.md
_docs/_help/release_notes.md
_docs/_help/release_notes/sdk_changelogs.md
_docs/_hidden/archived_layouts/overview.md
_docs/_hidden/redirects/sdk_changelogs.md
_docs/_user_guide/administrative/app_settings/manage_your_braze_users/user_permissions.md
_docs/_user_guide/data_and_analytics/custom_data/custom_events.md
_docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md
_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/reeligibility.md
_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/campaign_connector.md
_docs/_user_guide/engagement_tools/campaigns/building_campaigns/time_based_campaign.md
_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
_docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
_docs/_user_guide/getting_started/terms_to_know.md
_docs/_user_guide/message_building_by_channel/content_cards/creative_details.md
_docs/_user_guide/message_building_by_channel/push/android/rich_notifications.md
assets/js/broken_redirect_list.js

Broken link audit - December 2024
* Updates to redirect file
* Replacements for older links throughout the docs
- N/A
- N/A …

Broken link audit - December 2024

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/actioniq.md

Migrated the changes from https://github.com/braze-inc/braze-docs/pull/8639 to a new branch that the Braze team can edit.
- N/A
- N/A …

migrated the changes from abelfort:patch-1 to a new branch

---

_docs/_api/endpoints/subscription_groups/get_list_user_subscription_groups.md

Add example response for  /subscription/user/status endpoint
- BD-3734
- N/A …

BD-3734: Add example response for  /subscription/user/status
