braze-inc/braze-docs

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_lang/es/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_lang/fr_fr/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_lang/ja/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_lang/ko/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md
_lang/pt_br/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

`send_id` has been added to the other SMS events, so we can remove "(SMS Sends events only)"
[BD-3758](https://jira.braze.com/browse/BD-3758)
- N/A …

BD-3758 Revert changes for send_id field

---

_docs/_developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking.md

Just updating some instructions for users who use Jetpack Compose Navigation
- N/A
- N/A …

Jetpack Compose NavHost instructions

---

_docs/_user_guide/message_building_by_channel/sms/phone_numbers/user_phone_numbers.md

We no longer localize phone numbers; we now display them in the raw format.
[BD-3772 ](https://jira.braze.com/browse/BD-3772)
- N/A …

BD-3772 Update phone number formats

---

_plugins/urlnavmenu_generator.rb

Auto expand if current page navigation is expandable

auto expand current nav if possible

---

_includes/campaign_analytics.md

Change the suggested rate for Unique Opens.
[#BD-3781](https://jira.braze.com/browse/BD-3781)
- N/A …

BD-3781 Update Unique Opens suggested rate

---

_docs/_api/endpoints/user_data/post_user_track.md

Burst limits are enforced by Braze per 3 seconds, not per second. Updating the docs to match the actual behavior. 
- N/A
- N/A …

Minor tweak to burst limits

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md

update CDI doc with IP address for AU01
[DLK-2310](https://jira.braze.com/browse/DLK-2310)
- N/A …

[DLK-2310] add ip address for au01 for CDI

---

_docs/_user_guide/data_and_analytics/braze_currents/event_glossary/message_engagement_events.md

Clarify that there are no entry or exit events for split steps.
[BD-3715](https://jira.braze.com/browse/BD-3715)
- N/A …

BD-3715 No entry or exit events for split steps

---

README.md
_docs/_contributing/generating_a_preview.md

Realizing we haven't documented how to start servers for other languages. Added this to README and contributing.
- N/A
- N/A …

Add other langs to rake commands

---

_includes/header.html

This PR moves OneTrust's privacy banner from the bottom left, to the the bottom right of the browser window.
The first time you go to the docs site, the following privacy banner is displayed. When you accept it, it no longer displays. However, when building the docs locally, even if you accept it, the banner will always display (because your user data isn't stored anywhere).
The bottom left is an extremely inconvenient location for docs maintainers, as it blocks most of the left-side nav. So, when you need to navigate between several pages locally, you constantly need to accept/decline the prompt in order to access the rest of the nav and select a new page.
- N/A
- N/A
- My style and voice follows the …

Making OneTrust's privacy banner right-aligned

---

_docs/_contributing/bdocs.md

I forgot to update the `./bdocs help` output example when I merged #8652 .
- N/A
- N/A …

adding 'ulinks' to './bdocs help' docs

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

https://jira.braze.com/browse/CO-3164

[CO-3164] Specify NULL is not supported in CSV upload.

---

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md

Add new section to WhatsApp Meta resources doc
- BD-3804
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#u …

BD-3804: Add new section to WhatsApp Meta resources doc

---

_docs/_partners/canvas_steps/facebook_audience_sync.md

Update URLs for Facebook Audience Sync TOS
- BD-3803
- N/A …

BD-3803: Update URLs for Facebook Audience Sync TOS

---

_docs/_user_guide/message_building_by_channel/email/using_locales.md

Add alt text and clarification for CSV file
- N/A
- N/A …

Add alt text and clarification for CSV file

---

_docs/_partners/canvas_steps/facebook_audience_sync.md

Fix link formatting and add alt text
- N/A
- N/A …

Fix link formatting and add alt text

---

_docs/_partners/canvas_steps/overview.md

Add section about error emails for Audience Sync
- BD-3808
- N/A …

BD-3808: Add section about error emails for Audience Sync

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Added the _Soft Bounced_ segment filter.
[BD-3810](https://jira.braze.com/browse/BD-3810)
- N/A …

BD-3810 Add soft bounced filter

---

_docs/_developer_guide/platform_integration_guides/android/analytics/uninstall_tracking.md
_docs/_user_guide/data_and_analytics/tracking/uninstall_tracking.md

Update uninstall tracking docs

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Remove mention of full step
Minor edits for some capitalization consistencies
- BD-3749
- N/A …

BD-3749: Remove mention of full step

---

_docs/_api/endpoints/user_data/post_user_identify.md

Clarify that `merge_behavior` is set to `merge` by default
- BD-3811
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_manageme …

BD-3811: Clarify default behavior for `merge_behavior` parameter

---

_docs/_partners/data_and_infrastructure_agility/leads_capture/justuno.md

The metadata description for Justuno partner doc only had a placeholder.
- N/A
- N/A …

Add missing metadata description to Justuno

---

_docs/_partners/canvas_steps/facebook_audience_sync.md

"TOC" should be "TOS" and related minor edits for phrasing
- N/A
- N/A …

Minor typo fixes

---

_docs/_user_guide/data_and_analytics/cloud_ingestion/integrations.md

**From ticket:** It looks like an additional tab got added to step 3 for "Redshift Private Network" that isn't in any of the other tab groups, causing it to break the tabs on page when selected. This should likely be updated to a subtab in Redshift instead, since we don't want to make these local tabs.
- [BD-3796](https://jira.braze.com/browse/BD-3796)
- N/A …

[BD-3796] Fix redshift tab for datawarehouse

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Add section on automated emails and Message Activity Log entries for webhook and Connected Content errors
- BD-3779
- N/A …

BD-3779: Automated emails and Message Activity Log entries EA

---

_docs/_user_guide/data_and_analytics/user_data_collection/user_import.md

Adding an EA banner to a user import feature: importing a CSV file with email addresses and phone numbers.
[BD-3823](https://jira.braze.com/browse/BD-3823)
- N/A …

BD-3823 Add EA banner to importing with email and phone

---

_docs/_developer_guide/authentication.md
_docs/_developer_guide/banner_cards.md
_docs/_developer_guide/changelogs.md
_docs/_developer_guide/content_cards.md
_docs/_developer_guide/debugging.md
_docs/_developer_guide/disclosures.md
_docs/_developer_guide/feature_flags.md
_docs/_developer_guide/home.md
_docs/_developer_guide/platform_integration_guides.md
_docs/_developer_guide/sending_test_messages.md

The navigation order under Developer Guide is inconsistent. This PR changes a number of pages's `page_order` values to group similar top level docs pages together based on their theme. …

chore(nav): reordered pages

---

_includes/search_page.html
assets/css/search_page.scss

Search snippets

---

_docs/_contributing/home.md

Stipulating that the team cannot accept non-English contributions
- N/A
- N/A …

Add note about English-language only contributions

---

_includes/search_page.html

The added feature from #8730 accidently left out article titles from search. This fixes that issue.
- N/A
- N/A …

[hotfix] Add missing article titles to search results

---

_docs/_user_guide/message_building_by_channel/content_cards/create.md

We have a 250 Content Card limit enforced in our systems and do not mention it in our docs confusing our customers.
N/A
N/A …

[escalation-20250109-chrobinson-contentcardlimits] Add CC feed limit limit explanation back 

---

scripts/tests/update_old_links.md
scripts/update_old_links.py

Realized that the existing `ulinks` command in bdocs did not handle links found in YAML front matter like the following. This PR adds that functionality:
```
---
article_title: Update old links testing
guide_featured_title: "More links"
guide_featured_list:
- name: Bad link 1
link: /docs/best_practices/#android-push-category
- name: Bad link 2
link: /docs/user_guide/message_building_by_channel/email/link_templates/
- name: Bad link 3
link: /docs/user_guide/message_building_by_channel/email/link_templates/
---
```
- N/A
- N/A
- My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/p …

Fixing YAML handling for bdocs ulinks

---

_docs/_hidden/other/user_archival.md

Make it clear that the criteria is relative to the brand.
[BD-3615](https://jira.braze.com/browse/BD-3615)
- N/A …

BD-3615 Clarify criteria in user archival

---

_docs/_user_guide/data_and_analytics/custom_data/managing_custom_data.md

Add link to "managing custom attributes" to the "managing custom data" page
[BD-3795](https://jira.braze.com/browse/BD-3795)
- N/A …

BD-3795 Add link to custom attributes in custom data

---

_docs/_user_guide/data_and_analytics/reporting/configuring_reporting.md
_docs/_user_guide/data_and_analytics/reporting/data_by_segments.md
_docs/_user_guide/data_and_analytics/reporting/engagement_reports.md
_docs/_user_guide/data_and_analytics/reporting/funnel_reports.md
_docs/_user_guide/data_and_analytics/reporting/global_control_group_reporting.md
_docs/_user_guide/data_and_analytics/reporting/report_builder.md
_docs/_user_guide/data_and_analytics/reporting/reports_overview.md
_docs/_user_guide/data_and_analytics/reporting/retention_reports.md
_docs/_user_guide/data_and_analytics/reporting/revenue_report.md
_docs/_user_guide/data_and_analytics/reporting/viewing_and_understanding_segment_data.md

Apply Diàtaxis and brand standards to the Your Reports docs.
[BD-3814](https://jira.braze.com/browse/BD-3814)
- N/A …

BD-3814 Apply template standards to Your Reports

---

_docs/_api/endpoints/catalogs/catalog_fields/asynchronous/delete_catalog_field.md
_docs/_api/endpoints/catalogs/catalog_fields/asynchronous/post_create_catalog_fields.md
_docs/_api/endpoints/catalogs/catalog_selections/asynchronous/delete_catalog_selection.md
_docs/_api/endpoints/catalogs/catalog_selections/asynchronous/post_create_catalog_selections.md

GA endpoints include:
POST: Create Catalog Fields
DELETE: Delete Catalog Field
DELETE: Delete Catalog Selection
POST: Create Catalog Selection
- BD-3753 …

BD-3753: Catalog selections and async catalog fields endpoints GA  [MERGE JAN 13]

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
_docs/_user_guide/data_and_analytics/custom_data/custom_events.md

Adding tags to custom attributes GA
- BD-3756 …

BD-3756: Adding tags to custom attributes GA [MERGE JAN 13]

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md

Templating catalog items including Liquid GA
- BD-3754
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managemen …

BD-3754: Templating catalog items including Liquid GA [MERGE JAN 13]

---

_docs/_user_guide/data_and_analytics/data_centers.md

Add article about Braze data centers
- BD-3789
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an …

BD-3789: Add article about Braze data centers

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Update error threshold in the docs to keep them up to date
https://github.com/Appboy/platform/pull/90243/files …

Update error threshold in the docs to keep them up to date

---

_config.yml
assets/js/documents.js

Make external link open a new tab

make external links open its own tab

---

_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/array_of_objects.md
_docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md

Update max size for custom attributes to 100 kb.
[BD-3821](https://jira.braze.com/browse/BD-3821)
- N/A …

BD-3821 Update max size for Custom Attributes

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md

Add that you can preview a selection for a user GA
- BD-3755 …

BD-3755: Preview for selection GA

---

_includes/developer_guide/android/content_cards.md

Missing a space between two different words.
- N/A
- N/A …

Small typo in Android content_cards.md

---

assets/js/broken_redirect_list.js

The comment in `broken_redirect_list.js` was accidently moved up. This PR moves it back down to the end of the file.
- N/A
- N/A …

Move comment back in broken_redirect_list.js

---

_docs/_user_guide/message_building_by_channel/email/using_locales.md

Clarify locales aren't supported in email templates
- BD-3830
- N/A …

BD-3830: Clarify locales aren't supported in email templates

---

_docs/_contributing/home.md

Adding the final `rake` step to the contributing home page so that users know how to start/stop their local server.
- N/A
- N/A …

Add rake steps to contributing home.md

---

_includes/cordova/prerequisites.md

`_/includes/cordova/prerequisites.md` was removed in #8674 . This PR adds it back to prevent `_lang` deployments from breaking.
- N/A
- N/A …

Re-adding '_/includes/cordova/prerequisites.md'

---

_docs/_api/api_limits.md
_docs/_user_guide/analytics/dashboard.md
_docs/_user_guide/analytics/dashboard/api_usage_dashboard.md

Add new article for API usage dashboard GA
Add tip callout in related article
- BD-3815
- January 14, 2025 …

BD-3815: API usage dashboard GA

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Clarify behavior for "at a specific time" for delays
- BD-3750
- N/A …

BD-3750: Clarify behavior for "at a specific time" for delays

---

_docs/_docs_pages/redirects/api_usage_dashboard.md

Fix permalink error for API usage dashboard
- N/A
- N/A …

Fix permalink error

---

_lang/es/_user_guide/message_building_by_channel/sms/sms_campaign_analytics/message_usage.md
_lang/es/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign_analytics/message_usage.md

The the path in the `{% multi_lang_include %}` for these 2 files were accidentally translated. I reverted them back to their english translation so the include points to the right file.
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file …

[ES Lang] Reverting translated include

---

_includes/campaign_analytics.md

Add information about enabling CORS to prevent images from breaking in heatmap previews and exports.
[BD-3838](https://jira.braze.com/browse/BD-3838)
- N/A …

BD-3838 Add CORS info to heatmap docs

---

_docs/_contributing/troubleshooting.md

We recently discovered this new issue with `rake` and `permalinks` so we are adding it to our troubleshooting docs 👍🏽 
- N/A
- N/A …

Add troubleshooting steps for permalink

---

_docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md

Add info about Content Blocks with Connected Content for previewing user paths
- BD-3710
- N/A …

BD-3710: Add info about Content Blocks with Connected Content

---

_docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md

Clarify expected behavior for Canvas entry triggers in user previews 
- BD-3736
- N/A …

BD-3736: Clarify expected behavior for entry in user previews

---

_docs/_user_guide/engagement_tools/canvas/faqs.md

Add FAQ about building Canvases
- BD-3450
- N/A …

BD-3450: Add FAQ about building Canvases

---

_docs/_user_guide/engagement_tools/canvas/canvas_components.md

Add detail about orange connections in Canvas steps
- BD-3770
- N/A …

BD-3770: Add detail about orange connections in Canvas steps

---

_docs/_user_guide/data/custom_data/custom_attributes.md

Add alert for custom attribute data type check
- BD-3711
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#u …

BD-3711: Add alert for custom attribute data type check

---

_docs/_user_guide/analytics/dashboard/api_usage_dashboard.md

Add missing detail about where to find the API usage dashboard
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_manageme …

Add where to find API usage dashboard

---

_docs/_user_guide/data/cloud_ingestion/integrations.md

Snowflake has developed this very helpful guide that will help customers set up an automated pipeline to sync changed fields to Braze. Since we provide limited guidance on Snowflake setup for CDI, I'd like to direct Braze users to this resource. 
- N/A
- N/A …

add link to Snowflake quickstart guide (developed/hosted by snowflake) 

---

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md

Updates introduction to be more accurate of the integration
Style edits throughout
- BD-3716
- N/A …

BD-3716: Update intro and style edits

---

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md

Adding update about WhatsApp pausing marketing messages.
[BD-3841](https://jira.braze.com/browse/BD-3841)
- N/A …

BD-3841 Jan 2025 Meta update

---

_docs/_contributing/bdocs.md
bdocs
scripts/print_unique_syntax.sh

Adding a new command that simply prints all of the unique Markdown syntax supported by Braze Docs. (If I'm missing one, please let me know!)
```bash
$ ./bdocs syntax
This is all of the unique Markdown syntax supported by Braze Docs.
ALERTS
{% alert TYPE %}
{% endalert %}
IMAGE LINK
IMAGE RESIZING
{: style="max-width:NUMBER%;"}
INCLUDES
{% multi_lang_include PATH_TO_INCLUDE %}
LIQUID RAW TAGS
{% raw %}{% endraw %}
TABS
{% tabs %}
{% tab NAME %}
{% endtab %}
{% endtabs %}
SUBTABS
{% subtabs %}
{% subtab NAME %}
{% endsubtab %}
{% endsubtabs %}
TABLE WORD-BREAK
{: .reset-td-br-NUM .reset-td-br-NUM .reset-td-br-NUM .reset-td-br-NUM role="presentation"}
```
- N/A
- N/A
- My style and voice follows the [Braze …

[bdocs] Add command to print unique markdown syntax

---

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md

Update steps and reorganize content for Inbox Vision
- BD-3452
- N/A …

BD-3452: Update steps and reorganize content for Inbox Vision

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/audience_paths.md

Add info about Intelligent Channel filters for Audience Paths step example
- BD-3696
- N/A …

BD-3696: Add info about Intelligent Channel filters

---

_docs/_user_guide/analytics/dashboard/conversions_dashboard.md

Clarify conversions dashboard and custom event metrics
Add missing table syntax
- BD-3510
- N/A …

BD-3510: Clarify conversions dashboard and custom event metrics 

---

_docs/_user_guide/message_building_by_channel/sms/mms/about_mms.md

Update MMS message limits with clarifications.
[BD-3835](https://jira.braze.com/browse/BD-3835)
- N/A …

BD-3835 Update MMS message limits

---

_docs/_api/endpoints/scim.md
_docs/_api/endpoints/scim/get_see_user_account_information.md
_docs/_api/home.md

Clarify description for SCIM endpoint in YAML
Fix description on API home page
- BD-3748
- N/A …

BD-3748: Clarify YAML description for SCIM endpoint

---

_docs/_partners/data_and_infrastructure_agility/customer_data_platform/segment/segment.md

Updates to Destination framework options for Segment (Actions not Classic) because the Braze Classic destination has entered maintenance mode by Segment 
- BD-3558
- N/A …

BD-3558: Updates to Destination framework options for Segment

---

assets/js/broken_redirect_list.js

Fixed a link that was missing a redirect
NONE
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an- …

Fix broken data link

---

_docs/_api/objects_filters/purchase_object.md
_docs/_user_guide/data/custom_data/purchase_events.md

Add mention of product ID naming conventions best practices
- BD-3845
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managem …

BD-3845: Add mention of product ID naming conventions best practices

---

_docs/_developer_guide/home.md
_docs/_developer_guide/platform_integration_guides/tv_and_ott.md

Cleaning up the TV & OTT docs as a part of the [developer detangle project](https://confluence.braze.com/display/PDT/Developer+guide+detangle).
- [BD-3275](https://jira.braze.com/browse/BD-3275)
- N/A …

[BD-3275] TV & OTT tweaks

---

_docs/_developer_guide/banner_cards/integration.md

Required instructions for resizing and visibility changes to Banner Cards on iOS were previously omitted. Adding those in for clarity.
- N/A
- N/A …

Banner Cards: Add instructions for Swift resizing

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/create.md

Add a video that walks through the IAM feature.
[BD-3824](https://jira.braze.com/browse/BD-3824)
- N/A …

BD-3824 Embed IAM video

---

_includes/html_include.html
_layouts/broken_page.html
_layouts/redirect.html
assets/js/hash_redirect.js

Change redirects to allow up to max redirect limit

Change redirect to a number with max

---

_docs/_api/endpoints/messaging/duplicate_campaigns.md
_docs/_partners/data_and_infrastructure_agility/customer_data_platform/tealium/tealium_audience_stream.md
_docs/_partners/message_orchestration/additional_channels/mobile_wallet/passkit.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify_features/shopify_backfill.md
_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md
_docs/_partners/message_orchestration/channel_extensions/surveys/iterate.md
_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md
_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/localizing_a_campaign.md
_includes/developer_guide/android/push_notifications/android_tv.md

Fix links that include `redirected=true`
- BD-3857
- N/A …

BD-3857: Fix links that include `redirected=true`

---

_config.yml

When we renamed `platform_integration_guides` to `platforms` (as well as removed `platform_wide` and `customization`) , we did not update the `nav_expand_list` in `_config.yml`.
- N/A
- N/A …

Add `platforms` to `nav_expand_lists`

---

_docs/_hidden/misc_reference/scim_api_appendix.md

Add the `approve_deny_campaigns` permission to the SCIM appendix.
[BD-3863](https://jira.braze.com/browse/BD-3863)
- N/A …

BD-3863 Add permissions to SCIM appendix

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

Add note that `dispatch_id` will be removed from several events in the future.
[BD-3834](https://jira.braze.com/browse/BD-3834)
- N/A …

BD-3834 Add note about dispatch_id to Currents events

---

_docs/_user_guide/engagement_tools/campaigns/testing_and_more/campaign_funnel_report.md
_docs/_user_guide/engagement_tools/campaigns/testing_and_more/retention_reports.md
_docs/_user_guide/engagement_tools/canvas/testing_canvases/canvas_funnel_reports.md
_docs/_user_guide/engagement_tools/canvas/testing_canvases/retention_reports.md

Replace old links with updated ones for YAML redirects for campaign and Canvas analytics
- N/A
- N/A …

Update YAML redirects for campaign and Canvas analytics

---

_includes/archive/setting_user_ids/aliasing.md
_includes/developer_guide/android/_global/gifs.md
_includes/developer_guide/android/initialization/runtime_configuration.md

As part of our oncall process, we're trying to make small improvements to our docs.
- N/A
- N/A …

Android small updates

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Add EA banner for deleting custom data.
[BD-3870](https://jira.braze.com/browse/BD-3870)
- N/A …

BD-3870 Add Early Access note for custom data deletion

---

_includes/developer_guide/android/push_notifications/customization/html_messages.md

The supported HTML tags for Android are not currently listed. Keep in mind, this information was pulled from Google's `Html.java` file directly and this information is not listed online in this specific format (that I could find).
- [BD-3807](https://jira.braze.com/browse/BD-3807)
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for …

[BD-3807] List supported HTML tags

---

assets/js/broken_redirect_list.js

Add redirect (to be removed later)
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image …

Add redirect

---

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md

Reverts braze-inc/braze-docs#8823

Revert "Update creating_a_webhook.md"

---

assets/js/feedback.js

add page language to feedback

---

_docs/_user_guide/getting_started/terms_to_know.md

Terms to know audit, edits include:
* Updating old links
* Updating definitions to align with majority formatting
- N/A
- N/A …

Terms to know audit

---

_docs/_user_guide/analytics/dashboard/conversions_dashboard.md

Update "SMS Delivery" to "SMS Click"
- BD-3869
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an …

BD-3869: Update "SMS Delivery" to "SMS Click"

---

_docs/_user_guide/engagement_tools/landing_pages/connect_domain.md

Remove mentions of "subdomain" to help make it clearer that Apex domains aren't supported. Also add an FAQ about using subdomains that are already being used as a main website or sending domain.
[BD-3867](https://jira.braze.com/browse/BD-3867)
- N/A …

BD-3867 Update landing page custom domains

---

_docs/_developer_guide/content_cards.md

A few of the links were not pointing to the right places on this landing page.
- [BD-3879](https://jira.braze.com/browse/BD-3879)
- N/A …

[BD-3879] Fixing links on content_cards.md

---

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md

The Currents team has received multiple customer questions in the past couple of weeks asking about the fact that our example IAM policy has the `s3:GetObject` permission. I would like to add a clarifying note to hopefully answer the questions before they become PQs.
Fixes https://servicedesk.braze.com/browse/PQ-7758
- N/A …

[Currents] Add note about why Currents requires s3:GetObject permissions - PQ-7758

---

_includes/developer_guide/android/push_notifications.md

Setting up alerts for exceeding the FCM rate limit
- BD-3840
- N/A …

BD-3840: Notifications for exceeding FCM rate limit EA

---

_docs/_api/objects_filters/connected_audience.md

Add considerations for connected audience filters that state connected audiences can't filter users by default attributes
[BD-3873](https://jira.braze.com/browse/BD-3873)
- N/A …

BD-3873 Considerations for connected audience filters

---

_docs/_user_guide/getting_started/workspaces.md

Clarify column name and add links to description for Braze user permissions (dashboard users)
- BD-3860
- N/A …

BD-3860: Clarify column name and description for Braze user permissions

---

_docs/_user_guide/brazeai/intelligence/faqs.md

Remove expanded TOC in Intelligence FAQ

---

_plugins/sdk_min_versions_tag.rb

This PR addresses two issues:
1. Due to changing `platform_integration_guides` to `platforms` now all SDK min version chips always redirect before landing on the correct page. I updated their code so they are pointing to file directly instead of redirect.
2. I was asked to change `iOS Swift` to just `Swift` for the swift-specific chips.
- N/A
- N/A …

Updating 'sdk_min_versions' chips

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Adding some clarifications as we got 1 PQ on this. 
PQ-7902 …

Update Loudly Notify Docs

---

_docs/_user_guide/getting_started/workspaces.md

Clarify details for subscription status in workspaces
- N/A
- N/A …

Clarify subscription status row details

---

_docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md

Add information about using `json_scape` with Liquid tags that might break the JSON format. This allows the correct text to be templated into the message.
[BD-3865](https://jira.braze.com/browse/BD-3865)
- N/A …

BD-3865 Add section about json_escape and Liquid tags

---

scripts/utils/get_blog_links.py

Adding a small utility script that can be used to generate the list of pages on Braze Docs linking to Braze blog posts. This can be used to automate the content found on this confluence page:
- https://confluence.braze.com/display/PDT/List+of+pages+linking+to+Braze+blog+posts
```bash
cd braze-docs
git checkout develop; git pull
git checkout script-to-generate-list-of-blogs
./scripts/utils/get_blog_links.py
./scripts/utils/get_blog_links.py > list.md
```
- N/A
- N/A
- …

Util script to generate list of Braze blogs

---

_docs/_developer_guide/platforms/flutter/sdk_integration.md

https://servicedesk.braze.com/browse/PQ-7338
> Context:
>  Flutter requires integrators to allocate a BrazePlugin instance. Other platforms have different implementations that don't have the same issue - RN use static methods and Unity has a different binding architecture
- …

[Untracked] Add Flutter docs warning against having multiple `BrazePlugin` instances

---

_includes/developer_guide/android/push_notifications.md

We would like to make the docs clearer + specify some of the new findings we discovered on the Google side in terms of how to request a quota increase. …

Update FCM quota docs

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Add note about admins can perform custom data deletion only and minor edits
- BD-3891
- N/A …

BD-3891: Add note about admins can perform custom data deletion only

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

Remove note that says coupon codes aren't supported
[BD-3893](https://jira.braze.com/browse/BD-3893)
- N/A …

BD-3893 Coupon codes available now

---

_docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md

Update steps for registering domains for SparkPost
- BD-3868
- N/A …

BD-3868: Update steps for registering domains for SparkPost

---

_docs/_api/objects_filters/messaging/apple_object.md

Add example for push alert object
BD-3880
- N/A …

BD-3880: Add example for push alert object

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Add 300 item limit for blocklisting data
- BD-3892
- N/A …

BD-3892: Add 300 item limit for blocklisting data

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/conditional_logic.md

This converts a step-by-step section into a tutorial, and moves informational content about tags into their own section.
[BD-3658](https://jira.braze.com/browse/BD-3658)
- N/A …

BD-3658 Create tutorial for Liquid conditional logic

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md

Clarify JSON object support for catalogs
- BD-3850
- N/A …

BD-3850: Clarify JSON object support for catalogs

---

_docs/_developer_guide/platforms/legacy_sdks/ios/push_notifications/integration.md
_docs/_developer_guide/platforms/react_native/push_notifications.md
_includes/developer_guide/swift/apns_certificate.md

I integrated the Braze React Native SDK into a company project and wanted to enhance the documentation with the knowledge I gained from the experience.
- [BD-3848](https://jira.braze.com/browse/BD-3848)
- N/A …

Enhance push notifications doc

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

Add docs for WhatsApp video messages EA, which supports hosted URL videos
[BD-3897](https://jira.braze.com/browse/BD-3897)
- N/A …

BD-3897 WhatsApp video messages EA

---

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md

Our docs state to find your "Snowflake ID" by running `CURRENT_ACCOUNT()`. However, this returns `account_locator`--which is actually what should be used, _not_ `account_identifier`.
- [BD-3894](https://jira.braze.com/browse/BD-3894)
- N/A
- If I updated or replaced an image, …

[BD-3894] Snowflake fix: account ID to account locator

---

_docs/_user_guide/engagement_tools/segments/suppression_lists.md

Add more details to suppressing list usage in campaigns and Canvases.
[BD-3882
](https://jira.braze.com/browse/BD-3882)
- N/A …

BD-3882 Suppression list updates

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2025.md
_docs/_help/release_notes/2025/2_4_25.md

February release notes 
- N/A
- N/A
- If …

Fixed release notes

---

_docs/_user_guide/administrative/app_settings/company_settings/notification_preferences.md

Add notification for campaign and Canvas volume limit
- BD-3864
- N/A …

BD-3864: Add notification for campaign and Canvas volume limit

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Alert for webhook and Connected Content errors is per workspace
- BD-3900
- N/A …

BD-3900: Alert for webhook and Connected Content errors is per workspace

---

assets/js/broken_redirect_list.js

Two lines are missing a `;` char at the end of the line.
- N/A
- N/A …

Fix: Add missing ';' in broken_redirect_list.js

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing/faq.md

Add FAQs for the multivariate and A/B testing features
[BD-2544](https://jira.braze.com/browse/BD-2544)
- N/A …

BD-2544 Add multivariate and AB testing FAQs

---

_docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md

Add FAQ and alt text for AI item recommendation
- BD-3916
- N/A …

BD-3916: Add FAQ and alt text for AI item recommendation

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

Add supported features for WhatsApp outbound messages, including file types for video outbound messages.
[BD-3917](https://jira.braze.com/browse/BD-3917)
- N/A …

BD-3917 Update WhatsApp outbound features

---

_docs/_developer_guide/content_cards/logging_analytics.md

The existing hyperlink resulted in a 404 error page
The existing hyperlink was taking to a 404 Error page. 
- N/A
- N/A
- [] I confirm that my PR meets the following: …

Update iOS hyperlink

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
_docs/_user_guide/personalization_and_dynamic_content/liquid/faq.md

Removed an incorrect (and awkward) Liquid snippet and replaced another with a more accurate snippet.
[BD-3913](https://jira.braze.com/browse/BD-3913)
- N/A …

BD-3913 Correct two Liquid snippets

---

_docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md

Clarify same custom event for previewing user paths
- BD-3899
- N/A …

BD-3899: Clarify same custom event for previewing user paths

---

_docs/_user_guide/getting_started/workspaces.md

Updated the table of workspace approaches to state that you can copy certain types of campaigns across workspaces.
[BD-3910](https://jira.braze.com/browse/BD-3910)
- N/A …

BD-3910 Update overview of workspace approaches

---

_docs/_partners/isv_partners/currents_integration.md

Adding details about Currents retries.
[BD-3875](https://jira.braze.com/browse/BD-3875)
- N/A …

BD-3875 Add info about Currents retries

---

_docs/_user_guide/data/data_points.md

Add note about the data points table being illustrative. It doesn't necessarily show the exact capitalization/formatting of data type fields, which can be found on the relevant documentation for each ingestion type..
[BD-3924](https://jira.braze.com/browse/BD-3924)
- N/A
- If …

BD-3924 Add note about data type formatting

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

Add a permalink to the Message Engagement Events Glossary so that it can be referenced with a shorter link.
None
- N/A …

Add permalink for Message Engagement Events Glossary

---

_docs/_developer_guide/platforms/android/live_updates.md

A placeholder was left in the doc for the permissions. Adding it now.
- N/A
- N/A …

Hotfix: add permissions to android live udpates

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md
assets/js/broken_redirect_list.js

Fix broken links and redirects for Message Engagement Events
[BD-3939](https://jira.braze.com/browse/BD-3939)
- N/A …

BD-3939 Fix Message Engagement Events links

---

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake/data_retention.md

Specify that PII is automatically deleted every two years for events data in Snowflake.
[BD-3854](https://jira.braze.com/browse/BD-3854)
- N/A …

BD-3854 Call out Snowflake data retention for PII

---

_docs/_developer_guide/banner_cards/integration.md

banners html

---

_docs/_api/basics.md

Updating beta alert from note to important
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating- …

Update alert type

---

_docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md

Update note that Canvas entry properties are supported in Content Blocks
Add missing alt text
- BD-3929
- N/A …

BD-3929: Clarify Canvas entry properties are supported in Content Blocks

---

_docs/_user_guide/data/cloud_ingestion/faqs.md
_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/pre_post_launch_checklist.md
_docs/_user_guide/engagement_tools/testing/race_conditions.md

- Cleans up the definition of race condition
- Reorganizes headers for clarity
- Adds best practices for 3 types of race conditions
- BD-3915
- N/A …

BD-3915: Doc improvements for race conditions

---

_layouts/broken_page.html
assets/js/hash_redirect.js

Fix redirects `?` being replace incorrectly

fix redirects

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Loudly Notify is in GA. I'm removing the note that the feature is still in EA.
- N/A
- N/A …

Automated emails and Message Activity Log entries GA

---

_includes/metrics.md

Flip-flop the definitions for the "Lifetime value per user" and the "Average daily revenue". 
[BD-3960](https://jira.braze.com/browse/BD-3960)
- N/A …

BD-3960 Fix Revenue Report metrics

---

_docs/_partners/data_and_infrastructure_agility/cloud_storage/amazon_s3.md

Customers are attempting to use this and causing frustration for both of us
[PQ-8095](https://jira.braze.com/browse/PQ-8095)
- N/A …

[PQ-8095] Note that Currents does not support buckets with Object Lock

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md

Correct alert that says Confidence will only appear if you have an optimization. Confidence will appear if you have a control group.
[BD-3927](https://jira.braze.com/browse/BD-3927)
- N/A …

Bd-3927 Correct confidence alert

---

_docs/_developer_guide/platforms/web/analytics/setting_custom_attributes.md

You can only increase individual arrays that are manually set in Data Type
- N/A
- N/A …

Clarify detail for arrays limit

---

_docs/_developer_guide/platforms/legacy_sdks/ios/advanced_use_cases/locations_and_geofences.md
_docs/_developer_guide/platforms/swift/geofences.md
_includes/developer_guide/android/geofences.md

Clarify geofences are available for all platforms
- BD-3884
- N/A …

BD-3884: Clarify geofences are available for all platforms

---

_docs/_user_guide/engagement_tools/testing/multivariant_testing.md

Add tip to only add A/B tests to new campaigns, not to launched campaigns. Doing the latter can cause incorrect or misleading results.
[BD-3898](https://jira.braze.com/browse/BD-3898)
- N/A …

Bd-3898 Add warning about adding a/b test to launched campaign

---

_docs/_user_guide/engagement_tools/testing/race_conditions.md

Clarify details for best practices for race conditions
- N/A
- N/A …

Clarify details for best practices

---

_docs/_user_guide/data/report_metrics.md
_includes/metrics.md

Update/add report metrics that haven't been documented yet, are confusing, or incorrect.
[BD-3791](https://jira.braze.com/browse/BD-3791)
- N/A …

BD-3791 Update Report Metrics Glossary

---

_docs/_developer_guide/authentication.md
_docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md
_docs/_user_guide/message_building_by_channel/sms/sms_subscription_group.md
_docs/_user_guide/message_building_by_channel/whatsapp/message_processing/opt-ins_and_opt-outs.md
_docs/_user_guide/message_building_by_channel/whatsapp/user_subscription.md

Noticed some outdated links that point to the iOS AppboyKit SDK docs instead of the new Swift SDK docs.
Ignoring any cases where AppboyKit method documentation is linked under the `/legacy_sdks/ios` path since those are intentional.
- N/A
- N/A …

Update outdated Appboy method doc links

---

_docs/_partners/isv_partners/currents_integration.md

This is work migrated from #8955 .  @alexandre-bolduc-braze was the original PR owner and i made edits. i moved the work over without commit history.
- N/A
- N/A …

Update currents integration docs

---

_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Clarify why double-nested segments aren't allowed and that you should recreate the exact segment instead.
[BD-3952](https://jira.braze.com/browse/BD-3952)
- N/A …

BD-3952 Explain why double-nested segments aren't allowed

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/aborting_connected_content.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/connected_content_retries.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/public_apis.md
_docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md
_docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md
_docs/_user_guide/personalization_and_dynamic_content/key_value_pairs.md
_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md
_docs/_user_guide/personalization_and_dynamic_content/promotion_codes/migrating_from_data_feeds.md

Applying Diàtaxis standards to Personalization and Dynamic Content. Liquid has already been done, so that section is left out.
[BD-3982](https://jira.braze.com/browse/BD-3982)
- N/A …

BD-3982 Apply Diàtaxis standards to Dynamic Content

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Updates to the intro and mentions of "properties" to "variables"
- BD-3974
- N/A …

BD-3974: Update intro and mentions of properties

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md

Clean up wording
Reorganize headings
- N/A
- N/A …

Clean up in-app messages for Canvas article

---

_docs/_partners/home.md

Add Constructor to the list of partners.
None
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an- …

Add Constructor to partners list

---

_docs/_partners/message_personalization.md

Remove "_" from link
- N/A
- N/A
- If my …

Remove "_" from link

---

_includes/developer_guide/react_native/sdk_integration.md

There's a typo in the React Native integration docs - this PR amends that.
- N/A
- N/A …

Update title for React Native integration docs

---

Rakefile
_data/i18n.yml
_lang/_config_de.yml
public/index_de.html
public/index_es.html
public/index_pt-br.html

Allow building Germain version using `rake de`

Add DE build options

---

_docs/_developer_guide/platforms/swift/live_activities.md

Wrote some additional documentation to clarify the usage and expectations of implementing `brazeActivityId` for Live Activities push-to-start. This will make it clearer than it previously was.
- N/A
- N/A …

Add clarifying documentation for iOS Live Activities `brazeActivityId`

---

_docs/_user_guide/analytics/dashboard/email_performance_dashboard.md

Clarify Engagement Report by Device details to help with email PQ reduction
- BD-3969
- N/A …

BD-3969: Clarify Engagement Report by Device details

---

_includes/message_usage.md

Remove EA banner for message usage dashboard
- BD-4002
- N/A …

BD-4002: Remove EA banner

---

_docs/_partners/canvas_steps/faq.md
_docs/_partners/canvas_steps/google_audience_sync.md

Add FAQ and minor detail to Audience Sync articles
- BD-3970
- N/A …

BD-3970: Add FAQ and minor detail to Audience Sync articles

---

_docs/_user_guide/administrative/app_settings/push_ttl_settings.md
_docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md

Updates the Push TTL docs to add more usable information in relevant locations.
**Current settings doc:**
**Revised:**
I purposefully did not update the image in this, given that I will be logging a UX debt ticket for the settings page and the other related push for image updates.
**Current message-level doc:**
**Note:** That example is misleading, it seems to imply that you can extend the TTL past 4 weeks, which is not correct.
**Revised:**
- [BD-4007](https://jira.braze.com/browse/BD-4007)
- N/A
- My content contains …

BD-4007: Improve Push TTL docs

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Update Liquid for Context step
- [BD-4013](https://jira.braze.com/browse/BD-4013)
- N/A …

BD-4013: Update Liquid for Context step

---

_docs/_user_guide/message_building_by_channel/email/faq.md
_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md

Add FAQ about email hard bounces
- BD-3947
- N/A …

BD-3947: Add info about email hard bounces

---

_docs/_api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns.md

We got a [PQ](https://servicedesk.braze.com/browse/PQ-7780) in which a customer was confused why their /campaigns/trigger/schedule/update calls appeared to be doing nothing. This docs update can help prevent similar PQs in the future.
https://servicedesk.braze.com/browse/PQ-7780 …

[MP-5920] Update /campaigns/trigger/schedule/update Docs With Local Time Disclaimer

---

_docs/_user_guide/administrative/access_braze.md

Add a section that says if you're having dashboard performance issues, try clearing your browser cache and cookies.
[BD-3950](https://jira.braze.com/browse/BD-3950)
- N/A …

BD-3950 Clear browser cache and cookies to solve performance issues

---

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/copying_to_workspace.md

Describe behavior for copying campaigns with feature flags across workspaces
- BD-3971
- N/A …

BD-3971: Copying campaigns with feature flags edit

---

_docs/_user_guide/administrative/access_braze.md

If you get certain errors on your dashboard and in your browser console, your browser is outdated.
[BD-3957](https://jira.braze.com/browse/BD-3957)
- N/A …

BD-3957 Error messages for an outdated browser

---

_docs/_user_guide/administrative/app_settings/company_settings/security_settings.md

Update names of security events so they match the actual names in the security report.
[BD-3945](https://jira.braze.com/browse/BD-3945)
- N/A …

BD-3945 Update names of reported security events

---

_docs/_user_guide/brazeai/recommendations/using_recommendations.md

_I missed a broken image reference in #8999_
- N/A
- N/A …

Fix image reference

---

_docs/_user_guide/data/custom_data/custom_attributes.md
_docs/_user_guide/data/custom_data/custom_events.md

[CO-3334](https://jira.braze.com/browse/CO-3334)

CO-3334: update usage report limit

---

_docs/_user_guide/data/custom_data/custom_events.md

[CO-3335](https://jira.braze.com/browse/CO-3335)

CO-3335: remove EA banner for exporting data

---

_includes/rate_limits.md

September 2021 was a long time ago, so we want to remove the references to that date from our rate limit docs.
- [BD-4044](https://jira.braze.com/projects/BD/issues/BD-4044)
- [CO-3333](https://jira.braze.com/browse/CO-3333)
- N/A
- If I updated or replaced an image, I did …

CO-3333 Remove Sep 2021 reference from rate limit section.

---

_docs/_user_guide/data/custom_data/custom_attributes.md
_docs/_user_guide/data/custom_data/custom_events.md
_docs/_user_guide/data/custom_data/managing_custom_data.md

[CO-3328](https://jira.braze.com/browse/CO-3328)

CO-3328: update docs on blocklisting limits from 10 to 100

---

_docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md

https://jira.braze.com/browse/CO-3331

[CO-3331] Clarifies data point consumption

---

_docs/_user_guide/data/export_braze_data/message_archiving.md

The push platforms for Message Archiving are incorrectly documented. This PR serves to improve our documentation, so that it more accurately reflects reality.
- [MOPS-3266](https://jira.braze.com/browse/MOPS-3266)
- [PQ-8373](https://servicedesk.braze.com/browse/PQ-8373)
- N/A …

[MOPS-3266] Fix Message Archiving push platforms

---

_docs/_user_guide/data/export_braze_data/message_archiving.md

The file path structure for Message Archiving is incorrectly documented. This PR serves to improve our documentation, so that it more accurately reflects reality.
- [MOPS-3265](https://jira.braze.com/browse/MOPS-3265)
- [PQ-8440](https://servicedesk.braze.com/browse/PQ-8440)
- [PQ-8449](https://servicedesk.braze.com/browse/PQ-8449)
- N/A …

[MOPS-3265] Fix Message Archiving file path structure

---

_docs/_user_guide/data/custom_data/custom_events/nested_objects.md

https://jira.braze.com/browse/CO-3332

[CO-3332] Updated valid year range for nested custom events page

---

_docs/_api/endpoints/catalogs.md
_docs/_api/endpoints/catalogs/catalog_items/asynchronous/put_update_catalog_items.md
_docs/_api/endpoints/catalogs/catalog_items/synchronous/put_update_catalog_item.md
_docs/_api/home.md

[CO-3341](https://jira.braze.com/browse/CO-3341)

CO-3341: clarify PUT behaviour for catalog/items endpoint

---

_docs/_api/errors.md

Add info about 5XX class errors from a SF KB article.
[BD-4038](https://jira.braze.com/browse/BD-4038)
- N/A …

BD-4038 Add 5XX error information

---

_docs/_user_guide/administrative/app_settings/message_activity_log_tab.md

Add details about Message Activity Log storage duration and the number of errors stored.
[BD-3914](https://jira.braze.com/browse/BD-3914)
- N/A …

BD-3914 Add details to Message Activity Log

---

_docs/_api/endpoints/user_data/post_users_merge.md

[CO-3343](https://jira.braze.com/browse/CO-3343)
- Should we also update the error message for the translated pages?

CO-3343: update users merge API error message

---

_docs/_help/release_notes.md
_includes/campaign_analytics.md
_includes/metrics.md

Add new Deferrals event
- BD-4012
- N/A
- …

BD-4012: Add new Deferrals event

---

bdocs

`jq` is required for the `release` command in `bdocs` but it is hard to determine this due to how error handling works. i've added a check to the `release` command that tell's the end-user to install before they can use this command.
- N/A
- N/A …

Add 'jq' check to bdocs

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md

Should resolve PQs where customers are confused about why we're temporarily exceeding the rate limit (e.g. https://servicedesk.braze.com/browse/PQ-8239)
- https://servicedesk.braze.com/browse/PQ-8239
- https://jira.braze.com/browse/MP-5923
- N/A …

[MP-5923] Add Disclaimer Stating That We May Slightly Exceed Rate Limit

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Clarifying what happens when custom attribute data doesn't match its specified type.
- [BD-4058](https://jira.braze.com/projects/BD/issues/BD-4058)
- [CO-3347](https://jira.braze.com/browse/CO-3347)
- N/A …

CO-3347 Custom data: clarify data type coercion.

---

_docs/_help/release_notes.md

10am to 10 am
- N/A
- N/A
- If my PR is …

Fix time spacing

---

_docs/_user_guide/personalization_and_dynamic_content/connected_content/user_profile_fields_connected_content.md

Feature restriction was not documented.  Came up in [PQ-7687](https://servicedesk.braze.com/browse/PQ-7687)
- [MP-5815](https://jira.braze.com/browse/MP-5815)
- N/A …

[MP-5815] Clarify lack of rerendering with catalogs tags

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md

[CO-3342](https://jira.braze.com/browse/CO-3342)
Adds a note that unsubscribe events are optional, and the ways users can be unsubscribed without sending the event.

CO-3342 add note that unsubscribe events are optional

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

[CO-3346](https://jira.braze.com/browse/CO-3346)
- move EA banner for custom data deletion higher, for better visibility

CO-3346: move EA banner for custom data deletion to a more visible section

---

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/best_practices.md
_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/best_practices.md

Add missing info from KB article from BD-3674
- BD-3674
- N/A …

Add missing info for scheduling campaigns and Canvases

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

[CO-3339](https://jira.braze.com/browse/CO-3339)
- For in browser catalogs editing, specify which permissions are required

CO-3339: update permissions required for catalogs in-browser editing

---

_docs/_user_guide/data/custom_data/custom_attributes/array_of_objects.md
_docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md

At least one customer was under the impression that they could use the `$update` operator to delete nested keys from inside an array of objects. This update clarifies that this won't work, and provides a workaround.
- [CO-3329](https://jira.braze.com/browse/CO-3329)
- [BD-4072](https://jira.braze.com/browse/BD-4072)
- N/A …

CO-3329 Custom data: _merge_objects won't delete data from array of objects.

---

_docs/_user_guide/administrative/access_braze/navigation.md

Updated nav date was outdated
- N/A
- N/A …

Updated nav date was outdated

---

_docs/_partners/message_orchestration/channel_extensions/email_templates/email_love.md

Added Isaiah's review edits that weren't incorporated in the original PR.
None
- N/A …

Email Love Docs team edits

---

_docs/_user_guide/personalization_and_dynamic_content/deep_linking_to_in-app_content.md

Update old links to GA4
- BD-4057
- N/A
- …

BD-4057: Update old links to GA4

---

_docs/_user_guide/engagement_tools/segments/user_profiles.md

Add that Braze ID can be found on user profiles
- BD-4024
- N/A …

BD-4024: Add that Braze ID can be found on user profiles

---

_docs/_developer_guide/banner_cards/integration.md

Provide React Native information
- SDK-5420
- Date TBD. …

[SDK-5420] rn banners

---

_plugins/sdktabs.rb
assets/js/documents.js

Force toc to update if other conditions are not meet

Always update toc nav

---

_docs/_partners/canvas_steps/google_audience_sync.md

Update mobile advertiser ID description
- BD-4098
- N/A …

BD-4098: Update mobile advertiser ID description for audience sync

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Personalized delay and extended delay EA
- BD-3973
- N/A …

BD-3973: Personalized delay and extended delay EA

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Updating header based on feedback, will update it to a more general header after more Canvas steps can be used with Context step
- N/A
- N/A …

Update header to be more accurate with current EA

---

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status.md
_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md

Add detail about same phone numbers for external IDs
- BD-3876
- N/A …

BD-3876: Add detail about same phone numbers for external IDs

---

_includes/archive/setting_user_ids/aliasing.md

There are codes for aliasing users in Android, Web, and iOS but looks like Swift content was never added to the include file even though its being included in pages.
> **Note:** No vercel right now, so you may need to test locally to ensure the content is being included correctly.
- [BD-4094](https://jira.braze.com/browse/BD-4094)
- N/A …

[BD-4094] Add Swift option to Aliasing users code

---

_docs/_api/endpoints/subscription_groups/post_update_user_subscription_group_status_v2.md

Add missing parameter use_double_opt_in_logic
- BD-4102
- N/A …

BD-4102: Add missing parameter use_double_opt_in_logic

---

_docs/_help/help_articles/push/push_token_migration.md

**From the ticket:** We had a recent PQ relating to a case where the customer integrated the braze sdk first while staying with their previous push provider under the impression push tokens would still migrate.
- [BD-4096](https://jira.braze.com/browse/BD-4096)
- N/A
- If I …

[BD-4096] Considerations for web push tokens

---

_docs/_user_guide/administrative/access_braze/accessing_your_account.md

You can't log in with your password after using SSO.
[BD-3946](https://jira.braze.com/browse/BD-3946)
- N/A …

BD-3946 Can't log in with password after using SSO

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md

Removed a duplicate bracket in a Liquid snippet
[BD-4117](https://jira.braze.com/browse/BD-4117)
- N/A …

BD-4117 Fix Liquid snippet brackets

---

assets/download_file/data-sharing-raw-table-schemas.txt

[DLK-2766](https://jira.braze.com/browse/DLK-2766)
Include field level comments in the[ public schema](https://www.braze.com/docs/assets/download_file/data-sharing-raw-table-schemas.txt) we generate for Data Sharing  in addition to the raw schema. 
- N/A
- N/A
- If I updated …

[DLK-2766] add field level comments for datalake views

---

_docs/_user_guide/data/user_data_collection/user_profile_lifecycle.md

Added risk of using emails or hashed emails as `external_id`s.
[BD-4086](https://jira.braze.com/browse/BD-4086)
- N/A …

BD-4086 Risk of using emails or hashed emails as external IDs

---

_docs/_user_guide/engagement_tools/landing_pages/creating_pages.md

Fixing the bad link in the landing pages doc.
- N/A
- N/A …

Hotfix: landing pages link

---

_docs/_developer_guide/content_cards/customizing_feed.md
_includes/developer_guide/android/push_notifications.md

1. Quota emailing is in GA.
2. There was a confused customer asking about 60 seconds automatic refresh. https://servicedesk.braze.com/browse/PQ-8683
- N/A
- N/A …

Update Push and CC docs

---

_includes/developer_guide/android/push_notifications.md

Adjusted language so that it's clear that proper setting up of a small icon means it will properly display.
[BD-3948](https://jira.braze.com/browse/BD-3948)
- N/A …

BD-3948 Adjust language for properly creating small icons

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs.md

[CO-3338](https://jira.braze.com/browse/CO-3338)
- As part of an effort to reduce PQ's, this PR adds a section on catalog limits to the main catalogs page clarifying how we calculate storage.

[CO-3338] Add a section to the main catalogs page clarifying how limits work

---

_docs/_user_guide/brazeai/intelligence/intelligent_timing.md

Raised in docs feedback regarding wanting more clarity about what channels contribute to the optimal time calculation. This information is documented in the [FAQ](https://www.braze.com/docs/user_guide/brazeai/intelligence/faqs/#calculations), this PR adds that context to the main doc.
- N/A
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_ …

Pull FAQ entry on timing calculations into the "How it works" section

---

_docs/_user_guide/brazeai/intelligence/faqs.md

Flagged from docs feedback, the current FAQ entry for Machine Opens implies that those opens are only auto-opens, when in fact they also include the proportion of “opens” that are affected by Apple’s Mail Privacy Protection (MPP) for iOS 15. Revised by removing that implication and linking to the glossary entry for extra context instead.   
- N/A
- N/A …

Add link to Machine Opens glossary entry

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

Adds back list-unsubscribe for property details
- N/A
- N/A …

Adds back list-unsubscribe for property details

---

_docs/_partners/data_and_infrastructure_agility/workflow_automation/fivetran.md

Updating Fivetran article to display updating Currents UI
None
- N/A …

Docs feedback: Update UI in Fivetran

---

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md

SVG file types are supported by the media library.
None
- N/A …

Docs Feedback: Add SVG to Media Library file types

---

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md

Made minor grammatical edits, the Liquid is correct for updating a user subscription status to unsubscribed is: **${set_user_to_unsubscribed_url}**
- BD-3938
- N/A …

Minor grammatical edits

---

Gemfile.lock

update rack 3.1.11

---

_docs/_user_guide/message_building_by_channel/email/templates/link_template.md

Clarified what the link template preview does.
[BD-4214](https://jira.braze.com/browse/BD-4214)
- N/A …

BD-4214 Docs feedback: Clarify link template preview docs

---

_docs/_user_guide/message_building_by_channel/whatsapp/overview.md

Remove outdated limitation about not being able to have multiple WhatsApp Business Accounts.
[BD-4215](https://jira.braze.com/browse/BD-4215)
- N/A …

BD-4215 Docs feedback: Remove outdated WhatsApp limitation

---

_docs/_api/endpoints/user_data/post_user_track.md

Docs feedback: Update step path to API usage dashboard instead of API limits
- N/A
- N/A …

Docs feedback: Update to API usage dashboard instead of API limits

---

_docs/_user_guide/data/custom_data/event_naming_conventions.md

Add examples of naming conventions for custom events
- BD-4217
- N/A …

BD-4217 Docs feedback: Add examples of naming conventions for events

---

_docs/_user_guide/engagement_tools/landing_pages/creating_pages.md
_docs/_user_guide/engagement_tools/landing_pages/tracking_users.md

rename url handle

---

_docs/_user_guide/administrative/app_settings/exports_log.md

Remove EA banner for export logs
- BD-4228
- N/A …

BD-4228: Export Logs GA

---

_docs/_developer_guide/platforms/legacy_sdks/ios/push_notifications/troubleshooting.md
_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
_docs/_user_guide/message_building_by_channel/push.md
_docs/_user_guide/message_building_by_channel/push/troubleshooting.md
_includes/developer_guide/android/push_notifications/troubleshooting.md
assets/js/broken_redirect_list.js

Created a troubleshooting page for the Push channel, which absorbs a Help page and missing content from an SF KB article.
[BD-4043](https://jira.braze.com/browse/BD-4043)
- N/A …

BD-4043 Create Push troubleshooting page

---

_docs/_user_guide/data/user_data_collection/user_import.md

Adding troubleshooting items to the User Import page.
[Bd-3937](https://jira.braze.com/browse/BD-3937)
- N/A …

BD-3937 Update User Import troubleshooting

---

_docs/_user_guide/message_building_by_channel/whatsapp/user_phone_numbers.md

The UK phone number example would actually be dialled with a leading zero i.e. 0207 when dialled from a UK phone. The E.164 version of the number removes the leading zero, so that part of the documentation is correct.
- N/A
- N/A …

Corrected example UK local phone number, which should include a leading 0

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/advancement.md

Add expected behavior for users who are frequency capped on a Canvas step.
[BD-4000](https://jira.braze.com/browse/BD-4000)
- N/A …

BD-4000 Behavior for users frequency capped in Canvases

---

_docs/_api/endpoints/user_data/post_user_delete.md

If users have a use case that doesn't work with the bulk deletion API, they can contact Support for assistance.
[BD-3997](https://jira.braze.com/browse/BD-3997)
- N/A …

BD-3997 Support can assist with bulk user deletion

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Adding details to Email Available and Email Address segmentation filters to highlight differences.
[BD-3949](https://jira.braze.com/browse/BD-3949)
- N/A …

BD-3949 Add details to Email Available and Email Address filters

---

_docs/_user_guide/engagement_tools/segments/segment_extension.md

Adding FAQs to Segment Extensions so they can be removed from an associated SF KB article.
[BD-4030](https://jira.braze.com/browse/BD-4030)
- N/A …

BD-4030 Add FAQs to Segment Extensions

---

_docs/_api/api_limits.md

Fix broken links for api documentation 
- see: https://brazetechnology.slack.com/archives/G0140E8A210/p1741389195726559 
- N/A …

fix broken CDI API docs links 

---

_docs/_user_guide/data/user_data_collection/user_import.md

Removing EA banner b/c importing with email address and phone number GA 
- BD-4212
- N/A …

BD-4212: Importing with email address and phone number GA - MERGE 3/10

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Add JSON parsing edge case for context type
- BD-4111
- N/A …

BD-4111: Add JSON parsing edge case for Context step

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md

Update Canvas entry properties Liquid to context
- BD-4223
- N/A …

BD-4223: Update Canvas entry properties Liquid to context

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Updated segmentation filters to add the Unformatted Phone Number filter.
[BD-4177](https://jira.braze.com/browse/BD-4177)
10 March 2025 …

BD-4177 Unformatted Phone Number segmentation filter & other updates MERGE 3/10

---

_docs/_api/endpoints/export/campaigns/get_campaign_analytics.md

The "Export campaign analytics" docs do not accurately reflect the actual output.
This PR updates the multichannel response to correct the individual channel-level fields. …

Update campaign analytics API docs

---

_docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_stories.md

Clarify selecting iOS **or** Android for Push Stories option to appear
- BD-4205
- N/A …

BD-4205: Clarify selecting iOS or Android for Push Stories

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md

Update Canvas entry properties to context
- BD-4109
- N/A …

BD-4109: Update Canvas entry properties to context

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/back_in_stock_notifications.md

Clarify catalog item stock for user subscription
- BD-4047
- N/A …

BD-4047: Clarify catalog item stock for user subscription

---

_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md

Add details to troubleshooting why users aren't receiving Canvas Flow messages.
[Bd-3961](https://jira.braze.com/browse/BD-3961)
- N/A …

BD-3961 Add troubleshooting items to Canvas Flow

---

_docs/_user_guide/data/custom_data/custom_events.md

Add limit for segmentable event properties
- BD-4257
- N/A …

BD-4257: Add limit for segmentable event properties

---

_docs/_api/endpoints/translations/get_bulk_translations_canvases.md
_docs/_api/endpoints/translations/get_translation_canvas.md
_docs/_api/endpoints/translations/put_update_translation_canvas.md
_docs/_user_guide/message_building_by_channel/email/using_locales.md

Adding a "Managing translations" section to the locales docs.
[BD-4221
](https://jira.braze.com/browse/BD-4221)
- N/A …

BD-4221 Add "Managing translations" section to locales

---

_docs/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md

- N/A
- N/A
- If my PR is related to a …

Remove unnecessary subheading

---

_docs/_developer_guide/platforms/swift/push_notifications/dynamic_apns.md
_docs/_developer_guide/platforms/swift/push_notifications/examples.md

Add new article for Dynamic APNs gateway management for push notifications
- BD-4087
- N/A …

BD-4087: Dynamic APNs gateway management

---

_docs/_contributing/bdocs.md

Accidental spacing added in last PR #9176 
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating- …

typo in bdocs.md

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/punchh.md

This topic came up while onboarding one of our clients. This behavior has been confirmed by our partnerships team and Punchh contact.
- N/A
- N/A …

Update external Id configurations instructions

---

_includes/developer_guide/prerequisites/android.md
_includes/developer_guide/prerequisites/cordova.md
_includes/developer_guide/prerequisites/flutter.md
_includes/developer_guide/prerequisites/react_native.md
_includes/developer_guide/prerequisites/swift.md
_includes/developer_guide/prerequisites/unity.md
_includes/developer_guide/prerequisites/unreal_engine.md
_includes/developer_guide/prerequisites/web.md
_includes/developer_guide/prerequisites/xamarin.md

Updating the language in the prerequisite includes for the developer guide + adding missing sdks.
- N/A
- N/A …

Updating prereq includes for dev guide

---

_docs/_user_guide/analytics/dashboard/email_performance_dashboard.md

Fix incorrect reference to time zone setting

---

_docs/_user_guide/engagement_tools/segments/measuring_segment_size.md

Making a few edits to the new "Measuring segment size"
[BD-4289](https://jira.braze.com/browse/BD-4289)
- N/A …

BD-4289 Add edits to Measuring segment size

---

_docs/_user_guide/message_building_by_channel/push.md
_docs/_user_guide/message_building_by_channel/push/push_error_codes.md
_docs/_user_guide/message_building_by_channel/push/troubleshooting.md
assets/js/broken_redirect_list.js

Move "Push Error Codes" help article to the Push docs section and add the `BadToken` error name.
[BD-3999](https://jira.braze.com/browse/BD-3999)
- N/A …

BD-3999 Move Push Error Codes and add code name

---

_docs/_docs_pages/redirects/post_duplicate_canvas.md
_lang/de/_docs_pages/redirects/post_duplicate_canvas.md

Update redirect links so they don't 404 anymore.
[BD-4305](https://jira.braze.com/browse/BD-4305)
- N/A …

BD-4305 Fix 404 link for Duplicate Canvases

---

_includes/metrics.md

Clarify spam metric definition
- BD-4287
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image …

BD-4287: Clarify spam metric definition

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md

Clarify details for price-drop notifications (need to use array for `type` property
- BD-4303
- N/A …

BD-4303: Clarify details for price-drop notifications

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md

Added troubleshooting for when trying to add a user that already exists in another instance of the same dashboard cluster.
[BD-4191](https://jira.braze.com/browse/BD-4191)
- N/A …

BD-4191 New Braze user already exists within a difference instance

---

_docs/_user_guide/message_building_by_channel/email/faq.md

Add an FAQ telling users how to check if an email address is already associated with a Braze user.
BD-4064
- N/A …

BD-4064 How to check if an email address is already used

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md

Remove incorrect sentence about how subscription groups can't be updated with the attributes object 
- BD-3972
- N/A …

BD-3972: Remove incorrect sentence

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md

Update mention of Canvas entry properties to context
- BD-4110
- N/A …

BD-4110: Update mention of Canvas entry properties to context

---

_docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md

Add limitation for nested custom attribute for periods and dollar signs
- BD-4141
- N/A …

BD-4141: Add limitation for nested custom attribute for periods and dollar signs

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/action_paths.md

Clarify only custom attributes can be targeted and add alt text
- BD-4147
- N/A …

BD-4147: Clarify only custom attributes can be targeted

---

_docs/_api/endpoints/templates/email_templates/post_create_email_template.md

Remove out of place text
- BD-4319
- N/A
- …

BD-4319: Remove out of place text

---

_docs/_partners/home.md

Add missing partners to the home page.
[BD-4316](https://jira.braze.com/browse/BD-4316)
- N/A …

BD-4316 Add missing technology partners

---

_docs/_user_guide/message_building_by_channel/email/html_editor/css_inline.md

Clarify CSS inlining recommendation
- BD-4308
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an- …

BD-4308: Clarify CSS inlining recommendation

---

_docs/_developer_guide/content_cards/creating_cards.md

Minor grammar fix

---

_docs/_developer_guide/banner_cards/integration.md

- a bug was discovered affecting click events on web-sdk. Click functionality in lower SDK versions does not work as expected. A fix was rolled out in 5.8.1
https://servicedesk.braze.com/browse/PQ-9022 …

bump web sdk 5.8.1 for banners

---

_includes/metrics.md

Update the definition of spam metric 
- BD-4324
- N/A …

BD-4324: Update definition of spam metric

---

README.md
_docs/_contributing/generating_a_preview.md

Adding a callout for how to generate content generated from a `{% markdown_embed %}` tag.
- N/A
- N/A …

Previewing '{% markdown_embed %}' content

---

_docs/_partners/message_orchestration/channel_extensions/loyalty/antavo.md

Update all-caps styling to sentence-style
- N/A
- N/A …

Fix column names

---

_docs/_user_guide/message_building_by_channel/email/amphtml.md

AMP for Email generally available for all users
- BD-4345
- N/A …

BD-4345: AMP for Email generally available for all users

---

_docs/_user_guide/data/custom_data/custom_events/nested_objects.md

[CO-3303](https://jira.braze.com/browse/CO-3303)
- Clarify that a schema is not required to use nested data in segmentation and personalization

CO-3303: update docs to clarify that schema is not required for messaging

---

.gitignore

Issue with the formatting in the `.gitignore` file for `./scripts/temp` directory. This PR fixes it so all files in that directory are properly ignored.
- N/A
- N/A …

Fix formatting in .gitignore

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Remove EA banner for custom data deletion GA
- BD-4339
- March 25, 2025 …

BD-4339: Custom data deletion GA - MERGE 3/24

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

We are introducing a new value for the field `state_change_source`. This PR explains what this value means.
Meanwhile, I also fixed possible values for `subscription_status` as it didn't mention `Opted In` value.
- If I updated or replaced an image, I did not remove the …

[CH-NOTIX] Add explanation for 'Auto Opt-In By Token Registration'

---

_docs/_user_guide/data/data_centers.md

Remove sentence
- BD-4357
- N/A
- If my PR …

BD-4357: Remove sentence

---

README.md
_docs/_contributing/generating_a_preview.md
_plugins/alloy_partner.rb
_plugins/markdown_embed.rb

Currently the partner page layout will always try to fetch data even if you're offline. As far as I know, this is the only layout (or similar) that will prevent running `rake` offline. I'm only somewhat familiar with these systems, so let me know if there's a better strategy for handling this.
- N/A
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/red …

Allow offline build for 'rake'

---

_docs/_user_guide/message_building_by_channel/push/advanced_push_options/push_action_buttons.md
_docs/_user_guide/message_building_by_channel/push/creating_a_push_message/quick_push.md

Add push action button detail to device-specific settings for quick push doc
- BD-3989
- N/A …

BD-3989: Add push action button detail to device-specific settings

---

_docs/_partners/canvas_steps/pinterest_audience_sync.md

- Doc cleanup
- Add FAQ for Pinterest Audience Sync for selecting ad accounts
- BD-4258
- N/A …

BD-4258: Add FAQ for Pinterest Audience Sync for selecting ad accounts

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Clarify behavior for workspace default and how to override in message-level one-click list-unsubscribe settings
- BD-4365
- N/A …

BD-4365: Clarify behavior for workspace default and how to override in message-level settings

---

_docs/_partners/canvas_steps/criteo_audience_sync.md
_docs/_partners/canvas_steps/google_audience_sync.md
_docs/_partners/canvas_steps/linkedin_audience_sync.md
_docs/_partners/canvas_steps/overview.md
_docs/_partners/canvas_steps/snapchat_audience_sync.md
_docs/_partners/canvas_steps/tiktok_audience_sync.md

Converting Audience Sync Troubleshooting section and details dropdowns into FAQ section with H3s for better visibility when searching through the respective doc
- N/A
- N/A …

Converting Audience Sync Troubleshooting section and details dropdowns into FAQ section with H3s

---

_docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md

Update steps for sending emails for SendGrid
- BD-4140
- N/A …

BD-4140: Update steps for sending emails for SendGrid

---

_docs/_api/objects_filters/purchase_object.md

Clarify that you can add products via API
- BD-3920
- N/A …

BD-3920: Clarify that you can add products via API

---

_docs/_api/endpoints/messaging/live_activity/start.md
_docs/_api/endpoints/messaging/live_activity/update.md
_docs/_developer_guide/content_cards/creating_cards.md
_docs/_developer_guide/in_app_messages/triggering_messages.md
_docs/_developer_guide/platforms/tv_and_ott.md
_docs/_help/faqs.md
_docs/_help/release_notes.md
_docs/_help/release_notes/2025/3_4_25.md
_docs/_user_guide/data/user_data_collection/sdk_data_collection.md
_includes/developer_guide/android/in_app_messages/delivery.md
_includes/developer_guide/web/in_app_messages/delivery.md
assets/js/broken_redirect_list.js

My week of running the 404 checker
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image …

Run 404 checker - Week of March 24, 2025

---

_docs/_user_guide/data/cloud_ingestion.md

Fix tile URL
- N/A
- N/A
- If my PR is …

Fix tile link for CDI Overview

---

_docs/_developer_guide/banner_cards.md
_docs/_developer_guide/banner_cards/creating_campaigns.md
_docs/_developer_guide/banner_cards/embedding_cards.md

show banners

---

_docs/_api/objects_filters/trigger_properties_object.md
_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties/canvas_persistent_entry_properties.md

Add detail for API trigger properties aren't stored in user profile
- BD-4388
- N/A …

BD-4388: Add detail for API trigger properties aren't stored in user profile

---

_docs/_user_guide/engagement_tools/canvas/get_started/canvas_status.md

I left some review comments on your PR @rachel-feinberg, but because they required some re-formatting to the page, I figured it would be easier to apply the changes myself--that being said, I didn't want to just overwrite your work, so my PR here targets your PR, so if you are cool with these suggestions, you can apply them to your branch _or_ simply use my PR for inspo.
Let me know if you have any questions 👍🏽 
- N/A
- N/A
- If I …

[BD-3935] Isaiah seperate edits

---

_docs/_user_guide/message_building_by_channel/push/faq.md

Remove an FAQ
[BD-4093](https://jira.braze.com/browse/BD-4093)
- N/A …

BD-4093 Remove FAQ

---

_docs/_user_guide/brazeai/recommendations/ai_item_recommendations.md

More accurate information received from the product team.
- [BD-4016](https://jira.braze.com/browse/BD-4016)
- N/A …

BD-4016: More accurate FAQ entry for retraining schedule

---

_docs/_user_guide/administrative/access_braze/navigation.md

Confirmed with FIX that rebrand nav has been fully released to all clusters.
- N/A
- N/A …

Remove gradual release callout from navigation.md

---

_docs/_user_guide/data/cloud_ingestion/connected_sources.md

Remove tabs and add _includes for Snowflake tab
- N/A
- N/A …

Remove tabs and add _includes for Snowflake tab

---

_docs/_user_guide/data/user_data_collection/anonymous_users.md

Getting Started was still in the title of this. Removed it if this section is not in the getting started section.
- N/A
- N/A …

Remove Getting Started title

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/selections.md

Clarify Connected Content Liquid isn't supported for selections filter settings
- BD-4381
- N/A …

BD-4381: Clarify Connected Content Liquid isn't supported for selections filter settings

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md

Clarify rate limiting details
- BD-4071
- N/A …

BD-4071: Clarify rate limiting details

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md

Triggered IAMs for Canvas GA
- BD-4389
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)) …

BD-4389: Triggered IAMs for Canvas GA

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Add alert for user permissions needed to blocklist custom data
- BD-4382
- N/A …

BD-4382: Add alert for user permissions needed to blocklist custom data

---

_docs/_user_guide/data/custom_data/managing_custom_data.md

Clarify deleting custom data doesn't cost data points
- BD-4380
- N/A …

BD-4380: Clarify deleting custom data doesn't cost data points

---

_docs/_user_guide/data/braze_currents.md
_docs/_user_guide/data/braze_currents/faq.md

Add FAQ page to Currents
[BD-4183](https://jira.braze.com/browse/BD-4183)
- N/A …

BD-4183 Currents FAQ

---

_docs/_user_guide/data/report_metrics.md

Clarify 30 day look-back time detail for soft bounce metric
- BD-4134
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managem …

BD-4134: Clarify 30 day look-back time detail for soft bounce metric

---

_docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_drafts.md

Clarify Canvas drafts and Content Block inclusion count
- BD-4157
- N/A …

BD-4157: Clarify Canvas drafts and Content Block inclusion count

---

_docs/_developer_guide/getting_started/integration_overview.md
_docs/_developer_guide/getting_started/platform_overview.md
_docs/_developer_guide/references.md
_docs/_developer_guide/sdk_integration.md
_docs/_hidden/other/support_contact.md

Added links to the SDK debugger in the support web form
[BD-4367](https://jira.braze.com/browse/BD-4367)
- N/A …

Added some refreshed links for SDK debugger

---

_docs/_user_guide/getting_started/b2b_use_cases/account_based_segmentation.md

Clarify catalog ID and item ID are needed for CATALOGS_ITEMS_SHARED SQL table
- BD-4447
- N/A …

BD-4447: Clarify catalog ID and item ID are needed for CATALOGS_ITEMS_SHARED SQL table

---

_docs/_user_guide/brazeai/generative_ai/ai_content_qa.md

Clarify AI Content QA behavior with Liquid
- BD-4445
- N/A …

BD-4445: Clarify AI Content QA behavior with Liquid

---

_docs/_api/endpoints/templates/email_templates/post_create_email_template.md

Add example response for POST: Create email template
Update header from "Possible errors" to "Troubleshooting"
- BD-4333
- N/A …

BD-4333: Add example response for POST: Create email template

---

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md

<--
Thank you for contributing to Braze Docs! Read comments like this one for help filling out your Pull Request (PR). For more information about contributing to Braze Docs, see:
braze.com/docs/contributing/.
-->
Add tip alert for using `/messages/send` for sending messages immediately instead of scheduling many messages
- BD-4056
- N/A …

BD-4056: Add tip alert for using `/messages/send` for sending messages immediately instead

---

_docs/_user_guide/engagement_tools/testing/race_conditions.md

Add detail about adding a delay using the SDK to prevent race condition
- BD-4390
- N/A …

BD-4390: Add detail about adding a delay using the SDK to prevent race condition

---

_docs/_api/endpoints/user_data/post_user_identify.md

Clarify prioritization array for identifying users by email
- BD-4116
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_managem …

BD-4116: Clarify prioritization array for identifying users by email

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Remove inaccurate detail about updating From address
- BD-4139
- N/A …

BD-4139: Remove inaccurate detail about updating From address

---

_docs/_user_guide/message_building_by_channel/email/amphtml.md

Clarify context for AMP documentation link and mention of clients
- BD-3829
- N/A …

BD-3829: Clarify context for AMP documentation link and mention of clients

---

_docs/_user_guide/message_building_by_channel/line/line_setup.md

Add alert about checking channel secret for LINE integration
- BD-4272
- N/A …

BD-4272: Add alert about checking channel secret for LINE integration

---

_docs/_partners/canvas_steps/overview.md

Add details on managing consent for ad targeting for Audience Sync
- BD-4400
- N/A …

BD-4400: Add details on managing consent for ad targeting for Audience Sync

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Add clarification that expired promo codes are deleted after 6 months
- BD-4148
- N/A …

BD-4148: Add clarification that expired promo codes are deleted after 6 months

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md

Add that users can export catalogs
- BD-4383
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-i …

BD-4383: Add that users can export catalogs

---

bdocs
scripts/find_broken_links.ts
scripts/transform_reference_links.py

Added a simple logger/loading spinner function. For slower commands (like `ulinks`), this will visually indicate that the current process is still running and not hung. For example:
**Start**:
```bash
➜  braze-docs git:(bdocs-logger-and-load-spinner) ✓ ./bdocs ulinks _docs/_contributing
[|] Running...
```
**End:**
```bash
➜  braze-docs git:(bdocs-logger-and-load-spinner) ✓ ./bdocs ulinks _docs/_contributing
[✓] Complete. 
Total replacements made across all files: 0
```
Checkout this branch locally, then use the same command in my example above to test the spinner.
- N/A
- N/A
- My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwm …

bdocs: adding simple loading spinner

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

WhatsApp videos are now supported in the Media Library
[BD-4465](https://jira.braze.com/browse/BD-4465)
- N/A …

BD-4465 WhatsApp videos supported in Media Library

---

_includes/developer_guide/android/analytics/setting_user_attributes.md

Someone surfaced a typo in the following page where boolean was lumped inside the floating points tab. Here's the link in docs:
https://www.braze.com/docs/developer_guide/analytics/setting_user_attributes/?tab=floating-points&sdktab=android
- N/A
- N/A …

Fix tab typo in setting_user_attributes.md

---

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md

Add WhatsApp videos to the media library docs
[BD-4469](https://jira.braze.com/browse/BD-4469)
- N/A …

BD-4469 Adding WhatsApp videos to media library

---

_docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/appsflyer_audiences.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/census.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/heap.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/hightouch.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/kubit.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
_docs/_partners/data_and_infrastructure_agility/cohort_import/tinyclues.md

Update Cohort Import Partners to match Treasure Data warning banner for user creation behavior for non existing Braze User

[PP-4306] add warning banner for user creation behavior

---

_docs/_developer_guide/analytics.md
_docs/_developer_guide/analytics/logging_purchases.md
_docs/_developer_guide/analytics/tracking_uninstalls.md
_docs/_developer_guide/feature_flags.md
_docs/_developer_guide/in_app_messages/triggering_messages.md
_docs/_developer_guide/live_notifications/live_activities.md
_docs/_developer_guide/platforms/legacy_sdks/ios/analytics/uninstall_tracking.md
_docs/_developer_guide/platforms/legacy_sdks/ios/in-app_messaging/customization/handling_in_app_display.md
_docs/_developer_guide/platforms/legacy_sdks/ios/in-app_messaging/in-app_message_delivery.md
_docs/_developer_guide/platforms/swift/_archived_updates/ios_14.md
_docs/_developer_guide/platforms/swift/_archived_updates/ios_15.md
_docs/_developer_guide/platforms/swift/_archived_updates/ios_17.md
_docs/_developer_guide/platforms/web/browser_extensions.md
_docs/_developer_guide/references.md

Spellcheck for the Developer Guide
[BD-4486](https://jira.braze.com/browse/BD-4486)
- N/A …

BD-4486 Spellcheck for Developer Guide

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md

Fix Liquid
- BD-4468
- N/A
- If my PR is …

BD-4468: Fix Liquid

---

_docs/_user_guide/engagement_tools/campaigns/managing_campaigns/change_your_campaign_after_launch.md

Saving drafts for active campaigns GA
- BD-4448
- N/A …

BD-4448: Saving drafts for active campaigns GA

---

_docs/_partners/data_and_infrastructure_agility/data_warehouses/snowflake.md

Add clarification on how to set up the inbound share, and remove image (didn't seem helpful and distracted from important info). This is in response to an escalation where a customer deleted and recreated the share and then was unable to see their shared data.
- N/A
- N/A
- …

update snowflake setup docs

---

_docs/_user_guide/engagement_tools/templates_and_media/content_blocks.md

Add note about rendering of HTML Content Blocks in drag-and-drop emails AND drag-and-drop Content Blocks in HTML emails
- BD-4187
- N/A …

BD-4187: Add note about rendering of HTML Content Blocks in drag-and-drop emails (and vice-versa)

---

_docs/_user_guide/administrative/app_settings/multi_language_settings.md

Add more considerations for multi-language settings
- BD-4092
- N/A …

BD-4092: Add more considerations for multi-language settings

---

_includes/preference_center_warning.md

Clarify that Naver Android **and** iOS app don't support the Braze preference center
- BD-4512
- N/A …

BD-4512: Clarify browsers that don't support Braze preference center

---

_docs/_api/endpoints/user_data/post_user_identify.md
_docs/_api/endpoints/user_data/post_users_merge.md

Add `least_recently_updated` to prioritization array
- BD-4426
- N/A …

BD-4426: Add new `least_recently_updated` to prioritization array

---

_docs/_partners/canvas_steps/overview.md

Update table column name "Time to sync" to "Time to update audience size in destination" for clarity
- BD-4507
- N/A …

BD-4507: Update table column name for clarity for Audience Sync overview

---

_docs/_user_guide/data/custom_data/custom_attributes.md

Reverts braze-inc/braze-docs#9391

Revert "BD-4427: Update array size limit to 500"

---

_docs/_developer_guide/analytics/tracking_sessions.md

* Fixes a typo. "set to braze" should be "sent to braze"
* Fixes a grammatical error. "it's" is the proper contraction for "it is". Changed to "your app while **it's** in the background"
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file …

Ch notix fix typo

---

_docs/_user_guide/data/braze_currents/available_partners.md

Adding a link to Amperity into the available Currents partners
- N/A
- N/A …

Update available_partners.md to include Amperity

---

assets/js/broken_redirect_list.js

Fix 404 links
[BD-4522](https://jira.braze.com/browse/BD-4522)
- N/A …

BD-4522 404 link checker

---

_docs/_developer_guide/sdk_integration/authentication.md
_includes/developer_guide/android/sdk_initialization.md

SDK docs audit - small changes (mostly Appboy->Braze)
- N/A
- N/A …

[SDK Docs Audit] Android Initialization/Debugging

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md

Clarify alert for users participating in the Context EA
- N/A
- N/A …

Clarify alert for users participating in the Context EA

---

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize.md

Fix broken icon

---

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/create.md

Minor QoL enhancement
- N/A
- N/A
- If my …

Add crosslink to color profiles doc

---

_includes/developer_guide/web/sdk_integration.md

would prefer these to be expanded to make CTRL+F searches work on this page

expand web instructions

---

_docs/_user_guide/message_building_by_channel/in-app_messages/creative_details.md

It appears the sentence "Check out the following message type Creative Specs or the global Creative Details article." might be a hang over from a past re-org—this is the Creative Details page and its showing specs for each message type.
- N/A
- N/A …

Remove outdated sentence

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md

Our docs currently state that customers can set a frequency cap duration in minutes, days, weeks or months, but the "months" option isn't actually available, as seen below:
- N/A
- N/A …

Fix Frequency Capping Durations

---

_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/getting_started_shopify.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/setting_up_shopify.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/shopify_features.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/shopify_features/shopify_backfill.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/shopify_features/shopify_user_identity.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/shopify_overview.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/using_shopify.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/using_shopify/shopify_data_in_braze.md
_docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify_legacy/using_shopify/use_cases.md
_includes/alerts.md

Add "legacy" to all legacy integration docs for Shopify, including alerts.
[BD-4526](https://jira.braze.com/browse/BD-4526)
- N/A …

BD-4526 Add legacy titles and alerts to Shopify docs

---

_docs/_user_guide/analytics/dashboard/conversions_dashboard.md

You're required to select a breakdown layer in the Conversion dashboard.
[BD-4530](https://jira.braze.com/browse/BD-4530)
- N/A …

BD-4530 Breakdown layer is required in the Conversion dashboard

---

_docs/_user_guide/data/cloud_ingestion/overview.md

Clarify inclusive boundary and updated_at
- BD-4132
- N/A …

BD-4132: Clarify inclusive boundary and updated_at

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/editor_blocks.md

Add missing in-app message editor blocks
- BD-4106
- N/A …

BD-4106: Edits to in-app message editor blocks

---

_docs/_api/endpoints/translations.md
_docs/_api/endpoints/translations/get_bulk_translations_campaigns.md
_docs/_api/endpoints/translations/get_bulk_translations_canvases.md
_docs/_api/endpoints/translations/get_translation_campaign.md
_docs/_api/endpoints/translations/get_translation_canvas.md
_docs/_api/endpoints/translations/put_update_translation_campaign.md
_docs/_api/endpoints/translations/put_update_translation_canvas.md
_includes/rate_limits.md

Updates to translation endpoints
- BD-4508
- N/A …

BD-4508: Updates to translation endpoints

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Add considerations for Delay steps that use specific dates and times.
[BD-3976](https://jira.braze.com/browse/BD-3976)
- N/A …

BD-3976 Add considerations to Delay steps

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

We are changing the display name of the push registration process source to make it more accurate to the reality.
- N/A
- N/A …

[PUSH-NOTIX] Change the source name for the push registration process

---

_docs/_user_guide/engagement_tools/messaging_fundamentals/duplicating.md

Add tip alert for copying campaigns across workspaces
- BD-4574
- N/A …

BD-4574: Add tip alert for copying campaigns across workspaces

---

_includes/developer_guide/android/content_cards.md

Updating information to be correct.
- N/A
- N/A …

[NOTIX] Android Card Documentation Update

---

_includes/developer_guide/swift/geofences.md

This key has been deprecated by Apple, so it has been removed and a callout added.
- N/A
- N/A …

[BD-4277] Remove NSLocationAlwaysUsage key

---

_docs/_user_guide/data/export_braze_data/message_archiving.md

Add MMS to the Message Archiving article.
[BD-4598](https://jira.braze.com/browse/BD-4598)
- N/A …

BD-4598 Update Message Archiving to add MMS

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

Fix Currents Message Engagement Events glossary checkboxes from #9454
- BD-4586
- N/A …

BD-4586: Fix Currents Message Engagement Events glossary checkboxes

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery.md
_docs/_user_guide/engagement_tools/canvas.md
_docs/_user_guide/engagement_tools/canvas/troubleshooting.md

Adds troubleshooting for action-based campaigns and Canvases.
[BD-4054](https://jira.braze.com/browse/BD-4054)
- N/A …

BD-4054 Add troubleshooting details for campaigns and Canvases

---

_docs/_partners/data_and_analytics/customer_data_platform/mparticle.md
_docs/_partners/data_and_analytics/customer_data_platform/tealium.md
_docs/_partners/data_and_analytics/customer_data_platform/treasure_data.md
_docs/_partners/data_and_analytics/customer_data_platform/treasure_data/treasure_data_for_currents.md

Fixed landing page tiles for mParticle and other partners.
[BD-4599](https://jira.braze.com/browse/BD-4599)
- N/A …

BD-4599 Fix partner landing page tiles

---

_docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md

Remove EA banner
- BD-4613
- N/A
- If my …

BD-4613: Scheduled merging GA

---

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md

The description for the :override_messaging_limits parameter for the /messages/schedule/create endpoint is misleading: it states that the param overrides global rate limits, but it actual overrides frequency capping.
This came up in a PQ: https://servicedesk.braze.com/browse/PQ-9861
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) …

[MP-6142] Fix :override_messaging_limits Param Description

---

_includes/header.html

Add DE(German) to the language dropdown.

add German language dropdown

---

_docs/_api/objects_filters/recipient_object.md

As of the 4/24 release, you can now include "braze_id" in the recipient object.
- N/A
- N/A …

You can now include "braze_id" in the recipient object.

---

_docs/_partners/home.md
assets/js/broken_redirect_list.js

Fix links for a few partners.
None
- N/A
- …

Fix partner links

---

_docs/_api/objects_filters/messaging/whats_app_object.md

Adding a new response message type to our WhatsApp API Send message objects and need to have this here
- N/A
- N/A …

[WA-937] Update WA Docs for List Response Messages

---

assets/js/broken_redirect_list.js

Add a redirect for an old Shopify search result and fix formatting for another partner redirect
[BD-4387](https://jira.braze.com/browse/BD-4387)
- N/A …

BD-4601 Add Shopify redirect and fix another redirect

---

assets/download_file/data-sharing-raw-table-schemas.txt

update braze docs for new tables created in https://github.com/braze-inc/datalake-migrations/pull/484 
- N/A
- N/A …

[DLK-3016] re-generate doc for cue update

---

_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md

A question was raised in a PQ, we found that this note was not very accurate, since there's no distinction in between different retryable errors.
- N/A
- N/A …

[PUSH-NOTIX] Correct the erroneous alert note about Webhook retries

---

_docs/_user_guide/message_building_by_channel/email/using_locales.md

Remove duplicate FAQ section in email locales article.
None
- N/A …

Remove duplicate FAQs in message locales

---

_includes/developer_guide/swift/sdk_integration.md

Our upcoming Swift SDK 12.0.0 supports static frameworks with embedded resources. The current manual integration documentation is not accurate with this change.
- [SDK-4836](https://jira.braze.com/browse/SDK-4836)
- With the release of our Swift SDK 12.0.0 (next couple of days) …

[SDK-4836] Update Swift SDK manual integration to reflect support for static frameworks with resources

---

_docs/_api/endpoints/translations/put_update_translation_campaign.md
_docs/_api/endpoints/translations/put_update_translation_canvas.md

Update example request
- BD-4635
- N/A
- …

BD-4635: Fix example requests for  /campaigns/translations and  /canvas/translations

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Fixes typo and capitalization inconsistencies
- N/A
- N/A …

Edits for Context step

---

_docs/_user_guide/analytics/query_builder.md

Add a timezone conversion SQL example to Query Builder docs, as the Query Builder defaults to UTC.
[BD-4559](https://jira.braze.com/browse/BD-4559)
- N/A …

BD-4559 Add timezone conversion SQL for Query Builder

---

_docs/_user_guide/data/data_centers.md
_includes/data_centers.md

Add ID-01 instance URLs and IPs
- BD-4100
- April 29, 2025 …

BD-4100: Add ID-01 instance URLs and IPs [MERGE 4/25]

---

_docs/_developer_guide/analytics/tracking_sessions.md

The default session timeout on web is 30 minutes as per our javascript docs:
https://js.appboycdn.com/web-sdk/latest/doc/modules/braze.html#initializationoptions:~:text=Optional-,sessionTimeoutInSeconds%3F,-%3A%20undefined%20%7C
- [BD-4642](https://jira.braze.com/browse/BD-4642)
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for …

[BD-4642] Change web session timeout to 30 mins

---

_includes/developer_guide/android/sdk_integration.md

Android Integrating the SDK page - small changes from audit
- N/A
- N/A …

[SDK Docs Audit] Android Integrating the SDK

---

_docs/_user_guide/message_building_by_channel/email/apple_mail/email_private_relay_apple_SSO.md

Add missing email format
- N/A
- N/A
- If …

Add missing email format

---

_includes/html_include.html
_layouts/scrolly.html
_plugins/scrolly_code_processor.rb
assets/css/github-dark.scss
assets/css/scrollycode.scss
assets/js/scrolly-highlight.js
assets/js/scrollycode.js

More user friendly tutorials, similar to [Stripe walkthroughs](https://docs.stripe.com/checkout/embedded/quickstart).
**This is the re-added code from the original PR here: #9364 . The original PR introduced a bug to existing code blocks although the scrolly feature itself worked as expected. This will need to be QA'ed and fixed before merging.**
1. use opening liquid tag `{% scrolly %}`
2. define your code block first with standard markdown syntax, but add a file name like ` ```js file=index.js`. Don't use capitals.
3. define the beginning of your step, then define the line(s) you want to highlight using `lines-<filename>=#`
```md
!!step
lines-index.js=1,1-4
```
5. line values should have no white space, and be comma separated. Can can define ranges (x-y) or single values (x).
6. after …
```

Integration for scrolly-coding

---

_docs/_partners/canvas_audience_sync/facebook_audience_sync.md

Clarify fields to match for Facebook Audience Sync
- BD-4329
- N/A …

BD-4329: Clarify fields to match for Facebook Audience Sync

---

.github/workflows/ci-prod.yaml

Use github action to trigger language builds

change language deploys to prod only

---

.github/workflows/ci-prod.yaml

fix deploy action

---

.github/workflows/ci-prod.yaml

Deploy pt 3 - March 30, 2025

---

_docs/_user_guide/message_building_by_channel/email/best_practices/guidelines_and_tips.md

Add alert that unicode encoding isn't supported for from addresses
- BD-4477
- N/A …

BD-4477: Add alert that unicode encoding isn't supported for from addresses

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md

Clarify that Liquid should be placed in HTML editor blocks for drag-and-drop email editor
- BD-4478
- N/A …

BD-4478: Clarify Liquid should be placed in HTML editor blocks 

---

_docs/_user_guide/data/custom_data/event_naming_conventions.md

Fix typo in example
- BD-4669
- N/A
- If …

BD-4669: Fix typo

---

_docs/_hidden/other/segment_funnels.md
_docs/_user_guide/engagement_tools/segments.md
assets/js/broken_redirect_list.js

Hide Segment Funnels until they're returned to the UI
[BD-4672](https://jira.braze.com/browse/BD-4672)
- N/A …

BD-4672 Hide Segment Funnels

---

.github/workflows/ci-prod.yaml
_docs/_hidden/other/segment_funnels.md
_docs/_user_guide/data/custom_data/event_naming_conventions.md
_docs/_user_guide/engagement_tools/segments.md
_docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
assets/js/broken_redirect_list.js

#9586 - Hide Segment Funnels 
#9587 - add project id var 
#9584 - Fix typo

Deploy pt. 5 - March 303, 2025

---

.github/workflows/ci-prod.yaml

add archive flag

---

_docs/_user_guide/data/custom_data/purchase_events.md

Remove misleading bullet point.
[BD-4677](https://jira.braze.com/browse/BD-4677)
- N/A …

BD-4677 Remove bullet in Purchase Events

---

_docs/_developer_guide/banners.md
_docs/_developer_guide/banners/creating_campaigns.md
_docs/_developer_guide/banners/creating_placements.md
_includes/banner_cards/creating_placements.md
assets/js/broken_redirect_list.js

Clarified the language of Banners with PM. It's more accurate to say "create placements" rather than "embed banner" in reference to developer setup.
- N/A
- N/A …

Banners: Change 'embed' to 'create placements'

---

_docs/_partners/isv_partners/api_partner.md

Updating the formatting of the code samples to reflect our style guide.
- Hotfix for #9592
- N/A …

API partner integration 'User-Agents' header

---

_docs/_api/endpoints/messaging/duplicate_messages/post_duplicate_canvases.md

Fix YAML for Duplicate Canvases endpoint

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2016/july.md
_docs/_help/release_notes/2017/april.md
_docs/_help/release_notes/2017/august.md
_docs/_help/release_notes/2017/february.md
_docs/_help/release_notes/2017/july.md
_docs/_help/release_notes/2017/june.md
_docs/_help/release_notes/2017/may.md
_docs/_help/release_notes/2018/april.md
_docs/_help/release_notes/2024/10_15_24.md
_docs/_hidden/archive_docs/windows_universal/initial_sdk_setup.md
_docs/_hidden/archive_docs/windows_universal/push_notifications.md
_docs/_partners/home.md
_docs/_partners/message_personalization/dynamic_content/personalized_recommendations/amazon_personalize.md
_docs/_partners/message_personalization/dynamic_content/personalized_recommendations/amazon_personalize/amazon_personalize.md
_docs/_user_guide/data/braze_currents/available_partners.md
_docs/_user_guide/engagement_tools/campaigns/testing_and_more/sending_test_messages.md
assets/js/broken_redirect_list.js

Fix broken links
None
- N/A
- If my PR is …

404 Checker - May 1, 2025

---

_docs/_contributing/git_and_github.md

While walking someone through the GitHub page, it became clear that the steps are very confusing if someone does them in order. I have removed redundant info and instead linked to relevant headings. That way it makes sense for:
- Someone doing all the steps in order
- Someone jumping to a specific step and skipping previous steps
This doc is meant to serve both of these types of users and I think these changes help do that better.
- N/A
- N/A
- All links are working …

Remove redundant info on Contributing: GitHub

---

_docs/_contributing/bdocs.md

Adding `node` to the list of dependencies for `./bdocs fblinks` + commands to install. (I've also updated this in internal wiki).
- N/A
- N/A …

Add 'node' to list of dependencies for './bdocs fblinks'

---

_docs/_developer_guide/feature_flags/create.md

[Current documentation](https://www.braze.com/docs/developer_guide/feature_flags/create/#enabled) seemed to be using an outdated version of the API that didn't return an optional.
https://brazetechnology.slack.com/archives/GA44V39TN/p1745874996034129 …

[Untracked SDKs] Update nullability syntax for `FeatureFlags.featureFlag(id:)` in all SDKs

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog_triggers/price_drop_notifications.md

Update wording on limits for price-drop notifications
- BD-4713
- N/A …

BD-4713: Update wording on limits for price-drop notifications

---

_docs/_user_guide/message_building_by_channel/whatsapp/overview/embedded_signup.md

You can have one specific WhatsApp Business Account per workspace, but you can have multiple different WABAs per workspace.
[BD-4720](https://jira.braze.com/browse/BD-4720)
- N/A …

BD-4720 WhatsApp Business Accounts usage note

---

_docs/_user_guide/data/custom_data/custom_attributes.md

Reverts braze-inc/braze-docs#9420

Revert "Revert "BD-4427: Update array size limit to 500""

---

_docs/_api/endpoints/user_data/post_user_delete.md
_docs/_api/endpoints/user_data/post_user_identify.md

Generalized identifying and deleting users sections
- BD-4633
- N/A …

BD-4633: Generalized identifying and deleting users sections for email adresses and phone numbers

---

_docs/_developer_guide/banners/creating_campaigns.md

Fix step numbers
- N/A
- N/A
- If my PR is …

Fix step numbering

---

_docs/_developer_guide/references.md

Hiding H3 heading as it reflects specific platform types and could be confusing depending on which platform the end-user is coming from when reading the docs.
- N/A
- N/A …

Hide H3 headings in references.md

---

Gemfile.lock

upgrade to rack 3.1.14 and tested to make sure nothing broke.

update rack to 3.1.14

---

_config.yml
_includes/analytics.html
_includes/html_include.html
assets/developer-sync.html

implements https://github.com/Appboy/platform/pull/95795 to set developer profile in Braze SDK and changes to new Braze Workspace.

Docs Developer Profile

---

_docs/_user_guide/engagement_tools/segments/user_profiles/duplicate_users.md

Specify the approximate merge time schedule
- BD-4631
- N/A …

BD-4631: Specify approximate merge time schedule

---

assets/js/broken_redirect_list.js

Add redirects for several non-English support contact forms.
[BD-3831](https://jira.braze.com/browse/BD-3831)
- N/A …

BD-3831 Add redirects for support contact form

---

_lang/de/_hidden/support_contact.md
_lang/es/_hidden/other/support_contact.md
_lang/fr_fr/_hidden/other/support_contact.md
_lang/pt_br/_hidden/other/support_contact.md
assets/js/broken_redirect_list.js

Add redirects for language support contact pages.
- N/A
- N/A …

Add Support Contact redirect pages

---

_docs/_help/release_notes/2016/july.md
_docs/_help/release_notes/2019/march.md
_docs/_help/release_notes/2020/december.md
_docs/_help/release_notes/2021/december.md
_docs/_help/release_notes/2022/4_5_22.md
_docs/_help/release_notes/2022/7_26_22.md
_docs/_partners/home.md
_docs/_partners/message_personalization/dynamic_content/visual_and_interactive_content/movable_ink.md
_docs/_user_guide/brazeai/recommendations/rules_based_recommendations.md
assets/js/broken_redirect_list.js

404 checker — Week of May 5
- N/A
- N/A
- …

404 checker — Week of May 5

---

_docs/_developer_guide/banners.md
_docs/_user_guide/administrative/access_braze/accessing_your_account.md
_docs/_user_guide/engagement_tools/landing_pages.md
_docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
_docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop.md
_docs/_user_guide/message_building_by_channel/line.md
_includes/drag_and_drop_access.md

Add section in Accessing your account article
Add alerts for access to drag-and-drop editor and email HTML editors
- BD-4728
- N/A …

BD-4728: Add info for access to drag-and-drop and email HTML editors

---

_docs/_user_guide/brazeai/intelligence/intelligent_channel.md

SMS requires tracking to be turned on to populate interaction data, so without it the interaction rate for Intelligent Channel is always 0%.  However, it's still able to be the Intelligent Channel when both SMS and another channel have sufficient received events to invoke the tie-breaking behavior.
This is clarification is to result customer confusion from a PQ.
- [PQ-10246](https://servicedesk.braze.com/browse/PQ-10246)
- N/A
- If I …

Clarify intelligent timing tie-breaking behavior for SMS

---

_docs/_user_guide/message_building_by_channel/webhooks/understanding_webhooks.md

Add details about webhook error handling and rate limiting.
[BD-3988](https://jira.braze.com/browse/BD-3988)
- N/A …

BD-3988 Add details about webhook error handling

---

_docs/_api/endpoints/messaging/schedule_messages/post_schedule_messages.md

Remove "recipients" incorrect parameter from /messages/schedule/create
- BD-4733
- N/A …

BD-4733: Remove incorrect parameter from /messages/schedule/create

---

_docs/_user_guide/data/custom_data/custom_events.md
_docs/_user_guide/data/custom_data/purchase_events.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_entry_properties_event_properties.md
_includes/canvas_entry_event_properties.md

Create _includes file for Canvas entry properties and event properties for:
- Purchase events article
- Custom events article
Move original editor content into collapsible and remove "2023"
- N/A
- N/A …

Create _includes file for Canvas entry properties and event properties

---

_docs/_partners/ecommerce/shopify/multiple_stores.md

Bd 4723 isaiah edits

---

_layouts/broken_page.html
assets/js/broken_redirect_list.js

Fix issue with redirect when the destination is an array instead of a string.

fix broken redirect when destination is an array

---

scripts/make_redirects.py

whoops accidentally left in a couple debug statements!
- N/A
- N/A …

remove debug statments in make_redirects.py

---

scripts/make_redirects.py

whoops, print statement for success is printing for each file changed instead of 1 time 🤦🏽 
- N/A
- N/A …

only print success 1 time in make_redirects.py

---

_docs/_partners/ecommerce/shopify/multiple_stores.md

Made a few minor updates to the Shopify multiple store support doc. 
[BD-4762](https://jira.braze.com/browse/BD-4762)
- N/A …

BD-4762 Update Shopify Multiple Store Support doc

---

_docs/_partners/data_and_analytics/data_warehouses/snowflake/user_attributes.md

In the initial beta release, this dataset only supported default attributes. now, we support both default and custom attributes. The goal of this change is to document the new data sets, and slightly modify the structure of the docs to reflect the parallel schemas/usage patterns across default and custom attributes. 
- N/A
- N/A …

add custom attributes info to snowflake documentation

---

_docs/_user_guide/administrative/app_settings/manage_your_braze_users/adding_users_to_your_dashboard.md

Two images in the Users article are huge. I shrunk them down.
N/A
- N/A …

Shrink image sizes for Users article

---

_docs/_partners/ecommerce/shopify/shopify_data_features.md

Remove `v1` from eCommerence events
[BD-4765](https://jira.braze.com/browse/BD-4765)
- N/A …

BD-4765 Remove V1 from eCommerce events

---

_docs/_api/endpoints/user_data/post_user_track.md

[CO-3401](https://jira.braze.com/browse/CO-3401)
Currently, if a NCA is sent to us with an invalid $time value, we will drop the entire NCA update rather than just the invalid time value.
We want to update the documentation to make this clear. …

CO-3401: update documentation for invalid nested custom attributes when using users/track

---

_docs/_user_guide/engagement_tools/segments/creating_a_segment.md

Remove sentence about duplicating filter groups, as that's not possible. 
[BD-4774](https://jira.braze.com/browse/BD-4774)
- N/A …

BD-4774 Remove segmentation sentence

---

_docs/_user_guide/data/custom_data/custom_attributes.md
_docs/_user_guide/data/custom_data/custom_events.md

Core Objects is planning to add company entitlements which will limit the number of custom attributes and custom events that companies can create in their workspaces.
- [BD-4483](https://jira.braze.com/browse/BD-4483)
- [CO-3374](https://jira.braze.com/browse/CO-3374)
- 19 May 2025 …

CO-3374: Add documentation for custom attributes/events entitlements [MERGE 5/19]

---

_docs/_user_guide/data/report_metrics.md
_includes/campaign_analytics.md
_includes/metrics.md

Updating Content Card metric definitions and links.
[BD-4192](https://jira.braze.com/browse/BD-4192)
- N/A …

BD-4192 Update Content Card metrics

---

_docs/_hidden/compliance/audience_sync.md
_docs/_hidden/compliance/home.md
_docs/_hidden/compliance/message_archiving_field_level_encryption.md
_docs/_hidden/compliance/shopify_integration.md

Updates to Compliance documentation for FY'26 pricing
- BD-4658
- May 19, 2025 …

BD-4658: Updates to Compliance documentation

---

_docs/_user_guide/engagement_tools/testing/race_conditions.md

Header accidentally referenced the wrong endpoint--but the content in that section was still correct. Also, due to content on page, i hid the h3 headings as they didn't add a lot of info.
- [BD-4770](https://jira.braze.com/browse/BD-4770)
- N/A …

[BD-4770] Fix typo in race conditions

---

_docs/_user_guide/data/data_points.md

Add purchase properties to data points table
- BD-4714
- N/A …

BD-4714: Add purchase properties to data points table

---

_docs/_partners/data_and_analytics/analytics/saleswings.md

Remove extra {
- N/A
- N/A
- If my PR is …

Fix URL reference

---

assets/js/broken_redirect_list.js

Add SMS, MMS, RCS subscription group redirect link
None
- N/A …

Add SMS, MMS, RCS subscription group redirect

---

_docs/_user_guide/data/report_metrics.md

update _Total Opens_ calculation
[BD-4780](https://jira.braze.com/browse/BD-4780)
- N/A …

BD-4780 Update Total Opens calculation

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Add note that Context EA supports delays up to 2 years
- BD-4775
- N/A …

BD-4775: Add note that Context EA supports delays up to 2 years

---

_docs/_partners/ecommerce/shopify_legacy/using_shopify/shopify_data_in_braze.md

Remove `applied_discount` field from the example payload for Abandoned Checkout
- N/A
- N/A …

BD-4783 Remove applied_discount from payload example

---

_docs/_partners/data_and_analytics/data_warehouses/snowflake.md

The original version of Braze Benchmarks has been deprecated and these docs are no longer accurate/relevant. A replacement is coming but it will be available in the Braze dashboard rather than through Snowflake data sharing. 
- N/A
- N/A
- If I updated or replaced an image, I …

remove benchmarks section

---

_docs/_partners/data_and_analytics.md
_docs/_partners/data_and_analytics/ab_testing/eppo.md
_docs/_partners/home.md

New partner doc for Eppo
- [#9676](https://github.com/braze-inc/braze-docs/pull/9676)
- BD-4786
- N/A …

BD-4786: Eppo partner docs

---

assets/js/broken_redirect_list.js

Add a redirect for a double opt-in article
None
- N/A …

Add redirect for double opt-in article

---

_docs/_user_guide/data/custom_data/custom_events.md

Update data type table to remove outdated Object row that says they're ingested as strings
- BD-4771
- N/A …

BD-4771: Update data type table to remove outdated Objects row

---

_docs/_hidden/other/handbooks.md

Update bullet point text for FY'25 handbook at Legal's request
- BD-4787
- N/A …

BD-4787: Update bullet point from Legal

---

_docs/_user_guide/data/export_braze_data/message_archiving.md

Clarify latency cause for messaging archiving

---

_docs/_user_guide/analytics/query_builder.md

Clarify Query Builder credits
- BD-4647
- N/A …

BD-4647: Clarify Query Builder credits

---

_docs/_user_guide/data/custom_data/custom_attributes/nested_custom_attribute_support.md

Clarify nested custom attribute won't be updated if `$time` is incorrectly formatted
- BD-4273
- N/A …

BD-4273: Clarify nested custom attribute won't be updated if `$time` is incorrectly formatted

---

_docs/_partners/ecommerce/shopify/shopify_data_features.md
_docs/_partners/ecommerce/shopify/shopify_overview.md

If users are planning to integrate with a custom external ID, they will be required to add their custom external ID as a Shopify customer metafield to all existing Shopify customer profiles and then perform the historical backfill. 
[BD-4779](https://jira.braze.com/browse/BD-4779)
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for …

BD-4779 Add note about Shopify historical backfill

---

_docs/_developer_guide/banners/creating_placements.md
_docs/_user_guide/engagement_tools/messaging_fundamentals/know_before_send.md
_docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
_includes/banners/about.md
_includes/banners/faq.md
_includes/banners/placement_requests.md

This was raised by an SDK engineer that we should make this prominent in the user docs so the limits are prominent 
- N/A …

Add limit of 10 placements per session in the Banners FAQ

---

assets/js/broken_redirect_list.js

Adding 2 redirects to redirect file.
- N/A
- N/A …

Add 2 redirects to broken_redirect_list.js

---

_docs/_user_guide/message_building_by_channel/email/email_setup/ssl.md

Add warning for SSL CDN enabling header
- BD-4750
- N/A …

BD-4750: Add alert to enable header in CDN

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md

Clarify targeted device identifier description for multiple devices
- BD-4226
- N/A …

BD-4226: Clarify targeted device identifier description for multiple devices

---

_docs/_developer_guide/banners/creating_placements.md

putting the simple integration first

rearrange banners integration

---

.github/workflows/label-deploy.yml

Want to start incorporating some more automation with GitHub actions. Figured this would be a good first use case. Simply ensures that all deployment PRs (i.e. PRs where base branch == `master` and head branch == `develop`) are always given the `Deploy` label that we have historically manually added to PRs.
- N/A
- N/A …

GitHub Action: Add deploy label

---

_docs/_docs_pages/redirects/post_duplicate_canvas.md

Hide article from left nav and fix roundabout redirect
- N/A
- N/A …

Hide article from left nav and fix roundabout redirect

---

_includes/campaign_analytics.md

- Banners doesn't support canvas. Removes any reference to canvas in the Banners Analytics Page
Before:
After:
- N/A …

remove references to canvas for banners anayltics page

---

assets/js/feedback.js

rating events have been broken for some time

Fix rating events

---

.github/workflows/block-merge.yml

In addition to label added/removed, also having workflow trigger when PR is opened, set to draft, or set to ready for review.
- N/A
- N/A …

More PR types for block-merge.yml

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md

Sub-steps are currently formatted as `Step 1.a: TASK` instead of `Step 1.1: TASK`. Additionally, the right-side TOC was very wordy and busy so I attempted to streamline the headings as well.
(this page _probably_ needs an overhaul at some point, but out of scope for me at this time).
- N/A
- N/A
- If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_u …

Fix sub-step numbering for create canvas

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

Background Push Enabled filter was never supposed to include unsubbed users, clarifying that behaviour, similar to the description of Push Enabled filter.
- N/A
- N/A …

[PUSH-353] Clarify the behaviour of Background Push Enabled filter

---

_docs/_user_guide/message_building_by_channel/content_cards/create.md

Clarify test sends for Content Cards
- BD-4527
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an …

BD-4527: Clarify test sends for Content Cards

---

_docs/_user_guide/analytics/reporting/report_builder.md

Add table to explain certain metrics that are available for certain channels.
[BD-4709](https://jira.braze.com/browse/BD-4709)
- N/A …

BD-4709 Add metrics availability to Report Builder

---

_docs/_user_guide/analytics.md
_docs/_user_guide/data/field_level_encryption.md
assets/js/broken_redirect_list.js

Remove catalogs tile from Analytics section
- BD-4824
- N/A …

BD-4824: Remove catalogs tile from Analytics section

---

_docs/_api/objects_filters/messaging/email_object.md
_docs/_api/objects_filters/messaging/sms_object.md

Clarify any `app_id` works for all users if it's configured in your workspace for SMS and email objects
- BD-4800
- N/A …

BD-4800: Clarify any `app_id` works for all users if it's configured in your workspace for SMS and email objects

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md

Clarify link preview detail
- BD-4818
- N/A …

BD-4818: Clarify link preview detail

---

_docs/_user_guide/engagement_tools/campaigns/building_campaigns/rate-limiting.md

Clarify details on delivery speed rate limiting
- BD-4761
- N/A …

BD-4761: Clarify details on delivery speed rate limiting

---

_docs/_user_guide/message_building_by_channel/line/reporting.md

Unhide LINE reporting article
[BD-4828](https://jira.braze.com/browse/BD-4828)
- N/A …

BD-4828 Fix hidden LINE reporting article

---

_docs/_user_guide/message_building_by_channel/sms_mms_rcs/rcs/about_rcs.md

Update to contact account manager
- BD-4823
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-im …

BD-4823: Update to contact account manager

---

_docs/_user_guide/message_building_by_channel.md
assets/js/broken_redirect_list.js

Fix SMS & MMS tile link and name, and add 1 redirect
- N/A
- N/A …

Fix tile link

---

_docs/_help/accessibility.md

Fix duplicative "users" phrasing and removing extraneous bullet points
- N/A
- N/A …

Minor styling change to accessibility page

---

assets/css/scrollycode.scss
assets/js/scrollycode.js

Not perfect, but does fix the horizontal scroll bar issues.
- N/A
- N/A …

Potential fixes for scrolly code (testing)

---

_includes/developer_guide/web/sdk_integration.md

Fix spelling error in code comment for `sdk_integration.md`.
- N/A
- N/A …

Fix spelling error in code comment for sdk_integration.md

---

_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/click_tracking.md
_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md

Click Tracking and videos for WhatsApp are GA'd.
[BD-4842](https://jira.braze.com/browse/BD-4842)
- N/A …

BD-4842 Remove EA for click tracking and WhatsApp videos

---

_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/ecommerce_use_cases.md

Swapped the existing note with an EA alert
[BD-4827](https://jira.braze.com/browse/BD-4827)
- N/A …

BD-4827 Add EA alert to eCommerce use cases

---

_docs/_user_guide/brazeai/recommendations/creating_recommendations/ai.md

Fixing a merge conflict for the deployment, i.e. to merge `develop` into `master`. (also side note: there was no conflict locally, only in GitHub because GitHub's merge conflict handling isn't as robust as `git`'s local capabilities).
- N/A
- N/A …

Fix merge conflict into 'master' branch

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Fixing minor subject consistency, testing prompts
In this case, requester did not catch all the inconsistencies and neither did CoPilot
[BD-4845](https://jira.braze.com/browse/BD-4845)
- N/A
- [X ] I confirm that my PR meets the following:
- If I updated or replaced an image, …

[BD-4845]: Fix minor subject consistency, testing prompts

---

_docs/_user_guide/engagement_tools/segments/sql_segments/sql_segments_tables.md
assets/download_file/data-sharing-raw-table-schemas.txt

Remove `quiet_hours` from `abort_type` for Currents
- BD-4831
- N/A …

BD-4831: Remove `quiet_hours` from `abort_type` for Currents

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/using_catalogs.md

Clarify that variables must be wrapped in curly brackets
- BD-4570
- N/A …

BD-4570: Clarify that variables must be wrapped in curly brackets

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md

Remove {% raw %} and {%endraw%} around image references
- N/A
- N/A …

Remove `{% raw %}` and `{%endraw%}` around image references

---

_docs/_user_guide/engagement_tools/templates_and_media/media_library.md
assets/js/broken_redirect_list.js

Update redirects for broken links
None
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)) …

404 checker - June 11, 2025

---

_includes/developer_guide/react_native/push_notifications/rich.md

The link is self-referential / recursive.
- N/A
- N/A …

Remove self-referential link

---

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md

Remove incorrect limitation for link aliases 
- N/A
- N/A …

Remove incorrect limitation for link aliases

---

_docs/_hidden/other/dp-technical-assistance.md

Update Legal doc
[BD-4825](https://jira.braze.com/browse/BD-4825)
- N/A …

BD-4825 Update Data Protection Technical Assistance

---

_docs/_user_guide/engagement_tools/segments/segmentation_filters.md

The `Last Did Custom Event` filter supports filters, such as 0.25 hours.
[BD-4730](https://jira.braze.com/browse/BD-4730)
- N/A …

BD-4730 Last Did Custom Event filter supports decimals

---

_includes/data_centers.md

Fix US-10 dashboard URL

---

_docs/_user_guide/data/cloud_ingestion/overview.md

There is an error on the documentation
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-i …

Update example error on overview.md

---

_docs/_api/objects_filters/messaging/apple_object.md

The closing brace of Apple push object is accidentally deleted in https://github.com/braze-inc/braze-docs/commit/a3466471c8648f17afe610813bdc97a5e2da6686
https://github.com/braze-inc/braze-docs/commit/a3466471c8648f17afe610813bdc97a5e2da6686
- N/A …

[NO-TICKET] Add the missing brace

---

_docs/_user_guide/message_building_by_channel/email/inbox_vision.md

Add alert about known issue for accessibility testing
- N/A
- N/A …

Add alert about known issue for accessibility testing

---

_plugins/algolia_hooks.rb

force utf8 encoding for content

---

_docs/_partners/message_personalization/dynamic_content/visual_and_interactive_content/movable_ink.md

Fix URL
- BD-4865
- N/A
- If my PR is …

BD-4865: Fix URL

---

_docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md
_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/custom_domains.md
_includes/custom_domains.md

EA edits for self-serve custom domains
[BD-4868](https://jira.braze.com/browse/BD-4868)
- N/A …

BD-4868 Revert custom domain edits

---

Gemfile.lock

Fix upstream process to try and fix this issue

fix algolia indexing v3

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Update step details for email preferences
- BD-4869
- N/A …

BD-4869: Fix open tracking pixel steps

---

_docs/_user_guide/data/cloud_ingestion/file_storage_integrations.md

Add recommendation for file size and fix typos
- BD-4871
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#u …

BD-4871: Add recommendation for file size and fix typos

---

_docs/_user_guide/brazeai/generative_ai/images.md

Fix incorrect breadcrumb instructions

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Update analytics for Delay step
- BD-4421
- N/A …

BD-4421: Update analytics for Delay step

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/advanced_filters.md

Add filters to "Advanced Liquid filters"
[BD-4790](https://jira.braze.com/browse/BD-4790)
- N/A …

BD-4790 Add json_parse and as_json_string filters

---

_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md

Update details for original Canvas editor
- BD-4402
- N/A …

BD-4402: Update details for original Canvas editor

---

_docs/_developer_guide/home.md
_docs/_developer_guide/sdk_integration.md

Fixing grammar
- N/A
- N/A
- If my PR is …

Grammar fix.

---

scripts/create_deploy_text.sh

The script was not able to parse squash merges because it uses a different format than merge commits. Now it can handle both.
- N/A
- N/A …

Fix bdocs deploy command

---

_docs/_user_guide/message_building_by_channel/line/line_setup.md

If users want to add IP whitelisting to their LINE account, they have to add all of the ones listed for the cluster in IP allowlisting.
[BD-4401](https://jira.braze.com/browse/BD-4401)
- N/A
- If I updated or replaced an image, I did not remove the original image file from …

BD-4401 Add IP addresses to your IP allowlist for LINE setup

---

_docs/_user_guide/brazeai/generative_ai/content_qa.md

…
- [BD-4792](https://jira.braze.com/browse/BD-4792)
- N/A …

BD-4792: Update user docs to specify AI Content Q/A is mobile push only, not all push

---

_docs/_partners/canvas_audience_sync/google_audience_sync.md

Clarify Audience Sync to Google is for Google Ads, not Google Ads Manager
- BD-4874
- N/A …

BD-4874: Clarify Audience Sync to Google is for Google Ads, not Google Ads Manager

---

_docs/_user_guide/engagement_tools/segments/user_profiles.md

Adding feature flag eligibility to user_profiles.md

Adding feature flag eligibility to user_profiles.md

---

_docs/_user_guide/data/custom_data/recommended_events/ecommerce_events.md

Clarify details for eCommerce recommended events
- BD-4748
- N/A …

BD-4748: Clarify details for eCommerce recommended events

---

_docs/_api/endpoints/user_data/post_user_identify.md

Remove outdated parameter
- BD-4873
- N/A …

BD-4873: Remove outdated parameter

---

_docs/_user_guide/message_building_by_channel/content_cards/create/card_creation.md

increase readability
Before:
After: 
- If …

[no-tix] make at first impression rate limit limitation more readable with <br><br>

---

_docs/_user_guide/administrative/app_settings/email_settings.md

Clarify supported editors for message-level one-click list-unsubscribe
- BD-3774
- N/A …

BD-3774: Clarify supported editors for message-level one-click list-unsubscribe

---

_docs/_user_guide/brazeai/generative_ai.md
_docs/_user_guide/brazeai/generative_ai/sql_segment_extensions.md

Add an alias to SQL Segment Extensions and update title of landing page tile.
[BD-4894](https://jira.braze.com/browse/BD-4894)
- N/A …

Add alias to SQL Segment Extensions

---

_docs/_partners/ecommerce/shopify/shopify_overview.md
_docs/_partners/ecommerce/shopify/shopify_standard_integration.md

Add API information to the Shopify overview page, specifically for sign up forms.
[BD-4892](https://jira.braze.com/browse/BD-4892)
- N/A …

BD-4892 Update Shopify integration with API information

---

_docs/_user_guide/data/data_points.md

Adding message engagement events to the "non-billable" table.
- [BD-3773](https://jira.braze.com/browse/BD-3773)
- N/A …

[BD-3773] Add 'message engagement events' to non-billable

---

_docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md

Applying changes to Custom Domains article.
[BD-4897](https://jira.braze.com/browse/BD-4897)
- N/A …

BD-4897 Update Custom Domains article

---

_docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening/custom_domains.md

- [#9964](https://github.com/braze-inc/braze-docs/pull/9964) - Update Custom Domains article

Deploy pt 2 - July 3, 2025

---

_docs/_user_guide/engagement_tools/campaigns/faq.md

Clarify "safe zone" in campaign FAQ and minor edits
- N/A
- N/A …

Clarify "safe zone" in campaign FAQ and minor edits

---

_docs/_help/help_articles/api/webhook_connected_content_errors.md

Adding more info re: Currents
Add additional failure insights in Braze Currents for webhook and Connected Content
- BD-4911
- N/A …

BD-4911: Add additional failure insights in Braze Currents for webhook and Connected Content - MERGE 7/10

---

_docs/_user_guide/analytics/dashboard/conversions_dashboard.md
_docs/_user_guide/engagement_tools/canvas/testing_canvases/preview_user_paths.md
_docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md
_docs/_user_guide/message_building_by_channel/email/templates/link_template.md
_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

Update mentions of "(optional)" to "(Optional)" for text steps, not headings
- N/A
- N/A …

Update mentions of "(optional)" to "(Optional)" for text steps

---

_docs/_user_guide/engagement_tools/segments/user_profiles.md

Add WhatsApp engagement events to Messaging History tab.
[BD-4893](https://jira.braze.com/browse/BD-4893)
- N/A …

BD-4893 Add WhatsApp engagement events

---

_docs/_user_guide/analytics/query_builder.md
_docs/_user_guide/message_building_by_channel/sms_mms_rcs/link_shortening.md

Can we add a section to the FAQ linked above that states that send_ids are not associated to click events for advanced link tracking?
[BD-4889](https://jira.braze.com/browse/BD-4889)
- N/A …

BD-4889 send_ids aren't associated with SMS click events

---

_docs/_user_guide/message_building_by_channel/whatsapp/faqs.md

Clarify multiple WABA details.
[BD-4835](https://jira.braze.com/browse/BD-4835)
- N/A …

BD-4835 Clarify multiple WABAs details

---

_docs/_user_guide/message_building_by_channel/whatsapp/overview/multiple_subscription_groups.md

We want to clarify that customers can connect WABAs from different Meta Business Managers. There is no restriction around that.
[BD-4513](https://jira.braze.com/browse/BD-4513)
- N/A …

BD-4513 WABAs can be from different Meta Business Managers

---

_docs/_user_guide/administrative/app_settings/internal_groups_tab.md

Looks like the course name has changed
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-i …

Update Braze Learning course name

---

_docs/_developer_guide/sdk_integration/authentication.md

Update the terminology and try to eliminate confusion between "signatures" and JWTs
- N/A
- N/A …

Update authentication.md JWT terminology

---

_docs/_user_guide/administrative/app_settings/tags.md

Clarify bulk tagging details for campaigns
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating- …

BD-4915: Clarify bulk tagging details

---

_docs/_user_guide/administrative/app_settings/workspaces.md

Restructure an FAQ ("Should I create a new workspace when I'm releasing an updated app?") so that the recommendations are clearer.
[BD-4935](https://jira.braze.com/browse/BD-4935)
- N/A …

BD-4935 Update FAQs for workspaces

---

_docs/_user_guide/engagement_tools/messaging_fundamentals/copying_across_workspaces.md

Clarify supported channels for copying across workspaces
- BD-4940
- N/A …

BD-4940: Clarify supported channels for copying across workspaces

---

_docs/_user_guide/engagement_tools/messaging_fundamentals/copying_across_workspaces.md

Clarify translations aren't copied across campaigns and Canvases for workspaces
- BD-4694
- N/A …

BD-4694: Clarify translations aren't copied across campaigns and Canvases for workspaces

---

_docs/_user_guide/data/field_level_encryption.md

Reverts braze-inc/braze-docs#10032

Revert "Update field_level_encryption.md"

---

_docs/_user_guide/data/report_metrics.md

According to the docs, the number of spam is the result of formula "Spam % or Spam Rate %: (Marked as Spam) / (Sends)". But the number of spam in an email campaign follows a Feedback Loop (FBL).
[BD-4906](https://jira.braze.com/browse/BD-4906)
- N/A …

BD-4906 Add note to spam metric definition

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Clarify Context variable example for references in other steps
- BD-4895
- N/A …

BD-4895: Clarify Context variable example for references in other steps

---

_docs/_user_guide/analytics/reporting/dashboard_builder.md

Clarify "Touches" explanation
- BD-4707
- N/A …

BD-4707: Clarify "Touches" explanation

---

_lang/de/_developer_guide/sdk_integration/initialization.md
_lang/de/_docs_pages/sitemap.xml
_lang/es/_developer_guide/sdk_integration.md
_lang/es/_developer_guide/sdk_integration/initialization.md
_lang/es/_docs_pages/sitemap.xml
_lang/fr_fr/_developer_guide/sdk_integration.md
_lang/fr_fr/_developer_guide/sdk_integration/initialization.md
_lang/fr_fr/_docs_pages/sitemap.xml
_lang/ja/_developer_guide/sdk_integration.md
_lang/ja/_developer_guide/sdk_integration/initialization.md
_lang/ja/_docs_pages/sitemap.xml
_lang/ko/_developer_guide/sdk_integration.md
_lang/ko/_developer_guide/sdk_integration/initialization.md
_lang/ko/_docs_pages/sitemap.xml
_lang/pt_br/_developer_guide/sdk_integration.md
_lang/pt_br/_developer_guide/sdk_integration/initialization.md
_lang/pt_br/_docs_pages/sitemap.xml

Fix missing language site map, and languages missing includes

fix sitemap and prod deploy

---

_docs/_user_guide/message_building_by_channel/line/line_users/user_management.md

This sentence is missing a verb.
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)) …

line: add missing verb

---

_docs/_user_guide/message_building_by_channel/sms_mms_rcs.md

Broken link audit - July 17, 2025
- N/A
- N/A …

Broken link audit - July 17, 2025

---

_docs/_user_guide/administrative/app_settings/internal_groups_tab.md

Include that seed groups are also not included by delivery speed rate limits
- BD-4917
- N/A …

BD-4917: Include that seed groups are also not included by delivery speed rate limits

---

_docs/_api/endpoints/export/user_data/post_users_identifier.md
_includes/rate_limits.md

New faster rate limit available for `/users/export/ids` endpoint
- BD-4954
- N/A …

BD-4954: New faster rate limit available for `/users/export/ids` endpoint

---

_docs/_partners/ecommerce/analytics_workflow/okendo.md

new partner docs for okendo
- [BD-4942](https://jira.braze.com/browse/BD-4942)
- N/A …

Okendo Partner Docs

---

_docs/_hidden/other/support_contact.md
_lang/ja/_hidden/other/support_contact.md

- Add option for the select text and value to be different.
- Changed ja feedback to use english topic values

change ja support topic to be english

---

_includes/developer_guide/swift/push_notifications/push_stories.md

Swift prereqs accidentally linked to the cordova ones instead. [Relevant thread](https://brazetechnology.slack.com/archives/C0D10FTGQ/p1753205522714479).
- N/A
- N/A …

Fix Swift prereqs for push stories

---

_docs/_user_guide/message_building_by_channel/in-app_messages/traditional/customize/html_in-app_messages.md

There are inconsistencies in whether we advise clients to use single or double quotes when passing their parameters for brazeBridge.logClick(). If the client is not placing these methods inside a <script> tag, then we (in Support) advise them to use single quotes for values passed within the methods.
Specifically in the Button Tracking section, the table (clicks/methods) uses double-quotes. But the code snippet just below that (showing log click and close message), uses a single quote around the button ID.
- N/A
- N/A
- …

[BD-3682] Syntax for logging Click on custom HTML IAMs

---

_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md

Adds clarification about the dynamic `User-Agent` header format used in Connected Content and webhook requests.
- [BD-3720](https://jira.braze.com/browse/BD-3720)
- N/A …

[BD-3720] Specify webhook User-Agent header

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Clarify sending promotion codes to user details
- BD-4641
- N/A …

BD-4641: Clarify sending promotion codes to user details

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md

Update image size
- N/A
- N/A
- If my PR …

Update image size

---

_includes/brazeai/generative_ai/sql_segment_extensions.md

Minor tweak for "Invert SQL".
[BD-4965](https://jira.braze.com/browse/BD-4965)
- N/A …

BD-4965 Invert SQL updates

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2025/7_22_25.md

Clarify workspace API rate limits in release notes
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#u …

Clarify workspace API rate limits in release notes

---

_includes/developer_guide/web/analytics/setting_user_attributes.md

A possible typo was raised in #10128 -- changing `getCurrentUser()` > `getUser()`. Will need verification from PM/ENG for accuracy.
- #10128
- N/A …

Possible typo for getCurrentUser() > getUser()

---

.github/workflows/add-label.yml
README.md
_docs/_contributing/bdocs.md
bdocs

Misc. changes to support renaming the base/target branch from `master` to `main` for the braze docs repo.
- N/A
- N/A …

Support renaming base branch from 'master' to 'main'

---

_docs/_user_guide/engagement_tools/campaigns/ideas_and_strategies/new_features.md
_docs/_user_guide/engagement_tools/canvas/faqs.md
_docs/_user_guide/engagement_tools/segments/creating_a_segment.md
_docs/_user_guide/engagement_tools/segments/managing_segments.md
_docs/_user_guide/engagement_tools/segments/measuring_segment_size.md
_docs/_user_guide/engagement_tools/segments/segmentation_filters.md
_docs/_user_guide/engagement_tools/segments/troubleshooting.md
_docs/_user_guide/engagement_tools/segments/user_profiles.md
_docs/_user_guide/engagement_tools/testing/global_control_group.md
_docs/_user_guide/engagement_tools/testing/random_bucket_numbers.md

Transferring SF User Targeting articles
[BD-4706](https://jira.braze.com/browse/BD-4706)
- N/A …

BD-4706 Transfer User Targeting SF articles

---

_docs/_api/endpoints/messaging/send_messages/post_send_triggered_campaigns.md
_docs/_api/endpoints/messaging/send_messages/post_send_triggered_canvases.md
_docs/_api/objects_filters/connected_audience.md
_includes/rate_limits.md

Clarifications for segment_id from PQ thread
- N/A
- N/A …

Clarifications for segment_id

---

_docs/_developer_guide/sdk_integration/authentication.md

This explicitly calls out no-op for anonymous users
- N/A
- N/A …

Add no-op note to SDK Auth for anonymous users

---

.github/CODEOWNERS

Changes include:
- assigning `@braze-inc/docs-team` as codeowner for `support_contact.md`, rather than a specific member as its something any of us should have the ability to verify and approve.
- removing `@braze-inc/docs-team` from ingestion endpoints as `lydia` was already assigned. if for some reason lydia is out, myself, zeyuan, and any other high-level admin can still merge so the "backup" was redundant.
- general tweaks/improvements to organization and comments
- N/A
- N/A
- My content contains correct spelling …

Simplify + improve CODEOWNERS

---

_docs/_user_guide/message_building_by_channel/email/templates/link_aliasing.md

Clarify link identifiers behavior for duplicate emails and Content Blocks
- BD-4976
- N/A …

BD-4976: Clarify link identifiers behavior for duplicate emails and Content Blocks

---

_docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md

Clarifications on custom unsubscribe and custom opt-in pages
- BD-4464
- N/A …

BD-4464: Clarifications on custom unsubscribe and custom opt-in pages

---

_docs/_user_guide/engagement_tools/segments/suppression_lists.md

Update Suppression Lists.
[BD-5003](https://jira.braze.com/browse/BD-5003)
- N/A …

BD-5003-2 Update Suppression Lists

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/exit_criteria.md
_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/launching_canvas_flow.md
_docs/_user_guide/engagement_tools/canvas/managing_canvases/change_your_canvas_after_launch.md
_docs/_user_guide/engagement_tools/canvas/testing_canvases/measuring_and_testing_with_canvas_analytics.md
_docs/_user_guide/engagement_tools/messaging_fundamentals/reeligibility.md
_docs/_user_guide/engagement_tools/testing/race_conditions.md

Part 1 of CLX-related edits, part 2 will have the edit for the Experiment Paths step article
- N/A
- N/A …

SF KB articles to Braze docs migration: CLX pt. 1

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/context.md

Clarify time data type for Context step
- BD-4950
- N/A …

BD-4950: Clarify time data type for Context step

---

_docs/_partners/ecommerce/shopify/shopify_custom_integration.md

removing slash from link which caused redirects to 404

[PP-4757] fix link with extra slash

---

_docs/_api/endpoints/export/campaigns/get_campaign_details.md

Changes from https://github.com/braze-inc/braze-docs/pull/10211
- https://github.com/Appboy/platform/pull/103604
- August 5, 2025 …

PUSH-408: New API fields for /campaigns/details endpoint - MERGE 8/5

---

.github/PULL_REQUEST_TEMPLATE

Minor edit "follows" to "follow"
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)) …

Minor edit to PULL_REQUEST_TEMPLATE

---

_docs/_user_guide/data/braze_currents/event_glossary/customer_behavior_events.md

Add property details for Push Notification Token State Change events for Currents for Customer Behavior and User Events glossary
- BD-4636
- N/A …

BD-4636: Add property details for Push Notification Token State Change events for Currents

---

_docs/_contributing/styling_examples.md
_docs/_user_guide/engagement_tools/landing_pages.md
_includes/video.html

Adding support for embedded wistia videos in video.html includes file to support push for more short form video content in documentation
https://github.com/user-attachments/assets/973275c8-0129-4e90-9925-887738e7717c
- N/A
- N/A
- [ X ] I confirm that my PR meets the following: …

Wistia embedded video support

---

.github/copilot-instructions.md

Adding some instructions specifically around ticket numbers for the PR title and body that copilot creates.
- N/A
- N/A …

Notes about PR title and body for copilot-instructions.md

---

_docs/_user_guide/engagement_tools/landing_pages.md

Removing the existing hero image and adding an embedded video (from wistia) to the main Landing Page documetnation
Before
After
- N/A
- N/A
- [ X ] I confirm that my PR meets the following: …

Added video to landing page main page

---

_includes/analytics/metrics.md

Clarify Click-to-Open Rate metric definition
- N/A
- N/A …

Clarify Click-to-Open Rate metric definition

---

_docs/_user_guide/brazeai/intelligence/intelligent_timing.md

Add a troubleshooting item for how time zone affects intelligent timing sends.
[BD-4603](https://jira.braze.com/browse/BD-4603)
- N/A …

BD-4603 Add troubleshooting item for time zone and Intelligent Timing

---

bdocs

In the current iteration of `bdocs` i needed to manually list which commands were compatible across repos which was very error prone. Realized i could just have a single list that's auto-checked.
- [BD-5041](https://jira.braze.com/browse/BD-5041)
- N/A …

[BD-5041] Improve public/hidden handling for bdocs

---

_docs/_user_guide/engagement_tools/canvas/create_a_canvas/create_a_canvas.md
_docs/_user_guide/engagement_tools/messaging_fundamentals/targeting_users.md
_docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
_docs/_user_guide/message_building_by_channel/content_cards/create.md
_docs/_user_guide/message_building_by_channel/email/html_editor/creating_an_email_campaign.md
_docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
_docs/_user_guide/message_building_by_channel/sms_mms_rcs/rcs/create.md
_docs/_user_guide/message_building_by_channel/sms_mms_rcs/sms/create.md
_docs/_user_guide/message_building_by_channel/webhooks/creating_a_webhook.md
_docs/_user_guide/message_building_by_channel/whatsapp/whatsapp_campaign/create.md
_includes/target_audiences.md

Clarify how Braze evaluates users in Target Audiences first then confirms entry criteria
- BD-3441
- N/A …

BD-3441: Clarify how Braze evaluates users in Target Audiences first then confirms entry criteria

---

_docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md

Custom head tags for email
- BD-5026
- N/A …

BD-5026: Custom head tags for email

---

_docs/_user_guide/message_building_by_channel/whatsapp/meta_resources.md

Update Meta resources with WhatsApp updates for March and April 2025.
[BD-5070](https://jira.braze.com/browse/BD-5070)
- N/A …

BD-5070 Update Meta resources

---

assets/css/_content.scss
assets/js/copy-heading-tag-links.js

improves https://github.com/braze-inc/braze-docs/pull/10283/files to work on mobile

fix copy link position for mobile

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md

Update Personalized Paths to use proper terminology.
[BD-5079](https://jira.braze.com/browse/BD-5079)
- N/A …

BD-5079 Small edits to Personalized Paths

---

_docs/_developer_guide/banners/creating_placements.md
_docs/_developer_guide/in_app_messages.md
_docs/_developer_guide/in_app_messages/customization.md
_docs/_developer_guide/in_app_messages/triggering_messages.md
_docs/_developer_guide/in_app_messages/tutorials/conditionally_displaying_messages.md
_docs/_developer_guide/in_app_messages/tutorials/customizing_message_styling.md
_docs/_developer_guide/in_app_messages/tutorials/deferring_triggered_messages.md
_includes/banners/about.md
_includes/developer_guide/_shared/tutorial_feedback.md
_includes/developer_guide/android/banners/tutorial_displaying_banners.md
_includes/developer_guide/swift/banners/tutorial_displaying_banners.md
_includes/developer_guide/web/banners/tutorial_displaying_banners.md

Cross referencing tutorials and adding attribution to tutorial feedback links
- N/A
- N/A …

Cross referencing tutorials and adding attribution to tutorial feedback links

---

_docs/_user_guide/personalization_and_dynamic_content/catalogs/catalog.md

Clarifying supported data types for upload methods
- BD-5025
- N/A …

BD-5025: Clarifying supported data types for upload methods

---

_docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md

- We have updated the default limit for DnD email preference center from 50 to 100
- https://github.com/Appboy/platform/pull/104701
- https://servicedesk.braze.com/browse/PQ-11841 …

[EINFRA-2624] increase Email DnD preference center limit to 100

---

_docs/_user_guide/analytics/dashboard/email_performance_dashboard.md

Fix typo and add alt text
- N/A
- N/A
- If …

Fix typo and add alt text

---

_docs/_user_guide/analytics/dashboard/email_performance_dashboard.md

Fix an anchor link
N/A
- N/A
- If my PR is …

Fix anchor link

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

The current documentation for the IAM abort event is outdated. Update the documentation in the IAM abort event to specify that only templated IAM supports abort event.
[BD-5001](https://jira.braze.com/browse/BD-5001)
- N/A
- If I updated or replaced an image, I did not remove …

BD-5001 Clarify IAM abort events

---

_docs/_help/release_notes.md
_docs/_help/release_notes/2025.md
_docs/_help/release_notes/2025/8_19_25.md

Adding August 2025 release notes.
N/A
- N/A …

August 2025 release notes

---

_docs/_user_guide/brazeai/predictive_churn/creating_a_churn_prediction.md

Clarify churn audience construction and related details
- BD-5071
- N/A …

BD-5071: Clarify churn audience construction and related details

---

_lang/ja/_user_guide/offerfit/building_use_cases.md

Fix JA deployment attempt
- N/A
- N/A
- If …

Fix JA deployment attempt

---

_docs/_user_guide/data/braze_currents/event_glossary/message_engagement_events.md

Cleaned up the API tags on the Message Engagement Events page to make it more streamlined. 
[BD-5057](https://jira.braze.com/browse/BD-5057)
- N/A …

BD-5057 Simplify API tags for message engagement events

---

_docs/_user_guide/engagement_tools/messaging_fundamentals/archiving.md
_docs/_user_guide/engagement_tools/messaging_fundamentals/targeting_users.md

Fix typos and errors.
- N/A
- N/A
- If my …

Typo fixes

---

assets/css/_lang_pt-br.scss

reported an issue with alert icons not rendering for the pt_br locale, and zeyuan noted to update the `$base_url` in the SCSS file to use `pt-br` instead of `pt_br`. tested locally and it works ✅ 
- N/A
- N/A …

Fix brazil base url value

---

_docs/_user_guide/administrative/access_braze/navigation.md

From discussion with PM. Logging ticket to capture further changes needed.
- N/A
- N/A …

Remove intro list from Navigating Braze

---

_docs/_user_guide/message_building_by_channel/email/preference_center/dnd_preference_center.md
_docs/_user_guide/message_building_by_channel/email/preference_center/overview.md

Update navigation path to Email Preference Centers page
- BD-5064
- N/A …

[BD-5064] Update navigation path to Email Preference Centers page

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/using_liquid.md

Clarify when you need to make use of double brackets for Liquid. 
[BD-5062](https://jira.braze.com/browse/BD-5062)
- N/A …

[BD-5062] You can use double brackets or none for tags within tags

---

_docs/_developer_guide/analytics/logging_channel_data/in_app_messages.md
_docs/_developer_guide/in_app_messages.md
_docs/_user_guide/engagement_tools/canvas/create_a_canvas/canvas_by_channel/in-app_messages_in_canvas.md

Updating `In-App messages` to `In-app messages` where applicable.
- N/A
- N/A …

Fix casing for IAM nav titles

---

_docs/_user_guide/engagement_tools/segments/user_profiles.md

Add deferral event to list
- BD-5010
- N/A …

[BD-5010] Add deferral event to list

---

_docs/_user_guide/personalization_and_dynamic_content/promotion_codes.md

Add clarification on promotion codes with multiple channels
- BD-4216
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_manageme …

[BD-4216] Add clarification on promotion codes with multiple channels

---

_docs/_hidden/archive_docs/scuba.md
_docs/_partners/data_and_analytics.md
assets/js/broken_redirect_list.js

Archive Scuba docs
N/A
- N/A
- If my PR is …

Archive Scuba docs

---

_docs/_user_guide/engagement_tools/canvas/ideas_and_strategies/ecommerce_use_cases.md

Fix Liquid tag
- BD-5120
- N/A
- If my PR …

[BD-5120] Fix Liquid tag

---

_docs/_help/release_notes/2023/4_4_23.md
_docs/_partners/ecommerce/shopify/shopify_catalogs.md
_docs/_user_guide/brazeai/recommendations.md
_docs/_user_guide/brazeai/recommendations/creating_recommendations/rules_based.md
_docs/_user_guide/message_building_by_channel/banners/creating_campaigns.md
assets/js/broken_redirect_list.js

Fix broken links
None
- N/A
- If my PR is …

404 Checker Sep 3

---

_docs/_developer_guide/content_cards/content_card_inbox.md
assets/css/scrollycode.scss

Tutorials for using content cards to build inboxes!! And a small fix to the tutorial framework.
- N/A
- N/A …

added content card inbox tutorial + small scrolly fix

---

_docs/_user_guide/analytics/reporting/report_builder.md

Update Report Builder docs to specify that **Rows** impacts the metrics you can view.
[BD-5102](https://jira.braze.com/browse/BD-5102)
- N/A …

BD-5102 Clarify Report Builder rows

---

_docs/_user_guide/personalization_and_dynamic_content/connected_content/making_an_api_call.md

Updating docs for making a Connected Content API call. Pulled edits from [this PR](https://github.com/braze-inc/braze-docs/pull/10511), as I don't have permissions to directly edit those files.
None
- N/A …

Update API call

---

_docs/_user_guide/engagement_tools/segments/segment_extension/sql_segments/sql_segments_tables.md

We are updating the character limit for the abort_log field in the `users.messages.<channel>.abort` tables.
Platform PR: https://github.com/Appboy/platform/pull/106581
- N/A …

[MP-6798] Update abort_log Character Limit

---

scripts/create_deploy_text.sh
scripts/create_release_text.sh

Fixing the `jq` error for the release command (i.e. the tool that parses JSON). Also making it more stable in general.
- N/A
- N/A …

bdocs - fix release command

---

_docs/_user_guide/personalization_and_dynamic_content/liquid/filters.md

Updated links for Shopify Liquid filters because Shopify updated their API URL paths. Removed the `time_zone` filter, which is no longer provided as a possible filter.
[BD-5172](https://jira.braze.com/browse/BD-5172) & [BD-5172](https://jira.braze.com/browse/BD-5172)
- N/A
- …

[BD-5172] & [BD-5172] Update URLs for Liquid filters

---

_docs/_user_guide/engagement_tools/segments/suppression_lists.md

Remove EA banner
- N/A
- N/A
- If my PR is …

BD-5195: Remove EA banner

---

_includes/alerts/important_alerts.md

Update Shopify alert about supported webhooks and user data that is synced.
[BD-5160](https://jira.braze.com/browse/BD-5160)
- N/A …

[BD-5160] Update Shopify alert

---

_docs/_user_guide/engagement_tools/canvas/canvas_components/delay_step.md

Clarify time delay nuances and update details to match dashboard
- BD-5179
- BD-5175
- N/A …

[BD-5179, BD-5175] Clarify time delay nuances and update details to match dashboard

---

.github/ISSUE_TEMPLATE/report_an_issue.md
.github/ISSUE_TEMPLATE/request_a_feature.md

Update issue and feature request template assignees to `braze-inc/braze-docs` team instead of individuals.
- N/A
- N/A …

Update issue template assignees

---

_docs/_user_guide/message_building_by_channel/email/email_setup.md

Clarify IP pool selection in Target Audiences step of email composer
- BD-5190
- N/A …

[BD-5190] Clarify IP pool selection in Target Audiences step of email composer

---

_docs/_user_guide/getting_started/braze_pilot/data_dictionary.md

Updated table styling for logged events and attributes.
- N/A
- N/A …

Remove text

---

_docs/_user_guide/engagement_tools/locations_and_geofences/creating_geofences.md

Fix typo in metrics and some small edits
- N/A
- N/A
- If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an- …

Fix typo in metrics

---

_docs/_user_guide/data/activation/report_metrics.md

Clarify _Soft Bounces_ and _Deferrals_ metrics
- BD-5168
- N/A …

[BD-5168] Clarify Soft Bounces and Deferrals metrics

---

_docs/_user_guide/message_building_by_channel/in-app_messages/drag_and_drop/style_settings.md
assets/js/broken_redirect_list.js

Add redirects for 2 broken links.
None
- N/A …

Fix 404 links

---

_docs/_user_guide/data/unification/data_transformation.md

Added alias to the Data Transformation to fix broken links
N/A
- N/A …

Add alias to data transformation article

---

_docs/_user_guide/engagement_tools/segments/troubleshooting.md

Add troubleshooting errors regarding audience complexity.
[BD-5211](https://jira.braze.com/browse/BD-5211)
- N/A …

[BD-5211] Update audience complexity info

---

.github/workflows/docs-agent-test.yml

Testing GitHub Action
- N/A
- N/A
- [ X ] I confirm that my PR meets the following: …

GitHub Actions test

---

assets/js/broken_redirect_list.js

Add redirect for broken Jetpack Compose link
[Thread](https://brazetechnology.slack.com/archives/C02C7EQBHCL/p1759776350676809)
- N/A …

Fix Jetpack Compose link

---

.github/copilot-instructions.md

Clarified pull request title and body instructions, and improved wording for clarity.
Edit pull request title Copilot step
- N/A
- N/A …

Edit pull request title Copilot step

---

_includes/mcp_server/legal_disclaimer.md

Fix broken link
- BD-5243
- N/A
- If my PR …

[BD-5243] Fix broken link

---

_docs/_user_guide/data/distribution/braze_currents/event_glossary/message_engagement_events.md

This updates docs for the Currents Version 3 release. Formatting changes are from a change to the generation system; I've isolated them in https://github.com/braze-inc/braze-docs/pull/10705 to help ensure parity.
- [DI-7995](https://jira.braze.com/browse/DI-7995)
- 8 Oct 2025 …

[DI-7995] Update Currents event docs for version 3 release
